public class AvatarInPointChangeCard : EventCard<ObjectOfTimeline>
{
    private ObjectId _avatar;
    private bool _is_attached;

    public AvatarInPointChangeCard(ObjectId avatar, bool is_attached, long step) : base(step)
    {
        _avatar = avatar;
        _is_attached = is_attached;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        var netpoint = obj.GetComponent<NetPoint>();
        if (_is_attached)
        {
            netpoint.avatars_in_point.Add(_avatar);
        }
        else
        {
            netpoint.avatars_in_point.Remove(_avatar);
        }
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        var netpoint = obj.GetComponent<NetPoint>();
        if (_is_attached)
        {
            netpoint.avatars_in_point.Remove(_avatar);
        }
        else
        {
            netpoint.avatars_in_point.Add(_avatar);
        }
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _avatar);
        result = FieldScanner.ModifyHash(result, _is_attached);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as AvatarInPointChangeCard;
        return _avatar == other._avatar
            && _is_attached == other._is_attached
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
