public class ChangeLocationCard : EventCard<ObjectOfTimeline>
{
    private ObjectId _previous_location;
    private ObjectId _next_location;

    public ChangeLocationCard(ObjectId previous_location, ObjectId next_location, long step)
        : base(step)
    {
        _next_location = next_location;
        _previous_location = previous_location;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        (obj as Avatar).SetLocation(_next_location);
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        (obj as Avatar).SetLocation(_previous_location);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _previous_location);
        result = FieldScanner.ModifyHash(result, _next_location);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ChangeLocationCard;
        return _previous_location == other._previous_location
            && _next_location == other._next_location
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
