public class ChangeActivationStateObjectEvent : EventCard<ITimeline>
{
    ObjectId _id;
    bool _en;

    ChangeActivationStateObjectEvent(long step, ObjectId id, bool en) : base(step)
    {
        _id = id;
        _en = en;
    }

    public override void on_forward_enter(long step, ITimeline tl)
    {
        var obj = tl.GetObject(_id);
        if (_en)
            (tl as Timeline).present.AddActiveObject(obj);
        else
            (tl as Timeline).present.RemoveActiveObject(obj);
    }

    public override void on_backward_leave(long step, ITimeline tl)
    {
        var obj = tl.GetObject(_id);
        if (!_en)
            (tl as Timeline).present.AddActiveObject(obj);
        else
            (tl as Timeline).present.RemoveActiveObject(obj);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _id);
        result = FieldScanner.ModifyHash(result, _en);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ChangeActivationStateObjectEvent;
        return _id == other._id
            && _en == other._en
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
