public class CommandSpecificStateChange : EventCard<ObjectOfTimeline>
{
    CommandSpecificState _prev_state;
    CommandSpecificState _next_state;

    public CommandSpecificStateChange(
        CommandSpecificState prev_state,
        CommandSpecificState next_state,
        long stamp
    ) : base(stamp)
    {
        _prev_state = prev_state;
        _next_state = next_state;
    }

    public override void on_forward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        obj.SetCommandSpecificState(_next_state);
    }

    public override void on_backward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        obj.SetCommandSpecificState(_prev_state);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _prev_state);
        result = FieldScanner.ModifyHash(result, _next_state);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as CommandSpecificStateChange;
        return _prev_state == other._prev_state
            && _next_state == other._next_state
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
