public class CorpseFoundStateEvent : PatrolStateEvent
{
    ObjectId corpse_id;

    public CorpseFoundStateEvent(long step, ObjectId corpse_id) : base(step)
    {
        this.corpse_id = corpse_id;
    }

    public override void on_forward_enter(long local_step, ObjectOfTimeline actor)
    {
        AttentionModule(actor).FoundCorpse(local_step, corpse_id);
    }

    public override void on_backward_leave(long local_step, ObjectOfTimeline actor)
    {
        AttentionModule(actor).ForgetCorpse(corpse_id);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, corpse_id);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as CorpseFoundStateEvent;
        return corpse_id == other.corpse_id
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
