//using System.Diagnostics;
using System.Collections.Generic;
using UnityEngine;

public class DialogueObject : EventCard<NarativeState>
{
    public DialogueGraph dialogue;

    public DialogueObject(DialogueGraph dialogue, long step) : base(step, long.MaxValue)
    {
        this.dialogue = dialogue;
    }

    public void Apply(NarativeState state, long step)
    {
        Debug.Log("DialogueObject Apply " + step);
        var entrance = dialogue.entrance;

        long step_offset = 0;
        while (entrance != null)
        {
            var speach = new SpeachObject(
                entrance.speaker,
                entrance.text,
                step + step_offset,
                step + step_offset + (long)(Utility.GAME_GLOBAL_FREQUENCY * 5.5f)
            );

            state.speach_objects.Add(speach);
            if (entrance.next.Count == 0)
            {
                entrance = null;
                break;
            }
            entrance = entrance.next[0];
            step_offset += (long)(Utility.GAME_GLOBAL_FREQUENCY * 2.0f);
        }
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, dialogue);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as DialogueObject;
        return dialogue == other.dialogue
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
