public class DistructStateChangeEvent : AiControllerEvent
{
    public DistructStateChangeEvent(long step) : base(step, step + 1) { }

    public DistructState prevstate;
    public DistructState nextstate;

    public override void on_forward_enter(long local_step, ObjectOfTimeline actor)
    {
        (actor.AiController() as BasicAiController).SetDistructState(nextstate);
    }

    public override void on_backward_leave(long local_step, ObjectOfTimeline actor)
    {
        (actor.AiController() as BasicAiController).SetDistructState(prevstate);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, prevstate);
        result = FieldScanner.ModifyHash(result, nextstate);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as DistructStateChangeEvent;
        return prevstate == other.prevstate
            && nextstate == other.nextstate
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
