public class HearLoudSoundStateEvent : PatrolStateEvent
{
    public ReferencedPoint source;
    public RestlessnessParameters noise_parameters;

    public HearLoudSoundStateEvent(
        long step,
        ReferencedPoint source,
        RestlessnessParameters noise_parameters
    ) : base(step)
    {
        this.noise_parameters = noise_parameters;
        this.source = source;
    }

    public override void on_forward_enter(long local_step, ObjectOfTimeline actor)
    {
        AttentionModule(actor).HearLoudSound(local_step, source, noise_parameters);
    }

    public override void on_backward_leave(long local_step, ObjectOfTimeline actor)
    {
        AttentionModule(actor).ForgetLoudSound(source);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, source);
        result = FieldScanner.ModifyHash(result, noise_parameters);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as HearLoudSoundStateEvent;
        return source == other.source
            && noise_parameters == other.noise_parameters
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
