public class OnScreenMessage : BasicMultipleAction
{
    public string text;

    public OnScreenMessage(long start_step, long finish_step, string text)
        : base(start_step, finish_step)
    {
        this.text = text;
    }

    public string Compile()
    {
        return text;
    }

    public int CountOfStrings()
    {
        return 1;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, text);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as OnScreenMessage;
        return text == other.text
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
