public class PreDeathSelfEvent : EventCard<ObjectOfTimeline>
{
    public PreDeathSelfEvent(long step) : base(step) { }

    public override void on_forward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        obj.IsPreDead = true;
    }

    public override void on_backward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        obj.IsPreDead = false;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as PreDeathSelfEvent;
        return start_step == other.start_step && finish_step == other.finish_step && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
