using UnityEngine;

public class SetControlledHostCard : EventCard<ObjectOfTimeline>
{
    ObjectId name;
    bool attached_on_forward;

    public SetControlledHostCard(long step, ObjectId name, bool attached_on_forward) : base(step)
    {
        this.name = name;
        this.attached_on_forward = attached_on_forward;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        obj.SetDirectControlled(name);
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        obj.SetDirectControlled(default(ObjectId));
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, name);
        result = FieldScanner.ModifyHash(result, attached_on_forward);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as SetControlledHostCard;
        return name == other.name
            && attached_on_forward == other.attached_on_forward
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
