public class SetGrabbedCard : EventCard<ObjectOfTimeline>
{
    ObjectId prev;
    ObjectId next;
    bool is_dragging_prev;
    bool is_dragging_next;

    public SetGrabbedCard(
        long step,
        ObjectId prev,
        ObjectId next,
        bool is_dragging_prev,
        bool is_dragging_next
    ) : base(step)
    {
        this.prev = prev;
        this.next = next;
        this.is_dragging_prev = is_dragging_prev;
        this.is_dragging_next = is_dragging_next;
    }

    public override void on_forward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        (obj as Actor).grabbed_actor = next;
        (obj as Actor).is_drag_grabbed_actor = is_dragging_next;
    }

    public override void on_backward_leave(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        (obj as Actor).grabbed_actor = prev;
        (obj as Actor).is_drag_grabbed_actor = is_dragging_prev;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, prev);
        result = FieldScanner.ModifyHash(result, next);
        result = FieldScanner.ModifyHash(result, is_dragging_prev);
        result = FieldScanner.ModifyHash(result, is_dragging_next);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as SetGrabbedCard;
        return prev == other.prev
            && next == other.next
            && is_dragging_prev == other.is_dragging_prev
            && is_dragging_next == other.is_dragging_next
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
