public class TemporaryIncrementConfusedCounterCard : EventCard<ObjectOfTimeline>
{
    public TemporaryIncrementConfusedCounterCard(long step, long fini) : base(step, fini) { }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        (obj.AiController() as BasicAiController).IncrementConfusedCounter();
    }

    public override void on_forward_leave(long current_step, ObjectOfTimeline obj)
    {
        (obj.AiController() as BasicAiController).DecrementConfusedCounter();
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        (obj.AiController() as BasicAiController).DecrementConfusedCounter();
    }

    public override void on_backward_enter(long current_step, ObjectOfTimeline obj)
    {
        (obj.AiController() as BasicAiController).IncrementConfusedCounter();
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TemporaryIncrementConfusedCounterCard;
        return start_step == other.start_step && finish_step == other.finish_step && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
