class TimeReverse : TimeModifier
{
    int _mul = -2;

    public TimeReverse(long start_step, long finish_step) : base(start_step, finish_step) { }

    public override long TimeOffset(long step)
    {
        long from_start = step - StartStep;
        long multiplied = from_start * _mul;
        return multiplied;
    }

    public override long TimeOffsetOnFinish()
    {
        long from_start = FinishStep - StartStep;
        long multiplied = from_start * _mul;
        return multiplied;
    }

    public override float Multiplier()
    {
        return _mul;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _mul);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TimeReverse;
        return _mul == other._mul
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
