class TimeImmediateShift : TimeModifier
{
    int _offset = 0;

    public TimeImmediateShift(long start_step, int offset) : base(start_step, start_step)
    {
        _offset = offset;
    }

    public override long TimeOffset(long step)
    {
        return _offset;
    }

    public override long TimeOffsetOnFinish()
    {
        return _offset;
    }

    public override float Multiplier()
    {
        return 1;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _offset);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TimeImmediateShift;
        return _offset == other._offset
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
