public class TimeModifier : BasicMultipleAction
{
    public TimeModifier() { }

    public TimeModifier(long start_step, long finish_step) : base(start_step, finish_step) { }

    public virtual long TimeOffset(long step) => 0;

    public virtual long TimeOffsetOnFinish() => 0;

    public virtual float Multiplier() => 1.0f;

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TimeModifier;
        return start_step == other.start_step && finish_step == other.finish_step && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
