<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/editor_commands.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;Any<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.editor.undo_stack&nbsp;import&nbsp;UndoCommand<br>
from&nbsp;termin.geombase.pose3&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.kinematic.transform&nbsp;import&nbsp;Transform3<br>
from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity,&nbsp;Component<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;InspectField<br>
<br>
<br>
def&nbsp;_clone_pose(pose:&nbsp;Pose3)&nbsp;-&gt;&nbsp;Pose3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Создаёт&nbsp;независимую&nbsp;копию&nbsp;позы.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Массивы&nbsp;угла&nbsp;и&nbsp;смещения&nbsp;копируются,&nbsp;чтобы&nbsp;последующие<br>
&nbsp;&nbsp;&nbsp;&nbsp;изменения&nbsp;позы&nbsp;не&nbsp;портили&nbsp;снимок&nbsp;для&nbsp;undo/redo.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Pose3(ang=pose.ang.copy(),&nbsp;lin=pose.lin.copy())<br>
<br>
<br>
def&nbsp;_clone_value(value:&nbsp;Any)&nbsp;-&gt;&nbsp;Any:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Создаёт&nbsp;&quot;безопасную&quot;&nbsp;копию&nbsp;значения&nbsp;для&nbsp;хранения&nbsp;в&nbsp;команде.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Для&nbsp;numpy-матриц&nbsp;и&nbsp;numpy-векторов&nbsp;(модуль&nbsp;numpy)<br>
&nbsp;&nbsp;&nbsp;&nbsp;делается&nbsp;copy(),&nbsp;для&nbsp;остальных&nbsp;типов&nbsp;возвращается&nbsp;как&nbsp;есть.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(value,&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;value.copy()<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;value<br>
<br>
<br>
class&nbsp;TransformEditCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Команда&nbsp;изменения&nbsp;положения,&nbsp;ориентации&nbsp;и&nbsp;масштаба&nbsp;сущности<br>
&nbsp;&nbsp;&nbsp;&nbsp;через&nbsp;TransformInspector.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Ожидается,&nbsp;что&nbsp;transform&nbsp;принадлежит&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;(transform.entity&nbsp;is&nbsp;entity),&nbsp;а&nbsp;масштаб&nbsp;хранится&nbsp;в&nbsp;виде<br>
&nbsp;&nbsp;&nbsp;&nbsp;вектора&nbsp;длины&nbsp;3&nbsp;в&nbsp;Entity.scale.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform:&nbsp;Transform3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_pose:&nbsp;Pose3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_scale:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_pose:&nbsp;Pose3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_scale:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Transform&nbsp;change&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._transform&nbsp;=&nbsp;transform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity&nbsp;=&nbsp;transform.entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._old_pose&nbsp;=&nbsp;_clone_pose(old_pose)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._old_scale&nbsp;=&nbsp;np.asarray(old_scale,&nbsp;dtype=float).copy()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_pose&nbsp;=&nbsp;_clone_pose(new_pose)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_scale&nbsp;=&nbsp;np.asarray(new_scale,&nbsp;dtype=float).copy()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._entity&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.scale&nbsp;=&nbsp;self._new_scale<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._transform.relocate(self._new_pose)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._entity&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.scale&nbsp;=&nbsp;self._old_scale<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._transform.relocate(self._old_pose)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;merge_with(self,&nbsp;other:&nbsp;UndoCommand)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Склеивает&nbsp;серию&nbsp;мелких&nbsp;правок&nbsp;в&nbsp;одну&nbsp;команду.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Старое&nbsp;состояние&nbsp;остаётся&nbsp;состоянием&nbsp;до&nbsp;первого&nbsp;изменения,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;новое&nbsp;состояние&nbsp;—&nbsp;после&nbsp;последнего&nbsp;изменения.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;isinstance(other,&nbsp;TransformEditCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;other._transform&nbsp;is&nbsp;not&nbsp;self._transform:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_pose&nbsp;=&nbsp;_clone_pose(other._new_pose)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_scale&nbsp;=&nbsp;np.asarray(other._new_scale,&nbsp;dtype=float).copy()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;True<br>
<br>
<br>
class&nbsp;ComponentFieldEditCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Команда&nbsp;изменения&nbsp;значения&nbsp;одного&nbsp;поля&nbsp;компонента&nbsp;через&nbsp;инспектор.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Работает&nbsp;с&nbsp;объектом&nbsp;InspectField,&nbsp;который&nbsp;сам&nbsp;знает,<br>
&nbsp;&nbsp;&nbsp;&nbsp;как&nbsp;читать&nbsp;и&nbsp;записывать&nbsp;значение&nbsp;в&nbsp;компонент.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;component:&nbsp;Component,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;field:&nbsp;InspectField,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_value:&nbsp;Any,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_value:&nbsp;Any,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Component&nbsp;field&nbsp;change&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._component&nbsp;=&nbsp;component<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._field&nbsp;=&nbsp;field<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._old_value&nbsp;=&nbsp;_clone_value(old_value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_value&nbsp;=&nbsp;_clone_value(new_value)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;При&nbsp;каждом&nbsp;применении&nbsp;берём&nbsp;копию,&nbsp;чтобы&nbsp;не&nbsp;делиться<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;внутренними&nbsp;массивами&nbsp;между&nbsp;командой&nbsp;и&nbsp;объектом.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._field.set_value(self._component,&nbsp;_clone_value(self._new_value))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._field.set_value(self._component,&nbsp;_clone_value(self._old_value))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;merge_with(self,&nbsp;other:&nbsp;UndoCommand)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Склейка&nbsp;последовательных&nbsp;правок&nbsp;одного&nbsp;и&nbsp;того&nbsp;же&nbsp;поля<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;одного&nbsp;и&nbsp;того&nbsp;же&nbsp;компонента.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;isinstance(other,&nbsp;ComponentFieldEditCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;other._component&nbsp;is&nbsp;not&nbsp;self._component:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;other._field&nbsp;is&nbsp;not&nbsp;self._field:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._new_value&nbsp;=&nbsp;_clone_value(other._new_value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;True<br>
<br>
<br>
class&nbsp;AddComponentCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Добавление&nbsp;компонента&nbsp;к&nbsp;сущности.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;do()&nbsp;компонент&nbsp;добавляется,&nbsp;в&nbsp;undo()&nbsp;—&nbsp;удаляется.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Позиция&nbsp;компонента&nbsp;в&nbsp;списке&nbsp;может&nbsp;немного&nbsp;&quot;плавать&quot;,&nbsp;если<br>
&nbsp;&nbsp;&nbsp;&nbsp;между&nbsp;командами&nbsp;сильно&nbsp;менялась&nbsp;структура,&nbsp;но&nbsp;базовый&nbsp;сценарий<br>
&nbsp;&nbsp;&nbsp;&nbsp;(откат&nbsp;сразу&nbsp;после&nbsp;добавления)&nbsp;поддерживается&nbsp;корректно.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entity:&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;component:&nbsp;Component,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Add&nbsp;component&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity&nbsp;=&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._component&nbsp;=&nbsp;component<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Entity.components&nbsp;возвращает&nbsp;копию&nbsp;списка,&nbsp;поэтому<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;проверка&nbsp;&quot;компонент&nbsp;уже&nbsp;добавлен&quot;&nbsp;безопасна.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._component&nbsp;not&nbsp;in&nbsp;self._entity.components:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.add_component(self._component)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.remove_component(self._component)<br>
<br>
<br>
class&nbsp;RemoveComponentCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Удаление&nbsp;компонента&nbsp;из&nbsp;сущности.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;do()&nbsp;компонент&nbsp;удаляется,&nbsp;в&nbsp;undo()&nbsp;—&nbsp;добавляется&nbsp;обратно.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entity:&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;component:&nbsp;Component,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Remove&nbsp;component&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity&nbsp;=&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._component&nbsp;=&nbsp;component<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.remove_component(self._component)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Если&nbsp;кто-то&nbsp;уже&nbsp;вернул&nbsp;компонент&nbsp;руками&nbsp;—&nbsp;лишний&nbsp;раз<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;не&nbsp;добавляем.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._component&nbsp;not&nbsp;in&nbsp;self._entity.components:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.add_component(self._component)<br>
<br>
<br>
class&nbsp;AddEntityCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Добавление&nbsp;сущности&nbsp;в&nbsp;сцену.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;do()&nbsp;сущность&nbsp;добавляется,&nbsp;в&nbsp;undo()&nbsp;—&nbsp;удаляется.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entity:&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_transform:&nbsp;Transform3&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Add&nbsp;entity&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene&nbsp;=&nbsp;scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity&nbsp;=&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._parent_transform&nbsp;=&nbsp;parent_transform<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;entity(self)&nbsp;-&gt;&nbsp;Entity:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._entity<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;parent_entity(self)&nbsp;-&gt;&nbsp;Entity&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._parent_transform&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;getattr(self._parent_transform,&nbsp;&quot;entity&quot;,&nbsp;None)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._parent_transform&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.transform.set_parent(self._parent_transform)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities&nbsp;=&nbsp;getattr(self._scene,&nbsp;&quot;entities&quot;,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene_entities&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;self._entity&nbsp;in&nbsp;scene_entities:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(self._scene,&nbsp;&quot;add&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene.add(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;scene_entities&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities.append(self._entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(self._scene,&nbsp;&quot;remove&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene.remove(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities&nbsp;=&nbsp;getattr(self._scene,&nbsp;&quot;entities&quot;,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene_entities&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities.remove(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.on_removed()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;ValueError:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
<br>
class&nbsp;DeleteEntityCommand(UndoCommand):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Удаление&nbsp;сущности&nbsp;из&nbsp;сцены.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;do()&nbsp;сущность&nbsp;удаляется,&nbsp;в&nbsp;undo()&nbsp;—&nbsp;добавляется&nbsp;обратно.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entity:&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;Delete&nbsp;entity&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene&nbsp;=&nbsp;scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity&nbsp;=&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tf&nbsp;=&nbsp;getattr(entity,&nbsp;&quot;transform&quot;,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._parent_transform&nbsp;=&nbsp;getattr(tf,&nbsp;&quot;parent&quot;,&nbsp;None)&nbsp;if&nbsp;tf&nbsp;is&nbsp;not&nbsp;None&nbsp;else&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;entity(self)&nbsp;-&gt;&nbsp;Entity:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._entity<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;parent_entity(self)&nbsp;-&gt;&nbsp;Entity&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._parent_transform&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;getattr(self._parent_transform,&nbsp;&quot;entity&quot;,&nbsp;None)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(self._scene,&nbsp;&quot;remove&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene.remove(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities&nbsp;=&nbsp;getattr(self._scene,&nbsp;&quot;entities&quot;,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene_entities&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities.remove(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.on_removed()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;ValueError:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._parent_transform&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._entity.transform.set_parent(self._parent_transform)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities&nbsp;=&nbsp;getattr(self._scene,&nbsp;&quot;entities&quot;,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene_entities&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;self._entity&nbsp;in&nbsp;scene_entities:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(self._scene,&nbsp;&quot;add&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scene.add(self._entity)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;scene_entities&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_entities.append(self._entity)<br>
<br>
<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&quot;TransformEditCommand&quot;,<br>
&nbsp;&nbsp;&quot;ComponentFieldEditCommand&quot;,<br>
&nbsp;&nbsp;&quot;AddComponentCommand&quot;,<br>
&nbsp;&nbsp;&quot;RemoveComponentCommand&quot;,<br>
&nbsp;&nbsp;&quot;AddEntityCommand&quot;,<br>
&nbsp;&nbsp;&quot;DeleteEntityCommand&quot;,<br>
]<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;TransformEditCommand&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;ComponentFieldEditCommand&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;AddComponentCommand&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;RemoveComponentCommand&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;AddEntityCommand&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;DeleteEntityCommand&quot;,<br>
]<br>
<!-- END SCAT CODE -->
</body>
</html>
