<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/run_editor.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
import&nbsp;sys<br>
import&nbsp;time<br>
import&nbsp;warnings<br>
<br>
#&nbsp;Suppress&nbsp;SDL2&nbsp;informational&nbsp;warning&nbsp;about&nbsp;using&nbsp;pysdl2-dll&nbsp;binaries&nbsp;(Windows)<br>
warnings.filterwarnings(&quot;ignore&quot;,&nbsp;message=&quot;Using&nbsp;SDL2&nbsp;binaries&nbsp;from&nbsp;pysdl2-dll&quot;)<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;PyQt6.QtGui&nbsp;import&nbsp;QPalette,&nbsp;QColor<br>
from&nbsp;PyQt6.QtWidgets&nbsp;import&nbsp;QApplication<br>
from&nbsp;PyQt6&nbsp;import&nbsp;QtCore<br>
<br>
from&nbsp;termin.editor.editor_window&nbsp;import&nbsp;EditorWindow<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;GeneralPose3<br>
from&nbsp;termin.mesh.mesh&nbsp;import&nbsp;CubeMesh,&nbsp;CylinderMesh,&nbsp;Mesh3<br>
from&nbsp;termin.visualization.core.camera&nbsp;import&nbsp;PerspectiveCameraComponent,&nbsp;OrbitCameraController<br>
from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity<br>
from&nbsp;termin.visualization.core.material&nbsp;import&nbsp;Material<br>
from&nbsp;termin.visualization.core.scene&nbsp;import&nbsp;Scene<br>
from&nbsp;termin.visualization.core.world&nbsp;import&nbsp;VisualizationWorld<br>
from&nbsp;termin.visualization.platform.backends&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;OpenGLGraphicsBackend,<br>
&nbsp;&nbsp;&nbsp;&nbsp;set_default_graphics_backend,<br>
)<br>
from&nbsp;termin.visualization.platform.backends.sdl_embedded&nbsp;import&nbsp;SDLEmbeddedWindowBackend<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer<br>
from&nbsp;termin.visualization.render.components.light_component&nbsp;import&nbsp;LightComponent<br>
from&nbsp;termin.lighting&nbsp;import&nbsp;LightType,&nbsp;LightShadowParams<br>
<br>
<br>
def&nbsp;build_scene(world):<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.voxels.voxel_mesh&nbsp;import&nbsp;create_voxel_mesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;Scene(name=&quot;default&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.add_scene(scene)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene<br>
<br>
<br>
def&nbsp;apply_dark_palette(app:&nbsp;QApplication):<br>
&nbsp;&nbsp;&nbsp;&nbsp;app.setStyle(&quot;Fusion&quot;)&nbsp;&nbsp;#&nbsp;более&nbsp;аккуратный&nbsp;стиль,&nbsp;чем&nbsp;дефолтный<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette&nbsp;=&nbsp;QPalette()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Базовые&nbsp;цвета<br>
&nbsp;&nbsp;&nbsp;&nbsp;bg&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;QColor(30,&nbsp;30,&nbsp;30)<br>
&nbsp;&nbsp;&nbsp;&nbsp;window&nbsp;&nbsp;=&nbsp;QColor(37,&nbsp;37,&nbsp;38)<br>
&nbsp;&nbsp;&nbsp;&nbsp;base&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;QColor(45,&nbsp;45,&nbsp;48)<br>
&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;QColor(220,&nbsp;220,&nbsp;220)<br>
&nbsp;&nbsp;&nbsp;&nbsp;disabled_text&nbsp;=&nbsp;QColor(128,&nbsp;128,&nbsp;128)<br>
&nbsp;&nbsp;&nbsp;&nbsp;highlight&nbsp;=&nbsp;QColor(0,&nbsp;120,&nbsp;215)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.Window,&nbsp;window)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.WindowText,&nbsp;text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.Base,&nbsp;base)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.AlternateBase,&nbsp;bg)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.ToolTipBase,&nbsp;base)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.ToolTipText,&nbsp;text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.Text,&nbsp;text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.Button,&nbsp;window)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.ButtonText,&nbsp;text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.BrightText,&nbsp;QColor(255,&nbsp;0,&nbsp;0))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.Highlight,&nbsp;highlight)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorRole.HighlightedText,&nbsp;QColor(255,&nbsp;255,&nbsp;255))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Отключённые&nbsp;элементы<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorGroup.Disabled,&nbsp;QPalette.ColorRole.Text,&nbsp;disabled_text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorGroup.Disabled,&nbsp;QPalette.ColorRole.ButtonText,&nbsp;disabled_text)<br>
&nbsp;&nbsp;&nbsp;&nbsp;palette.setColor(QPalette.ColorGroup.Disabled,&nbsp;QPalette.ColorRole.WindowText,&nbsp;disabled_text)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;app.setPalette(palette)<br>
<br>
<br>
def&nbsp;run_editor(debug_resource:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;no_scene:&nbsp;bool&nbsp;=&nbsp;False):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Run&nbsp;the&nbsp;editor.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;debug_resource:&nbsp;If&nbsp;set,&nbsp;open&nbsp;framegraph&nbsp;debugger&nbsp;with&nbsp;this&nbsp;resource<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(e.g.,&nbsp;&quot;shadow_maps&quot;,&nbsp;&quot;color&quot;)&nbsp;from&nbsp;the&nbsp;first&nbsp;frame.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;no_scene:&nbsp;If&nbsp;True,&nbsp;start&nbsp;editor&nbsp;without&nbsp;any&nbsp;scene&nbsp;(no-scene&nbsp;mode).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;Qt&nbsp;application<br>
&nbsp;&nbsp;&nbsp;&nbsp;app&nbsp;=&nbsp;QApplication(sys.argv)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Initialize&nbsp;SDL&nbsp;once&nbsp;at&nbsp;startup<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;sdl2<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;sdl2.SDL_Init(sdl2.SDL_INIT_VIDEO)&nbsp;!=&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;RuntimeError(f&quot;Failed&nbsp;to&nbsp;initialize&nbsp;SDL:&nbsp;{sdl2.SDL_GetError()}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Setup&nbsp;graphics&nbsp;backend&nbsp;(singleton)<br>
&nbsp;&nbsp;&nbsp;&nbsp;graphics&nbsp;=&nbsp;OpenGLGraphicsBackend.get_instance()<br>
&nbsp;&nbsp;&nbsp;&nbsp;set_default_graphics_backend(graphics)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;SDL&nbsp;embedded&nbsp;backend&nbsp;for&nbsp;viewport&nbsp;rendering<br>
&nbsp;&nbsp;&nbsp;&nbsp;sdl_backend&nbsp;=&nbsp;SDLEmbeddedWindowBackend(graphics=graphics)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;world&nbsp;and&nbsp;scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;world&nbsp;=&nbsp;VisualizationWorld()<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;no_scene:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;build_scene(world)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Apply&nbsp;dark&nbsp;theme<br>
&nbsp;&nbsp;&nbsp;&nbsp;apply_dark_palette(app)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;editor&nbsp;window&nbsp;with&nbsp;SDL&nbsp;backend<br>
&nbsp;&nbsp;&nbsp;&nbsp;win&nbsp;=&nbsp;EditorWindow(world,&nbsp;scene,&nbsp;sdl_backend)<br>
&nbsp;&nbsp;&nbsp;&nbsp;win.showMaximized()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Process&nbsp;events&nbsp;to&nbsp;ensure&nbsp;window&nbsp;is&nbsp;visible<br>
&nbsp;&nbsp;&nbsp;&nbsp;app.processEvents()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Open&nbsp;debugger&nbsp;with&nbsp;specific&nbsp;resource&nbsp;if&nbsp;requested<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;debug_resource:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;win.open_framegraph_debugger(initial_resource=debug_resource)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.processEvents()&nbsp;&nbsp;#&nbsp;Process&nbsp;debugger&nbsp;show&nbsp;event<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Render&nbsp;first&nbsp;frame&nbsp;immediately&nbsp;to&nbsp;avoid&nbsp;showing&nbsp;uninitialized&nbsp;buffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;sdl_backend.poll_events()<br>
&nbsp;&nbsp;&nbsp;&nbsp;win.scene_manager.request_render()<br>
&nbsp;&nbsp;&nbsp;&nbsp;win.scene_manager.tick(0.016)&nbsp;&nbsp;#&nbsp;Render&nbsp;first&nbsp;frame<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Main&nbsp;render&nbsp;loop<br>
&nbsp;&nbsp;&nbsp;&nbsp;target_fps&nbsp;=&nbsp;60<br>
&nbsp;&nbsp;&nbsp;&nbsp;target_frame_time&nbsp;=&nbsp;1.0&nbsp;/&nbsp;target_fps<br>
&nbsp;&nbsp;&nbsp;&nbsp;last_time&nbsp;=&nbsp;time.perf_counter()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;not&nbsp;win.should_close():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current_time&nbsp;=&nbsp;time.perf_counter()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dt&nbsp;=&nbsp;current_time&nbsp;-&nbsp;last_time<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;last_time&nbsp;=&nbsp;current_time<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Process&nbsp;Qt&nbsp;events&nbsp;(UI,&nbsp;menus,&nbsp;dialogs,&nbsp;etc.)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;app.processEvents()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Process&nbsp;SDL&nbsp;events&nbsp;(viewport&nbsp;input)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sdl_backend.poll_events()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Tick&nbsp;editor&nbsp;(game&nbsp;mode&nbsp;update&nbsp;+&nbsp;render&nbsp;if&nbsp;needed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;win.scene_manager.tick(dt)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Frame&nbsp;limiting&nbsp;-&nbsp;sleep&nbsp;if&nbsp;we're&nbsp;ahead&nbsp;of&nbsp;schedule<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elapsed&nbsp;=&nbsp;time.perf_counter()&nbsp;-&nbsp;current_time<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;elapsed&nbsp;&lt;&nbsp;target_frame_time:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;time.sleep(target_frame_time&nbsp;-&nbsp;elapsed)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Cleanup<br>
&nbsp;&nbsp;&nbsp;&nbsp;sdl_backend.terminate()<br>
&nbsp;&nbsp;&nbsp;&nbsp;sdl2.SDL_Quit()<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;argparse<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser&nbsp;=&nbsp;argparse.ArgumentParser(description=&quot;Run&nbsp;termin&nbsp;editor&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--debug-resource&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Open&nbsp;framegraph&nbsp;debugger&nbsp;with&nbsp;this&nbsp;resource&nbsp;(e.g.,&nbsp;shadow_maps,&nbsp;color)&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--no-scene&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;action=&quot;store_true&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Start&nbsp;editor&nbsp;without&nbsp;opening&nbsp;a&nbsp;scene&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;args&nbsp;=&nbsp;parser.parse_args()<br>
&nbsp;&nbsp;&nbsp;&nbsp;run_editor(debug_resource=args.debug_resource,&nbsp;no_scene=args.no_scene)<br>
<!-- END SCAT CODE -->
</body>
</html>
