<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/undo_stack.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;List<br>
<br>
<br>
class&nbsp;UndoCommand:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Базовый&nbsp;класс&nbsp;команды&nbsp;для&nbsp;undo/redo.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Предполагается,&nbsp;что:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;do()&nbsp;приводит&nbsp;состояние&nbsp;в&nbsp;&quot;новое&quot;&nbsp;значение;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;undo()&nbsp;возвращает&nbsp;состояние&nbsp;к&nbsp;&quot;старому&quot;&nbsp;значению;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;merge_with()&nbsp;пытается&nbsp;слить&nbsp;другую&nbsp;команду&nbsp;в&nbsp;себя&nbsp;и&nbsp;вернуть&nbsp;True,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;если&nbsp;слияние&nbsp;удалось.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;text:&nbsp;str&nbsp;=&nbsp;&quot;&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.text&nbsp;=&nbsp;text<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;do(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;NotImplementedError<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;NotImplementedError<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;merge_with(self,&nbsp;other:&nbsp;&quot;UndoCommand&quot;)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Пытается&nbsp;поглотить&nbsp;соседнюю&nbsp;команду&nbsp;`other`,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;которая&nbsp;идёт&nbsp;сразу&nbsp;после&nbsp;текущей&nbsp;по&nbsp;времени.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;По&nbsp;умолчанию&nbsp;команды&nbsp;не&nbsp;сливаются.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
<br>
class&nbsp;UndoStack:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Простой&nbsp;стек&nbsp;undo/redo&nbsp;без&nbsp;привязки&nbsp;к&nbsp;GUI.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Ветви&nbsp;истории:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;_done&nbsp;&nbsp;&nbsp;—&nbsp;уже&nbsp;выполненные&nbsp;команды&nbsp;(можно&nbsp;откатить&nbsp;через&nbsp;undo);<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;_undone&nbsp;—&nbsp;отменённые&nbsp;команды&nbsp;(можно&nbsp;вернуть&nbsp;через&nbsp;redo).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;max_depth&nbsp;&gt;&nbsp;0&nbsp;ограничивает&nbsp;глубину&nbsp;истории:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;при&nbsp;переполнении&nbsp;отбрасывается&nbsp;самая&nbsp;старая&nbsp;выполненная&nbsp;команда;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;состояние&nbsp;при&nbsp;этом&nbsp;остаётся&nbsp;таким,&nbsp;какое&nbsp;сейчас&nbsp;есть,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;но&nbsp;вернуться&nbsp;&quot;ещё&nbsp;дальше&nbsp;назад&quot;&nbsp;уже&nbsp;нельзя.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;max_depth:&nbsp;int&nbsp;=&nbsp;1000)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;max_depth&nbsp;&lt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;max_depth&nbsp;must&nbsp;be&nbsp;non-negative&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done:&nbsp;List[UndoCommand]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undone:&nbsp;List[UndoCommand]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._max_depth&nbsp;=&nbsp;max_depth<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;can_undo(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;bool(self._done)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;can_redo(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;bool(self._undone)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;max_depth(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._max_depth<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clear(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Полностью&nbsp;очищает&nbsp;историю&nbsp;undo/redo.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Состояние&nbsp;объекта,&nbsp;над&nbsp;которым&nbsp;выполнялись&nbsp;команды,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;не&nbsp;трогается&nbsp;—&nbsp;ответственность&nbsp;вызывающего.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done.clear()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undone.clear()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;push(self,&nbsp;cmd:&nbsp;UndoCommand,&nbsp;merge:&nbsp;bool&nbsp;=&nbsp;False)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Добавляет&nbsp;новую&nbsp;команду&nbsp;в&nbsp;стек&nbsp;и&nbsp;выполняет&nbsp;её.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;merge&nbsp;==&nbsp;False:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;обычное&nbsp;поведение&nbsp;—&nbsp;команда&nbsp;добавляется&nbsp;в&nbsp;историю.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;merge&nbsp;==&nbsp;True:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;пытаемся&nbsp;слить&nbsp;команду&nbsp;с&nbsp;последней&nbsp;выполненной:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;если&nbsp;последняя&nbsp;команда&nbsp;self._done[-1].merge_with(cmd)&nbsp;вернула&nbsp;True,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;то:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;состояние&nbsp;объекта&nbsp;приводится&nbsp;к&nbsp;новому&nbsp;через&nbsp;cmd.do();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;сама&nbsp;команда&nbsp;cmd&nbsp;в&nbsp;историю&nbsp;не&nbsp;попадает;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*&nbsp;в&nbsp;истории&nbsp;остаётся&nbsp;старая&nbsp;команда,&nbsp;но&nbsp;с&nbsp;обновлённым<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;внутренним&nbsp;состоянием&nbsp;(после&nbsp;merge_with);<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;иначе&nbsp;работаем&nbsp;как&nbsp;при&nbsp;merge&nbsp;==&nbsp;False.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;любом&nbsp;случае&nbsp;ветка&nbsp;redo&nbsp;очищается.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;merge&nbsp;and&nbsp;self._done:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;last&nbsp;=&nbsp;self._done[-1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;last.merge_with(cmd):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Команда&nbsp;&quot;поглощена&quot;:&nbsp;применяем&nbsp;только&nbsp;новую&nbsp;часть,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;история&nbsp;redo&nbsp;всегда&nbsp;инвалидируется.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd.do()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undone.clear()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Обычное&nbsp;добавление&nbsp;новой&nbsp;команды<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd.do()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done.append(cmd)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ограничение&nbsp;глубины&nbsp;истории<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._max_depth&nbsp;&gt;&nbsp;0&nbsp;and&nbsp;len(self._done)&nbsp;&gt;&nbsp;self._max_depth:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Отбрасываем&nbsp;самую&nbsp;старую&nbsp;команду.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Её&nbsp;уже&nbsp;нельзя&nbsp;будет&nbsp;отменить,&nbsp;но&nbsp;состояние&nbsp;остаётся&nbsp;текущим.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done.pop(0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Любая&nbsp;новая&nbsp;команда&nbsp;инвалидирует&nbsp;ветку&nbsp;redo<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undone.clear()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;undo(self)&nbsp;-&gt;&nbsp;UndoCommand&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Откатывает&nbsp;последнюю&nbsp;выполненную&nbsp;команду,&nbsp;если&nbsp;такая&nbsp;есть.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает&nbsp;эту&nbsp;команду&nbsp;или&nbsp;None,&nbsp;если&nbsp;откатывать&nbsp;нечего.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self._done:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd&nbsp;=&nbsp;self._done.pop()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd.undo()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undone.append(cmd)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cmd<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;redo(self)&nbsp;-&gt;&nbsp;UndoCommand&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Повторно&nbsp;выполняет&nbsp;последнюю&nbsp;отменённую&nbsp;команду,&nbsp;если&nbsp;такая&nbsp;есть.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает&nbsp;эту&nbsp;команду&nbsp;или&nbsp;None,&nbsp;если&nbsp;повторять&nbsp;нечего.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self._undone:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd&nbsp;=&nbsp;self._undone.pop()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd.do()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done.append(cmd)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._max_depth&nbsp;&gt;&nbsp;0&nbsp;and&nbsp;len(self._done)&nbsp;&gt;&nbsp;self._max_depth:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Если&nbsp;при&nbsp;повторном&nbsp;применении&nbsp;переполнили&nbsp;историю,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;выкидываем&nbsp;самую&nbsp;старую&nbsp;команду.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._done.pop(0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cmd<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__len__(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Количество&nbsp;выполненных&nbsp;команд&nbsp;в&nbsp;истории&nbsp;(ветка&nbsp;undo).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;len(self._done)<br>
<!-- END SCAT CODE -->
</body>
</html>
