<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/undo_stack_viewer.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;Optional<br>
<br>
from&nbsp;PyQt5.QtCore&nbsp;import&nbsp;Qt<br>
from&nbsp;PyQt5.QtWidgets&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;QDialog,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QVBoxLayout,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QHBoxLayout,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QListWidget,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QLabel,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QPushButton,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QWidget,<br>
)<br>
<br>
from&nbsp;termin.editor.undo_stack&nbsp;import&nbsp;UndoStack,&nbsp;UndoCommand<br>
<br>
<br>
class&nbsp;UndoStackViewer(QDialog):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Простое&nbsp;отладочное&nbsp;окно,&nbsp;показывающее&nbsp;текущее&nbsp;содержимое&nbsp;undo/redo&nbsp;стека.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Запускается&nbsp;как&nbsp;отдельное&nbsp;top-level&nbsp;окно&nbsp;поверх&nbsp;главного&nbsp;редактора.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;undo_stack:&nbsp;UndoStack,&nbsp;parent:&nbsp;Optional[QWidget]&nbsp;=&nbsp;None,&nbsp;stack_changed_signal=None)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(parent)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undo_stack&nbsp;=&nbsp;undo_stack<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setWindowTitle(&quot;Undo/Redo&nbsp;Stack&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setMinimumSize(500,&nbsp;400)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setModal(False)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Не&nbsp;используем&nbsp;Qt.WA_WindowTitleHint&nbsp;—&nbsp;в&nbsp;PyQt5&nbsp;его&nbsp;нет<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Оставляем&nbsp;только&nbsp;управление&nbsp;удалением&nbsp;по&nbsp;закрытию<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.setAttribute(Qt.WA_DeleteOnClose,&nbsp;False)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout&nbsp;=&nbsp;QVBoxLayout(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header&nbsp;=&nbsp;QLabel(&quot;Отладочное&nbsp;окно.&nbsp;Показывает&nbsp;выполненные&nbsp;и&nbsp;отменённые&nbsp;команды&nbsp;undo/redo.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;header.setWordWrap(True)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout.addWidget(header)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lists_layout&nbsp;=&nbsp;QHBoxLayout()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout.addLayout(lists_layout)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done_container&nbsp;=&nbsp;QWidget(self)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done_layout&nbsp;=&nbsp;QVBoxLayout(done_container)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done_label&nbsp;=&nbsp;QLabel(&quot;Выполненные&nbsp;команды&nbsp;(Undo)&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.done_list&nbsp;=&nbsp;QListWidget()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done_layout.addWidget(done_label)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done_layout.addWidget(self.done_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lists_layout.addWidget(done_container)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone_container&nbsp;=&nbsp;QWidget(self)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone_layout&nbsp;=&nbsp;QVBoxLayout(undone_container)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone_label&nbsp;=&nbsp;QLabel(&quot;Отменённые&nbsp;команды&nbsp;(Redo)&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.undone_list&nbsp;=&nbsp;QListWidget()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone_layout.addWidget(undone_label)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone_layout.addWidget(self.undone_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lists_layout.addWidget(undone_container)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttons_layout&nbsp;=&nbsp;QHBoxLayout()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttons_layout.addStretch(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;refresh_button&nbsp;=&nbsp;QPushButton(&quot;Обновить&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;close_button&nbsp;=&nbsp;QPushButton(&quot;Закрыть&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttons_layout.addWidget(refresh_button)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;buttons_layout.addWidget(close_button)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout.addLayout(buttons_layout)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;refresh_button.clicked.connect(self.refresh)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;close_button.clicked.connect(self.close)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;stack_changed_signal&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stack_changed_signal.connect(self.refresh)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.refresh()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_format_command(self,&nbsp;index:&nbsp;int,&nbsp;cmd:&nbsp;UndoCommand,&nbsp;is_done:&nbsp;bool)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind&nbsp;=&nbsp;&quot;undo&quot;&nbsp;if&nbsp;is_done&nbsp;else&nbsp;&quot;redo&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text&nbsp;=&nbsp;getattr(cmd,&nbsp;&quot;text&quot;,&nbsp;&quot;&quot;)&nbsp;or&nbsp;cmd.__class__.__name__<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;f&quot;[{kind}&nbsp;#{index}]&nbsp;{text}&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;refresh(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Перечитывает&nbsp;содержимое&nbsp;undo/redo&nbsp;стека&nbsp;и&nbsp;обновляет&nbsp;списки.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.done_list.clear()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.undone_list.clear()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;done&nbsp;=&nbsp;getattr(self._undo_stack,&nbsp;&quot;_done&quot;,&nbsp;[])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;undone&nbsp;=&nbsp;getattr(self._undo_stack,&nbsp;&quot;_undone&quot;,&nbsp;[])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i,&nbsp;cmd&nbsp;in&nbsp;enumerate(done):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.done_list.addItem(self._format_command(i,&nbsp;cmd,&nbsp;True))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i,&nbsp;cmd&nbsp;in&nbsp;enumerate(undone):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.undone_list.addItem(self._format_command(i,&nbsp;cmd,&nbsp;False))<br>
<!-- END SCAT CODE -->
</body>
</html>
