<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/mesh/mesh.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Base&nbsp;mesh&nbsp;classes&nbsp;and&nbsp;vertex&nbsp;layout&nbsp;definitions.&quot;&quot;&quot;<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;enum&nbsp;import&nbsp;Enum<br>
<br>
from&nbsp;termin.mesh._mesh_native&nbsp;import&nbsp;Mesh3<br>
<br>
#&nbsp;GPU&nbsp;COMPATIBILITY<br>
<br>
class&nbsp;VertexAttribType(Enum):<br>
&nbsp;&nbsp;&nbsp;&nbsp;FLOAT32&nbsp;=&nbsp;&quot;float32&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;INT32&nbsp;=&nbsp;&quot;int32&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;UINT32&nbsp;=&nbsp;&quot;uint32&quot;<br>
<br>
class&nbsp;VertexAttribute:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;size,&nbsp;vtype:&nbsp;VertexAttribType,&nbsp;offset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.size&nbsp;=&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.vtype&nbsp;=&nbsp;vtype<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.offset&nbsp;=&nbsp;offset<br>
<br>
<br>
class&nbsp;VertexLayout:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;stride,&nbsp;attributes):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.stride&nbsp;=&nbsp;stride&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;размер&nbsp;одной&nbsp;вершины&nbsp;в&nbsp;байтах<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.attributes&nbsp;=&nbsp;attributes&nbsp;&nbsp;#&nbsp;список&nbsp;VertexAttribute<br>
<br>
<br>
class&nbsp;Mesh:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;vertices:&nbsp;np.ndarray,&nbsp;indices:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.vertices&nbsp;=&nbsp;np.asarray(vertices,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.indices&nbsp;&nbsp;=&nbsp;np.asarray(indices,&nbsp;&nbsp;dtype=np.uint32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.type&nbsp;=&nbsp;&quot;triangles&quot;&nbsp;if&nbsp;indices.shape[1]&nbsp;==&nbsp;3&nbsp;else&nbsp;&quot;lines&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._inter&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_vertex_layout(self)&nbsp;-&gt;&nbsp;VertexLayout:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;NotImplementedError(&quot;get_vertex_layout&nbsp;must&nbsp;be&nbsp;implemented&nbsp;in&nbsp;subclasses.&quot;)<br>
<br>
<br>
class&nbsp;Mesh2(Mesh):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Simple&nbsp;triangle&nbsp;mesh&nbsp;storing&nbsp;vertex&nbsp;positions&nbsp;and&nbsp;triangle&nbsp;indices.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_lists(vertices:&nbsp;list[tuple[float,&nbsp;float]],&nbsp;indices:&nbsp;list[tuple[int,&nbsp;int]])&nbsp;-&gt;&nbsp;&quot;Mesh2&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;verts&nbsp;=&nbsp;np.asarray(vertices,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;idx&nbsp;=&nbsp;np.asarray(indices,&nbsp;dtype=int)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Mesh2(verts,&nbsp;idx)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;vertices:&nbsp;np.ndarray,&nbsp;indices:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(vertices,&nbsp;indices)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._validate_mesh()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;copy(self)&nbsp;-&gt;&nbsp;&quot;Mesh2&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Mesh2(self.vertices.copy(),&nbsp;self.indices.copy())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_validate_mesh(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Ensure&nbsp;that&nbsp;the&nbsp;vertex/index&nbsp;arrays&nbsp;have&nbsp;correct&nbsp;shapes&nbsp;and&nbsp;bounds.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.vertices.ndim&nbsp;!=&nbsp;2&nbsp;or&nbsp;self.vertices.shape[1]&nbsp;!=&nbsp;3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Vertices&nbsp;must&nbsp;be&nbsp;a&nbsp;Nx3&nbsp;array.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.indices.ndim&nbsp;!=&nbsp;2&nbsp;or&nbsp;self.indices.shape[1]&nbsp;!=&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Indices&nbsp;must&nbsp;be&nbsp;a&nbsp;Mx2&nbsp;array.&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;interleaved_buffer(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.vertices.astype(np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_vertex_layout(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;VertexLayout(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stride=3*4,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attributes=[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;position&quot;,&nbsp;3,&nbsp;VertexAttribType.FLOAT32,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
#&nbsp;Add&nbsp;Python&nbsp;methods&nbsp;to&nbsp;native&nbsp;Mesh3<br>
<br>
def&nbsp;_mesh3_get_vertex_layout(self)&nbsp;-&gt;&nbsp;VertexLayout:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;vertex&nbsp;layout&nbsp;for&nbsp;Mesh3:&nbsp;pos(3)&nbsp;+&nbsp;normal(3)&nbsp;+&nbsp;uv(2).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;VertexLayout(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stride=8&nbsp;*&nbsp;4,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attributes=[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;position&quot;,&nbsp;3,&nbsp;VertexAttribType.FLOAT32,&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;normal&quot;,&nbsp;&nbsp;&nbsp;3,&nbsp;VertexAttribType.FLOAT32,&nbsp;12),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;uv&quot;,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2,&nbsp;VertexAttribType.FLOAT32,&nbsp;24),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
Mesh3.get_vertex_layout&nbsp;=&nbsp;_mesh3_get_vertex_layout<br>
<br>
<br>
#&nbsp;Helper&nbsp;functions&nbsp;for&nbsp;Mesh3<br>
<br>
def&nbsp;mesh3_vertex_layout()&nbsp;-&gt;&nbsp;VertexLayout:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;vertex&nbsp;layout&nbsp;for&nbsp;Mesh3:&nbsp;pos(3)&nbsp;+&nbsp;normal(3)&nbsp;+&nbsp;uv(2).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;VertexLayout(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stride=8&nbsp;*&nbsp;4,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attributes=[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;position&quot;,&nbsp;3,&nbsp;VertexAttribType.FLOAT32,&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;normal&quot;,&nbsp;&nbsp;&nbsp;3,&nbsp;VertexAttribType.FLOAT32,&nbsp;12),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VertexAttribute(&quot;uv&quot;,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2,&nbsp;VertexAttribType.FLOAT32,&nbsp;24),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
def&nbsp;mesh3_from_assimp(assimp_mesh)&nbsp;-&gt;&nbsp;Mesh3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Create&nbsp;Mesh3&nbsp;from&nbsp;assimp&nbsp;mesh.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;verts&nbsp;=&nbsp;np.asarray(assimp_mesh.vertices,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;idx&nbsp;=&nbsp;np.asarray(assimp_mesh.indices,&nbsp;dtype=np.uint32).reshape(-1,&nbsp;3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;uvs&nbsp;=&nbsp;np.asarray(assimp_mesh.uvs,&nbsp;dtype=np.float32)&nbsp;if&nbsp;assimp_mesh.uvs&nbsp;is&nbsp;not&nbsp;None&nbsp;else&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;mesh&nbsp;=&nbsp;Mesh3(verts,&nbsp;idx,&nbsp;uvs)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;assimp_mesh.normals&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh.vertex_normals&nbsp;=&nbsp;np.asarray(assimp_mesh.normals,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh.compute_vertex_normals()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mesh<br>
<br>
<br>
def&nbsp;mesh3_from_convex_hull(hull)&nbsp;-&gt;&nbsp;Mesh3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Create&nbsp;Mesh3&nbsp;from&nbsp;scipy.spatial.ConvexHull.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;hull.points.astype(np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;triangles&nbsp;=&nbsp;hull.simplices.astype(np.uint32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;np.mean(vertices,&nbsp;axis=0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(triangles.shape[0]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v0&nbsp;=&nbsp;vertices[triangles[i,&nbsp;0]]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;vertices[triangles[i,&nbsp;1]]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v2&nbsp;=&nbsp;vertices[triangles[i,&nbsp;2]]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal&nbsp;=&nbsp;np.cross(v1&nbsp;-&nbsp;v0,&nbsp;v2&nbsp;-&nbsp;v0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_center&nbsp;=&nbsp;center&nbsp;-&nbsp;v0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;np.dot(normal,&nbsp;to_center)&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;triangles[i,&nbsp;[1,&nbsp;2]]&nbsp;=&nbsp;triangles[i,&nbsp;[2,&nbsp;1]]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Mesh3(vertices,&nbsp;triangles)<br>
<br>
<br>
def&nbsp;show_mesh(mesh:&nbsp;Mesh3):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Show&nbsp;the&nbsp;mesh&nbsp;in&nbsp;a&nbsp;simple&nbsp;viewer&nbsp;application.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.mesh_viewer_miniapp&nbsp;import&nbsp;show_mesh_app<br>
&nbsp;&nbsp;&nbsp;&nbsp;show_mesh_app(mesh)<br>
<br>
<br>
#&nbsp;Re-export&nbsp;primitives&nbsp;for&nbsp;backward&nbsp;compatibility<br>
from&nbsp;.primitives&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;CubeMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TexturedCubeMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;UVSphereMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;IcoSphereMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PlaneMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;CylinderMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;ConeMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TorusMesh,<br>
&nbsp;&nbsp;&nbsp;&nbsp;RingMesh,<br>
)<br>
<!-- END SCAT CODE -->
</body>
</html>
