<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/assets/resources/_assets.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Asset&nbsp;management&nbsp;mixin&nbsp;for&nbsp;all&nbsp;resource&nbsp;types.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;Any,&nbsp;Dict,&nbsp;List,&nbsp;Optional,&nbsp;TYPE_CHECKING<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.material&nbsp;import&nbsp;Material<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.material_asset&nbsp;import&nbsp;MaterialAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.mesh_asset&nbsp;import&nbsp;MeshAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.mesh&nbsp;import&nbsp;TcMesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.texture_handle&nbsp;import&nbsp;TextureHandle<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.glb_asset&nbsp;import&nbsp;GLBAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.texture&nbsp;import&nbsp;Texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.texture_asset&nbsp;import&nbsp;TextureAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.shader_parser&nbsp;import&nbsp;ShaderMultyPhaseProgramm<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.shader_asset&nbsp;import&nbsp;ShaderAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.voxels.grid&nbsp;import&nbsp;VoxelGrid<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.voxel_grid_asset&nbsp;import&nbsp;VoxelGridAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.navmesh.types&nbsp;import&nbsp;NavMesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.navmesh_asset&nbsp;import&nbsp;NavMeshAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.animation.clip&nbsp;import&nbsp;TcAnimationClip<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.animation_clip_asset&nbsp;import&nbsp;AnimationClipAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.skeleton&nbsp;import&nbsp;TcSkeleton<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.skeleton_asset&nbsp;import&nbsp;SkeletonAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.prefab_asset&nbsp;import&nbsp;PrefabAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.kinematic.general_transform&nbsp;import&nbsp;GeneralTransform3<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.audio_clip_asset&nbsp;import&nbsp;AudioClipAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.audio_clip_handle&nbsp;import&nbsp;AudioClipHandle<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.asset&nbsp;import&nbsp;Asset<br>
<br>
<br>
class&nbsp;AssetsMixin:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Mixin&nbsp;for&nbsp;all&nbsp;asset&nbsp;type&nbsp;management&nbsp;methods.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Prefabs&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_prefab_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;PrefabAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;PrefabAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._prefab_assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_prefab(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;PrefabAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;PrefabAsset&nbsp;by&nbsp;name&nbsp;(alias&nbsp;for&nbsp;get_prefab_asset).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._prefab_assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_prefab_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;PrefabAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;PrefabAsset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.prefab_asset&nbsp;import&nbsp;PrefabAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets_by_uuid.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;isinstance(asset,&nbsp;PrefabAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_prefab(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset:&nbsp;&quot;PrefabAsset&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;a&nbsp;PrefabAsset.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._prefab_assets[name]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets_by_uuid[asset.uuid]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;source_path:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset._source_path&nbsp;=&nbsp;source_path<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_prefab_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;List&nbsp;all&nbsp;registered&nbsp;prefab&nbsp;names.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(self._prefab_assets.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_prefab_name(self,&nbsp;asset:&nbsp;&quot;PrefabAsset&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;name&nbsp;of&nbsp;a&nbsp;PrefabAsset.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;a&nbsp;in&nbsp;self._prefab_assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;a&nbsp;is&nbsp;asset:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_prefab_uuid(self,&nbsp;asset:&nbsp;&quot;PrefabAsset&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;UUID&nbsp;of&nbsp;a&nbsp;PrefabAsset.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.uuid&nbsp;if&nbsp;asset&nbsp;else&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;instantiate_prefab(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name_or_uuid:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;&quot;GeneralTransform3&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;position:&nbsp;tuple[float,&nbsp;float,&nbsp;float]&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;instance_name:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;Optional[&quot;Entity&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Instantiate&nbsp;a&nbsp;prefab&nbsp;by&nbsp;name&nbsp;or&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._prefab_assets.get(name_or_uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self.get_prefab_by_uuid(name_or_uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;asset.is_loaded:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset.ensure_loaded()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.instantiate(parent=parent,&nbsp;position=position,&nbsp;name=instance_name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_prefab(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Remove&nbsp;prefab&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._prefab_assets.pop(name,&nbsp;None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets_by_uuid.pop(asset.uuid,&nbsp;None)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_glsl(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;GLSL&nbsp;source&nbsp;by&nbsp;include&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._glsl_registry.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_glb_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;GLBAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;GLBAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._glb_assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;Asset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;any&nbsp;Asset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._assets_by_uuid.get(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Materials&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_material_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;MaterialAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;MaterialAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._material_assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_material(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;mat:&nbsp;&quot;Material&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;a&nbsp;material.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.material_asset&nbsp;import&nbsp;MaterialAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;MaterialAsset.from_material(mat,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._material_assets[name]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets_by_uuid[asset.uuid]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials[name]&nbsp;=&nbsp;mat<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_material(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;&quot;Material&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get&nbsp;material&nbsp;by&nbsp;name&nbsp;(lazy&nbsp;loading).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Returns&nbsp;UnknownMaterial&nbsp;if&nbsp;material&nbsp;is&nbsp;not&nbsp;found&nbsp;or&nbsp;failed&nbsp;to&nbsp;load.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.materials.unknown_material&nbsp;import&nbsp;UnknownMaterial<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;self.materials.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mat<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._material_assets.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;asset.ensure_loaded():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials[name]&nbsp;=&nbsp;asset.material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_material_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;names&nbsp;=&nbsp;set(self._material_assets.keys())&nbsp;|&nbsp;set(self.materials.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(names)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_material_name(self,&nbsp;mat:&nbsp;&quot;Material&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;asset&nbsp;in&nbsp;self._material_assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;mat:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;n,&nbsp;m&nbsp;in&nbsp;self.materials.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;m&nbsp;is&nbsp;mat:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;n<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_material_uuid(self,&nbsp;mat:&nbsp;&quot;Material&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;asset&nbsp;in&nbsp;self._material_assets.values():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;mat:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_material_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;&quot;Material&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get&nbsp;Material&nbsp;by&nbsp;UUID&nbsp;(lazy&nbsp;loading).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Returns&nbsp;UnknownMaterial&nbsp;if&nbsp;material&nbsp;is&nbsp;not&nbsp;found&nbsp;or&nbsp;failed&nbsp;to&nbsp;load.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.material_asset&nbsp;import&nbsp;MaterialAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.materials.unknown_material&nbsp;import&nbsp;UnknownMaterial<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets_by_uuid.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;isinstance(asset,&nbsp;MaterialAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(f&quot;uuid:{uuid}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;asset.ensure_loaded():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(asset.name&nbsp;or&nbsp;f&quot;uuid:{uuid}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.material&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials[asset.name]&nbsp;=&nbsp;asset.material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UnknownMaterial.for_missing_material(asset.name&nbsp;or&nbsp;f&quot;uuid:{uuid}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_material_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;MaterialAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;MaterialAsset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.material_asset&nbsp;import&nbsp;MaterialAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets_by_uuid.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;isinstance(asset,&nbsp;MaterialAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_texture_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TextureAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;TextureAsset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.texture_asset&nbsp;import&nbsp;TextureAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets_by_uuid.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;isinstance(asset,&nbsp;TextureAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Shaders&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_shader_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;ShaderAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;ShaderAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._shader_assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_shader(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;shader:&nbsp;&quot;ShaderMultyPhaseProgramm&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;a&nbsp;shader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.shader_asset&nbsp;import&nbsp;ShaderAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;ShaderAsset.from_program(shader,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._shader_assets[name]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets_by_uuid[asset.uuid]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shaders[name]&nbsp;=&nbsp;shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;source_path:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shader.source_path&nbsp;=&nbsp;source_path<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_shader(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;ShaderMultyPhaseProgramm&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;shader&nbsp;by&nbsp;name&nbsp;(lazy&nbsp;loading).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shader&nbsp;=&nbsp;self.shaders.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;shader&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._shader_assets.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.program&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;asset.ensure_loaded():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.program&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shaders[name]&nbsp;=&nbsp;asset.program<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.program<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_shader_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;ShaderMultyPhaseProgramm&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;shader&nbsp;by&nbsp;UUID&nbsp;(lazy&nbsp;loading).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.shader_asset&nbsp;import&nbsp;ShaderAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets_by_uuid.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;isinstance(asset,&nbsp;ShaderAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.program&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;asset.ensure_loaded():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.program<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_shader_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;names&nbsp;=&nbsp;set(self._shader_assets.keys())&nbsp;|&nbsp;set(self.shaders.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(names)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_default_shader(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;DefaultShader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_default_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register_default_shader(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_pbr_shader(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;PBR&nbsp;shader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_pbr_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register_pbr_shader(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_advanced_pbr_shader(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;Advanced&nbsp;PBR&nbsp;shader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_advanced_pbr_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register_advanced_pbr_shader(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_skinned_shader(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;SkinnedShader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_skinned_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register_skinned_shader(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_builtin_materials(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;materials.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_builtin_materials<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;register_builtin_materials(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_builtin_meshes(self)&nbsp;-&gt;&nbsp;List[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;builtin&nbsp;primitive&nbsp;meshes.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.builtin_resources&nbsp;import&nbsp;register_builtin_meshes<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;register_builtin_meshes(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Meshes&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_mesh_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;MeshAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;MeshAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_mesh_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;asset:&nbsp;&quot;MeshAsset&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;MeshAsset.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mesh_registry.register(name,&nbsp;asset,&nbsp;source_path,&nbsp;uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_mesh(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TcMesh&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;TcMesh&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_mesh_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(self._mesh_assets.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_mesh_name(self,&nbsp;mesh:&nbsp;&quot;TcMesh&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;mesh&nbsp;name&nbsp;by&nbsp;TcMesh.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name&nbsp;=&nbsp;self._mesh_registry.find_name(mesh)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh.is_valid&nbsp;and&nbsp;mesh.name&nbsp;and&nbsp;mesh.name&nbsp;in&nbsp;self._mesh_assets:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mesh.name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_mesh_uuid(self,&nbsp;mesh:&nbsp;&quot;TcMesh&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;mesh&nbsp;UUID&nbsp;by&nbsp;TcMesh.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.find_uuid(mesh)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_mesh_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TcMesh&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;TcMesh&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.get_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_mesh_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;MeshAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;MeshAsset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_or_create_mesh_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;&quot;Asset&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_key:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;MeshAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;MeshAsset&nbsp;by&nbsp;name,&nbsp;creating&nbsp;if&nbsp;needed.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh_registry.get_or_create_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid,&nbsp;parent=parent,&nbsp;parent_key=parent_key,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_mesh(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Remove&nbsp;mesh.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mesh_registry.unregister(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Voxel&nbsp;Grids&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_voxel_grid_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;VoxelGridAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;VoxelGridAsset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._voxel_grid_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_voxel_grid(self,&nbsp;name:&nbsp;str,&nbsp;grid:&nbsp;&quot;VoxelGrid&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Register&nbsp;voxel&nbsp;grid.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.voxel_grid_asset&nbsp;import&nbsp;VoxelGridAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;existing_asset&nbsp;=&nbsp;self._voxel_grid_registry.get_asset(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;existing_asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;existing_asset.data&nbsp;=&nbsp;grid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.voxel_grids[name]&nbsp;=&nbsp;grid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;VoxelGridAsset.from_grid(grid,&nbsp;name=name,&nbsp;source_path=source_path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._voxel_grid_registry.register(name,&nbsp;asset,&nbsp;source_path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.voxel_grids[name]&nbsp;=&nbsp;grid<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_voxel_grid(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;VoxelGrid&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;voxel&nbsp;grid&nbsp;by&nbsp;name&nbsp;(lazy&nbsp;loading).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid&nbsp;=&nbsp;self.voxel_grids.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;grid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;grid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid&nbsp;=&nbsp;self._voxel_grid_registry.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;grid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.voxel_grids[name]&nbsp;=&nbsp;grid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;grid<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_voxel_grid_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._voxel_grid_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_voxel_grid_name(self,&nbsp;grid:&nbsp;&quot;VoxelGrid&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._voxel_grid_registry.find_name(grid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_voxel_grid_uuid(self,&nbsp;grid:&nbsp;&quot;VoxelGrid&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._voxel_grid_registry.find_uuid(grid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_voxel_grid_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;VoxelGrid&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid&nbsp;=&nbsp;self._voxel_grid_registry.get_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;grid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._voxel_grid_registry.get_asset_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;asset.name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.voxel_grids[asset.name]&nbsp;=&nbsp;grid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;grid<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_voxel_grid_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;VoxelGridAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._voxel_grid_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_voxel_grid(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._voxel_grid_registry.unregister(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;name&nbsp;in&nbsp;self.voxel_grids:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self.voxel_grids[name]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;NavMeshes&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_navmesh_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;NavMeshAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._navmesh_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_navmesh(self,&nbsp;name:&nbsp;str,&nbsp;navmesh:&nbsp;&quot;NavMesh&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.navmesh_asset&nbsp;import&nbsp;NavMeshAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;navmesh.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;NavMeshAsset.from_navmesh(navmesh,&nbsp;name=name,&nbsp;source_path=source_path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._navmesh_registry.register(name,&nbsp;asset,&nbsp;source_path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.navmeshes[name]&nbsp;=&nbsp;navmesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_navmesh(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;NavMesh&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;navmesh&nbsp;=&nbsp;self.navmeshes.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;navmesh&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;navmesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;navmesh&nbsp;=&nbsp;self._navmesh_registry.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;navmesh&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.navmeshes[name]&nbsp;=&nbsp;navmesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;navmesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_navmesh_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._navmesh_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_navmesh_name(self,&nbsp;navmesh:&nbsp;&quot;NavMesh&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._navmesh_registry.find_name(navmesh)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_navmesh_uuid(self,&nbsp;navmesh:&nbsp;&quot;NavMesh&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._navmesh_registry.find_uuid(navmesh)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_navmesh_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;NavMesh&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;navmesh&nbsp;=&nbsp;self._navmesh_registry.get_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;navmesh&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._navmesh_registry.get_asset_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;asset.name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.navmeshes[asset.name]&nbsp;=&nbsp;navmesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;navmesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_navmesh_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;NavMeshAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._navmesh_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_navmesh(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._navmesh_registry.unregister(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;name&nbsp;in&nbsp;self.navmeshes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self.navmeshes[name]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Animation&nbsp;Clips&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_animation_clip_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AnimationClipAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_animation_clip(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;clip:&nbsp;&quot;TcAnimationClip&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.animation_clip_asset&nbsp;import&nbsp;AnimationClipAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;AnimationClipAsset(clip=clip,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._animation_clip_registry.register(name,&nbsp;asset,&nbsp;source_path,&nbsp;uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.animation_clips[name]&nbsp;=&nbsp;clip<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_animation_clip(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TcAnimationClip&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;clip&nbsp;=&nbsp;self.animation_clips.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;clip&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;clip<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_animation_clip_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AnimationClipAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_or_create_animation_clip_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;&quot;Asset&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_key:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;AnimationClipAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.get_or_create_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid,&nbsp;parent=parent,&nbsp;parent_key=parent_key,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_animation_clip_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_animation_clip_name(self,&nbsp;clip:&nbsp;&quot;TcAnimationClip&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._animation_clip_registry.find_name(clip)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_animation_clip(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._animation_clip_registry.unregister(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;name&nbsp;in&nbsp;self.animation_clips:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self.animation_clips[name]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Skeletons&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_skeleton_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;SkeletonAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_skeleton(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;skeleton:&nbsp;&quot;TcSkeleton&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.skeleton_asset&nbsp;import&nbsp;SkeletonAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;SkeletonAsset.from_tc_skeleton(skeleton,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._skeleton_registry.register(name,&nbsp;asset,&nbsp;source_path,&nbsp;uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.skeletons[name]&nbsp;=&nbsp;skeleton<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_skeleton(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TcSkeleton&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skeleton&nbsp;=&nbsp;self.skeletons.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;skeleton&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;skeleton<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skeleton&nbsp;=&nbsp;self._skeleton_registry.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;skeleton&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.skeletons[name]&nbsp;=&nbsp;skeleton<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;skeleton<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_skeleton_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_skeleton_name(self,&nbsp;skeleton:&nbsp;&quot;TcSkeleton&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.find_name(skeleton)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_skeleton_uuid(self,&nbsp;skeleton:&nbsp;&quot;TcSkeleton&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.find_uuid(skeleton)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_skeleton_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TcSkeleton&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;skeleton&nbsp;=&nbsp;self._skeleton_registry.get_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;skeleton&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._skeleton_registry.get_asset_by_uuid(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;asset.name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.skeletons[asset.name]&nbsp;=&nbsp;skeleton<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;skeleton<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_skeleton_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;SkeletonAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_or_create_skeleton_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;&quot;Asset&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_key:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;SkeletonAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._skeleton_registry.get_or_create_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid,&nbsp;parent=parent,&nbsp;parent_key=parent_key,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_skeleton(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._skeleton_registry.unregister(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;name&nbsp;in&nbsp;self.skeletons:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self.skeletons[name]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Audio&nbsp;Clips&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_audio_clip_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AudioClipAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_audio_clip(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AudioClipHandle&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_audio_clip_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;asset:&nbsp;&quot;AudioClipAsset&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._audio_clip_registry.register(name,&nbsp;asset,&nbsp;source_path,&nbsp;uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_audio_clip_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_audio_clip_name(self,&nbsp;handle:&nbsp;&quot;AudioClipHandle&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.find_name(handle)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_audio_clip_uuid(self,&nbsp;handle:&nbsp;&quot;AudioClipHandle&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.find_uuid(handle)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_audio_clip_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AudioClipHandle&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.get_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_audio_clip_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;AudioClipAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_or_create_audio_clip_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;AudioClipAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._audio_clip_registry.get_or_create_asset(name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_audio_clip(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._audio_clip_registry.unregister(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;UI&nbsp;Layouts&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_ui_asset(self,&nbsp;name:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._ui_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_ui_handle(self,&nbsp;name:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.ui_handle&nbsp;import&nbsp;UIHandle<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._ui_registry.get_asset(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;UIHandle.from_asset(asset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_ui_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._ui_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_ui_asset_by_uuid(self,&nbsp;uuid:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._ui_registry.get_asset_by_uuid(uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_ui(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ui_registry.unregister(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Textures&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_texture_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TextureAsset&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._texture_registry.get_asset(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_texture_handle(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;TextureHandle&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._texture_registry.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_texture(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;Texture&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.texture&nbsp;import&nbsp;Texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._texture_registry.get_asset(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Texture.from_asset(asset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_texture_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;name:&nbsp;str,&nbsp;asset:&nbsp;&quot;TextureAsset&quot;,&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._texture_registry.register(name,&nbsp;asset,&nbsp;source_path,&nbsp;uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_texture_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._texture_registry.list_names()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_texture_name(self,&nbsp;texture)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.texture_handle&nbsp;import&nbsp;TextureHandle<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.texture&nbsp;import&nbsp;TcTexture<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(texture,&nbsp;TextureHandle):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Get&nbsp;asset&nbsp;from&nbsp;handle&nbsp;and&nbsp;compare&nbsp;by&nbsp;uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;texture.asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;not&nbsp;isinstance(asset,&nbsp;type(None)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_uuid&nbsp;=&nbsp;asset.uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;a&nbsp;in&nbsp;self._texture_registry.assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;a.uuid&nbsp;==&nbsp;asset_uuid:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;(AttributeError,&nbsp;TypeError):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Fallback&nbsp;to&nbsp;registry&nbsp;method<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._texture_registry.find_name(texture)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;isinstance(texture,&nbsp;TcTexture):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;TcTexture&nbsp;from&nbsp;material&nbsp;bindings&nbsp;-&nbsp;find&nbsp;by&nbsp;uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex_uuid&nbsp;=&nbsp;texture.uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex_uuid:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;a&nbsp;in&nbsp;self._texture_registry.assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;a.uuid&nbsp;==&nbsp;tex_uuid:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Fallback&nbsp;to&nbsp;name&nbsp;match<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex_name&nbsp;=&nbsp;texture.name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex_name&nbsp;and&nbsp;tex_name&nbsp;in&nbsp;self._texture_registry.assets:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tex_name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;n,&nbsp;a&nbsp;in&nbsp;self._texture_assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;a&nbsp;is&nbsp;texture:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;n<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister_texture(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._texture_registry.unregister(name)<br>
<!-- END SCAT CODE -->
</body>
</html>
