<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/navmesh/region_growing.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Region&nbsp;Growing&nbsp;алгоритмы&nbsp;для&nbsp;построения&nbsp;NavMesh.<br>
<br>
Группировка&nbsp;поверхностных&nbsp;вокселей&nbsp;в&nbsp;регионы&nbsp;по&nbsp;схожести&nbsp;нормалей.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;collections&nbsp;import&nbsp;deque<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.voxels.grid&nbsp;import&nbsp;VoxelGrid<br>
<br>
<br>
#&nbsp;6-связность&nbsp;для&nbsp;3D&nbsp;(только&nbsp;по&nbsp;осям)<br>
NEIGHBORS_6&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;(1,&nbsp;0,&nbsp;0),&nbsp;(-1,&nbsp;0,&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;(0,&nbsp;1,&nbsp;0),&nbsp;(0,&nbsp;-1,&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;(0,&nbsp;0,&nbsp;1),&nbsp;(0,&nbsp;0,&nbsp;-1),<br>
]<br>
<br>
#&nbsp;26-связность&nbsp;для&nbsp;3D&nbsp;(все&nbsp;соседи&nbsp;включая&nbsp;диагональные)<br>
NEIGHBORS_26&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;(dx,&nbsp;dy,&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx&nbsp;in&nbsp;(-1,&nbsp;0,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dy&nbsp;in&nbsp;(-1,&nbsp;0,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dz&nbsp;in&nbsp;(-1,&nbsp;0,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(dx,&nbsp;dy,&nbsp;dz)&nbsp;!=&nbsp;(0,&nbsp;0,&nbsp;0)<br>
]<br>
<br>
<br>
def&nbsp;collect_surface_voxels(<br>
&nbsp;&nbsp;&nbsp;&nbsp;grid:&nbsp;VoxelGrid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;max_slope_cos:&nbsp;float&nbsp;=&nbsp;0.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;up_axis:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
)&nbsp;-&gt;&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;1:&nbsp;Собрать&nbsp;поверхностные&nbsp;воксели&nbsp;с&nbsp;нормалями.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid:&nbsp;Воксельная&nbsp;сетка.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max_slope_cos:&nbsp;Косинус&nbsp;максимального&nbsp;угла&nbsp;наклона&nbsp;(0&nbsp;=&nbsp;без&nbsp;фильтрации).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Например:&nbsp;cos(45°)&nbsp;≈&nbsp;0.707,&nbsp;cos(60°)&nbsp;=&nbsp;0.5.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up_axis:&nbsp;Вектор&nbsp;&quot;вверх&quot;&nbsp;для&nbsp;проверки&nbsp;наклона.&nbsp;По&nbsp;умолчанию&nbsp;(0,&nbsp;0,&nbsp;1).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{(vx,&nbsp;vy,&nbsp;vz):&nbsp;[normal,&nbsp;...]}&nbsp;для&nbsp;всех&nbsp;проходимых&nbsp;поверхностных&nbsp;вокселей.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;up_axis&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up_axis&nbsp;=&nbsp;np.array([0.0,&nbsp;0.0,&nbsp;1.0],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;result:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]]&nbsp;=&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;coord,&nbsp;normals_list&nbsp;in&nbsp;grid.surface_normals.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;grid.get(*coord)&nbsp;!=&nbsp;0&nbsp;and&nbsp;normals_list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Фильтрация&nbsp;по&nbsp;углу&nbsp;наклона<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;max_slope_cos&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверяем&nbsp;первую&nbsp;нормаль&nbsp;(основную)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal&nbsp;=&nbsp;normals_list[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dot&nbsp;=&nbsp;float(np.dot(normal,&nbsp;up_axis))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;dot&nbsp;&lt;&nbsp;max_slope_cos:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Слишком&nbsp;крутой&nbsp;склон&nbsp;—&nbsp;непроходим<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result[coord]&nbsp;=&nbsp;normals_list<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;region_growing_basic(<br>
&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2:&nbsp;Группировка&nbsp;вокселей&nbsp;методом&nbsp;Region&nbsp;Growing.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Использует&nbsp;первую&nbsp;нормаль&nbsp;из&nbsp;списка&nbsp;для&nbsp;начального&nbsp;роста&nbsp;региона.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;{(vx,&nbsp;vy,&nbsp;vz):&nbsp;[normal,&nbsp;...]}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;Порог&nbsp;dot&nbsp;product&nbsp;для&nbsp;совместимости&nbsp;нормалей.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Список&nbsp;(список&nbsp;вокселей,&nbsp;усреднённая&nbsp;нормаль).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;remaining&nbsp;=&nbsp;set(surface_voxels.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;remaining:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seed&nbsp;=&nbsp;next(iter(remaining))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seed_normal&nbsp;=&nbsp;surface_voxels[seed][0]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region:&nbsp;list[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_sum&nbsp;=&nbsp;np.zeros(3,&nbsp;dtype=np.float64)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;queue:&nbsp;deque[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;deque([seed])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;remaining.remove(seed)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;queue:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current&nbsp;=&nbsp;queue.popleft()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current_normal&nbsp;=&nbsp;surface_voxels[current][0]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dot&nbsp;=&nbsp;np.dot(seed_normal,&nbsp;current_normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;dot&nbsp;&lt;&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;remaining.add(current)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region.append(current)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_sum&nbsp;+=&nbsp;current_normal<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;current<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;remaining:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;remaining.remove(neighbor)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;queue.append(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;region:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;avg_normal&nbsp;=&nbsp;normal_sum&nbsp;/&nbsp;len(region)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm&nbsp;=&nbsp;np.linalg.norm(avg_normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm&nbsp;&gt;&nbsp;1e-6:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;avg_normal&nbsp;/=&nbsp;norm<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;regions.append((region,&nbsp;avg_normal.astype(np.float32)))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;regions<br>
<br>
<br>
def&nbsp;greedy_absorption(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.3:&nbsp;Жадное&nbsp;поглощение&nbsp;—&nbsp;большие&nbsp;регионы&nbsp;поглощают&nbsp;воксели&nbsp;меньших.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;Список&nbsp;(воксели,&nbsp;нормаль).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;{(vx,&nbsp;vy,&nbsp;vz):&nbsp;[normal,&nbsp;...]}.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;Порог&nbsp;совместимости&nbsp;нормалей.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Обновлённый&nbsp;список&nbsp;регионов.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(regions)&nbsp;&lt;=&nbsp;1:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;regions<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_sets:&nbsp;list[set[tuple[int,&nbsp;int,&nbsp;int]]]&nbsp;=&nbsp;[set(voxels)&nbsp;for&nbsp;voxels,&nbsp;_&nbsp;in&nbsp;regions]<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_normals:&nbsp;list[np.ndarray]&nbsp;=&nbsp;[normal.copy()&nbsp;for&nbsp;_,&nbsp;normal&nbsp;in&nbsp;regions]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_region:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;int]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx,&nbsp;voxel_set&nbsp;in&nbsp;enumerate(region_sets):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v&nbsp;in&nbsp;voxel_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_region[v]&nbsp;=&nbsp;idx<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sorted_indices&nbsp;=&nbsp;sorted(range(len(regions)),&nbsp;key=lambda&nbsp;i:&nbsp;len(region_sets[i]),&nbsp;reverse=True)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;total_absorbed&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;total_pruned&nbsp;=&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;rank,&nbsp;region_idx&nbsp;in&nbsp;enumerate(sorted_indices):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_normal&nbsp;=&nbsp;region_normals[region_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set&nbsp;=&nbsp;region_sets[region_idx]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(region_set)&nbsp;==&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current_size&nbsp;=&nbsp;len(region_set)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;absorbed_this_region&nbsp;=&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;changed:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary_neighbors:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;not&nbsp;in&nbsp;region_set&nbsp;and&nbsp;neighbor&nbsp;in&nbsp;surface_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary_neighbors.add(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_absorb:&nbsp;list[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;neighbor&nbsp;in&nbsp;boundary_neighbors:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;voxel_to_region:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_region_idx&nbsp;=&nbsp;voxel_to_region[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_region_size&nbsp;=&nbsp;len(region_sets[neighbor_region_idx])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor_region_size&nbsp;&gt;=&nbsp;current_size:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_normals&nbsp;=&nbsp;surface_voxels[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compatible&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;normal&nbsp;in&nbsp;neighbor_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dot&nbsp;=&nbsp;np.dot(region_normal,&nbsp;normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;dot&nbsp;&gt;=&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;compatible&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;compatible:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_absorb.append(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;to_absorb:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;voxel&nbsp;in&nbsp;voxel_to_region:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_region_idx&nbsp;=&nbsp;voxel_to_region[voxel]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_sets[old_region_idx].discard(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set.add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_region[voxel]&nbsp;=&nbsp;region_idx<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;absorbed_this_region&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total_absorbed&nbsp;+=&nbsp;absorbed_this_region<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Перераспределение&nbsp;висячих&nbsp;вокселей<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;redistributed_this_region&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;redistribute_changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;redistribute_changed&nbsp;and&nbsp;len(region_set)&nbsp;&gt;&nbsp;1:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;redistribute_changed&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_redistribute:&nbsp;list[tuple[tuple[int,&nbsp;int,&nbsp;int],&nbsp;int]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;list(region_set):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;voxel<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbors_in_current&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbors_in_current&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbors_in_current&nbsp;&lt;&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_counts:&nbsp;dict[int,&nbsp;int]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;voxel_to_region:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;other_idx&nbsp;=&nbsp;voxel_to_region[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;other_idx&nbsp;!=&nbsp;region_idx:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_counts[other_idx]&nbsp;=&nbsp;neighbor_counts.get(other_idx,&nbsp;0)&nbsp;+&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;best_region&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;best_count&nbsp;=&nbsp;neighbors_in_current<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_normals&nbsp;=&nbsp;surface_voxels.get(voxel,&nbsp;[])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;other_idx,&nbsp;count&nbsp;in&nbsp;neighbor_counts.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;count&nbsp;&gt;&nbsp;best_count:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;other_normal&nbsp;=&nbsp;region_normals[other_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;vn&nbsp;in&nbsp;voxel_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;np.dot(vn,&nbsp;other_normal)&nbsp;&gt;=&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;best_region&nbsp;=&nbsp;other_idx<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;best_count&nbsp;=&nbsp;count<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;best_region&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_redistribute.append((voxel,&nbsp;best_region))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel,&nbsp;target_idx&nbsp;in&nbsp;to_redistribute:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set.discard(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_sets[target_idx].add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_region[voxel]&nbsp;=&nbsp;target_idx<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;redistribute_changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;redistributed_this_region&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total_pruned&nbsp;+=&nbsp;redistributed_this_region<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;absorbed_this_region&nbsp;&gt;&nbsp;0&nbsp;or&nbsp;redistributed_this_region&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_sum&nbsp;=&nbsp;np.zeros(3,&nbsp;dtype=np.float64)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;v&nbsp;in&nbsp;surface_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal_sum&nbsp;+=&nbsp;surface_voxels[v][0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm&nbsp;=&nbsp;np.linalg.norm(normal_sum)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm&nbsp;&gt;&nbsp;1e-6:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_normals[region_idx]&nbsp;=&nbsp;(normal_sum&nbsp;/&nbsp;norm).astype(np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;result:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;empty_count&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx&nbsp;in&nbsp;range(len(regions)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(region_sets[idx])&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.append((list(region_sets[idx]),&nbsp;region_normals[idx]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;empty_count&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;greedy&nbsp;absorption:&nbsp;{len(regions)}&nbsp;regions,&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f&quot;absorbed&nbsp;{total_absorbed}&nbsp;voxels,&nbsp;redistributed&nbsp;{total_pruned}&nbsp;hanging,&nbsp;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f&quot;removed&nbsp;{empty_count}&nbsp;empty&nbsp;regions,&nbsp;result:&nbsp;{len(result)}&nbsp;regions&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;add_multi_normal_voxels_to_regions(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.4:&nbsp;Воксели&nbsp;с&nbsp;несколькими&nbsp;нормалями&nbsp;добавляются&nbsp;во&nbsp;все&nbsp;совместимые&nbsp;регионы.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;multi_normal_voxels&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v:&nbsp;normals&nbsp;for&nbsp;v,&nbsp;normals&nbsp;in&nbsp;surface_voxels.items()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(normals)&nbsp;&gt;&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;multi_normal_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;regions<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_sets:&nbsp;list[set[tuple[int,&nbsp;int,&nbsp;int]]]&nbsp;=&nbsp;[set(voxels)&nbsp;for&nbsp;voxels,&nbsp;_&nbsp;in&nbsp;regions]<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_normals:&nbsp;list[np.ndarray]&nbsp;=&nbsp;[normal&nbsp;for&nbsp;_,&nbsp;normal&nbsp;in&nbsp;regions]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;added_count&nbsp;=&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel,&nbsp;voxel_normals&nbsp;in&nbsp;multi_normal_voxels.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_idx,&nbsp;region_normal&nbsp;in&nbsp;enumerate(region_normals):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;voxel&nbsp;in&nbsp;region_sets[region_idx]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;vn&nbsp;in&nbsp;voxel_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;np.dot(vn,&nbsp;region_normal)&nbsp;&gt;=&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_sets[region_idx].add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;added_count&nbsp;+=&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(list(region_sets[i]),&nbsp;region_normals[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(regions))<br>
&nbsp;&nbsp;&nbsp;&nbsp;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;added&nbsp;{added_count}&nbsp;multi-normal&nbsp;voxels&nbsp;to&nbsp;additional&nbsp;regions&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;expand_all_regions(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.4:&nbsp;Расширение&nbsp;всех&nbsp;регионов&nbsp;на&nbsp;соседние&nbsp;воксели.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_sets:&nbsp;list[set[tuple[int,&nbsp;int,&nbsp;int]]]&nbsp;=&nbsp;[set(voxels)&nbsp;for&nbsp;voxels,&nbsp;_&nbsp;in&nbsp;regions]<br>
&nbsp;&nbsp;&nbsp;&nbsp;region_normals:&nbsp;list[np.ndarray]&nbsp;=&nbsp;[normal&nbsp;for&nbsp;_,&nbsp;normal&nbsp;in&nbsp;regions]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;total_added&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;iteration&nbsp;=&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;changed:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iteration&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_idx&nbsp;in&nbsp;range(len(region_sets)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set&nbsp;=&nbsp;region_sets[region_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_normal&nbsp;=&nbsp;region_normals[region_idx]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;candidates:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;surface_voxels&nbsp;and&nbsp;neighbor&nbsp;not&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;candidates.add(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;candidate&nbsp;in&nbsp;candidates:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;candidate_normals&nbsp;=&nbsp;surface_voxels[candidate]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;cn&nbsp;in&nbsp;candidate_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;np.dot(cn,&nbsp;region_normal)&nbsp;&gt;=&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set.add(candidate)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;total_added&nbsp;+=&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(list(region_sets[i]),&nbsp;region_normals[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(regions))<br>
&nbsp;&nbsp;&nbsp;&nbsp;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;expand_all_regions:&nbsp;{iteration}&nbsp;iterations,&nbsp;added&nbsp;{total_added}&nbsp;voxels&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;filter_hanging_voxels(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.6:&nbsp;Фильтрация&nbsp;&quot;висячих&quot;&nbsp;вокселей.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_voxels,&nbsp;region_normal&nbsp;in&nbsp;regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(region_voxels)&nbsp;&lt;=&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.append((region_voxels,&nbsp;region_normal))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set&nbsp;=&nbsp;set(region_voxels)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;changed:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_evict:&nbsp;list[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_count&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;voxel<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_count&nbsp;+=&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor_count&nbsp;&lt;=&nbsp;1:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_evict.append(voxel)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;to_evict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set.discard(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(region_set)&nbsp;&lt;=&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;region_set:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.append((list(region_set),&nbsp;region_normal))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;are_connected_26(voxels:&nbsp;list[tuple[int,&nbsp;int,&nbsp;int]])&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Проверить,&nbsp;связаны&nbsp;ли&nbsp;все&nbsp;воксели&nbsp;между&nbsp;собой&nbsp;по&nbsp;26-связности.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(voxels)&nbsp;&lt;=&nbsp;1:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;voxel_set&nbsp;=&nbsp;set(voxels)<br>
&nbsp;&nbsp;&nbsp;&nbsp;visited:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;queue&nbsp;=&nbsp;[voxels[0]]<br>
&nbsp;&nbsp;&nbsp;&nbsp;visited.add(voxels[0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;queue:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current&nbsp;=&nbsp;queue.pop()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;current<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;voxel_set&nbsp;and&nbsp;neighbor&nbsp;not&nbsp;in&nbsp;visited:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;visited.add(neighbor)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;queue.append(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;len(visited)&nbsp;==&nbsp;len(voxels)<br>
<br>
<br>
def&nbsp;decimate_boundary(<br>
&nbsp;&nbsp;&nbsp;&nbsp;boundary:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]],<br>
)&nbsp;-&gt;&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Децимация&nbsp;границы&nbsp;—&nbsp;удаляем&nbsp;избыточные&nbsp;воксели.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;set(boundary)<br>
&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;iteration&nbsp;=&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;changed:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iteration&nbsp;+=&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_remove:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;result:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;voxel<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbors_in_boundary:&nbsp;list[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;result&nbsp;and&nbsp;neighbor&nbsp;not&nbsp;in&nbsp;to_remove:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbors_in_boundary.append(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(neighbors_in_boundary)&nbsp;&lt;&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_remove.add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;are_connected_26(neighbors_in_boundary):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_remove.add(voxel)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;to_remove:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.discard(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;changed&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;boundary&nbsp;decimation:&nbsp;{len(boundary)}&nbsp;-&gt;&nbsp;{len(result)}&nbsp;({iteration}&nbsp;iterations)&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;share_boundary_voxels(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
)&nbsp;-&gt;&nbsp;tuple[list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.7:&nbsp;Граничные&nbsp;воксели&nbsp;становятся&nbsp;общими&nbsp;для&nbsp;соседних&nbsp;регионов.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(обновлённые&nbsp;регионы,&nbsp;множество&nbsp;граничных&nbsp;вокселей)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;set[int]]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx,&nbsp;(voxels,&nbsp;_)&nbsp;in&nbsp;enumerate(regions):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v&nbsp;in&nbsp;voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;v&nbsp;not&nbsp;in&nbsp;voxel_to_regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions[v]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions[v].add(idx)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;boundary_voxels:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;to_add:&nbsp;dict[int,&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]]&nbsp;=&nbsp;{i:&nbsp;set()&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(regions))}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_idx,&nbsp;(region_voxels,&nbsp;_)&nbsp;in&nbsp;enumerate(regions):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;region_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;voxel<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;voxel_to_regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_regions&nbsp;=&nbsp;voxel_to_regions[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;other_idx&nbsp;in&nbsp;neighbor_regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;other_idx&nbsp;&gt;&nbsp;region_idx:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;to_add[other_idx].add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary_voxels.add(voxel)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;boundary_voxels&nbsp;=&nbsp;decimate_boundary(boundary_voxels)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;result:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx,&nbsp;(voxels,&nbsp;normal)&nbsp;in&nbsp;enumerate(regions):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filtered_to_add&nbsp;=&nbsp;to_add[idx]&nbsp;&amp;&nbsp;boundary_voxels<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_voxels&nbsp;=&nbsp;set(voxels)&nbsp;|&nbsp;filtered_to_add<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.append((list(new_voxels),&nbsp;normal))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;shared&nbsp;{len(boundary_voxels)}&nbsp;boundary&nbsp;voxels&nbsp;between&nbsp;regions&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result,&nbsp;boundary_voxels<br>
<br>
<br>
def&nbsp;find_inter_region_boundaries(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
)&nbsp;-&gt;&nbsp;dict[int,&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Найти&nbsp;воксели&nbsp;на&nbsp;границах&nbsp;между&nbsp;регионами.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Воксель&nbsp;считается&nbsp;граничным,&nbsp;если&nbsp;он&nbsp;имеет&nbsp;соседа&nbsp;из&nbsp;другого&nbsp;региона.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Эти&nbsp;воксели&nbsp;должны&nbsp;сохраняться&nbsp;при&nbsp;упрощении&nbsp;контуров.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;Список&nbsp;(воксели,&nbsp;нормаль)&nbsp;для&nbsp;каждого&nbsp;региона.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{region_idx:&nbsp;set&nbsp;of&nbsp;boundary&nbsp;voxels}&nbsp;—&nbsp;для&nbsp;каждого&nbsp;региона<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;множество&nbsp;его&nbsp;вокселей,&nbsp;которые&nbsp;граничат&nbsp;с&nbsp;другими&nbsp;регионами.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Строим&nbsp;карту:&nbsp;воксель&nbsp;-&gt;&nbsp;множество&nbsp;регионов,&nbsp;которым&nbsp;он&nbsp;принадлежит<br>
&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;set[int]]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_idx,&nbsp;(voxels,&nbsp;_)&nbsp;in&nbsp;enumerate(regions):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v&nbsp;in&nbsp;voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;v&nbsp;not&nbsp;in&nbsp;voxel_to_regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions[v]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;voxel_to_regions[v].add(region_idx)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Для&nbsp;каждого&nbsp;региона&nbsp;находим&nbsp;воксели&nbsp;на&nbsp;границе&nbsp;с&nbsp;другими&nbsp;регионами<br>
&nbsp;&nbsp;&nbsp;&nbsp;result:&nbsp;dict[int,&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]]&nbsp;=&nbsp;{i:&nbsp;set()&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(regions))}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_idx,&nbsp;(voxels,&nbsp;_)&nbsp;in&nbsp;enumerate(regions):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set&nbsp;=&nbsp;set(voxels)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;voxel&nbsp;in&nbsp;voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;=&nbsp;voxel<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверяем&nbsp;соседей&nbsp;по&nbsp;26-связности<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;in&nbsp;voxel_to_regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor_regions&nbsp;=&nbsp;voxel_to_regions[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Если&nbsp;сосед&nbsp;принадлежит&nbsp;другому&nbsp;региону<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor_regions&nbsp;-&nbsp;{region_idx}:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result[region_idx].add(voxel)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;total_boundary&nbsp;=&nbsp;sum(len(v)&nbsp;for&nbsp;v&nbsp;in&nbsp;result.values())<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;PolygonBuilder:&nbsp;found&nbsp;{total_boundary}&nbsp;inter-region&nbsp;boundary&nbsp;voxels&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;result<br>
<br>
<br>
def&nbsp;expand_regions(<br>
&nbsp;&nbsp;&nbsp;&nbsp;regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;surface_voxels:&nbsp;dict[tuple[int,&nbsp;int,&nbsp;int],&nbsp;list[np.ndarray]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;normal_threshold:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Шаг&nbsp;2.5:&nbsp;Расширить&nbsp;регионы,&nbsp;добавляя&nbsp;граничные&nbsp;воксели&nbsp;с&nbsp;подходящими&nbsp;нормалями.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;expanded_regions:&nbsp;list[tuple[list[tuple[int,&nbsp;int,&nbsp;int]],&nbsp;np.ndarray]]&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;region_voxels,&nbsp;region_normal&nbsp;in&nbsp;regions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;region_set&nbsp;=&nbsp;set(region_voxels)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expanded&nbsp;=&nbsp;list(region_voxels)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary:&nbsp;set[tuple[int,&nbsp;int,&nbsp;int]]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;vx,&nbsp;vy,&nbsp;vz&nbsp;in&nbsp;region_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;dx,&nbsp;dy,&nbsp;dz&nbsp;in&nbsp;NEIGHBORS_26:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;neighbor&nbsp;=&nbsp;(vx&nbsp;+&nbsp;dx,&nbsp;vy&nbsp;+&nbsp;dy,&nbsp;vz&nbsp;+&nbsp;dz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;neighbor&nbsp;not&nbsp;in&nbsp;region_set&nbsp;and&nbsp;neighbor&nbsp;in&nbsp;surface_voxels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary.add(neighbor)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;neighbor&nbsp;in&nbsp;boundary:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals_list&nbsp;=&nbsp;surface_voxels[neighbor]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;normal&nbsp;in&nbsp;normals_list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dot&nbsp;=&nbsp;np.dot(region_normal,&nbsp;normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;dot&nbsp;&gt;=&nbsp;normal_threshold:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expanded.append(neighbor)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expanded_regions.append((expanded,&nbsp;region_normal))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;expanded_regions<br>
<!-- END SCAT CODE -->
</body>
</html>
