<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/project/Materials/NavMeshFOV.shader</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
@program&nbsp;NavMeshFOV<br>
<br>
@phase&nbsp;transparent<br>
<br>
@glDepthTest&nbsp;true<br>
@glDepthMask&nbsp;false<br>
@glCull&nbsp;false<br>
@glBlend&nbsp;true<br>
<br>
@property&nbsp;Color&nbsp;u_color&nbsp;=&nbsp;Color(0.0,&nbsp;1.0,&nbsp;0.0,&nbsp;0.2)<br>
@property&nbsp;Texture&nbsp;u_fov&nbsp;=&nbsp;&quot;white&quot;<br>
@property&nbsp;Float&nbsp;u_fov_distance&nbsp;=&nbsp;100.0<br>
@property&nbsp;Float&nbsp;u_depth_bias&nbsp;=&nbsp;0.02<br>
<br>
@stage&nbsp;vertex<br>
#version&nbsp;330&nbsp;core<br>
<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
layout(location&nbsp;=&nbsp;2)&nbsp;in&nbsp;vec2&nbsp;a_texcoord;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
uniform&nbsp;mat4&nbsp;u_fov_view;<br>
uniform&nbsp;mat4&nbsp;u_fov_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_world_pos;<br>
out&nbsp;vec3&nbsp;v_normal;<br>
out&nbsp;vec4&nbsp;v_fov_clip_pos;<br>
out&nbsp;float&nbsp;v_fov_linear_depth;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec4&nbsp;world_pos&nbsp;=&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_world_pos&nbsp;=&nbsp;world_pos.xyz;<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(u_model)&nbsp;*&nbsp;a_normal;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Transform&nbsp;to&nbsp;FOV&nbsp;camera&nbsp;clip&nbsp;space<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec4&nbsp;fov_view_pos&nbsp;=&nbsp;u_fov_view&nbsp;*&nbsp;world_pos;<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_fov_clip_pos&nbsp;=&nbsp;u_fov_projection&nbsp;*&nbsp;fov_view_pos;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Linear&nbsp;depth&nbsp;in&nbsp;FOV&nbsp;camera&nbsp;space&nbsp;(forward&nbsp;=&nbsp;+Y)<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_fov_linear_depth&nbsp;=&nbsp;fov_view_pos.y;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;world_pos;<br>
}<br>
<br>
@stage&nbsp;fragment<br>
#version&nbsp;330&nbsp;core<br>
<br>
in&nbsp;vec3&nbsp;v_world_pos;<br>
in&nbsp;vec3&nbsp;v_normal;<br>
in&nbsp;vec4&nbsp;v_fov_clip_pos;<br>
in&nbsp;float&nbsp;v_fov_linear_depth;<br>
<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
uniform&nbsp;sampler2D&nbsp;u_fov;<br>
uniform&nbsp;float&nbsp;u_fov_distance;<br>
uniform&nbsp;float&nbsp;u_depth_bias;<br>
<br>
uniform&nbsp;mat4&nbsp;u_fov_view;<br>
<br>
out&nbsp;vec4&nbsp;frag_color;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Perspective&nbsp;divide<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;ndc&nbsp;=&nbsp;v_fov_clip_pos.xyz&nbsp;/&nbsp;v_fov_clip_pos.w;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;if&nbsp;within&nbsp;FOV&nbsp;frustum&nbsp;[-1,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ndc.x&nbsp;&lt;&nbsp;-1.0&nbsp;||&nbsp;ndc.x&nbsp;&gt;&nbsp;1.0&nbsp;||&nbsp;ndc.y&nbsp;&lt;&nbsp;-1.0&nbsp;||&nbsp;ndc.y&nbsp;&gt;&nbsp;1.0)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;discard;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;if&nbsp;in&nbsp;front&nbsp;of&nbsp;FOV&nbsp;camera&nbsp;(positive&nbsp;Y&nbsp;in&nbsp;view&nbsp;space)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(v_fov_linear_depth&nbsp;&lt;&nbsp;0.0)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;discard;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Check&nbsp;max&nbsp;distance<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(v_fov_linear_depth&nbsp;&gt;&nbsp;u_fov_distance)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;discard;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Convert&nbsp;NDC&nbsp;to&nbsp;UV&nbsp;[0,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec2&nbsp;fov_uv&nbsp;=&nbsp;ndc.xy&nbsp;*&nbsp;0.5&nbsp;+&nbsp;0.5;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Sample&nbsp;depth&nbsp;from&nbsp;FOV&nbsp;depth&nbsp;texture&nbsp;(linear&nbsp;Y&nbsp;depth,&nbsp;normalized&nbsp;to&nbsp;u_fov_distance)<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;stored_depth&nbsp;=&nbsp;texture(u_fov,&nbsp;fov_uv).r&nbsp;*&nbsp;u_fov_distance;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Current&nbsp;pixel&nbsp;depth&nbsp;(normalized)<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;current_depth&nbsp;=&nbsp;v_fov_linear_depth;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Visibility&nbsp;test:&nbsp;pixel&nbsp;is&nbsp;visible&nbsp;if&nbsp;its&nbsp;depth&nbsp;&lt;=&nbsp;stored&nbsp;depth&nbsp;+&nbsp;bias<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(current_depth&nbsp;&gt;&nbsp;stored_depth&nbsp;+&nbsp;u_depth_bias)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;discard;<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Pixel&nbsp;is&nbsp;visible&nbsp;from&nbsp;FOV&nbsp;camera<br>
&nbsp;&nbsp;&nbsp;&nbsp;frag_color&nbsp;=&nbsp;u_color;<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
