<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/animation/channel.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
from&nbsp;typing&nbsp;import&nbsp;List,&nbsp;Optional,&nbsp;Tuple<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.util&nbsp;import&nbsp;qslerp<br>
from&nbsp;.keyframe&nbsp;import&nbsp;AnimationKeyframe<br>
<br>
<br>
class&nbsp;AnimationChannel:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Канал&nbsp;одного&nbsp;узла&nbsp;FBX:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;translation_keys:&nbsp;ключи&nbsp;позиций&nbsp;(в&nbsp;тиках)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;rotation_keys:&nbsp;ключи&nbsp;вращения&nbsp;(кватернионы)&nbsp;(в&nbsp;тиках)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;scale_keys:&nbsp;ключи&nbsp;скейла&nbsp;(в&nbsp;тиках)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Всё&nbsp;хранится&nbsp;в&nbsp;ТИКАХ,&nbsp;без&nbsp;пересчёта&nbsp;в&nbsp;секунды.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;translation_keys,&nbsp;rotation_keys,&nbsp;scale_keys):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.translation_keys&nbsp;=&nbsp;sorted(translation_keys,&nbsp;key=lambda&nbsp;k:&nbsp;k.time)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.rotation_keys&nbsp;=&nbsp;sorted(rotation_keys,&nbsp;key=lambda&nbsp;k:&nbsp;k.time)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.scale_keys&nbsp;=&nbsp;sorted(scale_keys,&nbsp;key=lambda&nbsp;k:&nbsp;k.time)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;duration&nbsp;в&nbsp;тиках<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.duration&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;arr&nbsp;in&nbsp;(self.translation_keys,&nbsp;self.rotation_keys,&nbsp;self.scale_keys):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;arr:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.duration&nbsp;=&nbsp;max(self.duration,&nbsp;arr[-1].time)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;--------------------------------------------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_interp_linear(a,&nbsp;b,&nbsp;alpha):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(1.0&nbsp;-&nbsp;alpha)&nbsp;*&nbsp;np.asarray(a,&nbsp;float)&nbsp;+&nbsp;alpha&nbsp;*&nbsp;np.asarray(b,&nbsp;float)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_sample_keys(keys,&nbsp;t_ticks,&nbsp;interp):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;keys:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;first&nbsp;=&nbsp;keys[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;last&nbsp;=&nbsp;keys[-1]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;t_ticks&nbsp;&lt;=&nbsp;first.time:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;interp(first,&nbsp;first,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;t_ticks&nbsp;&gt;=&nbsp;last.time:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;interp(last,&nbsp;last,&nbsp;0.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;k1,&nbsp;k2&nbsp;in&nbsp;zip(keys,&nbsp;keys[1:]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;k1.time&nbsp;&lt;=&nbsp;t_ticks&nbsp;&lt;=&nbsp;k2.time:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dt&nbsp;=&nbsp;k2.time&nbsp;-&nbsp;k1.time<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;alpha&nbsp;=&nbsp;(t_ticks&nbsp;-&nbsp;k1.time)&nbsp;/&nbsp;dt&nbsp;if&nbsp;dt&nbsp;!=&nbsp;0&nbsp;else&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;interp(k1,&nbsp;k2,&nbsp;alpha)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;interp(last,&nbsp;last,&nbsp;0.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;--------------------------------------------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;sample(self,&nbsp;t_ticks:&nbsp;float)&nbsp;-&gt;&nbsp;Tuple[Optional[np.ndarray],&nbsp;Optional[np.ndarray],&nbsp;Optional[float]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t_ticks&nbsp;—&nbsp;время&nbsp;в&nbsp;ТИКАХ.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sc&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.translation_keys:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;self._sample_keys(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.translation_keys,&nbsp;t_ticks,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lambda&nbsp;a,&nbsp;b,&nbsp;alpha:&nbsp;self._interp_linear(a.translation,&nbsp;b.translation,&nbsp;alpha)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.rotation_keys:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;self._sample_keys(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.rotation_keys,&nbsp;t_ticks,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lambda&nbsp;a,&nbsp;b,&nbsp;alpha:&nbsp;qslerp(a.rotation,&nbsp;b.rotation,&nbsp;alpha)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.scale_keys:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sc&nbsp;=&nbsp;self._sample_keys(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.scale_keys,&nbsp;t_ticks,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lambda&nbsp;a,&nbsp;b,&nbsp;alpha:&nbsp;float((1&nbsp;-&nbsp;alpha)&nbsp;*&nbsp;a.scale&nbsp;+&nbsp;alpha&nbsp;*&nbsp;b.scale)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;tr,&nbsp;rot,&nbsp;sc<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;--------------------------------------------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_assimp_channel(ch):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Берёт&nbsp;pos_keys,&nbsp;rot_keys,&nbsp;scale_keys&nbsp;в&nbsp;ТИКАХ&nbsp;(как&nbsp;из&nbsp;fbx_loader)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;и&nbsp;создаёт&nbsp;единый&nbsp;канал.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;[AnimationKeyframe(t,&nbsp;translation=np.array(v))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(t,&nbsp;v)&nbsp;in&nbsp;getattr(ch,&nbsp;&quot;pos_keys&quot;,&nbsp;[])]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;[AnimationKeyframe(t,&nbsp;rotation=np.array(v))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(t,&nbsp;v)&nbsp;in&nbsp;getattr(ch,&nbsp;&quot;rot_keys&quot;,&nbsp;[])]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sc&nbsp;=&nbsp;[AnimationKeyframe(t,&nbsp;scale=float(np.mean(v)))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(t,&nbsp;v)&nbsp;in&nbsp;getattr(ch,&nbsp;&quot;scale_keys&quot;,&nbsp;[])]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;AnimationChannel(tr,&nbsp;rot,&nbsp;sc)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;--------------------------------------------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__repr__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;f&quot;&lt;AnimationChannel&nbsp;ticks={self.duration:.2f}&nbsp;tr_keys={len(self.translation_keys)}&nbsp;rot_keys={len(self.rotation_keys)}&nbsp;scale_keys={len(self.scale_keys)}&gt;&quot;<br>
<!-- END SCAT CODE -->
</body>
</html>
