<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/colliders/__init__.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Модуль&nbsp;коллайдеров&nbsp;для&nbsp;обнаружения&nbsp;столкновений&nbsp;и&nbsp;вычисления&nbsp;расстояний.<br>
<br>
Содержит:<br>
-&nbsp;Базовый&nbsp;класс&nbsp;Collider<br>
-&nbsp;Примитивные&nbsp;коллайдеры:&nbsp;SphereCollider,&nbsp;BoxCollider,&nbsp;CapsuleCollider<br>
-&nbsp;AttachedCollider&nbsp;-&nbsp;коллайдер,&nbsp;прикрепленный&nbsp;к&nbsp;Pose3<br>
-&nbsp;ColliderHit,&nbsp;RayHit&nbsp;-&nbsp;результаты&nbsp;запросов<br>
&quot;&quot;&quot;<br>
<br>
#&nbsp;Setup&nbsp;DLL&nbsp;paths&nbsp;before&nbsp;importing&nbsp;native&nbsp;extensions<br>
from&nbsp;termin&nbsp;import&nbsp;_dll_setup&nbsp;&nbsp;#&nbsp;noqa:&nbsp;F401<br>
<br>
from&nbsp;._colliders_native&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Collider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;SphereCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;BoxCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;CapsuleCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;AttachedCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;UnionCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;ColliderHit,<br>
&nbsp;&nbsp;&nbsp;&nbsp;RayHit,<br>
&nbsp;&nbsp;&nbsp;&nbsp;ColliderType,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Ray3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ground&nbsp;contact&nbsp;helpers<br>
&nbsp;&nbsp;&nbsp;&nbsp;SphereGroundContact,<br>
&nbsp;&nbsp;&nbsp;&nbsp;BoxGroundContact,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Geometry&nbsp;primitives<br>
&nbsp;&nbsp;&nbsp;&nbsp;Sphere,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Box,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Capsule,<br>
)<br>
<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;'Collider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'SphereCollider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'BoxCollider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'CapsuleCollider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'AttachedCollider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'UnionCollider',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'ColliderHit',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'RayHit',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'ColliderType',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'Ray3',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'SphereGroundContact',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'BoxGroundContact',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'Sphere',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'Box',<br>
&nbsp;&nbsp;&nbsp;&nbsp;'Capsule',<br>
]<br>
<!-- END SCAT CODE -->
</body>
</html>
