<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/fem/dynamic_assembler.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;termin.fem.assembler&nbsp;import&nbsp;MatrixAssembler,&nbsp;Variable,&nbsp;Contribution<br>
from&nbsp;typing&nbsp;import&nbsp;Dict,&nbsp;List,&nbsp;Tuple<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;termin.linalg.subspaces&nbsp;import&nbsp;project_onto_affine,&nbsp;metric_project_onto_constraints&nbsp;<br>
from&nbsp;termin.geombase.pose3&nbsp;import&nbsp;Pose3<br>
<br>
class&nbsp;DynamicMatrixAssembler(MatrixAssembler):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.time_step&nbsp;=&nbsp;0.01<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_build_index_maps(self)&nbsp;-&gt;&nbsp;Dict[Variable,&nbsp;List[int]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Построить&nbsp;отображение:&nbsp;Variable&nbsp;-&gt;&nbsp;глобальные&nbsp;индексы&nbsp;DOF<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Назначает&nbsp;каждой&nbsp;компоненте&nbsp;каждой&nbsp;переменной&nbsp;уникальный<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;глобальный&nbsp;индекс&nbsp;в&nbsp;системе.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._index_map_by_tags&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tags&nbsp;=&nbsp;set(var.tag&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;tag&nbsp;in&nbsp;tags:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vars_with_tag&nbsp;=&nbsp;[var&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;tag]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self._build_index_map(vars_with_tag)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._index_map_by_tags[tag]&nbsp;=&nbsp;index_map<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._index_map&nbsp;=&nbsp;self._index_map_by_tags.get(&quot;acceleration&quot;,&nbsp;{})<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._holonomic_index_map&nbsp;=&nbsp;self._index_map_by_tags.get(&quot;force&quot;,&nbsp;{})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._dirty_index_map&nbsp;=&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;def&nbsp;collect_current_q(self,&nbsp;index_map:&nbsp;Dict[Variable,&nbsp;List[int]]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Собрать&nbsp;текущее&nbsp;значение&nbsp;q&nbsp;из&nbsp;всех&nbsp;переменных&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q&nbsp;=&nbsp;np.zeros(self.total_variables_by_tag(&quot;acceleration&quot;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;&quot;acceleration&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q[indices]&nbsp;=&nbsp;var.value_by_rank(2)&nbsp;&nbsp;#&nbsp;текущее&nbsp;значение<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;old_q<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;def&nbsp;collect_current_q_dot(self,&nbsp;index_map:&nbsp;Dict[Variable,&nbsp;List[int]]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Собрать&nbsp;текущее&nbsp;значение&nbsp;q_dot&nbsp;из&nbsp;всех&nbsp;переменных&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q_dot&nbsp;=&nbsp;np.zeros(self.total_variables_by_tag(&quot;acceleration&quot;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;&quot;acceleration&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q_dot[indices]&nbsp;=&nbsp;var.value_by_rank(1)&nbsp;&nbsp;#&nbsp;текущее&nbsp;значение&nbsp;скорости<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;old_q_dot<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;def&nbsp;set_old_q(self,&nbsp;q:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Установить&nbsp;старое&nbsp;значение&nbsp;q&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.old_q&nbsp;=&nbsp;np.array(q)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;def&nbsp;set_old_q_dot(self,&nbsp;q_dot:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Установить&nbsp;старое&nbsp;значение&nbsp;q_dot&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.old_q_dot&nbsp;=&nbsp;np.array(q_dot)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;index_maps(self)&nbsp;-&gt;&nbsp;Dict[str,&nbsp;Dict[Variable,&nbsp;List[int]]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Получить&nbsp;текущее&nbsp;отображение&nbsp;Variable&nbsp;-&gt;&nbsp;глобальные&nbsp;индексы&nbsp;DOF<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;для&nbsp;разных&nbsp;типов&nbsp;переменных<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._dirty_index_map:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._build_index_maps()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;acceleration&quot;:&nbsp;self._index_map,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;force&quot;:&nbsp;self._holonomic_index_map<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;index_map_by_tag(self,&nbsp;tag:&nbsp;str)&nbsp;-&gt;&nbsp;Dict[Variable,&nbsp;List[int]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Получить&nbsp;текущее&nbsp;отображение&nbsp;Variable&nbsp;-&gt;&nbsp;глобальные&nbsp;индексы&nbsp;DOF<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;для&nbsp;переменных&nbsp;с&nbsp;заданным&nbsp;тегом<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._dirty_index_map:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._build_index_maps()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._index_map_by_tags.get(tag,&nbsp;{})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_electric_domain(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Построить&nbsp;карту&nbsp;индексов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_maps&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;voltage&quot;:&nbsp;self.index_map_by_tag(&quot;voltage&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;current&quot;:&nbsp;self.index_map_by_tag(&quot;current&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;charge&quot;:&nbsp;self.index_map_by_tag(&quot;charge&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создать&nbsp;глобальные&nbsp;матрицы&nbsp;и&nbsp;вектор<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;voltage&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_currents&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;current&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#n_charge&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;charge&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;conductance&quot;:&nbsp;np.zeros((n_voltage,&nbsp;n_voltage)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electric_holonomic&quot;:&nbsp;np.zeros((n_currents,&nbsp;n_voltage)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electric_holonomic_rhs&quot;:&nbsp;np.zeros(n_currents),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;rhs&quot;:&nbsp;np.zeros(n_voltage),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;current_to_current&quot;:&nbsp;np.zeros((n_currents,&nbsp;n_currents)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;charge_constraint&quot;:&nbsp;np.zeros((n_charge,&nbsp;n_voltage)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;charge_constraint_rhs&quot;:&nbsp;np.zeros((n_charge)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.contribute(matrices,&nbsp;index_maps)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;matrices<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_electromechanic_domain(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Построить&nbsp;карту&nbsp;индексов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_maps&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;voltage&quot;:&nbsp;self.index_map_by_tag(&quot;voltage&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;current&quot;:&nbsp;self.index_map_by_tag(&quot;current&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;acceleration&quot;:&nbsp;self.index_map_by_tag(&quot;acceleration&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;force&quot;:&nbsp;self.index_map_by_tag(&quot;force&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создать&nbsp;глобальные&nbsp;матрицы&nbsp;и&nbsp;вектор<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;voltage&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_currents&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;current&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_acceleration&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_force&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;conductance&quot;:&nbsp;np.zeros((n_voltage,&nbsp;n_voltage)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;mass&quot;:&nbsp;np.zeros((n_acceleration,&nbsp;n_acceleration)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;load&quot;&nbsp;:&nbsp;np.zeros(n_acceleration),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electric_holonomic&quot;:&nbsp;np.zeros((n_currents,&nbsp;n_voltage)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electric_holonomic_rhs&quot;:&nbsp;np.zeros(n_currents),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;current_to_current&quot;:&nbsp;np.zeros((n_currents,&nbsp;n_currents)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic&quot;:&nbsp;np.zeros((n_force,&nbsp;n_acceleration)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electromechanic_coupling&quot;:&nbsp;np.zeros((n_acceleration,&nbsp;n_currents)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;electromechanic_coupling_damping&quot;:&nbsp;np.zeros((n_acceleration,&nbsp;n_currents)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic_load&quot;:&nbsp;np.zeros(n_force),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;rhs&quot;:&nbsp;np.zeros(n_voltage),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.contribute(matrices,&nbsp;index_maps)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;matrices<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;names_from_variables(self,&nbsp;variables:&nbsp;List[Variable])&nbsp;-&gt;&nbsp;List[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Получить&nbsp;список&nbsp;имен&nbsp;переменных&nbsp;из&nbsp;списка&nbsp;Variable&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;names&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;names.extend(var.names())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;names<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_extended_system_for_electromechanic(self,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray])&nbsp;-&gt;&nbsp;Tuple[np.ndarray,&nbsp;np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;voltage&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_currents&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;current&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_acceleration&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_force&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext&nbsp;=&nbsp;np.zeros((n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;С_ext&nbsp;=&nbsp;np.zeros((n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext&nbsp;=&nbsp;np.zeros(n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;voltage&quot;).keys())&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;current&quot;).keys())&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;acceleration&quot;).keys())&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;force&quot;).keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;self.names_from_variables(variables)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r0&nbsp;=&nbsp;n_voltage<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r1&nbsp;=&nbsp;n_voltage&nbsp;+&nbsp;n_currents<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r2&nbsp;=&nbsp;n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r3&nbsp;=&nbsp;n_voltage&nbsp;+&nbsp;n_currents&nbsp;+&nbsp;n_acceleration&nbsp;+&nbsp;n_force<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#v&nbsp;=&nbsp;[0:r0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#c&nbsp;=&nbsp;[r0:r1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#a&nbsp;=&nbsp;[r1:r2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#f&nbsp;=&nbsp;[r2:r3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;0:r0]&nbsp;=&nbsp;matrices[&quot;conductance&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r0:r1,&nbsp;0:r0]&nbsp;=&nbsp;matrices[&quot;electric_holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;r0:r1]&nbsp;=&nbsp;matrices[&quot;electric_holonomic&quot;].T<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r0:r1,&nbsp;r0:r1]&nbsp;=&nbsp;matrices[&quot;current_to_current&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r1:r2,&nbsp;r1:r2]&nbsp;=&nbsp;matrices[&quot;mass&quot;]&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r2:r3,&nbsp;r1:r2]&nbsp;=&nbsp;matrices[&quot;holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r1:r2,&nbsp;r2:r3]&nbsp;=&nbsp;matrices[&quot;holonomic&quot;].T<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r1:r2,&nbsp;r0:r1]&nbsp;=&nbsp;matrices[&quot;electromechanic_coupling&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#A_ext[r0:r1,&nbsp;r1:r2]&nbsp;=&nbsp;matrices[&quot;electromechanic_coupling&quot;].T<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[0:r0]&nbsp;=&nbsp;matrices[&quot;rhs&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r0:r1]&nbsp;=&nbsp;matrices[&quot;electric_holonomic_rhs&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r1:r2]&nbsp;=&nbsp;matrices[&quot;load&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r2:r3]&nbsp;=&nbsp;matrices[&quot;holonomic_load&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;EM_damping&nbsp;=&nbsp;matrices[&quot;electromechanic_coupling_damping&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_dot&nbsp;=&nbsp;self.collect_variables(&quot;velocity&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_em&nbsp;=&nbsp;EM_damping&nbsp;@&nbsp;q_dot<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r0:r1]&nbsp;+=&nbsp;b_em<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;A_ext,&nbsp;b_ext,&nbsp;variables<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_extended_system_for_electric(self,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray])&nbsp;-&gt;&nbsp;Tuple[np.ndarray,&nbsp;np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_voltage&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;voltage&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_currents&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;current&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext&nbsp;=&nbsp;np.zeros((n_voltage&nbsp;+&nbsp;n_currents,&nbsp;n_voltage&nbsp;+&nbsp;n_currents))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext&nbsp;=&nbsp;np.zeros(n_voltage&nbsp;+&nbsp;n_currents)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;voltage&quot;).keys())&nbsp;+<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;current&quot;).keys()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;[var&nbsp;for&nbsp;var&nbsp;in&nbsp;variables]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r0&nbsp;=&nbsp;n_voltage<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r1&nbsp;=&nbsp;n_voltage&nbsp;+&nbsp;n_currents<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c0&nbsp;=&nbsp;n_voltage<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c1&nbsp;=&nbsp;n_voltage&nbsp;+&nbsp;n_currents<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;0:c0]&nbsp;=&nbsp;matrices[&quot;conductance&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r0:r1,&nbsp;0:c0]&nbsp;=&nbsp;matrices[&quot;electric_holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;c0:c1]&nbsp;=&nbsp;matrices[&quot;electric_holonomic&quot;].T<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[c0:c1,&nbsp;c0:c1]&nbsp;=&nbsp;matrices[&quot;current_to_current&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[0:r0]&nbsp;=&nbsp;matrices[&quot;rhs&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r0:r1]&nbsp;=&nbsp;matrices[&quot;electric_holonomic_rhs&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;A_ext,&nbsp;b_ext,&nbsp;variables&nbsp;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Построить&nbsp;карту&nbsp;индексов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_maps&nbsp;=&nbsp;self.index_maps()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создать&nbsp;глобальные&nbsp;матрицы&nbsp;и&nbsp;вектор<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_dofs&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_positions&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;position&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_constraints&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;mass&quot;:&nbsp;np.zeros((n_dofs,&nbsp;n_dofs)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;damping&quot;:&nbsp;np.zeros((n_dofs,&nbsp;n_dofs)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;stiffness&quot;:&nbsp;np.zeros((n_dofs,&nbsp;n_positions)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;load&quot;:&nbsp;np.zeros(n_dofs),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic&quot;:&nbsp;np.zeros((n_constraints,&nbsp;n_dofs)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic_rhs&quot;:&nbsp;np.zeros(n_constraints),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;old_q&quot;:&nbsp;self.collect_variables(index_maps[&quot;acceleration&quot;]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;old_q_dot&quot;:&nbsp;self.collect_current_q_dot(index_maps[&quot;acceleration&quot;]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&quot;holonomic_velocity_rhs&quot;:&nbsp;np.zeros(n_constraints),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.contribute(matrices,&nbsp;index_maps)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;matrices<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_for_constraints_correction(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Построить&nbsp;карту&nbsp;индексов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_maps&nbsp;=&nbsp;self.index_maps()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создать&nbsp;глобальные&nbsp;матрицы&nbsp;и&nbsp;вектор<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_dofs&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_constraints&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;mass&quot;:&nbsp;np.zeros((n_dofs,&nbsp;n_dofs)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic&quot;:&nbsp;np.zeros((n_constraints,&nbsp;n_dofs)),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;position_error&quot;:&nbsp;np.zeros(n_constraints),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;holonomic_velocity_rhs&quot;:&nbsp;np.zeros(n_constraints),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.contribute_for_constraints_correction(matrices,&nbsp;index_maps)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;matrices<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assemble_extended_system(self,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray])&nbsp;-&gt;&nbsp;Tuple[np.ndarray,&nbsp;np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;=&nbsp;matrices[&quot;mass&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;=&nbsp;matrices[&quot;damping&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;K&nbsp;=&nbsp;matrices[&quot;stiffness&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;matrices[&quot;load&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q_dot&nbsp;=&nbsp;self.collect_variables(&quot;velocity&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_q&nbsp;=&nbsp;self.collect_variables(&quot;position&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;H&nbsp;=&nbsp;matrices[&quot;holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;=&nbsp;matrices[&quot;holonomic_rhs&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;acceleration&quot;).keys())&nbsp;+&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;list(self.index_map_by_tag(&quot;force&quot;).keys()))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;variables&nbsp;=&nbsp;self.names_from_variables(variables)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)&nbsp;+&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_dofs&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_holonomic&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Расширенная&nbsp;система<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext&nbsp;=&nbsp;np.zeros((size,&nbsp;size))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext&nbsp;=&nbsp;np.zeros(size)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r0&nbsp;=&nbsp;A.shape[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r1&nbsp;=&nbsp;A.shape[0]&nbsp;+&nbsp;n_holonomic<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c0&nbsp;=&nbsp;A.shape[1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c1&nbsp;=&nbsp;A.shape[1]&nbsp;+&nbsp;n_holonomic<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;0:c0]&nbsp;=&nbsp;A<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[0:r0,&nbsp;c0:c1]&nbsp;=&nbsp;H.T<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A_ext[r0:r1,&nbsp;0:c0]&nbsp;=&nbsp;H<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[0:r0]&nbsp;=&nbsp;b&nbsp;-&nbsp;C&nbsp;@&nbsp;old_q_dot&nbsp;-&nbsp;K&nbsp;@&nbsp;old_q<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b_ext[r0:r1]&nbsp;=&nbsp;h<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;A_ext,&nbsp;b_ext,&nbsp;variables<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;velocity_project_onto_constraints(self,&nbsp;q_dot:&nbsp;np.ndarray,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray])&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Проецировать&nbsp;скорости&nbsp;на&nbsp;ограничения&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;H&nbsp;=&nbsp;matrices[&quot;holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;h&nbsp;=&nbsp;matrices[&quot;holonomic_velocity_rhs&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M&nbsp;=&nbsp;matrices[&quot;mass&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M_inv&nbsp;=&nbsp;np.linalg.inv(M)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;metric_project_onto_constraints(q_dot,&nbsp;H,&nbsp;M_inv,&nbsp;h=h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;coords_project_onto_constraints(self,&nbsp;q:&nbsp;np.ndarray,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray])&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Проецировать&nbsp;скорости&nbsp;на&nbsp;ограничения&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;H&nbsp;=&nbsp;matrices[&quot;holonomic&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;f&nbsp;=&nbsp;matrices[&quot;position_error&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M&nbsp;=&nbsp;matrices[&quot;mass&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;M_inv&nbsp;=&nbsp;np.linalg.inv(M)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;metric_project_onto_constraints(q,&nbsp;H,&nbsp;M_inv,&nbsp;error=f)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;collect_variables(self,&nbsp;tag:&nbsp;str)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Собрать&nbsp;текущее&nbsp;значение&nbsp;переменных&nbsp;с&nbsp;заданным&nbsp;тегом&nbsp;из&nbsp;всех&nbsp;переменных&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q&nbsp;=&nbsp;np.zeros(self.total_variables_by_tag(tag))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self.index_map_by_tag(tag)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;tag:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q[indices]&nbsp;=&nbsp;var.value&nbsp;&nbsp;#&nbsp;текущее&nbsp;значение<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;q<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;upload_variables(self,&nbsp;tag:&nbsp;str,&nbsp;values:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Загрузить&nbsp;значения&nbsp;переменных&nbsp;с&nbsp;заданным&nbsp;тегом&nbsp;обратно&nbsp;в&nbsp;переменные&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self.index_map_by_tag(tag)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;tag:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var.set_value(values[indices])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;count&nbsp;+=&nbsp;var.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;count&nbsp;!=&nbsp;len(values):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Количество&nbsp;загруженных&nbsp;значений&nbsp;не&nbsp;соответствует&nbsp;количеству&nbsp;переменных&nbsp;с&nbsp;заданным&nbsp;тегом&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;upload_solution(self,&nbsp;variables:&nbsp;List[Variable],&nbsp;values:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Загрузить&nbsp;значения&nbsp;обратно&nbsp;в&nbsp;переменные&nbsp;по&nbsp;списку&nbsp;Variable&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;var.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var.set_value(values[index:index&nbsp;+&nbsp;size])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index&nbsp;+=&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;index&nbsp;!=&nbsp;len(values):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Количество&nbsp;загруженных&nbsp;значений&nbsp;не&nbsp;соответствует&nbsp;количеству&nbsp;переменных&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;integrate_with_constraint_projection(self,&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_ddot:&nbsp;np.ndarray,&nbsp;matrices:&nbsp;Dict[str,&nbsp;np.ndarray]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dt&nbsp;=&nbsp;self.time_step<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.upload_variables(&quot;acceleration&quot;,&nbsp;q_ddot)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.finish_timestep(dt)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_dot&nbsp;=&nbsp;self.collect_variables(&quot;velocity&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;_&nbsp;in&nbsp;range(2):&nbsp;&nbsp;#&nbsp;несколько&nbsp;итераций&nbsp;проекции&nbsp;положений<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q&nbsp;=&nbsp;self.collect_variables(&quot;position&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;self.assemble_for_constraints_correction()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q&nbsp;=&nbsp;self.coords_project_onto_constraints(q,&nbsp;matrices)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.upload_variables(&quot;position&quot;,&nbsp;q)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;contribution&nbsp;in&nbsp;self.contributions:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(contribution,&nbsp;&quot;finish_correction_step&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;contribution.finish_correction_step()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;matrices&nbsp;=&nbsp;self.assemble_for_constraints_correction()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_dot&nbsp;=&nbsp;self.velocity_project_onto_constraints(q_dot,&nbsp;matrices)&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.upload_variables(&quot;velocity&quot;,&nbsp;q_dot)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;q_dot,&nbsp;q<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;sort_results(self,&nbsp;x_ext:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;Tuple[np.ndarray,&nbsp;np.ndarray,&nbsp;np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Разделить&nbsp;расширенное&nbsp;решение&nbsp;на&nbsp;ускорения&nbsp;и&nbsp;множители&nbsp;Лагранжа&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_dofs&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;acceleration&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_holonomic&nbsp;=&nbsp;self.total_variables_by_tag(tag=&quot;force&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_ddot&nbsp;=&nbsp;x_ext[:n_dofs]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;holonomic_lambdas&nbsp;=&nbsp;x_ext[n_dofs:n_dofs&nbsp;+&nbsp;n_holonomic]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;nonholonomic_lambdas&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;q_ddot,&nbsp;holonomic_lambdas,&nbsp;nonholonomic_lambdas<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;integrate_velocities(self,&nbsp;old_q_dot:&nbsp;np.ndarray,&nbsp;q_ddot:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Интегрировать&nbsp;ускорения&nbsp;для&nbsp;получения&nbsp;новых&nbsp;скоростей&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;old_q_dot&nbsp;+&nbsp;q_ddot&nbsp;*&nbsp;self.time_step<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;restore_velocity_constraints(self,&nbsp;q_dot:&nbsp;np.ndarray,&nbsp;HN:&nbsp;np.ndarray,&nbsp;hn:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Восстановить&nbsp;ограничения&nbsp;на&nbsp;скорости&nbsp;(например,&nbsp;для&nbsp;закрепленных&nbsp;тел)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HN&nbsp;-&nbsp;матрица&nbsp;ограничений&nbsp;на&nbsp;скорости,&nbsp;объединение&nbsp;H&nbsp;и&nbsp;N<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;project_onto_affine(q_dot,&nbsp;HN,&nbsp;hn)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;integrate_positions(self,&nbsp;old_q:&nbsp;np.ndarray,&nbsp;q_dot:&nbsp;np.ndarray,&nbsp;q_ddot:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Интегрировать&nbsp;скорости&nbsp;для&nbsp;получения&nbsp;новых&nbsp;положений&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;old_q&nbsp;+&nbsp;q_dot&nbsp;*&nbsp;self.time_step&nbsp;+&nbsp;0.5&nbsp;*&nbsp;q_ddot&nbsp;*&nbsp;self.time_step**2<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;def&nbsp;restore_position_constraints(self,&nbsp;q:&nbsp;np.ndarray,&nbsp;H:&nbsp;np.ndarray,&nbsp;h:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Восстановить&nbsp;ограничения&nbsp;на&nbsp;положения&nbsp;(например,&nbsp;для&nbsp;закрепленных&nbsp;тел)&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;project_onto_affine(q,&nbsp;H,&nbsp;h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;upload_results(self,&nbsp;q_ddot:&nbsp;np.ndarray,&nbsp;q_dot:&nbsp;np.ndarray,&nbsp;q:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Загрузить&nbsp;результаты&nbsp;обратно&nbsp;в&nbsp;переменные&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self.index_maps()[&quot;acceleration&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;&quot;acceleration&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var.set_values(q_ddot[indices],&nbsp;q_dot[indices],&nbsp;q[indices])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;upload_result_values(self,&nbsp;q:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Загрузить&nbsp;только&nbsp;положения&nbsp;обратно&nbsp;в&nbsp;переменные&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self.index_maps()[&quot;acceleration&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;&quot;acceleration&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;index_map[var]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var.set_value(q[indices])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;integrate_nonlinear(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Интегрировать&nbsp;нелинейные&nbsp;переменные&nbsp;(если&nbsp;есть)&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index_map&nbsp;=&nbsp;self.index_maps()[&quot;acceleration&quot;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;var&nbsp;in&nbsp;self.variables:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;var.tag&nbsp;==&nbsp;&quot;acceleration&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var.integrate_nonlinear(self.time_step)<br>
<!-- END SCAT CODE -->
</body>
</html>
