<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/player/__main__.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Command-line&nbsp;entry&nbsp;point&nbsp;for&nbsp;Termin&nbsp;Player.<br>
<br>
Usage:<br>
&nbsp;&nbsp;&nbsp;&nbsp;python&nbsp;-m&nbsp;termin.player&nbsp;path/to/project&nbsp;--scene&nbsp;main.scene<br>
&quot;&quot;&quot;<br>
<br>
import&nbsp;argparse<br>
import&nbsp;sys<br>
from&nbsp;pathlib&nbsp;import&nbsp;Path<br>
<br>
<br>
def&nbsp;main():<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser&nbsp;=&nbsp;argparse.ArgumentParser(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;description=&quot;Run&nbsp;a&nbsp;Termin&nbsp;project&nbsp;in&nbsp;standalone&nbsp;player&nbsp;mode&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;project&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Path&nbsp;to&nbsp;project&nbsp;directory&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--scene&quot;,&nbsp;&quot;-s&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default=None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Scene&nbsp;file&nbsp;to&nbsp;load&nbsp;(default:&nbsp;first&nbsp;.scene&nbsp;file&nbsp;found)&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--width&quot;,&nbsp;&quot;-W&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default=1280,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Window&nbsp;width&nbsp;(default:&nbsp;1280)&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--height&quot;,&nbsp;&quot;-H&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default=720,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Window&nbsp;height&nbsp;(default:&nbsp;720)&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;parser.add_argument(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;--title&quot;,&nbsp;&quot;-t&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type=str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default=&quot;Termin&nbsp;Player&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help=&quot;Window&nbsp;title&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;args&nbsp;=&nbsp;parser.parse_args()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;project_path&nbsp;=&nbsp;Path(args.project)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;project_path.exists():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Error:&nbsp;Project&nbsp;path&nbsp;does&nbsp;not&nbsp;exist:&nbsp;{project_path}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sys.exit(1)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Find&nbsp;scene&nbsp;file<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene_name&nbsp;=&nbsp;args.scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene_name&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Look&nbsp;for&nbsp;first&nbsp;.scene&nbsp;file&nbsp;(recursively)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_files&nbsp;=&nbsp;list(project_path.rglob(&quot;*.scene&quot;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;scene_files:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Error:&nbsp;No&nbsp;.scene&nbsp;files&nbsp;found&nbsp;in&nbsp;{project_path}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sys.exit(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Use&nbsp;relative&nbsp;path&nbsp;from&nbsp;project&nbsp;root<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_name&nbsp;=&nbsp;str(scene_files[0].relative_to(project_path))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Using&nbsp;scene:&nbsp;{scene_name}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.player&nbsp;import&nbsp;run_project<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;run_project(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;project_path=project_path,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_name=scene_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width=args.width,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height=args.height,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title=args.title,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
<!-- END SCAT CODE -->
</body>
</html>
