<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/robot/hqtasks.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;typing&nbsp;import&nbsp;Optional<br>
<br>
from&nbsp;.hqsolver&nbsp;import&nbsp;QuadraticTask,&nbsp;EqualityConstraint,&nbsp;InequalityConstraint<br>
<br>
<br>
def&nbsp;_prepare_weight(weight:&nbsp;Optional[np.ndarray],&nbsp;rows:&nbsp;int)&nbsp;-&gt;&nbsp;Optional[np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;weight&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;W&nbsp;=&nbsp;np.asarray(weight,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;W.ndim&nbsp;==&nbsp;1:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;W.size&nbsp;!=&nbsp;rows:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Weight&nbsp;vector&nbsp;size&nbsp;must&nbsp;match&nbsp;the&nbsp;task&nbsp;dimension.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;np.diag(W)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;W.shape&nbsp;!=&nbsp;(rows,&nbsp;rows):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Weight&nbsp;matrix&nbsp;must&nbsp;be&nbsp;square&nbsp;with&nbsp;size&nbsp;equal&nbsp;to&nbsp;the&nbsp;task&nbsp;dimension.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;W<br>
<br>
<br>
class&nbsp;JointTrackingTask(QuadraticTask):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Следит&nbsp;за&nbsp;желаемыми&nbsp;суставными&nbsp;координатами.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Минимизируется&nbsp;функционал<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min_x&nbsp;||&nbsp;S&nbsp;x&nbsp;-&nbsp;S&nbsp;q_ref&nbsp;||_W^2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;где&nbsp;x&nbsp;—&nbsp;искомые&nbsp;обобщённые&nbsp;скорости/приращения,&nbsp;q_ref&nbsp;—&nbsp;желаемый&nbsp;вектор,<br>
&nbsp;&nbsp;&nbsp;&nbsp;а&nbsp;S&nbsp;—&nbsp;матрица&nbsp;выбора&nbsp;(по&nbsp;умолчанию&nbsp;S&nbsp;=&nbsp;I).&nbsp;При&nbsp;W&nbsp;=&nbsp;diag(w)&nbsp;это&nbsp;простая<br>
&nbsp;&nbsp;&nbsp;&nbsp;взвешенная&nbsp;подстройка&nbsp;отдельных&nbsp;координат.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_ref:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selection:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;weight:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_ref&nbsp;=&nbsp;np.asarray(q_ref,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;q_ref.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;selection&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;J&nbsp;=&nbsp;np.eye(n)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target&nbsp;=&nbsp;q_ref<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selection&nbsp;=&nbsp;np.asarray(selection,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;selection.shape[1]&nbsp;!=&nbsp;n:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Selection&nbsp;matrix&nbsp;must&nbsp;have&nbsp;the&nbsp;same&nbsp;number&nbsp;of&nbsp;columns&nbsp;as&nbsp;len(q_ref).&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;J&nbsp;=&nbsp;selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;target&nbsp;=&nbsp;selection&nbsp;@&nbsp;q_ref<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;W&nbsp;=&nbsp;_prepare_weight(weight,&nbsp;J.shape[0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(J,&nbsp;target,&nbsp;W)<br>
<br>
<br>
class&nbsp;CartesianTrackingTask(QuadraticTask):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Типовая&nbsp;задача:&nbsp;совместить&nbsp;линейную/угловую&nbsp;скорость&nbsp;с&nbsp;целью.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Функционал:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min_x&nbsp;||&nbsp;J_cart&nbsp;x&nbsp;-&nbsp;v_des&nbsp;||_W^2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;где&nbsp;J_cart&nbsp;—&nbsp;пространственный&nbsp;Якобиан,&nbsp;v_des&nbsp;=&nbsp;v_ref&nbsp;+&nbsp;K&nbsp;e&nbsp;—&nbsp;желаемая<br>
&nbsp;&nbsp;&nbsp;&nbsp;скорость/скользящий&nbsp;вектор.&nbsp;Вызов&nbsp;принимает&nbsp;уже&nbsp;сформированные&nbsp;(J_cart,&nbsp;v_des).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jacobian:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;desired_twist:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;weight:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jacobian&nbsp;=&nbsp;np.asarray(jacobian,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;desired_twist&nbsp;=&nbsp;np.asarray(desired_twist,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;jacobian.shape[0]&nbsp;!=&nbsp;desired_twist.size:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Jacobian&nbsp;rows&nbsp;must&nbsp;match&nbsp;the&nbsp;size&nbsp;of&nbsp;desired_twist.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;W&nbsp;=&nbsp;_prepare_weight(weight,&nbsp;jacobian.shape[0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(jacobian,&nbsp;desired_twist,&nbsp;W)<br>
<br>
<br>
class&nbsp;JointEqualityConstraint(EqualityConstraint):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Фиксирует&nbsp;отдельные&nbsp;суставы:&nbsp;S&nbsp;x&nbsp;=&nbsp;S&nbsp;q_target.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Это&nbsp;линейное&nbsp;равенство&nbsp;с&nbsp;матрицей&nbsp;S&nbsp;(по&nbsp;умолчанию&nbsp;I).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;q_target:&nbsp;np.ndarray,&nbsp;selection:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_target&nbsp;=&nbsp;np.asarray(q_target,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;q_target.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;selection&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;=&nbsp;np.eye(n)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;q_target<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;selection&nbsp;=&nbsp;np.asarray(selection,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;selection.shape[1]&nbsp;!=&nbsp;n:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Selection&nbsp;matrix&nbsp;must&nbsp;have&nbsp;the&nbsp;same&nbsp;number&nbsp;of&nbsp;columns&nbsp;as&nbsp;len(q_target).&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A&nbsp;=&nbsp;selection<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;selection&nbsp;@&nbsp;q_target<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(A,&nbsp;b)<br>
<br>
<br>
class&nbsp;CartesianEqualityConstraint(EqualityConstraint):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Жёсткая&nbsp;задача&nbsp;J&nbsp;x&nbsp;=&nbsp;rhs&nbsp;для&nbsp;контактов&nbsp;или&nbsp;привязки&nbsp;инструмента.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;jacobian:&nbsp;np.ndarray,&nbsp;rhs:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(jacobian,&nbsp;rhs)<br>
<br>
<br>
class&nbsp;JointBoundsConstraint(InequalityConstraint):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Задаёт&nbsp;ограничения&nbsp;вида&nbsp;lower&nbsp;≤&nbsp;x&nbsp;≤&nbsp;upper&nbsp;(возможно&nbsp;односторонние).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Преобразуется&nbsp;к&nbsp;стандартной&nbsp;форме&nbsp;C&nbsp;x&nbsp;≤&nbsp;d:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x&nbsp;≤&nbsp;upper&nbsp;&nbsp;→&nbsp;&nbsp;[&nbsp;I]&nbsp;x&nbsp;≤&nbsp;upper<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-x&nbsp;≤&nbsp;-lower&nbsp;→&nbsp;[-I]&nbsp;x&nbsp;≤&nbsp;-lower.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;lower:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,&nbsp;upper:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower&nbsp;is&nbsp;None&nbsp;and&nbsp;upper&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;At&nbsp;least&nbsp;one&nbsp;of&nbsp;lower/upper&nbsp;bounds&nbsp;must&nbsp;be&nbsp;provided.&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs_parts&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n:&nbsp;Optional[int]&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;upper&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;upper&nbsp;=&nbsp;np.asarray(upper,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;upper.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.append(np.eye(n))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs_parts.append(upper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lower&nbsp;=&nbsp;np.asarray(lower,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;n&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;lower.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower.size&nbsp;!=&nbsp;n:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;Lower/upper&nbsp;bounds&nbsp;must&nbsp;have&nbsp;the&nbsp;same&nbsp;length.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.append(-np.eye(n))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs_parts.append(-lower)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;n&nbsp;is&nbsp;not&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;=&nbsp;np.vstack(rows)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d&nbsp;=&nbsp;np.concatenate(rhs_parts)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(C,&nbsp;d)<br>
<br>
<br>
class&nbsp;JointVelocityDampingTask(QuadraticTask):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Сглаживает&nbsp;управление,&nbsp;минимизируя&nbsp;норму&nbsp;суставных&nbsp;скоростей.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;n_dofs:&nbsp;int,&nbsp;weight:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;n_dofs&nbsp;&lt;=&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;n_dofs&nbsp;must&nbsp;be&nbsp;positive.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;J&nbsp;=&nbsp;np.eye(n_dofs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v&nbsp;=&nbsp;np.zeros(n_dofs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;W&nbsp;=&nbsp;_prepare_weight(weight,&nbsp;n_dofs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(J,&nbsp;v,&nbsp;W)<br>
<br>
<br>
class&nbsp;JointPositionBoundsConstraint(InequalityConstraint):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Гарантирует,&nbsp;что&nbsp;q&nbsp;+&nbsp;dt&nbsp;*&nbsp;dq&nbsp;останется&nbsp;в&nbsp;[lower,&nbsp;upper].&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_current:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lower:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;upper:&nbsp;Optional[np.ndarray]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dt:&nbsp;float&nbsp;=&nbsp;1.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;dt&nbsp;&lt;=&nbsp;0.0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;dt&nbsp;must&nbsp;be&nbsp;positive.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;q_current&nbsp;=&nbsp;np.asarray(q_current,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;q_current.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower&nbsp;is&nbsp;None&nbsp;and&nbsp;upper&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;At&nbsp;least&nbsp;one&nbsp;of&nbsp;lower/upper&nbsp;bounds&nbsp;must&nbsp;be&nbsp;provided.&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;upper&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;upper&nbsp;=&nbsp;np.asarray(upper,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;upper.size&nbsp;!=&nbsp;n:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;upper&nbsp;must&nbsp;have&nbsp;same&nbsp;length&nbsp;as&nbsp;q_current.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.append(np.eye(n)&nbsp;*&nbsp;dt)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs.append(upper&nbsp;-&nbsp;q_current)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lower&nbsp;=&nbsp;np.asarray(lower,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower.size&nbsp;!=&nbsp;n:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(&quot;lower&nbsp;must&nbsp;have&nbsp;same&nbsp;length&nbsp;as&nbsp;q_current.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.append(-np.eye(n)&nbsp;*&nbsp;dt)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rhs.append(q_current&nbsp;-&nbsp;lower)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C&nbsp;=&nbsp;np.vstack(rows)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d&nbsp;=&nbsp;np.concatenate(rhs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(C,&nbsp;d)<br>
<br>
<br>
def&nbsp;build_joint_soft_limit_task(<br>
&nbsp;&nbsp;&nbsp;&nbsp;q_current:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;lower:&nbsp;Optional[np.ndarray],<br>
&nbsp;&nbsp;&nbsp;&nbsp;upper:&nbsp;Optional[np.ndarray],<br>
&nbsp;&nbsp;&nbsp;&nbsp;margin:&nbsp;float,<br>
&nbsp;&nbsp;&nbsp;&nbsp;gain:&nbsp;float,<br>
)&nbsp;-&gt;&nbsp;Optional[QuadraticTask]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;QuadraticTask,&nbsp;отталкивающий&nbsp;суставы&nbsp;от&nbsp;мягких&nbsp;зон.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;margin&nbsp;&lt;=&nbsp;0&nbsp;or&nbsp;gain&nbsp;&lt;=&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;q_current&nbsp;=&nbsp;np.asarray(q_current,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;q_current.size<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;upper_arr&nbsp;=&nbsp;np.asarray(upper,&nbsp;dtype=float)&nbsp;if&nbsp;upper&nbsp;is&nbsp;not&nbsp;None&nbsp;else&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;lower_arr&nbsp;=&nbsp;np.asarray(lower,&nbsp;dtype=float)&nbsp;if&nbsp;lower&nbsp;is&nbsp;not&nbsp;None&nbsp;else&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;rows&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;targets&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_push(amount:&nbsp;float)&nbsp;-&gt;&nbsp;float:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase&nbsp;=&nbsp;min(max(amount&nbsp;/&nbsp;margin,&nbsp;0.0),&nbsp;1.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;gain&nbsp;*&nbsp;phase<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx&nbsp;in&nbsp;range(n):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;coord&nbsp;=&nbsp;q_current[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;desired&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;active&nbsp;=&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;upper_arr&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary&nbsp;=&nbsp;upper_arr[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trigger&nbsp;=&nbsp;boundary&nbsp;-&nbsp;margin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;coord&nbsp;&gt;&nbsp;trigger:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;desired&nbsp;-=&nbsp;_push(coord&nbsp;-&nbsp;trigger)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;active&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;lower_arr&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;boundary&nbsp;=&nbsp;lower_arr[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trigger&nbsp;=&nbsp;boundary&nbsp;+&nbsp;margin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;coord&nbsp;&lt;&nbsp;trigger:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;desired&nbsp;+=&nbsp;_push(trigger&nbsp;-&nbsp;coord)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;active&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;active:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;row&nbsp;=&nbsp;np.zeros(n)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;row[idx]&nbsp;=&nbsp;1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rows.append(row)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;targets.append(desired)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;rows:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;J&nbsp;=&nbsp;np.vstack(rows)<br>
&nbsp;&nbsp;&nbsp;&nbsp;v&nbsp;=&nbsp;np.array(targets,&nbsp;dtype=float)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;QuadraticTask(J,&nbsp;v)<br>
<!-- END SCAT CODE -->
</body>
</html>
