<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/framegraph/resource.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Иерархия&nbsp;ресурсов&nbsp;framegraph.<br>
<br>
FrameGraphResource&nbsp;—&nbsp;базовый&nbsp;класс&nbsp;для&nbsp;всех&nbsp;ресурсов&nbsp;конвейера.<br>
Ресурсы&nbsp;передаются&nbsp;между&nbsp;пассами&nbsp;через&nbsp;reads/writes.<br>
<br>
Типы&nbsp;ресурсов:<br>
-&nbsp;SingleFBO:&nbsp;обёртка&nbsp;над&nbsp;одним&nbsp;framebuffer'ом<br>
-&nbsp;ShadowMapArray:&nbsp;массив&nbsp;shadow&nbsp;maps&nbsp;для&nbsp;освещения<br>
<br>
Алиасы&nbsp;(inplace):<br>
&nbsp;&nbsp;&nbsp;&nbsp;При&nbsp;inplace-операции&nbsp;ресурс&nbsp;читается&nbsp;и&nbsp;пишется&nbsp;одновременно.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Для&nbsp;этого&nbsp;используется&nbsp;пара&nbsp;алиасов&nbsp;(read_name,&nbsp;write_name),<br>
&nbsp;&nbsp;&nbsp;&nbsp;которые&nbsp;ссылаются&nbsp;на&nbsp;один&nbsp;и&nbsp;тот&nbsp;же&nbsp;физический&nbsp;ресурс.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;abc&nbsp;import&nbsp;ABC,&nbsp;abstractmethod<br>
from&nbsp;dataclasses&nbsp;import&nbsp;dataclass,&nbsp;field<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING,&nbsp;List,&nbsp;Tuple<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;FramebufferHandle,&nbsp;TextureHandle<br>
<br>
<br>
class&nbsp;FrameGraphResource(ABC):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Базовый&nbsp;класс&nbsp;для&nbsp;ресурсов&nbsp;framegraph.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Каждый&nbsp;ресурс&nbsp;имеет&nbsp;тип&nbsp;(resource_type),&nbsp;по&nbsp;которому<br>
&nbsp;&nbsp;&nbsp;&nbsp;RenderEngine&nbsp;определяет,&nbsp;как&nbsp;с&nbsp;ним&nbsp;работать.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;@abstractmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;resource_type(self)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тип&nbsp;ресурса&nbsp;для&nbsp;идентификации&nbsp;в&nbsp;pipeline.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...<br>
<br>
<br>
@dataclass<br>
class&nbsp;SingleFBO(FrameGraphResource):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Обёртка&nbsp;над&nbsp;одним&nbsp;framebuffer'ом.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Это&nbsp;стандартный&nbsp;тип&nbsp;ресурса&nbsp;для&nbsp;большинства&nbsp;пассов:<br>
&nbsp;&nbsp;&nbsp;&nbsp;color&nbsp;pass,&nbsp;depth&nbsp;pass,&nbsp;id&nbsp;pass&nbsp;и&nbsp;т.д.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Атрибуты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo:&nbsp;handle&nbsp;на&nbsp;framebuffer<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size:&nbsp;размер&nbsp;(width,&nbsp;height)&nbsp;или&nbsp;None&nbsp;для&nbsp;автоматического<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fbo:&nbsp;&quot;FramebufferHandle&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;size:&nbsp;Tuple[int,&nbsp;int]&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;resource_type(self)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;fbo&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;color_texture(self)&nbsp;-&gt;&nbsp;&quot;TextureHandle&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;color&nbsp;attachment&nbsp;как&nbsp;текстуру.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.fbo.color_texture()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;depth_texture(self)&nbsp;-&gt;&nbsp;&quot;TextureHandle&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;depth&nbsp;attachment&nbsp;как&nbsp;текстуру&nbsp;(если&nbsp;есть).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.fbo.depth_texture()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;resize(self,&nbsp;size:&nbsp;Tuple[int,&nbsp;int])&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Изменяет&nbsp;размер&nbsp;framebuffer'а.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.fbo.resize(size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.size&nbsp;=&nbsp;size<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;текущий&nbsp;размер.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.size&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.fbo.get_size()<br>
<br>
<br>
@dataclass<br>
class&nbsp;ShadowMapArrayEntry:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Данные&nbsp;одного&nbsp;shadow&nbsp;map&nbsp;для&nbsp;одного&nbsp;источника&nbsp;света.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Атрибуты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo:&nbsp;FBO,&nbsp;в&nbsp;который&nbsp;рендерится&nbsp;shadow&nbsp;map<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_space_matrix:&nbsp;матрица&nbsp;P&nbsp;*&nbsp;V&nbsp;для&nbsp;преобразования&nbsp;мировых&nbsp;координат<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;в&nbsp;clip-пространство&nbsp;источника&nbsp;света<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_index:&nbsp;индекс&nbsp;источника&nbsp;в&nbsp;scene.lights<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Формула&nbsp;преобразования&nbsp;точки&nbsp;p&nbsp;в&nbsp;shadow&nbsp;map&nbsp;координаты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_light_clip&nbsp;=&nbsp;light_space_matrix&nbsp;@&nbsp;[p.x,&nbsp;p.y,&nbsp;p.z,&nbsp;1]^T<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uv&nbsp;=&nbsp;(p_light_clip.xy&nbsp;/&nbsp;p_light_clip.w)&nbsp;*&nbsp;0.5&nbsp;+&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;depth_from_light&nbsp;=&nbsp;p_light_clip.z&nbsp;/&nbsp;p_light_clip.w<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;fbo:&nbsp;&quot;FramebufferHandle&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_space_matrix:&nbsp;np.ndarray<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_index:&nbsp;int<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;texture(self)&nbsp;-&gt;&nbsp;&quot;TextureHandle&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;color-текстуру&nbsp;FBO.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.fbo.color_texture()<br>
<br>
<br>
@dataclass<br>
class&nbsp;ShadowMapArrayResource(FrameGraphResource):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Массив&nbsp;shadow&nbsp;maps&nbsp;для&nbsp;всех&nbsp;источников&nbsp;света&nbsp;с&nbsp;тенями.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Это&nbsp;ресурс&nbsp;framegraph,&nbsp;который&nbsp;ShadowPass&nbsp;создаёт&nbsp;и&nbsp;записывает,<br>
&nbsp;&nbsp;&nbsp;&nbsp;а&nbsp;ColorPass&nbsp;читает.<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Атрибуты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entries:&nbsp;список&nbsp;ShadowMapArrayEntry,&nbsp;по&nbsp;одному&nbsp;на&nbsp;источник<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resolution:&nbsp;разрешение&nbsp;каждого&nbsp;shadow&nbsp;map&nbsp;(квадратное)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;entries:&nbsp;List[ShadowMapArrayEntry]&nbsp;=&nbsp;field(default_factory=list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;resolution:&nbsp;int&nbsp;=&nbsp;1024<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;resource_type(self)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;&quot;shadow_map_array&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__len__(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;len(self.entries)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__getitem__(self,&nbsp;index:&nbsp;int)&nbsp;-&gt;&nbsp;ShadowMapArrayEntry:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.entries[index]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__iter__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;iter(self.entries)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;add_entry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo:&nbsp;&quot;FramebufferHandle&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_space_matrix:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_index:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Добавляет&nbsp;запись&nbsp;для&nbsp;нового&nbsp;источника&nbsp;света.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.entries.append(ShadowMapArrayEntry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo=fbo,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_space_matrix=light_space_matrix,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;light_index=light_index,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clear(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Очищает&nbsp;массив&nbsp;(FBO&nbsp;не&nbsp;удаляются,&nbsp;только&nbsp;ссылки).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.entries.clear()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_by_light_index(self,&nbsp;light_index:&nbsp;int)&nbsp;-&gt;&nbsp;ShadowMapArrayEntry&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Находит&nbsp;entry&nbsp;по&nbsp;индексу&nbsp;источника&nbsp;света.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;entry&nbsp;in&nbsp;self.entries:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;entry.light_index&nbsp;==&nbsp;light_index:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;entry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<!-- END SCAT CODE -->
</body>
</html>
