<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>utest/collider_test.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;termin.colliders.capsule&nbsp;import&nbsp;CapsuleCollider<br>
from&nbsp;termin.colliders.sphere&nbsp;import&nbsp;SphereCollider<br>
from&nbsp;termin.colliders.union_collider&nbsp;import&nbsp;UnionCollider<br>
from&nbsp;termin.colliders.box&nbsp;import&nbsp;BoxCollider<br>
import&nbsp;unittest<br>
from&nbsp;termin.kinematic&nbsp;import&nbsp;Transform3<br>
from&nbsp;termin.colliders.attached&nbsp;import&nbsp;AttachedCollider<br>
import&nbsp;numpy<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;AABB<br>
<br>
class&nbsp;TestCollider(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_closest_to_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule1&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;1.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.25<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule2&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.25<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_near,&nbsp;q_near,&nbsp;dist&nbsp;=&nbsp;capsule1.closest_to_capsule(capsule2)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_dist&nbsp;=&nbsp;0.5&nbsp;&nbsp;#&nbsp;Capsules&nbsp;are&nbsp;touching<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_dist)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_p_near&nbsp;=&nbsp;numpy.array([0.25,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_q_near&nbsp;=&nbsp;numpy.array([0.75,&nbsp;0.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_near,&nbsp;expected_p_near)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(q_near,&nbsp;expected_q_near)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_closest_sphere_to_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;2.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere_center&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere_radius&nbsp;=&nbsp;0.5<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;sphere_center,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;sphere_radius<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_near,&nbsp;q_near,&nbsp;dist&nbsp;=&nbsp;sphere.closest_to_capsule(capsule)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_dist&nbsp;=&nbsp;0.0&nbsp;&nbsp;#&nbsp;They&nbsp;are&nbsp;touching<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_dist)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_p_near&nbsp;=&nbsp;numpy.array([0.5,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_q_near&nbsp;=&nbsp;numpy.array([0.5,&nbsp;0.0,&nbsp;1.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_near,&nbsp;expected_p_near)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(q_near,&nbsp;expected_q_near)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_closest_union_collider(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere1&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere2&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union_collider&nbsp;=&nbsp;UnionCollider([sphere1,&nbsp;sphere2])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;test_sphere&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;1.5,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_near,&nbsp;q_near,&nbsp;dist&nbsp;=&nbsp;union_collider.closest_to_collider(test_sphere)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_dist&nbsp;=&nbsp;0.5&nbsp;&nbsp;#&nbsp;Closest&nbsp;to&nbsp;sphere1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_dist)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_p_near&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.5,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_q_near&nbsp;=&nbsp;numpy.array([0.0,&nbsp;1.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_near,&nbsp;expected_p_near)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(q_near,&nbsp;expected_q_near)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_two_union_colliders(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere1&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere2&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union_collider1&nbsp;=&nbsp;UnionCollider([sphere1,&nbsp;sphere2])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere3&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([1.25,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere4&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([5.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union_collider2&nbsp;=&nbsp;UnionCollider([sphere3,&nbsp;sphere4])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_near,&nbsp;q_near,&nbsp;dist&nbsp;=&nbsp;union_collider1.closest_to_collider(union_collider2)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_dist&nbsp;=&nbsp;0.25&nbsp;&nbsp;#&nbsp;Closest&nbsp;between&nbsp;sphere2&nbsp;and&nbsp;sphere3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_dist)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_p_near&nbsp;=&nbsp;numpy.array([0.5,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_q_near&nbsp;=&nbsp;numpy.array([0.75,&nbsp;0.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_near,&nbsp;expected_p_near)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(q_near,&nbsp;expected_q_near)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_closest_of_box_and_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box&nbsp;=&nbsp;BoxCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;numpy.array([2.0,&nbsp;1.0,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b&nbsp;=&nbsp;numpy.array([4.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;closest_box_point,&nbsp;closest_capsule_point,&nbsp;distance&nbsp;=&nbsp;box.closest_point_to_capsule(capsule)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_distance&nbsp;=&nbsp;1.8<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(distance,&nbsp;expected_distance)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_closest_box_point&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_closest_capsule_point&nbsp;=&nbsp;numpy.array([2.8,&nbsp;0.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(closest_box_point,&nbsp;expected_closest_box_point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(closest_capsule_point,&nbsp;expected_closest_capsule_point)<br>
<br>
class&nbsp;TestColliderAvoidance(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_avoidance_vector(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere1&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere2&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([6.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction,&nbsp;dist,&nbsp;closest_point&nbsp;=&nbsp;sphere1.avoidance(sphere2)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_direction&nbsp;=&nbsp;numpy.array([-1.0,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_dist&nbsp;=&nbsp;5.0&nbsp;&nbsp;#&nbsp;Distance&nbsp;between&nbsp;surfaces<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_closest_point&nbsp;=&nbsp;numpy.array([0.5,&nbsp;0.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(direction,&nbsp;expected_direction)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(closest_point,&nbsp;expected_closest_point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_dist)<br>
<br>
class&nbsp;AttachedColliderTest(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_attached_collider_distance(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box&nbsp;=&nbsp;BoxCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size&nbsp;=&nbsp;numpy.array([2.0,&nbsp;1.0,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(box.local_aabb().min_point,&nbsp;numpy.array([-1.0,&nbsp;-0.5,&nbsp;-0.25]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(box.local_aabb().max_point,&nbsp;numpy.array([1.0,&nbsp;0.5,&nbsp;0.25]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;trans&nbsp;=&nbsp;Transform3()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attached_box&nbsp;=&nbsp;AttachedCollider(box,&nbsp;trans)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius&nbsp;=&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attached_sphere&nbsp;=&nbsp;AttachedCollider(sphere,&nbsp;Transform3())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_near,&nbsp;q_near,&nbsp;dist&nbsp;=&nbsp;attached_box.closest_to_collider(attached_sphere)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_distance&nbsp;=&nbsp;1.5&nbsp;&nbsp;#&nbsp;Distance&nbsp;between&nbsp;surfaces<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_p_near&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_q_near&nbsp;=&nbsp;numpy.array([2.5,&nbsp;0.0,&nbsp;0.0])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;expected_distance)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_near,&nbsp;expected_p_near)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(q_near,&nbsp;expected_q_near)<br>
<br>
class&nbsp;TestColliderRay(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_hits_sphere(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([0.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;sphere.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Должно&nbsp;быть&nbsp;прямое&nbsp;попадание&nbsp;—&nbsp;расстояние&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;0.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Точка&nbsp;пересечения&nbsp;должна&nbsp;быть&nbsp;на&nbsp;z&nbsp;=&nbsp;4&nbsp;(радиус&nbsp;=&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected&nbsp;=&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;4.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;expected)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_col,&nbsp;expected)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_misses_sphere(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([0.0,&nbsp;5.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;sphere.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Простая&nbsp;геометрия:&nbsp;кратчайшая&nbsp;точка&nbsp;луча&nbsp;—&nbsp;(0,0,5)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;5.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Точка&nbsp;на&nbsp;сфере&nbsp;ближе&nbsp;всего&nbsp;по&nbsp;вертикали<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;центр&nbsp;=&nbsp;(0,5,5),&nbsp;радиус=1&nbsp;→&nbsp;ближайшая&nbsp;точка&nbsp;=&nbsp;(0,4,5)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_col,&nbsp;numpy.array([0.0,&nbsp;4.0,&nbsp;5.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Расстояние&nbsp;от&nbsp;луча&nbsp;до&nbsp;центра&nbsp;=&nbsp;5,&nbsp;до&nbsp;поверхности&nbsp;=&nbsp;5&nbsp;-&nbsp;1&nbsp;=&nbsp;4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;4.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_hits_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a=numpy.array([0.0,&nbsp;0.0,&nbsp;3.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b=numpy.array([0.0,&nbsp;0.0,&nbsp;7.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;capsule.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Луч&nbsp;входит&nbsp;в&nbsp;капсулу&nbsp;на&nbsp;z=2&nbsp;(нижняя&nbsp;сфера)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_col,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;2.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_misses_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule&nbsp;=&nbsp;CapsuleCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a=numpy.array([5.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;b=numpy.array([5.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;capsule.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Геометрия:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Луч&nbsp;проходит&nbsp;по&nbsp;линии&nbsp;x=0&nbsp;→&nbsp;кратчайшая&nbsp;точка&nbsp;луча&nbsp;к&nbsp;сегменту&nbsp;—&nbsp;(0,0,z)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ближайшая&nbsp;точка&nbsp;сегмента&nbsp;—&nbsp;(5,0,z)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Расстояние&nbsp;=&nbsp;5&nbsp;-&nbsp;0.5&nbsp;=&nbsp;4.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;4.5)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_hits_box(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box&nbsp;=&nbsp;BoxCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([0.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size=numpy.array([2.0,&nbsp;2.0,&nbsp;2.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;box.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Бокс&nbsp;начинается&nbsp;на&nbsp;z&nbsp;=&nbsp;4&nbsp;(size&nbsp;z=2,&nbsp;центр&nbsp;на&nbsp;5)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;4.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_misses_box(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;box&nbsp;=&nbsp;BoxCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([5.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size=numpy.array([2.0,&nbsp;2.0,&nbsp;2.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;box.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Минимальная&nbsp;точка&nbsp;на&nbsp;луче&nbsp;лежит&nbsp;на&nbsp;входной&nbsp;грани&nbsp;z=4&nbsp;(любая&nbsp;z∈[4,6]&nbsp;эквивалентна)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;4.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ближайшая&nbsp;точка&nbsp;в&nbsp;коробке&nbsp;по&nbsp;x&nbsp;—&nbsp;4&nbsp;(центр&nbsp;5,&nbsp;halfsize=1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_box_pt&nbsp;=&nbsp;numpy.array([4.0,&nbsp;0.0,&nbsp;4.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_col,&nbsp;expected_box_pt)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Расстояние&nbsp;между&nbsp;точками&nbsp;=&nbsp;4&nbsp;(смещение&nbsp;только&nbsp;по&nbsp;x)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;4.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_ray_hits_union(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere1&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([0.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sphere2&nbsp;=&nbsp;SphereCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=numpy.array([10.0,&nbsp;0.0,&nbsp;5.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;union&nbsp;=&nbsp;UnionCollider([sphere1,&nbsp;sphere2])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase.ray&nbsp;import&nbsp;Ray3<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ray&nbsp;=&nbsp;Ray3(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=numpy.array([0.0,&nbsp;0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_col,&nbsp;p_ray,&nbsp;dist&nbsp;=&nbsp;union.closest_to_ray(ray)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Попадёт&nbsp;в&nbsp;sphere1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(dist,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(p_ray,&nbsp;numpy.array([0.0,&nbsp;0.0,&nbsp;4.0]))<br>
<!-- END SCAT CODE -->
</body>
</html>
