<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>utest/pose2_test.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#!/usr/bin/env&nbsp;python3<br>
import&nbsp;unittest<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
import&nbsp;math<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose2<br>
<br>
<br>
class&nbsp;TestPose2(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;класса&nbsp;Pose2&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_identity(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;создания&nbsp;единичной&nbsp;позы&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2.identity()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(pose.ang,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose.lin,&nbsp;np.array([0.0,&nbsp;0.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_rotation_matrix(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;матрицы&nbsp;поворота&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;=&nbsp;math.pi&nbsp;/&nbsp;4&nbsp;&nbsp;#&nbsp;45&nbsp;градусов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=angle)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;=&nbsp;pose.rotation_matrix()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;размера<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(R.shape,&nbsp;(2,&nbsp;2))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;значений&nbsp;для&nbsp;45&nbsp;градусов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;=&nbsp;math.cos(angle)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;s&nbsp;=&nbsp;math.sin(angle)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected&nbsp;=&nbsp;np.array([[c,&nbsp;-s],&nbsp;[s,&nbsp;c]])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(R,&nbsp;expected)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_transform_point(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;трансформации&nbsp;точки&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Поворот&nbsp;на&nbsp;90&nbsp;градусов&nbsp;против&nbsp;часовой&nbsp;стрелки&nbsp;+&nbsp;сдвиг&nbsp;на&nbsp;(1,&nbsp;2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=math.pi/2,&nbsp;lin=np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Точка&nbsp;(1,&nbsp;0)&nbsp;после&nbsp;поворота&nbsp;на&nbsp;90°&nbsp;становится&nbsp;(0,&nbsp;1),&nbsp;потом&nbsp;сдвиг&nbsp;-&gt;&nbsp;(1,&nbsp;3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;np.array([1.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transformed&nbsp;=&nbsp;pose.transform_point(point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected&nbsp;=&nbsp;np.array([1.0,&nbsp;3.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(transformed,&nbsp;expected)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_transform_vector(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;трансформации&nbsp;вектора&nbsp;(без&nbsp;сдвига)&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Поворот&nbsp;на&nbsp;90&nbsp;градусов&nbsp;+&nbsp;сдвиг&nbsp;(сдвиг&nbsp;не&nbsp;должен&nbsp;влиять&nbsp;на&nbsp;вектор)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=math.pi/2,&nbsp;lin=np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Вектор&nbsp;(1,&nbsp;0)&nbsp;после&nbsp;поворота&nbsp;на&nbsp;90°&nbsp;становится&nbsp;(0,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vector&nbsp;=&nbsp;np.array([1.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transformed&nbsp;=&nbsp;pose.transform_vector(vector)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected&nbsp;=&nbsp;np.array([0.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(transformed,&nbsp;expected)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_inverse(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;инверсии&nbsp;позы&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=math.pi/4,&nbsp;lin=np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inv_pose&nbsp;=&nbsp;pose.inverse()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Композиция&nbsp;позы&nbsp;с&nbsp;её&nbsp;инверсией&nbsp;должна&nbsp;дать&nbsp;единичную&nbsp;позу<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;identity&nbsp;=&nbsp;pose&nbsp;*&nbsp;inv_pose<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(identity.ang,&nbsp;0.0,&nbsp;places=10)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(identity.lin,&nbsp;np.array([0.0,&nbsp;0.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_composition(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;композиции&nbsp;поз&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Первая&nbsp;поза:&nbsp;поворот&nbsp;на&nbsp;45°&nbsp;+&nbsp;сдвиг&nbsp;на&nbsp;(1,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose1&nbsp;=&nbsp;Pose2(ang=math.pi/4,&nbsp;lin=np.array([1.0,&nbsp;0.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Вторая&nbsp;поза:&nbsp;поворот&nbsp;на&nbsp;45°&nbsp;+&nbsp;сдвиг&nbsp;на&nbsp;(0,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose2&nbsp;=&nbsp;Pose2(ang=math.pi/4,&nbsp;lin=np.array([0.0,&nbsp;1.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Композиция<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;composed&nbsp;=&nbsp;pose1&nbsp;*&nbsp;pose2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Угол&nbsp;должен&nbsp;быть&nbsp;суммой&nbsp;углов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_ang&nbsp;=&nbsp;math.pi/2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(composed.ang,&nbsp;expected_ang)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;трансформации&nbsp;точки<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;np.array([1.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Применяем&nbsp;композицию<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_composed&nbsp;=&nbsp;composed.transform_point(point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Применяем&nbsp;последовательно<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_temp&nbsp;=&nbsp;pose2.transform_point(point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p_sequential&nbsp;=&nbsp;pose1.transform_point(p_temp)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(p_composed,&nbsp;p_sequential)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_translation(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;создания&nbsp;позы&nbsp;с&nbsp;только&nbsp;сдвигом&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2.translation(3.0,&nbsp;4.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(pose.ang,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose.lin,&nbsp;np.array([3.0,&nbsp;4.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;трансформации&nbsp;точки<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;np.array([1.0,&nbsp;2.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transformed&nbsp;=&nbsp;pose.transform_point(point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(transformed,&nbsp;np.array([4.0,&nbsp;6.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_rotation(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;создания&nbsp;позы&nbsp;с&nbsp;только&nbsp;поворотом&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;=&nbsp;math.pi&nbsp;/&nbsp;3&nbsp;&nbsp;#&nbsp;60&nbsp;градусов<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2.rotation(angle)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(pose.ang,&nbsp;angle)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose.lin,&nbsp;np.array([0.0,&nbsp;0.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_as_matrix(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;получения&nbsp;матрицы&nbsp;трансформации&nbsp;3x3&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=math.pi/2,&nbsp;lin=np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;pose.as_matrix()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;размера<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(mat.shape,&nbsp;(3,&nbsp;3))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверка&nbsp;структуры&nbsp;матрицы<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;[R&nbsp;|&nbsp;t]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;[0&nbsp;|&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R&nbsp;=&nbsp;pose.rotation_matrix()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(mat[:2,&nbsp;:2],&nbsp;R)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(mat[:2,&nbsp;2],&nbsp;pose.lin)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(mat[2,&nbsp;:],&nbsp;np.array([0.0,&nbsp;0.0,&nbsp;1.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_inverse_transform_point(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;обратной&nbsp;трансформации&nbsp;точки&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=math.pi/4,&nbsp;lin=np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Прямая&nbsp;и&nbsp;обратная&nbsp;трансформация&nbsp;должны&nbsp;компенсировать&nbsp;друг&nbsp;друга<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;original&nbsp;=&nbsp;np.array([3.0,&nbsp;4.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transformed&nbsp;=&nbsp;pose.transform_point(original)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;restored&nbsp;=&nbsp;pose.inverse_transform_point(transformed)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(restored,&nbsp;original)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_lerp(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;линейной&nbsp;интерполяции&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose1&nbsp;=&nbsp;Pose2(ang=0.0,&nbsp;lin=np.array([0.0,&nbsp;0.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose2&nbsp;=&nbsp;Pose2(ang=math.pi/2,&nbsp;lin=np.array([2.0,&nbsp;4.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Интерполяция&nbsp;в&nbsp;середине<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mid&nbsp;=&nbsp;Pose2.lerp(pose1,&nbsp;pose2,&nbsp;0.5)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(mid.ang,&nbsp;math.pi/4)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(mid.lin,&nbsp;np.array([1.0,&nbsp;2.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Интерполяция&nbsp;в&nbsp;начале<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start&nbsp;=&nbsp;Pose2.lerp(pose1,&nbsp;pose2,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(start.ang,&nbsp;pose1.ang)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(start.lin,&nbsp;pose1.lin)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Интерполяция&nbsp;в&nbsp;конце<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end&nbsp;=&nbsp;Pose2.lerp(pose1,&nbsp;pose2,&nbsp;1.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(end.ang,&nbsp;pose2.ang)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_almost_equal(end.lin,&nbsp;pose2.lin)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_properties(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;свойств&nbsp;x&nbsp;и&nbsp;y&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(lin=np.array([3.0,&nbsp;4.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(pose.x,&nbsp;3.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertEqual(pose.y,&nbsp;4.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Изменение&nbsp;через&nbsp;свойства<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose.x&nbsp;=&nbsp;5.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose.y&nbsp;=&nbsp;6.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose.lin,&nbsp;np.array([5.0,&nbsp;6.0]))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_normalize_angle(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;нормализации&nbsp;угла&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Угол&nbsp;больше&nbsp;π<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=3&nbsp;*&nbsp;math.pi)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose.normalize_angle()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Должен&nbsp;быть&nbsp;нормализован&nbsp;к&nbsp;[-π,&nbsp;π]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertGreaterEqual(pose.ang,&nbsp;-math.pi)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertLessEqual(pose.ang,&nbsp;math.pi)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;3π&nbsp;нормализуется&nbsp;к&nbsp;π&nbsp;(или&nbsp;-π,&nbsp;они&nbsp;эквивалентны)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(abs(pose.ang),&nbsp;math.pi,&nbsp;places=10)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_moveX_moveY(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тест&nbsp;вспомогательных&nbsp;методов&nbsp;перемещения&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose_x&nbsp;=&nbsp;Pose2.moveX(3.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose_x.lin,&nbsp;np.array([3.0,&nbsp;0.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose_y&nbsp;=&nbsp;Pose2.moveY(4.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose_y.lin,&nbsp;np.array([0.0,&nbsp;4.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose_right&nbsp;=&nbsp;Pose2.right(2.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose_right.lin,&nbsp;np.array([2.0,&nbsp;0.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose_forward&nbsp;=&nbsp;Pose2.forward(5.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_array_equal(pose_forward.lin,&nbsp;np.array([0.0,&nbsp;5.0]))<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;'__main__':<br>
&nbsp;&nbsp;&nbsp;&nbsp;unittest.main()<br>
<!-- END SCAT CODE -->
</body>
</html>
