<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>utest/project_test.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;termin.geomalgo.project&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;project_point_on_aabb,<br>
&nbsp;&nbsp;&nbsp;&nbsp;project_segment_on_aabb,<br>
&nbsp;&nbsp;&nbsp;&nbsp;project_point_on_plane,<br>
&nbsp;&nbsp;&nbsp;&nbsp;project_point_on_line<br>
)<br>
import&nbsp;unittest<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;AABB<br>
from&nbsp;termin.geomalgo.project&nbsp;import&nbsp;closest_of_aabb_and_capsule<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
import&nbsp;numpy<br>
<br>
<br>
class&nbsp;TestProjectPointOnAABB(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;функции&nbsp;project_point_on_aabb&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_inside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;внутри&nbsp;AABB&nbsp;должна&nbsp;проецироваться&nbsp;в&nbsp;саму&nbsp;себя&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[0.5,&nbsp;0.5,&nbsp;0.5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_aabb(point,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_outside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;вне&nbsp;AABB&nbsp;должна&nbsp;проецироваться&nbsp;на&nbsp;угол&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[3,&nbsp;3,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_aabb(point,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;[2,&nbsp;2,&nbsp;2])<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_on_aabb_boundary(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;на&nbsp;границе&nbsp;AABB&nbsp;должна&nbsp;остаться&nbsp;на&nbsp;месте&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[2,&nbsp;1,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_aabb(point,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_outside_one_dimension(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;вне&nbsp;только&nbsp;по&nbsp;одной&nbsp;координате&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[1,&nbsp;1,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_aabb(point,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;[1,&nbsp;1,&nbsp;2])<br>
<br>
<br>
class&nbsp;TestProjectSegmentOnAABB(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;функции&nbsp;project_segment_on_aabb&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_completely_inside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;полностью&nbsp;внутри&nbsp;AABB&nbsp;-&nbsp;расстояние&nbsp;должно&nbsp;быть&nbsp;0&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[0.5,&nbsp;0.5,&nbsp;0.5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[1.5,&nbsp;1.5,&nbsp;1.5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;0.0,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Точки&nbsp;должны&nbsp;совпадать<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result[0],&nbsp;result[1])<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_completely_outside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;полностью&nbsp;вне&nbsp;AABB&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[3,&nbsp;3,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[4,&nbsp;4,&nbsp;4]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_distance&nbsp;=&nbsp;np.sqrt(3)&nbsp;&nbsp;#&nbsp;От&nbsp;[3,3,3]&nbsp;до&nbsp;[2,2,2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;expected_distance,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_intersects_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;пересекает&nbsp;AABB&nbsp;-&nbsp;расстояние&nbsp;должно&nbsp;быть&nbsp;0&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[-1,&nbsp;1,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[3,&nbsp;1,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;0.0,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_degenerate_point_inside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Вырожденный&nbsp;случай:&nbsp;точка&nbsp;(отрезок&nbsp;нулевой&nbsp;длины)&nbsp;внутри&nbsp;AABB&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[0.5,&nbsp;0.5,&nbsp;0.5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[0.5,&nbsp;0.5,&nbsp;0.5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;0.0,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result[0],&nbsp;seg_start)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result[1],&nbsp;seg_start)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_degenerate_point_outside_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Вырожденный&nbsp;случай:&nbsp;точка&nbsp;вне&nbsp;AABB&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[3,&nbsp;3,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[3,&nbsp;3,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_distance&nbsp;=&nbsp;np.sqrt(3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;expected_distance,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_parallel_to_face_outside(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;параллелен&nbsp;грани&nbsp;AABB&nbsp;(снаружи)&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[3,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[3,&nbsp;2,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;1.0,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_touches_corner(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;касается&nbsp;угла&nbsp;AABB&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;-1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;0.0,&nbsp;places=6)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_segment_diagonal_through_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Отрезок&nbsp;проходит&nbsp;по&nbsp;диагонали&nbsp;через&nbsp;весь&nbsp;AABB&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_start&nbsp;=&nbsp;[-1,&nbsp;-1,&nbsp;-1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_end&nbsp;=&nbsp;[3,&nbsp;3,&nbsp;3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_min&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb_max&nbsp;=&nbsp;[2,&nbsp;2,&nbsp;2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_segment_on_aabb(seg_start,&nbsp;seg_end,&nbsp;aabb_min,&nbsp;aabb_max)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(result[2],&nbsp;0.0,&nbsp;places=6)<br>
<br>
<br>
class&nbsp;TestProjectPointOnPlane(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;функции&nbsp;project_point_on_plane&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_on_plane(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;на&nbsp;плоскости&nbsp;должна&nbsp;остаться&nbsp;на&nbsp;месте&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[1,&nbsp;1,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_normal&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_plane(point,&nbsp;plane_point,&nbsp;plane_normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_above_plane(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;над&nbsp;плоскостью&nbsp;должна&nbsp;проецироваться&nbsp;вниз&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[1,&nbsp;1,&nbsp;5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_normal&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_plane(point,&nbsp;plane_point,&nbsp;plane_normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;[1,&nbsp;1,&nbsp;0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_below_plane(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;под&nbsp;плоскостью&nbsp;должна&nbsp;проецироваться&nbsp;вверх&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[1,&nbsp;1,&nbsp;-3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plane_normal&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_plane(point,&nbsp;plane_point,&nbsp;plane_normal)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;[1,&nbsp;1,&nbsp;0])<br>
<br>
<br>
class&nbsp;TestProjectPointOnLine(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;функции&nbsp;project_point_on_line&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_on_line(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;на&nbsp;линии&nbsp;должна&nbsp;остаться&nbsp;на&nbsp;месте&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[2,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_direction&nbsp;=&nbsp;[1,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_line(point,&nbsp;line_point,&nbsp;line_direction)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_perpendicular_to_line(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;перпендикулярно&nbsp;линии&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[1,&nbsp;5,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_direction&nbsp;=&nbsp;[1,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_line(point,&nbsp;line_point,&nbsp;line_direction)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;[1,&nbsp;0,&nbsp;0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_point_arbitrary_position(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Точка&nbsp;в&nbsp;произвольной&nbsp;позиции&nbsp;относительно&nbsp;линии&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;[3,&nbsp;4,&nbsp;5]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_point&nbsp;=&nbsp;[0,&nbsp;0,&nbsp;0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;line_direction&nbsp;=&nbsp;[1,&nbsp;1,&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;=&nbsp;project_point_on_line(point,&nbsp;line_point,&nbsp;line_direction)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проекция&nbsp;точки&nbsp;[3,4,5]&nbsp;на&nbsp;линию&nbsp;через&nbsp;начало&nbsp;координат&nbsp;в&nbsp;направлении&nbsp;[1,1,1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;должна&nbsp;дать&nbsp;точку&nbsp;[4,4,4]&nbsp;(т.к.&nbsp;dot([3,4,5],&nbsp;[1,1,1])/|[1,1,1]|^2&nbsp;=&nbsp;12/3&nbsp;=&nbsp;4)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected&nbsp;=&nbsp;[4,&nbsp;4,&nbsp;4]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.testing.assert_allclose(result,&nbsp;expected)<br>
<br>
<br>
class&nbsp;TestClosestOfAABBAndCapsule(unittest.TestCase):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Тесты&nbsp;для&nbsp;функции&nbsp;closest_of_aabb_and_capsule&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_closest_of_aabb_and_capsule(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb&nbsp;=&nbsp;AABB(numpy.array([0.0,&nbsp;0.0,&nbsp;0.0]),&nbsp;numpy.array([1.0,&nbsp;1.0,&nbsp;1.0]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule_start&nbsp;=&nbsp;numpy.array([2.0,&nbsp;0.5,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule_end&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.5,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;capsule_radius&nbsp;=&nbsp;0.2<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;closest_aabb_point,&nbsp;closest_capsule_point,&nbsp;distance&nbsp;=&nbsp;closest_of_aabb_and_capsule(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb.min_point,&nbsp;aabb.max_point,&nbsp;capsule_start,&nbsp;capsule_end,&nbsp;capsule_radius<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_closest_aabb_point&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.5,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_closest_capsule_point&nbsp;=&nbsp;numpy.array([1.8,&nbsp;0.5,&nbsp;0.5])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_distance&nbsp;=&nbsp;0.8<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(closest_aabb_point,&nbsp;expected_closest_aabb_point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(closest_capsule_point,&nbsp;expected_closest_capsule_point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.assertAlmostEqual(distance,&nbsp;expected_distance)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;test_project_point_on_aabb(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;aabb&nbsp;=&nbsp;AABB(numpy.array([-1.0,&nbsp;-0.5,&nbsp;-0.25]),&nbsp;numpy.array([1.0,&nbsp;0.5,&nbsp;0.25]))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;point&nbsp;=&nbsp;numpy.array([3.0,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;projected_point&nbsp;=&nbsp;project_point_on_aabb(point,&nbsp;aabb.min_point,&nbsp;aabb.max_point)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expected_point&nbsp;=&nbsp;numpy.array([1.0,&nbsp;0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;numpy.testing.assert_array_almost_equal(projected_point,&nbsp;expected_point)<br>
<!-- END SCAT CODE -->
</body>
</html>
