<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/assets/animation_clip_asset.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;AnimationClipAsset&nbsp;-&nbsp;Asset&nbsp;for&nbsp;animation&nbsp;clip&nbsp;data.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;pathlib&nbsp;import&nbsp;Path<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING<br>
<br>
from&nbsp;termin.assets.data_asset&nbsp;import&nbsp;DataAsset<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.animation.clip&nbsp;import&nbsp;TcAnimationClip<br>
<br>
<br>
class&nbsp;AnimationClipAsset(DataAsset[&quot;TcAnimationClip&quot;]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Asset&nbsp;for&nbsp;animation&nbsp;clip&nbsp;data.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;IMPORTANT:&nbsp;Create&nbsp;through&nbsp;ResourceManager.get_or_create_animation_clip_asset(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;not&nbsp;directly.&nbsp;This&nbsp;ensures&nbsp;proper&nbsp;registration&nbsp;and&nbsp;avoids&nbsp;duplicates.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Stores&nbsp;TcAnimationClip&nbsp;(channels,&nbsp;duration,&nbsp;etc).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Can&nbsp;be&nbsp;loaded&nbsp;from:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Standalone&nbsp;.anim&nbsp;files<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;GLB&nbsp;files&nbsp;(embedded,&nbsp;via&nbsp;parent&nbsp;asset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_uses_binary&nbsp;=&nbsp;False&nbsp;&nbsp;#&nbsp;.anim&nbsp;files&nbsp;are&nbsp;text/JSON<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;clip:&nbsp;&quot;TcAnimationClip&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;=&nbsp;&quot;animation&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(data=clip,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Convenience&nbsp;property&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clip(self)&nbsp;-&gt;&nbsp;&quot;TcAnimationClip&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;TcAnimationClip&nbsp;data&nbsp;(lazy-loaded&nbsp;via&nbsp;parent's&nbsp;data&nbsp;property).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.data<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@clip.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clip(self,&nbsp;value:&nbsp;&quot;TcAnimationClip&nbsp;|&nbsp;None&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;clip&nbsp;and&nbsp;bump&nbsp;version.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.data&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;duration(self)&nbsp;-&gt;&nbsp;float:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Animation&nbsp;duration&nbsp;in&nbsp;seconds.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data&nbsp;=&nbsp;self.data<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;data.duration&nbsp;if&nbsp;data&nbsp;else&nbsp;0.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Content&nbsp;parsing&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_parse_content(self,&nbsp;content:&nbsp;str)&nbsp;-&gt;&nbsp;&quot;TcAnimationClip&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Parse&nbsp;animation&nbsp;content&nbsp;from&nbsp;file.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.animation.clip_io&nbsp;import&nbsp;parse_animation_content<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;parse_animation_content(content)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Factory&nbsp;methods&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_clip(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;clip:&nbsp;&quot;TcAnimationClip&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;AnimationClipAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Create&nbsp;AnimationClipAsset&nbsp;from&nbsp;existing&nbsp;TcAnimationClip.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_name&nbsp;=&nbsp;name&nbsp;or&nbsp;clip.name&nbsp;or&nbsp;&quot;animation&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cls(clip=clip,&nbsp;name=asset_name,&nbsp;source_path=source_path)<br>
<!-- END SCAT CODE -->
</body>
</html>
