<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/assets/asset_registry.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
AssetRegistry&nbsp;—&nbsp;generic&nbsp;registry&nbsp;for&nbsp;assets.<br>
<br>
Eliminates&nbsp;code&nbsp;duplication&nbsp;for&nbsp;asset&nbsp;management&nbsp;across&nbsp;different&nbsp;resource&nbsp;types.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Callable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Dict,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Generic,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Optional,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TypeVar,<br>
)<br>
<br>
from&nbsp;termin.assets.asset&nbsp;import&nbsp;Asset<br>
<br>
AssetT&nbsp;=&nbsp;TypeVar(&quot;AssetT&quot;,&nbsp;bound=Asset)&nbsp;&nbsp;#&nbsp;Asset&nbsp;type&nbsp;(MeshAsset,&nbsp;TextureAsset,&nbsp;etc.)<br>
DataT&nbsp;=&nbsp;TypeVar(&quot;DataT&quot;)&nbsp;&nbsp;#&nbsp;Data/Handle&nbsp;type&nbsp;(TcMesh,&nbsp;Material,&nbsp;VoxelGrid,&nbsp;etc.)<br>
<br>
<br>
class&nbsp;AssetRegistry(Generic[AssetT,&nbsp;DataT]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Generic&nbsp;registry&nbsp;for&nbsp;assets.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Handles&nbsp;common&nbsp;operations:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;get_asset(name)&nbsp;-&gt;&nbsp;AssetT<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;register(name,&nbsp;asset,&nbsp;...)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;get(name)&nbsp;-&gt;&nbsp;DataT&nbsp;(via&nbsp;data_from_asset&nbsp;callback)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;list_names()<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;find_name(data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;find_uuid(data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;get_by_uuid(uuid)&nbsp;-&gt;&nbsp;DataT<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;get_asset_by_uuid(uuid)&nbsp;-&gt;&nbsp;AssetT<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;unregister(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Type&nbsp;parameters:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AssetT:&nbsp;Asset&nbsp;class&nbsp;(e.g.,&nbsp;MeshAsset,&nbsp;TextureAsset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DataT:&nbsp;Data/Handle&nbsp;class&nbsp;returned&nbsp;by&nbsp;get()&nbsp;(e.g.,&nbsp;TcMesh,&nbsp;Material)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_class:&nbsp;type[AssetT]&nbsp;|&nbsp;Callable[[],&nbsp;type[AssetT]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid_registry:&nbsp;Dict[str,&nbsp;Asset],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data_from_asset:&nbsp;Callable[[AssetT],&nbsp;DataT&nbsp;|&nbsp;None],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data_to_asset:&nbsp;Callable[[DataT],&nbsp;AssetT&nbsp;|&nbsp;None]&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Initialize&nbsp;registry.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_class:&nbsp;Asset&nbsp;class&nbsp;for&nbsp;isinstance&nbsp;checks,&nbsp;or&nbsp;a&nbsp;callable&nbsp;that&nbsp;returns&nbsp;it&nbsp;(for&nbsp;lazy&nbsp;loading)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid_registry:&nbsp;Shared&nbsp;dict&nbsp;for&nbsp;UUID&nbsp;lookups&nbsp;(ResourceManager._assets_by_uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data_from_asset:&nbsp;Callback&nbsp;to&nbsp;extract&nbsp;Data/Handle&nbsp;from&nbsp;Asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;data_to_asset:&nbsp;Optional&nbsp;callback&nbsp;to&nbsp;find&nbsp;Asset&nbsp;from&nbsp;Data&nbsp;(for&nbsp;find_name/find_uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets:&nbsp;Dict[str,&nbsp;AssetT]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._asset_class_or_factory&nbsp;=&nbsp;asset_class<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._asset_class_cached:&nbsp;type[AssetT]&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._uuid_registry&nbsp;=&nbsp;uuid_registry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._data_from_asset&nbsp;=&nbsp;data_from_asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._data_to_asset&nbsp;=&nbsp;data_to_asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_asset_class(self)&nbsp;-&gt;&nbsp;type[AssetT]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;asset&nbsp;class,&nbsp;resolving&nbsp;lazy&nbsp;factory&nbsp;if&nbsp;needed.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._asset_class_cached&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callable(self._asset_class_or_factory)&nbsp;and&nbsp;not&nbsp;isinstance(self._asset_class_or_factory,&nbsp;type):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._asset_class_cached&nbsp;=&nbsp;self._asset_class_or_factory()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._asset_class_cached&nbsp;=&nbsp;self._asset_class_or_factory<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._asset_class_cached<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;assets(self)&nbsp;-&gt;&nbsp;Dict[str,&nbsp;AssetT]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Direct&nbsp;access&nbsp;to&nbsp;assets&nbsp;dict.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._assets<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_asset(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;AssetT&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;asset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._assets.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_or_create_asset(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;&quot;Asset&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_key:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;AssetT:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get&nbsp;asset&nbsp;by&nbsp;UUID&nbsp;(if&nbsp;provided),&nbsp;or&nbsp;create&nbsp;a&nbsp;new&nbsp;one.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UUID&nbsp;is&nbsp;the&nbsp;primary&nbsp;key&nbsp;for&nbsp;assets.&nbsp;Name&nbsp;is&nbsp;used&nbsp;for&nbsp;display<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;for&nbsp;assets&nbsp;without&nbsp;UUID&nbsp;(like&nbsp;GLSL&nbsp;includes).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;Resource&nbsp;name&nbsp;(for&nbsp;display&nbsp;and&nbsp;name-based&nbsp;lookup)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Source&nbsp;file&nbsp;path&nbsp;(for&nbsp;new&nbsp;assets)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;UUID&nbsp;(primary&nbsp;key&nbsp;for&nbsp;lookup)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent:&nbsp;Parent&nbsp;asset&nbsp;(for&nbsp;embedded&nbsp;assets&nbsp;like&nbsp;mesh&nbsp;from&nbsp;GLB)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_key:&nbsp;Key&nbsp;within&nbsp;parent&nbsp;(e.g.,&nbsp;mesh&nbsp;name&nbsp;in&nbsp;GLB)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;UUID&nbsp;is&nbsp;the&nbsp;primary&nbsp;key&nbsp;-&nbsp;check&nbsp;it&nbsp;first<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;uuid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._uuid_registry.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;isinstance(asset,&nbsp;self._asset_class):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;For&nbsp;assets&nbsp;without&nbsp;UUID,&nbsp;check&nbsp;by&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;uuid&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;new&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._asset_class(name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Set&nbsp;parent&nbsp;for&nbsp;embedded&nbsp;assets<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;parent&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;parent_key&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.data_asset&nbsp;import&nbsp;DataAsset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(asset,&nbsp;DataAsset):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset.set_parent(parent,&nbsp;parent_key)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Register&nbsp;by&nbsp;both&nbsp;UUID&nbsp;and&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets[name]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._uuid_registry[asset.uuid]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset:&nbsp;AssetT,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Register&nbsp;asset.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;Resource&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset:&nbsp;Asset&nbsp;instance<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Optional&nbsp;source&nbsp;file&nbsp;path<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;Optional&nbsp;fixed&nbsp;UUID&nbsp;(for&nbsp;builtins)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset._name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;source_path:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset._source_path&nbsp;=&nbsp;source_path<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;uuid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset._uuid&nbsp;=&nbsp;uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset._runtime_id&nbsp;=&nbsp;hash(uuid)&nbsp;&amp;&nbsp;0xFFFFFFFFFFFFFFFF<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets[name]&nbsp;=&nbsp;asset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._uuid_registry[asset.uuid]&nbsp;=&nbsp;asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;DataT&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;data/handle&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._data_from_asset(asset)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;List&nbsp;all&nbsp;registered&nbsp;names.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(self._assets.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_name(self,&nbsp;data:&nbsp;DataT)&nbsp;-&gt;&nbsp;str&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;name&nbsp;by&nbsp;data/handle.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._data_to_asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._data_to_asset(data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;a&nbsp;in&nbsp;self._assets.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;a&nbsp;is&nbsp;asset:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_uuid(self,&nbsp;data:&nbsp;DataT)&nbsp;-&gt;&nbsp;str&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Find&nbsp;UUID&nbsp;by&nbsp;data/handle.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._data_to_asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._data_to_asset(data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset.uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;DataT&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;data/handle&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._uuid_registry.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;isinstance(asset,&nbsp;self._asset_class):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._data_from_asset(asset)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_asset_by_uuid(self,&nbsp;uuid:&nbsp;str)&nbsp;-&gt;&nbsp;AssetT&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;asset&nbsp;by&nbsp;UUID.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._uuid_registry.get(uuid)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;isinstance(asset,&nbsp;self._asset_class):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;asset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;unregister(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Remove&nbsp;asset&nbsp;by&nbsp;name.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;self._assets.get(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.uuid&nbsp;in&nbsp;self._uuid_registry:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self._uuid_registry[asset.uuid]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self._assets[name]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clear(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Remove&nbsp;all&nbsp;assets.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;asset&nbsp;in&nbsp;list(self._assets.values()):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset.uuid&nbsp;in&nbsp;self._uuid_registry:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self._uuid_registry[asset.uuid]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._assets.clear()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__contains__(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Check&nbsp;if&nbsp;name&nbsp;is&nbsp;registered.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;name&nbsp;in&nbsp;self._assets<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__len__(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Number&nbsp;of&nbsp;registered&nbsp;assets.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;len(self._assets)<br>
<!-- END SCAT CODE -->
</body>
</html>
