<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/assets/ui_asset.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;UIAsset&nbsp;-&nbsp;Asset&nbsp;for&nbsp;widget-based&nbsp;UI&nbsp;layouts&nbsp;(.ui.yaml&nbsp;files).&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;pathlib&nbsp;import&nbsp;Path<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING<br>
<br>
from&nbsp;termin.assets.data_asset&nbsp;import&nbsp;DataAsset<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.ui.widgets.widget&nbsp;import&nbsp;Widget<br>
<br>
<br>
class&nbsp;UIAsset(DataAsset[&quot;Widget&quot;]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Asset&nbsp;for&nbsp;widget-based&nbsp;UI&nbsp;layouts.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;IMPORTANT:&nbsp;Create&nbsp;through&nbsp;ResourceManager,&nbsp;not&nbsp;directly.<br>
&nbsp;&nbsp;&nbsp;&nbsp;This&nbsp;ensures&nbsp;proper&nbsp;registration&nbsp;and&nbsp;avoids&nbsp;duplicates.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Stores&nbsp;Widget&nbsp;tree&nbsp;loaded&nbsp;from&nbsp;YAML&nbsp;files.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_uses_binary&nbsp;=&nbsp;False&nbsp;&nbsp;#&nbsp;YAML&nbsp;text&nbsp;format<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;widget:&nbsp;&quot;Widget&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;=&nbsp;&quot;ui&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(data=widget,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Convenience&nbsp;property&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;widget(self)&nbsp;-&gt;&nbsp;&quot;Widget&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Root&nbsp;widget&nbsp;(lazy-loaded).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.data<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@widget.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;widget(self,&nbsp;value:&nbsp;&quot;Widget&nbsp;|&nbsp;None&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;widget&nbsp;and&nbsp;bump&nbsp;version.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.data&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;root(self)&nbsp;-&gt;&nbsp;&quot;Widget&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Alias&nbsp;for&nbsp;widget.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.data<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Content&nbsp;parsing&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_parse_content(self,&nbsp;content:&nbsp;str)&nbsp;-&gt;&nbsp;&quot;Widget&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Parse&nbsp;YAML&nbsp;content&nbsp;into&nbsp;Widget&nbsp;tree.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.ui.widgets.loader&nbsp;import&nbsp;UILoader<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loader&nbsp;=&nbsp;UILoader()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;loader.load_string(content)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Factory&nbsp;methods&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_widget(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;widget:&nbsp;&quot;Widget&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;UIAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Create&nbsp;UIAsset&nbsp;from&nbsp;existing&nbsp;Widget.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_name&nbsp;=&nbsp;name&nbsp;or&nbsp;widget.name&nbsp;or&nbsp;&quot;ui&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cls(widget=widget,&nbsp;name=asset_name,&nbsp;source_path=source_path)<br>
<!-- END SCAT CODE -->
</body>
</html>
