<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/assets/voxel_grid_asset.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;VoxelGridAsset&nbsp;-&nbsp;Asset&nbsp;for&nbsp;voxel&nbsp;grid&nbsp;data.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;pathlib&nbsp;import&nbsp;Path<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING<br>
<br>
from&nbsp;termin.assets.data_asset&nbsp;import&nbsp;DataAsset<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.voxels.grid&nbsp;import&nbsp;VoxelGrid<br>
<br>
<br>
class&nbsp;VoxelGridAsset(DataAsset[&quot;VoxelGrid&quot;]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Asset&nbsp;for&nbsp;voxel&nbsp;grid&nbsp;data.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;IMPORTANT:&nbsp;Create&nbsp;through&nbsp;ResourceManager,&nbsp;not&nbsp;directly.<br>
&nbsp;&nbsp;&nbsp;&nbsp;This&nbsp;ensures&nbsp;proper&nbsp;registration&nbsp;and&nbsp;avoids&nbsp;duplicates.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Stores&nbsp;VoxelGrid&nbsp;(sparse&nbsp;voxel&nbsp;structure).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_uses_binary&nbsp;=&nbsp;False&nbsp;&nbsp;#&nbsp;JSON&nbsp;text&nbsp;format<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid:&nbsp;&quot;VoxelGrid&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;=&nbsp;&quot;voxel_grid&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(data=grid,&nbsp;name=name,&nbsp;source_path=source_path,&nbsp;uuid=uuid)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Convenience&nbsp;property&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;grid(self)&nbsp;-&gt;&nbsp;&quot;VoxelGrid&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;VoxelGrid&nbsp;data&nbsp;(lazy-loaded).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.data<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@grid.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;grid(self,&nbsp;value:&nbsp;&quot;VoxelGrid&nbsp;|&nbsp;None&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;grid&nbsp;and&nbsp;bump&nbsp;version.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.data&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Content&nbsp;parsing&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_parse_content(self,&nbsp;content:&nbsp;str)&nbsp;-&gt;&nbsp;&quot;VoxelGrid&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Parse&nbsp;JSON&nbsp;content&nbsp;into&nbsp;VoxelGrid.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.voxels.persistence&nbsp;import&nbsp;VoxelPersistence<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid&nbsp;=&nbsp;VoxelPersistence.load_from_content(content)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;grid&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid.name&nbsp;=&nbsp;self._name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;grid<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Factory&nbsp;methods&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_grid(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;grid:&nbsp;&quot;VoxelGrid&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path:&nbsp;Path&nbsp;|&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;&quot;VoxelGridAsset&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Create&nbsp;VoxelGridAsset&nbsp;from&nbsp;existing&nbsp;VoxelGrid.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset_name&nbsp;=&nbsp;name&nbsp;or&nbsp;grid.name&nbsp;or&nbsp;&quot;voxel_grid&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cls(grid=grid,&nbsp;name=asset_name,&nbsp;source_path=source_path)<br>
<!-- END SCAT CODE -->
</body>
</html>
