<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/core/plugin_loader.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Plugin&nbsp;loader&nbsp;for&nbsp;dynamic&nbsp;loading&nbsp;of&nbsp;Components&nbsp;and&nbsp;FramePasses.<br>
<br>
Scans&nbsp;directories,&nbsp;modules,&nbsp;and&nbsp;files&nbsp;for&nbsp;plugin&nbsp;classes.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;importlib<br>
import&nbsp;importlib.util<br>
import&nbsp;os<br>
import&nbsp;pkgutil<br>
import&nbsp;sys<br>
from&nbsp;typing&nbsp;import&nbsp;Callable,&nbsp;Set<br>
<br>
<br>
def&nbsp;scan_paths(<br>
&nbsp;&nbsp;&nbsp;&nbsp;paths:&nbsp;list[str],<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str&nbsp;=&nbsp;&quot;_dynamic_&quot;,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scan&nbsp;paths&nbsp;and&nbsp;load&nbsp;classes&nbsp;into&nbsp;registry.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Classes&nbsp;are&nbsp;auto-registered&nbsp;via&nbsp;__init_subclass__&nbsp;when&nbsp;modules&nbsp;are&nbsp;imported.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;paths:&nbsp;List&nbsp;of&nbsp;paths&nbsp;(files,&nbsp;directories,&nbsp;or&nbsp;module&nbsp;names)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;Dict&nbsp;to&nbsp;track&nbsp;registered&nbsp;classes&nbsp;(before/after&nbsp;comparison)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;Prefix&nbsp;for&nbsp;dynamically&nbsp;loaded&nbsp;modules<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List&nbsp;of&nbsp;newly&nbsp;registered&nbsp;class&nbsp;names<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;loaded&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;path&nbsp;in&nbsp;paths:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;os.path.isfile(path)&nbsp;and&nbsp;path.endswith(&quot;.py&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_file(path,&nbsp;registry,&nbsp;module_prefix))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;os.path.isdir(path):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_directory(path,&nbsp;registry,&nbsp;module_prefix))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_module(path,&nbsp;registry))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;loaded<br>
<br>
<br>
def&nbsp;_scan_file(<br>
&nbsp;&nbsp;&nbsp;&nbsp;filepath:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;classes&nbsp;from&nbsp;a&nbsp;single&nbsp;.py&nbsp;file.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;before&nbsp;=&nbsp;set(registry.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;filename&nbsp;=&nbsp;os.path.basename(filepath)<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_name&nbsp;=&nbsp;f&quot;{module_prefix}.{os.path.splitext(filename)[0]}_{id(filepath)}&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec&nbsp;=&nbsp;importlib.util.spec_from_file_location(module_name,&nbsp;filepath)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;spec&nbsp;is&nbsp;None&nbsp;or&nbsp;spec.loader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;importlib.util.module_from_spec(spec)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sys.modules[module_name]&nbsp;=&nbsp;module<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec.loader.exec_module(module)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;load&nbsp;{filepath}:&nbsp;{e}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;after&nbsp;=&nbsp;set(registry.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(after&nbsp;-&nbsp;before)<br>
<br>
<br>
def&nbsp;_scan_module(<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;module&nbsp;and&nbsp;all&nbsp;its&nbsp;submodules.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;before&nbsp;=&nbsp;set(registry.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;importlib.import_module(module_name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;If&nbsp;it's&nbsp;a&nbsp;package,&nbsp;scan&nbsp;submodules<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(module,&nbsp;&quot;__path__&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;importer,&nbsp;name,&nbsp;is_pkg&nbsp;in&nbsp;pkgutil.walk_packages(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module.__path__,&nbsp;prefix=module_name&nbsp;+&nbsp;&quot;.&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;importlib.import_module(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;import&nbsp;{name}:&nbsp;{e}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;import&nbsp;module&nbsp;{module_name}:&nbsp;{e}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;after&nbsp;=&nbsp;set(registry.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(after&nbsp;-&nbsp;before)<br>
<br>
<br>
def&nbsp;_scan_directory(<br>
&nbsp;&nbsp;&nbsp;&nbsp;directory:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Scan&nbsp;directory&nbsp;and&nbsp;load&nbsp;all&nbsp;.py&nbsp;files&nbsp;as&nbsp;modules.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;before&nbsp;=&nbsp;set(registry.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;root,&nbsp;dirs,&nbsp;files&nbsp;in&nbsp;os.walk(directory):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Skip&nbsp;__pycache__&nbsp;and&nbsp;hidden&nbsp;directories<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dirs[:]&nbsp;=&nbsp;[d&nbsp;for&nbsp;d&nbsp;in&nbsp;dirs&nbsp;if&nbsp;not&nbsp;d.startswith((&quot;.&quot;,&nbsp;&quot;__&quot;))]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;filename&nbsp;in&nbsp;files:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;filename.endswith(&quot;.py&quot;)&nbsp;or&nbsp;filename.startswith(&quot;_&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filepath&nbsp;=&nbsp;os.path.join(root,&nbsp;filename)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;unique&nbsp;module&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rel_path&nbsp;=&nbsp;os.path.relpath(filepath,&nbsp;directory)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;unique_name&nbsp;=&nbsp;f&quot;{module_prefix}.{rel_path.replace(os.sep,&nbsp;'.')[:-3]}&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec&nbsp;=&nbsp;importlib.util.spec_from_file_location(unique_name,&nbsp;filepath)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;spec&nbsp;is&nbsp;None&nbsp;or&nbsp;spec.loader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;importlib.util.module_from_spec(spec)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sys.modules[unique_name]&nbsp;=&nbsp;module<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec.loader.exec_module(module)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;load&nbsp;{filepath}:&nbsp;{e}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;after&nbsp;=&nbsp;set(registry.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(after&nbsp;-&nbsp;before)<br>
<br>
<br>
def&nbsp;scan_for_subclasses(<br>
&nbsp;&nbsp;&nbsp;&nbsp;paths:&nbsp;list[str],<br>
&nbsp;&nbsp;&nbsp;&nbsp;base_class:&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str&nbsp;=&nbsp;&quot;_dynamic_&quot;,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scan&nbsp;paths&nbsp;and&nbsp;find&nbsp;all&nbsp;subclasses&nbsp;of&nbsp;base_class.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Unlike&nbsp;scan_paths(),&nbsp;this&nbsp;explicitly&nbsp;searches&nbsp;for&nbsp;subclasses<br>
&nbsp;&nbsp;&nbsp;&nbsp;(useful&nbsp;when&nbsp;classes&nbsp;don't&nbsp;auto-register&nbsp;via&nbsp;__init_subclass__).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;paths:&nbsp;List&nbsp;of&nbsp;paths&nbsp;to&nbsp;scan<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;base_class:&nbsp;Base&nbsp;class&nbsp;to&nbsp;find&nbsp;subclasses&nbsp;of<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;Dict&nbsp;to&nbsp;store&nbsp;found&nbsp;classes<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;Prefix&nbsp;for&nbsp;dynamically&nbsp;loaded&nbsp;modules<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List&nbsp;of&nbsp;newly&nbsp;registered&nbsp;class&nbsp;names<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;loaded&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;path&nbsp;in&nbsp;paths:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;os.path.isfile(path)&nbsp;and&nbsp;path.endswith(&quot;.py&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_file_for_subclasses(path,&nbsp;base_class,&nbsp;registry,&nbsp;module_prefix))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;os.path.isdir(path):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_directory_for_subclasses(path,&nbsp;base_class,&nbsp;registry,&nbsp;module_prefix))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_module_for_subclasses(path,&nbsp;base_class,&nbsp;registry))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;loaded<br>
<br>
<br>
def&nbsp;_scan_file_for_subclasses(<br>
&nbsp;&nbsp;&nbsp;&nbsp;filepath:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;base_class:&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;subclasses&nbsp;from&nbsp;a&nbsp;single&nbsp;.py&nbsp;file.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;before&nbsp;=&nbsp;set(registry.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;filename&nbsp;=&nbsp;os.path.basename(filepath)<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_name&nbsp;=&nbsp;f&quot;{module_prefix}.{os.path.splitext(filename)[0]}_{id(filepath)}&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec&nbsp;=&nbsp;importlib.util.spec_from_file_location(module_name,&nbsp;filepath)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;spec&nbsp;is&nbsp;None&nbsp;or&nbsp;spec.loader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;importlib.util.module_from_spec(spec)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sys.modules[module_name]&nbsp;=&nbsp;module<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec.loader.exec_module(module)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Find&nbsp;subclasses&nbsp;in&nbsp;the&nbsp;module<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;attr_name&nbsp;in&nbsp;dir(module):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attr&nbsp;=&nbsp;getattr(module,&nbsp;attr_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isinstance(attr,&nbsp;type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;issubclass(attr,&nbsp;base_class)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr&nbsp;is&nbsp;not&nbsp;base_class<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr_name&nbsp;not&nbsp;in&nbsp;registry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry[attr_name]&nbsp;=&nbsp;attr<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;load&nbsp;{filepath}:&nbsp;{e}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;after&nbsp;=&nbsp;set(registry.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(after&nbsp;-&nbsp;before)<br>
<br>
<br>
def&nbsp;_scan_directory_for_subclasses(<br>
&nbsp;&nbsp;&nbsp;&nbsp;directory:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;base_class:&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_prefix:&nbsp;str,<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Scan&nbsp;directory&nbsp;for&nbsp;subclasses.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;loaded&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;root,&nbsp;dirs,&nbsp;files&nbsp;in&nbsp;os.walk(directory):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dirs[:]&nbsp;=&nbsp;[d&nbsp;for&nbsp;d&nbsp;in&nbsp;dirs&nbsp;if&nbsp;not&nbsp;d.startswith((&quot;.&quot;,&nbsp;&quot;__&quot;))]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;filename&nbsp;in&nbsp;files:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;filename.endswith(&quot;.py&quot;)&nbsp;or&nbsp;filename.startswith(&quot;_&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filepath&nbsp;=&nbsp;os.path.join(root,&nbsp;filename)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;loaded.extend(_scan_file_for_subclasses(filepath,&nbsp;base_class,&nbsp;registry,&nbsp;module_prefix))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;loaded<br>
<br>
<br>
def&nbsp;_scan_module_for_subclasses(<br>
&nbsp;&nbsp;&nbsp;&nbsp;module_name:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;base_class:&nbsp;type,<br>
&nbsp;&nbsp;&nbsp;&nbsp;registry:&nbsp;dict[str,&nbsp;type],<br>
)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;subclasses&nbsp;from&nbsp;module.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;before&nbsp;=&nbsp;set(registry.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module&nbsp;=&nbsp;importlib.import_module(module_name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Find&nbsp;subclasses&nbsp;in&nbsp;the&nbsp;module&nbsp;itself<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;attr_name&nbsp;in&nbsp;dir(module):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attr&nbsp;=&nbsp;getattr(module,&nbsp;attr_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isinstance(attr,&nbsp;type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;issubclass(attr,&nbsp;base_class)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr&nbsp;is&nbsp;not&nbsp;base_class<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr_name&nbsp;not&nbsp;in&nbsp;registry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry[attr_name]&nbsp;=&nbsp;attr<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;If&nbsp;it's&nbsp;a&nbsp;package,&nbsp;scan&nbsp;submodules<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(module,&nbsp;&quot;__path__&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;importer,&nbsp;name,&nbsp;is_pkg&nbsp;in&nbsp;pkgutil.walk_packages(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;module.__path__,&nbsp;prefix=module_name&nbsp;+&nbsp;&quot;.&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;submodule&nbsp;=&nbsp;importlib.import_module(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;attr_name&nbsp;in&nbsp;dir(submodule):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;attr&nbsp;=&nbsp;getattr(submodule,&nbsp;attr_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;isinstance(attr,&nbsp;type)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;issubclass(attr,&nbsp;base_class)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr&nbsp;is&nbsp;not&nbsp;base_class<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;and&nbsp;attr_name&nbsp;not&nbsp;in&nbsp;registry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry[attr_name]&nbsp;=&nbsp;attr<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;import&nbsp;{name}:&nbsp;{e}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Warning:&nbsp;Failed&nbsp;to&nbsp;import&nbsp;module&nbsp;{module_name}:&nbsp;{e}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;after&nbsp;=&nbsp;set(registry.keys())<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;list(after&nbsp;-&nbsp;before)<br>
<!-- END SCAT CODE -->
</body>
</html>
