<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/core/python_component.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Pure&nbsp;Python&nbsp;Component&nbsp;base&nbsp;class.<br>
<br>
Uses&nbsp;tc_component&nbsp;(C&nbsp;core)&nbsp;directly&nbsp;via&nbsp;TcComponent&nbsp;wrapper,<br>
without&nbsp;inheriting&nbsp;from&nbsp;C++&nbsp;Component&nbsp;class.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING,&nbsp;Any,&nbsp;Dict,&nbsp;Optional<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.entity&nbsp;import&nbsp;Entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.scene&nbsp;import&nbsp;Scene<br>
<br>
from&nbsp;termin._native.component&nbsp;import&nbsp;TcComponent<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;InspectField<br>
<br>
<br>
class&nbsp;PythonComponent:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Base&nbsp;class&nbsp;for&nbsp;pure&nbsp;Python&nbsp;components.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Uses&nbsp;tc_component&nbsp;C&nbsp;core&nbsp;directly,&nbsp;independent&nbsp;of&nbsp;C++&nbsp;Component&nbsp;class.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Provides&nbsp;the&nbsp;same&nbsp;API&nbsp;as&nbsp;the&nbsp;C++&nbsp;Component&nbsp;for&nbsp;compatibility.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Class-level&nbsp;inspect&nbsp;fields&nbsp;-&nbsp;enabled&nbsp;is&nbsp;inherited&nbsp;by&nbsp;all&nbsp;subclasses<br>
&nbsp;&nbsp;&nbsp;&nbsp;inspect_fields:&nbsp;Dict[str,&nbsp;Any]&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;display_name&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;display_name&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Name&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;string&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;is_inspectable=False,&nbsp;&nbsp;#&nbsp;Hidden&nbsp;from&nbsp;inspector,&nbsp;renamed&nbsp;via&nbsp;context&nbsp;menu<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;enabled&quot;:&nbsp;InspectField(path=&quot;enabled&quot;,&nbsp;label=&quot;Enabled&quot;,&nbsp;kind=&quot;bool&quot;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Override&nbsp;to&nbsp;True&nbsp;in&nbsp;drawable&nbsp;subclasses&nbsp;(that&nbsp;have&nbsp;phase_marks)<br>
&nbsp;&nbsp;&nbsp;&nbsp;is_drawable:&nbsp;bool&nbsp;=&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;enabled:&nbsp;bool&nbsp;=&nbsp;True,&nbsp;display_name:&nbsp;str&nbsp;=&nbsp;&quot;&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Custom&nbsp;display&nbsp;name&nbsp;for&nbsp;this&nbsp;component&nbsp;instance<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.display_name&nbsp;=&nbsp;display_name<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;TcComponent&nbsp;wrapper<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type_name&nbsp;=&nbsp;type(self).__name__<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc&nbsp;=&nbsp;TcComponent(self,&nbsp;type_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.enabled&nbsp;=&nbsp;enabled<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Auto-detect&nbsp;if&nbsp;update/fixed_update&nbsp;are&nbsp;overridden<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls&nbsp;=&nbsp;type(self)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.has_update&nbsp;=&nbsp;cls.update&nbsp;is&nbsp;not&nbsp;PythonComponent.update<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.has_fixed_update&nbsp;=&nbsp;cls.fixed_update&nbsp;is&nbsp;not&nbsp;PythonComponent.fixed_update<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Install&nbsp;drawable&nbsp;vtable&nbsp;if&nbsp;this&nbsp;is&nbsp;a&nbsp;drawable&nbsp;component<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;cls.is_drawable:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.install_drawable_vtable()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init_subclass__(cls,&nbsp;**kwargs):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;a&nbsp;class&nbsp;inherits&nbsp;from&nbsp;PythonComponent.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init_subclass__(**kwargs)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Don't&nbsp;register&nbsp;the&nbsp;base&nbsp;class&nbsp;itself<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;cls.__name__&nbsp;==&nbsp;&quot;PythonComponent&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.inspect&nbsp;import&nbsp;InspectRegistry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry&nbsp;=&nbsp;InspectRegistry.instance()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Register&nbsp;only&nbsp;own&nbsp;fields&nbsp;(not&nbsp;inherited)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;own_fields&nbsp;=&nbsp;cls.__dict__.get('inspect_fields',&nbsp;{})<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;own_fields:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry.register_python_fields(cls.__name__,&nbsp;own_fields)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Find&nbsp;parent&nbsp;component&nbsp;type&nbsp;and&nbsp;register&nbsp;inheritance<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_name&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;klass&nbsp;in&nbsp;cls.__mro__[1:]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;klass&nbsp;is&nbsp;PythonComponent:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_name&nbsp;=&nbsp;&quot;PythonComponent&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(klass,&nbsp;'inspect_fields'):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent_name&nbsp;=&nbsp;klass.__name__<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;parent_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;registry.set_type_parent(cls.__name__,&nbsp;parent_name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Register&nbsp;in&nbsp;Python&nbsp;ResourceManager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.resources&nbsp;import&nbsp;ResourceManager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manager&nbsp;=&nbsp;ResourceManager.instance()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;manager.register_component(cls.__name__,&nbsp;cls)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;ImportError:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Register&nbsp;factory&nbsp;in&nbsp;C++&nbsp;ComponentRegistry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.entity&nbsp;import&nbsp;ComponentRegistry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ComponentRegistry.instance().register_python(cls.__name__,&nbsp;cls,&nbsp;parent_name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Mark&nbsp;as&nbsp;drawable&nbsp;if&nbsp;class&nbsp;has&nbsp;is_drawable&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;getattr(cls,&nbsp;'is_drawable',&nbsp;False):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ComponentRegistry.set_drawable(cls.__name__,&nbsp;True)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Mark&nbsp;as&nbsp;input&nbsp;handler&nbsp;if&nbsp;class&nbsp;has&nbsp;is_input_handler&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;getattr(cls,&nbsp;'is_input_handler',&nbsp;False):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ComponentRegistry.set_input_handler(cls.__name__,&nbsp;True)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Properties&nbsp;(delegate&nbsp;to&nbsp;TcComponent)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;enabled(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.enabled<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@enabled.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;enabled(self,&nbsp;value:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.enabled&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;active_in_editor(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.active_in_editor<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@active_in_editor.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;active_in_editor(self,&nbsp;value:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.active_in_editor&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;is_python_component(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;is_cxx_component(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_started(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc._started<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@_started.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_started(self,&nbsp;value:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc._started&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;has_update(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.has_update<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@has_update.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;has_update(self,&nbsp;value:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.has_update&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;has_fixed_update(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.has_fixed_update<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@has_fixed_update.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;has_fixed_update(self,&nbsp;value:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.has_fixed_update&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;is_input_handler(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Check&nbsp;if&nbsp;this&nbsp;component&nbsp;handles&nbsp;input&nbsp;events&nbsp;(has&nbsp;input_vtable&nbsp;installed).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.is_input_handler<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;entity(self)&nbsp;-&gt;&nbsp;Optional[Entity]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;owner&nbsp;entity&nbsp;from&nbsp;C-level&nbsp;tc_component.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ent&nbsp;=&nbsp;self._tc.entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;ent&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;ent.valid():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ent<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;scene(self)&nbsp;-&gt;&nbsp;Optional[Scene]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;scene&nbsp;this&nbsp;component&nbsp;belongs&nbsp;to.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ent&nbsp;=&nbsp;self.entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;ent&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ent.scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Type&nbsp;identification<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;type_name(self)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.type_name()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_type_name(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Type&nbsp;name&nbsp;is&nbsp;set&nbsp;at&nbsp;construction,&nbsp;but&nbsp;allow&nbsp;override<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;C&nbsp;component&nbsp;access<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;c_component_ptr(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Return&nbsp;tc_component*&nbsp;as&nbsp;integer&nbsp;for&nbsp;C&nbsp;interop.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._tc.c_ptr_int()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;sync_to_c(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Sync&nbsp;Python&nbsp;state&nbsp;to&nbsp;C&nbsp;(no-op&nbsp;for&nbsp;pure&nbsp;Python&nbsp;components).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;sync_from_c(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Sync&nbsp;C&nbsp;state&nbsp;to&nbsp;Python&nbsp;(no-op&nbsp;for&nbsp;pure&nbsp;Python&nbsp;components).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Lifecycle&nbsp;methods&nbsp;(override&nbsp;in&nbsp;subclasses)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;start(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;once&nbsp;when&nbsp;component&nbsp;starts&nbsp;(after&nbsp;being&nbsp;added&nbsp;to&nbsp;scene).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;update(self,&nbsp;dt:&nbsp;float)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;every&nbsp;frame.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;fixed_update(self,&nbsp;dt:&nbsp;float)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;at&nbsp;fixed&nbsp;timestep&nbsp;intervals.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_destroy(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;component&nbsp;is&nbsp;destroyed.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_editor_start(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;editor&nbsp;mode&nbsp;starts.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;setup_editor_defaults(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;component&nbsp;is&nbsp;created&nbsp;via&nbsp;editor&nbsp;UI.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Entity&nbsp;relationship<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_added_to_entity(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;added&nbsp;to&nbsp;an&nbsp;entity.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_removed_from_entity(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;removed&nbsp;from&nbsp;an&nbsp;entity.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Lifecycle<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_added(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;after&nbsp;component&nbsp;is&nbsp;fully&nbsp;attached&nbsp;to&nbsp;entity.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_removed(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;component&nbsp;is&nbsp;removed.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_scene_inactive(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;scene&nbsp;mode&nbsp;changes&nbsp;to&nbsp;INACTIVE.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_scene_active(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Called&nbsp;when&nbsp;scene&nbsp;mode&nbsp;changes&nbsp;from&nbsp;INACTIVE&nbsp;to&nbsp;active&nbsp;(EDITOR&nbsp;or&nbsp;GAME).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;destroy(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Explicitly&nbsp;release&nbsp;all&nbsp;resources.&nbsp;Called&nbsp;by&nbsp;Scene.destroy().&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.on_destroy()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Serialization<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;=========================================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;serialize_data(self)&nbsp;-&gt;&nbsp;Dict[str,&nbsp;Any]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Serialize&nbsp;component&nbsp;data&nbsp;using&nbsp;InspectRegistry.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Uses&nbsp;the&nbsp;same&nbsp;mechanism&nbsp;as&nbsp;CxxComponent&nbsp;-&nbsp;kind&nbsp;handlers&nbsp;are&nbsp;applied<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;enum,&nbsp;handles,&nbsp;etc.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ensure&nbsp;builtin&nbsp;kind&nbsp;handlers&nbsp;are&nbsp;registered<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.serialization.kind&nbsp;&nbsp;#&nbsp;noqa:&nbsp;F401<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.inspect&nbsp;import&nbsp;InspectRegistry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;InspectRegistry.instance().serialize_all(self)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;deserialize_data(self,&nbsp;data:&nbsp;Dict[str,&nbsp;Any],&nbsp;context:&nbsp;Any&nbsp;=&nbsp;None)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Deserialize&nbsp;component&nbsp;data&nbsp;using&nbsp;InspectRegistry.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Uses&nbsp;the&nbsp;same&nbsp;mechanism&nbsp;as&nbsp;CxxComponent&nbsp;-&nbsp;kind&nbsp;handlers&nbsp;are&nbsp;applied<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;enum,&nbsp;handles,&nbsp;etc.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;data:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ensure&nbsp;builtin&nbsp;kind&nbsp;handlers&nbsp;are&nbsp;registered<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.serialization.kind&nbsp;&nbsp;#&nbsp;noqa:&nbsp;F401<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.inspect&nbsp;import&nbsp;InspectRegistry<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;InspectRegistry.instance().deserialize_all(self,&nbsp;data)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;serialize(self)&nbsp;-&gt;&nbsp;Dict[str,&nbsp;Any]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Serialize&nbsp;component&nbsp;with&nbsp;type&nbsp;info.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;type&quot;:&nbsp;self.type_name(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;data&quot;:&nbsp;self.serialize_data()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
<br>
class&nbsp;InputComponent(PythonComponent):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Component&nbsp;capable&nbsp;of&nbsp;handling&nbsp;input&nbsp;events.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Class-level&nbsp;flag&nbsp;for&nbsp;input&nbsp;handler&nbsp;detection<br>
&nbsp;&nbsp;&nbsp;&nbsp;is_input_handler:&nbsp;bool&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;enabled:&nbsp;bool&nbsp;=&nbsp;True,&nbsp;active_in_editor:&nbsp;bool&nbsp;=&nbsp;False):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(enabled=enabled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.active_in_editor&nbsp;=&nbsp;active_in_editor<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Install&nbsp;input&nbsp;vtable&nbsp;for&nbsp;C-level&nbsp;dispatch<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._tc.install_input_vtable()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_mouse_button(self,&nbsp;event):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_mouse_move(self,&nbsp;event):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_scroll(self,&nbsp;event):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_key(self,&nbsp;event):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
<br>
__all__&nbsp;=&nbsp;[&quot;PythonComponent&quot;,&nbsp;&quot;InputComponent&quot;]<br>
<br>
<br>
#&nbsp;Register&nbsp;PythonComponent&nbsp;base&nbsp;class&nbsp;(can't&nbsp;use&nbsp;__init_subclass__&nbsp;for&nbsp;itself)<br>
from&nbsp;termin._native.inspect&nbsp;import&nbsp;InspectRegistry<br>
from&nbsp;termin.entity&nbsp;import&nbsp;ComponentRegistry<br>
<br>
#&nbsp;Register&nbsp;inspect_fields&nbsp;for&nbsp;PythonComponent&nbsp;(so&nbsp;subclasses&nbsp;inherit&nbsp;'enabled')<br>
InspectRegistry.instance().register_python_fields(&quot;PythonComponent&quot;,&nbsp;PythonComponent.inspect_fields)<br>
ComponentRegistry.instance().register_python(&quot;PythonComponent&quot;,&nbsp;PythonComponent)<br>
<!-- END SCAT CODE -->
</body>
</html>
