<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/core/resources.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#&nbsp;termin/visualization/resources.py<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;dataclasses&nbsp;import&nbsp;dataclass,&nbsp;field<br>
from&nbsp;typing&nbsp;import&nbsp;Dict,&nbsp;Optional,&nbsp;TYPE_CHECKING<br>
<br>
if&nbsp;TYPE_CHECKING:&nbsp;&nbsp;#&nbsp;только&nbsp;для&nbsp;типов,&nbsp;чтобы&nbsp;не&nbsp;ловить&nbsp;циклы&nbsp;импортов<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.material&nbsp;import&nbsp;Material<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.mesh&nbsp;import&nbsp;MeshDrawable<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.texture&nbsp;import&nbsp;Texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Component<br>
<br>
<br>
<br>
class&nbsp;ResourceManager:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Глобальный&nbsp;менеджер&nbsp;ресурсов&nbsp;редактора.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;_instance:&nbsp;&quot;ResourceManager&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials:&nbsp;Dict[str,&nbsp;&quot;Material&quot;]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.meshes:&nbsp;Dict[str,&nbsp;&quot;MeshDrawable&quot;]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.textures:&nbsp;Dict[str,&nbsp;&quot;Texture&quot;]&nbsp;=&nbsp;{}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.components:&nbsp;Dict[str,&nbsp;type[&quot;Component&quot;]]&nbsp;=&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;instance(cls)&nbsp;-&gt;&nbsp;&quot;ResourceManager&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;cls._instance&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cls._instance&nbsp;=&nbsp;cls()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cls._instance<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Материалы&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_material(self,&nbsp;name:&nbsp;str,&nbsp;mat:&nbsp;&quot;Material&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials[name]&nbsp;=&nbsp;mat<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_material(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;Material&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.materials.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_material_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(self.materials.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_material_name(self,&nbsp;mat:&nbsp;&quot;Material&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;n,&nbsp;m&nbsp;in&nbsp;self.materials.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;m&nbsp;is&nbsp;mat:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;n<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Меши&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_mesh(self,&nbsp;name:&nbsp;str,&nbsp;mesh:&nbsp;&quot;MeshDrawable&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.meshes[name]&nbsp;=&nbsp;mesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_mesh(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[&quot;MeshDrawable&quot;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.meshes.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_mesh_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(self.meshes.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;find_mesh_name(self,&nbsp;mesh:&nbsp;&quot;MeshDrawable&quot;)&nbsp;-&gt;&nbsp;Optional[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;n,&nbsp;m&nbsp;in&nbsp;self.meshes.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;m&nbsp;is&nbsp;mesh:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;n<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Компоненты&nbsp;(на&nbsp;будущее)&nbsp;---------<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;register_component(self,&nbsp;name:&nbsp;str,&nbsp;cls:&nbsp;type[&quot;Component&quot;]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.components[name]&nbsp;=&nbsp;cls<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_component(self,&nbsp;name:&nbsp;str)&nbsp;-&gt;&nbsp;Optional[type[&quot;Component&quot;]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self.components.get(name)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;list_component_names(self)&nbsp;-&gt;&nbsp;list[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;sorted(self.components.keys())<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---------&nbsp;Сериализация&nbsp;---------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;serialize(self)&nbsp;-&gt;&nbsp;dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Сериализует&nbsp;все&nbsp;ресурсы&nbsp;ResourceManager.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;materials&quot;:&nbsp;{name:&nbsp;mat.serialize()&nbsp;for&nbsp;name,&nbsp;mat&nbsp;in&nbsp;self.materials.items()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;meshes&quot;:&nbsp;{name:&nbsp;mesh.serialize()&nbsp;for&nbsp;name,&nbsp;mesh&nbsp;in&nbsp;self.meshes.items()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;textures&quot;:&nbsp;{name:&nbsp;self._serialize_texture(tex)&nbsp;for&nbsp;name,&nbsp;tex&nbsp;in&nbsp;self.textures.items()},<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_serialize_texture(self,&nbsp;tex:&nbsp;&quot;Texture&quot;)&nbsp;-&gt;&nbsp;dict:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Сериализует&nbsp;текстуру.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_path&nbsp;=&nbsp;tex.source_path&nbsp;if&nbsp;tex.source_path&nbsp;else&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;source_path:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{&quot;type&quot;:&nbsp;&quot;file&quot;,&nbsp;&quot;source_path&quot;:&nbsp;source_path}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;{&quot;type&quot;:&nbsp;&quot;unknown&quot;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;deserialize(cls,&nbsp;data:&nbsp;dict,&nbsp;context=None)&nbsp;-&gt;&nbsp;&quot;ResourceManager&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Восстанавливает&nbsp;ResourceManager&nbsp;из&nbsp;сериализованных&nbsp;данных.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.material&nbsp;import&nbsp;Material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.mesh&nbsp;import&nbsp;MeshDrawable<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm&nbsp;=&nbsp;cls()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Материалы<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;mat_data&nbsp;in&nbsp;data.get(&quot;materials&quot;,&nbsp;{}).items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;Material.deserialize(mat_data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm.register_material(name,&nbsp;mat)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Меши<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;name,&nbsp;mesh_data&nbsp;in&nbsp;data.get(&quot;meshes&quot;,&nbsp;{}).items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;drawable&nbsp;=&nbsp;MeshDrawable.deserialize(mesh_data,&nbsp;context)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;drawable&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm.register_mesh(name,&nbsp;drawable)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Текстуры&nbsp;-&nbsp;TODO:&nbsp;добавить&nbsp;Texture.deserialize()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;for&nbsp;name,&nbsp;tex_data&nbsp;in&nbsp;data.get(&quot;textures&quot;,&nbsp;{}).items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex&nbsp;=&nbsp;Texture.deserialize(tex_data,&nbsp;context)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm.register_texture(name,&nbsp;tex)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;rm<br>
<!-- END SCAT CODE -->
</body>
</html>
