<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/platform/window.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Window&nbsp;—&nbsp;фасад&nbsp;для&nbsp;совместимости&nbsp;со&nbsp;старым&nbsp;API.<br>
<br>
Объединяет&nbsp;Display&nbsp;и&nbsp;SimpleDisplayInputManager&nbsp;в&nbsp;один&nbsp;класс,<br>
предоставляя&nbsp;старый&nbsp;API&nbsp;Window&nbsp;для&nbsp;examples&nbsp;и&nbsp;простых&nbsp;приложений.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;Callable,&nbsp;List,&nbsp;Optional,&nbsp;Tuple,&nbsp;TYPE_CHECKING<br>
<br>
from&nbsp;termin.visualization.core.display&nbsp;import&nbsp;Display<br>
from&nbsp;termin.visualization.core.viewport&nbsp;import&nbsp;Viewport<br>
from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Action,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MouseButton,<br>
)<br>
from&nbsp;termin.visualization.platform.input_manager&nbsp;import&nbsp;SimpleDisplayInputManager<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.camera&nbsp;import&nbsp;CameraComponent<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.scene&nbsp;import&nbsp;Scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;GraphicsBackend<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.platform&nbsp;import&nbsp;SDLWindowBackend,&nbsp;SDLWindowRenderSurface<br>
<br>
<br>
class&nbsp;Window:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Фасад,&nbsp;объединяющий&nbsp;Display&nbsp;и&nbsp;SimpleDisplayInputManager.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Предоставляет&nbsp;старый&nbsp;API&nbsp;Window&nbsp;для&nbsp;совместимости&nbsp;с&nbsp;examples.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Внутри&nbsp;создаёт:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;SDLWindowRenderSurface&nbsp;(C++&nbsp;окно&nbsp;+&nbsp;поверхность&nbsp;рендеринга)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Display&nbsp;(управление&nbsp;viewport'ами)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;SimpleDisplayInputManager&nbsp;(обработка&nbsp;ввода)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics:&nbsp;&quot;GraphicsBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;backend:&nbsp;&quot;SDLWindowBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share:&nbsp;Optional[&quot;Window&nbsp;|&nbsp;SDLWindowRenderSurface&quot;]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Создаёт&nbsp;окно&nbsp;с&nbsp;дисплеем&nbsp;и&nbsp;обработчиком&nbsp;ввода.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;Ширина&nbsp;окна&nbsp;в&nbsp;пикселях.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;Высота&nbsp;окна&nbsp;в&nbsp;пикселях.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;Заголовок&nbsp;окна.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics:&nbsp;Графический&nbsp;бэкенд.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;backend:&nbsp;C++&nbsp;SDLWindowBackend.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share:&nbsp;Окно&nbsp;для&nbsp;sharing&nbsp;OpenGL&nbsp;контекста.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.platform&nbsp;import&nbsp;SDLWindowRenderSurface<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._graphics&nbsp;=&nbsp;graphics<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend&nbsp;=&nbsp;backend<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Определяем&nbsp;share&nbsp;surface<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share_surface:&nbsp;Optional[SDLWindowRenderSurface]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(share,&nbsp;Window):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share_surface&nbsp;=&nbsp;share._surface<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;share&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share_surface&nbsp;=&nbsp;share<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создаём&nbsp;C++&nbsp;SDLWindowRenderSurface&nbsp;(окно&nbsp;+&nbsp;surface)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface:&nbsp;SDLWindowRenderSurface&nbsp;=&nbsp;SDLWindowRenderSurface(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width,&nbsp;height,&nbsp;title,&nbsp;backend,&nbsp;share_surface<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface.set_graphics(graphics)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создаём&nbsp;Display<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._display&nbsp;=&nbsp;Display(self._surface)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создаём&nbsp;input&nbsp;manager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._input_manager&nbsp;=&nbsp;SimpleDisplayInputManager(self._display.tc_display_ptr)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Connect&nbsp;input&nbsp;manager&nbsp;to&nbsp;surface<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface.set_input_manager(self._input_manager.tc_input_manager_ptr)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Колбэки&nbsp;для&nbsp;внешнего&nbsp;кода&nbsp;(совместимость)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.on_mouse_button_event:&nbsp;Optional[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Callable[[MouseButton,&nbsp;Action,&nbsp;float,&nbsp;float,&nbsp;Optional[Viewport]],&nbsp;None]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.on_mouse_move_event:&nbsp;Optional[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Callable[[float,&nbsp;float,&nbsp;Optional[Viewport]],&nbsp;None]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.after_render_handler:&nbsp;Optional[Callable[[&quot;Window&quot;],&nbsp;None]]&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._world_mode&nbsp;=&nbsp;&quot;game&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;surface(self)&nbsp;-&gt;&nbsp;&quot;SDLWindowRenderSurface&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;C++&nbsp;SDLWindowRenderSurface.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._surface<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;display(self)&nbsp;-&gt;&nbsp;Display:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Display&nbsp;для&nbsp;управления&nbsp;viewport'ами.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._display<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;viewports(self)&nbsp;-&gt;&nbsp;List[Viewport]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Список&nbsp;viewport'ов&nbsp;(делегирует&nbsp;в&nbsp;Display).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._display.viewports<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_world_mode(self,&nbsp;mode:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;режим&nbsp;работы&nbsp;('game'&nbsp;или&nbsp;'editor').&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._world_mode&nbsp;=&nbsp;mode<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;close(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Закрывает&nbsp;окно.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;C++&nbsp;surface&nbsp;handles&nbsp;cleanup<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;should_close(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Проверяет,&nbsp;должно&nbsp;ли&nbsp;окно&nbsp;закрыться.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._surface&nbsp;is&nbsp;None&nbsp;or&nbsp;self._surface.should_close()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;make_current(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Делает&nbsp;контекст&nbsp;текущим.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._surface&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface.make_current()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;swap_buffers(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Swap&nbsp;buffers.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._surface&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface.swap_buffers()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;poll_events(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Poll&nbsp;SDL&nbsp;events.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend.poll_events()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;add_viewport(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene:&nbsp;&quot;Scene&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;camera:&nbsp;&quot;CameraComponent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rect:&nbsp;Tuple[float,&nbsp;float,&nbsp;float,&nbsp;float]&nbsp;=&nbsp;(0.0,&nbsp;0.0,&nbsp;1.0,&nbsp;1.0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;Viewport:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Создаёт&nbsp;и&nbsp;добавляет&nbsp;viewport.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene:&nbsp;Сцена&nbsp;для&nbsp;рендеринга.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;camera:&nbsp;Камера&nbsp;для&nbsp;рендеринга.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rect:&nbsp;Нормализованный&nbsp;прямоугольник&nbsp;(x,&nbsp;y,&nbsp;w,&nbsp;h).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Созданный&nbsp;Viewport.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.make_current()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._display.create_viewport(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene=scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;camera=camera,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rect=rect,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;update(self,&nbsp;dt:&nbsp;float)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Reserved&nbsp;for&nbsp;future&nbsp;per-window&nbsp;updates.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;viewport_rect_to_pixels(self,&nbsp;viewport:&nbsp;Viewport)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int,&nbsp;int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Преобразует&nbsp;rect&nbsp;viewport'а&nbsp;в&nbsp;пиксели.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._display.viewport_rect_to_pixels(viewport)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_request_update(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Запрашивает&nbsp;перерисовку.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._surface&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._surface.request_update()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_viewport_under_cursor(self,&nbsp;x:&nbsp;float,&nbsp;y:&nbsp;float)&nbsp;-&gt;&nbsp;Optional[Viewport]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Находит&nbsp;viewport&nbsp;под&nbsp;курсором.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._display.viewport_at_pixels(x,&nbsp;y)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Returns&nbsp;framebuffer&nbsp;size.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._surface&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._surface.get_size()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(0,&nbsp;0)<br>
<br>
<br>
#&nbsp;Backwards&nbsp;compatibility<br>
GLWindow&nbsp;=&nbsp;Window<br>
<!-- END SCAT CODE -->
</body>
</html>
