#!/usr/bin/env python3

from setuptools import setup
from termin_build.versioning import public_version


setup(
    name="termin-player",
    version=public_version(),
    license="Apache-2.0",
    description="Standalone/source/headless Termin player runtime",
    author="mirmik",
    author_email="mirmikns@yandex.ru",
    python_requires=">=3.14",
    packages=["termin.player"],
    package_dir={"termin.player": "termin/player"},
    install_requires=[
        "termin-base",
        "termin-assets",
        "termin-default-assets",
        "termin-bootstrap",
        "termin-prefab",
        "termin-glb",
        "termin-glb-adapters",
        "termin-tween",
        "termin-components-tween",
        "termin-audio",
        "termin-voxels",
        "termin-components-voxels",
        "termin-components-physics",
        "termin-components-ui",
        "termin-materials",
        "termin-render-passes",
        "termin-mcp",
        "termin-graphics-mcp",
        "termin-shader-runtime",
        "termin-nanobind",
        "termin-modules",
        "termin-project-modules",
        "termin-project",
        "termin-stdlib",
        "termin-scene",
        "termin-display",
        "termin-engine",
        "termin-render",
        "termin-components-render",
        "termin-input",
        "termin-inspect",
        "termin-collision",
        "termin-physics",
        "termin-navmesh",
        "termin-lighting",
        "termin-mesh",
        "termin-graphics-core",
        "numpy",
        "packaging",
    ],
    zip_safe=False,
)
