[project]
name = "termin-graphics-showcase"
version = "0.5.2"
requires-python = ">=3.14"
dependencies = [
    "numpy",
    "termin-plot",
    "termin-plot-gui-native",
    "termin-animation",
    "termin-glb",
    "termin-graphics-mcp",
    "termin-gui-native",
    "termin-image",
    "termin-mesh",
    "termin-nodegraph",
    "termin-skeleton",
    "termin-visual-scene",
    "termin-graphics",
]
