using UnityEngine;

public class AutomaticDoorPhaseAnimatronic : Animatronic
{
    float _start_phase;
    float _finish_phase;

    ReferencedPose _referencedPose;

    public AutomaticDoorPhaseAnimatronic(
        float start_phase,
        float finish_phase,
        ReferencedPose referencedPose,
        long start_step,
        long finish_step
    ) : base(start_step, finish_step)
    {
        _start_phase = start_phase;
        _finish_phase = finish_phase;
        _referencedPose = referencedPose;
    }

    public override void apply(ObjectOfTimeline obj, global::System.Int64 current_step)
    {
        var coeff = (float)(current_step - StartStep) / (FinishStep - StartStep);
        var phase = Mathf.Lerp(_start_phase, _finish_phase, coeff);
        var door = obj as AutomaticDoorObject;
        door.SetPhase(phase);
    }

    public override AnimationType GetAnimationType(global::System.Int64 local_step)
    {
        throw new System.NotImplementedException();
    }

    public override ReferencedPose GetReferencedPose(long local_step, ITimeline timeline)
    {
        return _referencedPose;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _start_phase);
        result = FieldScanner.ModifyHash(result, _finish_phase);
        result = FieldScanner.ModifyHash(result, _referencedPose);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as AutomaticDoorPhaseAnimatronic;
        return _start_phase == other._start_phase
            && _finish_phase == other._finish_phase
            && _referencedPose == other._referencedPose
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
