using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

[Serializable]
public class DisguiseAnimatronic : Animatronic
{
    ReferencedPose _pose;

    // public override long HashCode()
    // {
    //     long h = base.HashCode();

    //     var h2 = _direction.GetHashCode();
    //     var h3 = _position.GetHashCode();

    //     h = h * 31 + h2 + h3 + GetType().Name.GetHashCode();
    //     return h;
    // }

    public DisguiseAnimatronic(long start_step, long finish_step, ReferencedPose pose)
        : base(start_step, finish_step)
    {
        _pose = pose;
    }

    // public Vector3 Direction(Int64 stepstamp, ITimeline tl)
    // {
    //     return _direction;
    // }

    // public Vector3 Position(Int64 stepstamp, ITimeline tl)
    // {
    //     return _position;
    // }

    public override ReferencedPose GetReferencedPose(Int64 stepstamp, ITimeline tl)
    {
        return _pose;
    }

    public override AnimationType GetAnimationType(long local_step)
    {
        return AnimationType.Idle;
    }

    // public override string FrameName(Int64 stepstamp)
    // {
    // 	return _pose.Frame;
    // }


    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _pose);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as DisguiseAnimatronic;
        return _pose == other._pose
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
