using System;
using System.Collections.Generic;

#if UNITY_64
using UnityEngine;
#endif

[Serializable]
public class GrabbedAnimatronic : Animatronic
{
    ObjectId dragger_name_hash;

    public GrabbedAnimatronic(long start_step, long finish_step, Actor dragger)
        : base(start_step, finish_step)
    {
        this.dragger_name_hash = dragger.ObjectId();
    }

    public override ReferencedPose GetReferencedPose(Int64 stepstamp, ITimeline tl)
    {
        return tl.GetObject(dragger_name_hash).CurrentReferencedPose();
    }

    public override AnimationType GetAnimationType(long local_step)
    {
        return AnimationType.Death;
    }

    // public override string FrameName(Int64 stepstamp)
    // {
    // 	return tl.GetActor(dragger_name).CurrentReferencedPose().Frame;
    // }


    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, dragger_name_hash);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as GrabbedAnimatronic;
        return dragger_name_hash == other.dragger_name_hash
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
