public class NullAnimatronic : Animatronic
{
    ReferencedPose _pose;

    public NullAnimatronic(long step, ReferencedPose pose) : base(step, long.MaxValue)
    {
        _pose = pose;
    }

    public override bool IsLooped()
    {
        return true;
    }

    public NullAnimatronic() { }

    public override ReferencedPose GetReferencedPose(long stepstamp, ITimeline tl)
    {
        return _pose;
    }

    public override AnimationType GetAnimationType(long local_step)
    {
        return AnimationType.None;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _pose);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as NullAnimatronic;
        return _pose == other._pose
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
