using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class ParasiteParasiteAnimatronic : Animatronic
{
    ObjectId _host_name;
    AnimationType anim_type;

    public ParasiteParasiteAnimatronic(
        long start_step,
        long finish_step,
        ObjectId host,
        AnimationType anim_type = AnimationType.Idle
    ) : base(start_step, finish_step)
    {
        _host_name = host;
        this.anim_type = anim_type;
    }

    public new Vector3 Direction(Int64 stepstamp, ITimeline tl)
    {
        return tl.GetActor(_host_name).Direction();
    }

    public new Vector3 Position(Int64 stepstamp, ITimeline tl)
    {
        return tl.GetActor(_host_name).Position();
    }

    public override ReferencedPose GetReferencedPose(long stepstamp, ITimeline tl)
    {
        //var dir = Direction(stepstamp, tl);
        return new ReferencedPose(new Pose(Vector3.zero, Quaternion.identity), _host_name);
    }

    public override AnimationType GetAnimationType(long local_step)
    {
        return anim_type;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _host_name);
        result = FieldScanner.ModifyHash(result, anim_type);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ParasiteParasiteAnimatronic;
        return _host_name == other._host_name
            && anim_type == other.anim_type
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
