public class PatrolIdleAnimatronic : IdleAnimatronic
{
    public PatrolIdleAnimatronic(
        long start_step,
        ReferencedPose pose,
        AnimationType idle_animation,
        Pose local_camera_pose,
        LookAroundSettings look_around
    ) : base(start_step, pose, idle_animation, local_camera_pose, look_around) { }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _pose);
        result = FieldScanner.ModifyHash(result, _idle_animation);
        result = FieldScanner.ModifyHash(result, _local_camera_pose);
        result = FieldScanner.ModifyHash(result, _look_around);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as PatrolIdleAnimatronic;
        return _pose == other._pose
            && _idle_animation == other._idle_animation
            && _local_camera_pose == other._local_camera_pose
            && _look_around == other._look_around
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
