using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class PoseBezierLerpAnimatronic : Animatronic
{
    ReferencedPose pose_a;
    ReferencedPose pose_b;
    ReferencedPose pose_c;

    public PoseBezierLerpAnimatronic(
        ReferencedPose pose_a,
        ReferencedPose pose_b,
        ReferencedPose pose_c,
        long start_step,
        long finish_step
    ) : base(start_step, finish_step)
    {
        this.pose_a = pose_a;
        this.pose_b = pose_b;
        this.pose_c = pose_c;
    }

    public override ReferencedPose GetReferencedPose(long stepstamp, ITimeline tl)
    {
        float t = (float)(stepstamp - StartStep) / (FinishStep - StartStep);

        ObjectId frame;
        if (t < 0.5f)
        {
            frame = pose_a.Frame;
        }
        else
        {
            frame = pose_b.Frame;
        }

        var a_glb_pose = pose_a.GlobalPose(tl);
        var b_glb_pose = pose_b.GlobalPose(tl);
        var c_glb_pose = pose_c.GlobalPose(tl);

        var lerped_pose = Pose.BezierLerp(a_glb_pose, b_glb_pose, c_glb_pose, t);
        return ReferencedPose.FromGlobalPose(lerped_pose, frame, tl);
    }

    public override AnimationType GetAnimationType(long local_step)
    {
        throw new NotImplementedException();
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, pose_a);
        result = FieldScanner.ModifyHash(result, pose_b);
        result = FieldScanner.ModifyHash(result, pose_c);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as PoseBezierLerpAnimatronic;
        return pose_a == other.pose_a
            && pose_b == other.pose_b
            && pose_c == other.pose_c
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
