using UnityEngine;

public class SinusAutomaticDoorPhaseAnimatronic : Animatronic
{
    ReferencedPose _referencedPose;

    public SinusAutomaticDoorPhaseAnimatronic(
        ReferencedPose referencedPose,
        long start_step,
        long finish_step
    ) : base(start_step, finish_step)
    {
        _referencedPose = referencedPose;
    }

    public float Phase(float coeff)
    {
        return Mathf.Sin(coeff * Mathf.PI) * 0.5f + 0.5f;
    }

    public override void apply(ObjectOfTimeline obj, global::System.Int64 current_step)
    {
        var coeff = current_step / (float)Utility.GAME_GLOBAL_FREQUENCY;
        var phase = Phase(coeff);
        var door = obj as AutomaticDoorObject;
        door.SetPhase(phase);
    }

    public override AnimationType GetAnimationType(global::System.Int64 local_step)
    {
        return AnimationType.None;
    }

    public override ReferencedPose GetReferencedPose(long local_step, ITimeline timeline)
    {
        return _referencedPose;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _referencedPose);
        result = FieldScanner.ModifyHash(result, _initial_animation_time);
        result = FieldScanner.ModifyHash(result, unchanged_start_step);
        result = FieldScanner.ModifyHash(result, unchanged_finish_step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as SinusAutomaticDoorPhaseAnimatronic;
        return _referencedPose == other._referencedPose
            && _initial_animation_time == other._initial_animation_time
            && unchanged_start_step == other.unchanged_start_step
            && unchanged_finish_step == other.unchanged_finish_step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
