<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/__init__.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Visualization&nbsp;package&nbsp;providing&nbsp;a&nbsp;minimal&nbsp;rendering&nbsp;stack&nbsp;with&nbsp;pluggable&nbsp;backends.<br>
<br>
The&nbsp;module&nbsp;exposes&nbsp;abstractions&nbsp;for&nbsp;window/context&nbsp;management,&nbsp;scene&nbsp;graphs,<br>
camera&nbsp;models&nbsp;and&nbsp;GPU&nbsp;resources&nbsp;such&nbsp;as&nbsp;meshes,&nbsp;shaders,&nbsp;materials&nbsp;and&nbsp;textures.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;termin.visualization.platform.window&nbsp;import&nbsp;Window,&nbsp;GLWindow<br>
from&nbsp;termin.visualization.core.scene&nbsp;import&nbsp;Scene<br>
from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity,&nbsp;Component,&nbsp;InputComponent<br>
from&nbsp;termin.visualization.render.render_context&nbsp;import&nbsp;RenderContext<br>
from&nbsp;termin.visualization.core.input_events&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;MouseButtonEvent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MouseMoveEvent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;ScrollEvent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;KeyEvent,<br>
)<br>
from&nbsp;termin.visualization.core.camera&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;CameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PerspectiveCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrthographicCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrbitCameraController,<br>
)<br>
from&nbsp;termin.visualization.core.mesh&nbsp;import&nbsp;MeshDrawable<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer<br>
from&nbsp;termin.visualization.ui&nbsp;import&nbsp;Canvas,&nbsp;UIElement,&nbsp;UIRectangle<br>
from&nbsp;termin.visualization.core.material&nbsp;import&nbsp;Material<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
from&nbsp;termin.visualization.render.texture&nbsp;import&nbsp;Texture<br>
from&nbsp;termin.visualization.core.world&nbsp;import&nbsp;VisualizationWorld,&nbsp;Visualization<br>
from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;GraphicsBackend,&nbsp;WindowBackend,&nbsp;MouseButton,&nbsp;Key,&nbsp;Action<br>
from&nbsp;termin.visualization.platform.backends.qt&nbsp;import&nbsp;QtWindowBackend,&nbsp;QtGLWindowHandle<br>
<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Window&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GLWindow&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Renderer&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Scene&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Entity&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Component&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;InputComponent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;RenderContext&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;MouseButtonEvent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;MouseMoveEvent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;ScrollEvent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;KeyEvent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;CameraComponent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;PerspectiveCameraComponent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;OrthographicCameraComponent&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;OrbitCameraController&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;MeshDrawable&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;MeshRenderer&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Canvas&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;UIElement&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;UIRectangle&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Material&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;TcShader&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Texture&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Visualization&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;VisualizationWorld&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GraphicsBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;WindowBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;MouseButton&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Key&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Action&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;QtWindowBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;QtGLWindowHandle&quot;,<br>
]<br>
<!-- END SCAT CODE -->
</body>
</html>
