from termin_nanobind.runtime import preload_sdk_libs

preload_sdk_libs("termin_display")

from termin.display._display_native import Display
from termin.display._display_native import _display_get_input_manager as _display_get_input_manager
from termin.display._display_native import _input_manager_create_vtable as _input_manager_create_vtable
from termin.display._display_native import _input_manager_free as _input_manager_free
from termin.display._display_native import _input_manager_new as _input_manager_new
from termin.display._display_native import _input_manager_on_char as _input_manager_on_char
from termin.display._display_native import _input_manager_on_key as _input_manager_on_key
from termin.display._display_native import _input_manager_on_mouse_button as _input_manager_on_mouse_button
from termin.display._display_native import _input_manager_on_mouse_move as _input_manager_on_mouse_move
from termin.display._display_native import _input_manager_on_pointer as _input_manager_on_pointer
from termin.display._display_native import _input_manager_on_scroll as _input_manager_on_scroll
from termin.display._display_native import _viewport_get_input_manager as _viewport_get_input_manager
from termin.display._display_native import _viewport_input_manager_free as _viewport_input_manager_free
from termin.display._display_native import _viewport_input_manager_new as _viewport_input_manager_new
from termin.display.input_manager import BasicDisplayInputManager

__all__ = [
    "Display",
    "BasicDisplayInputManager",
]
