using System.Collections.Generic;
using System;
using UnityEngine;

public class GrubbedWhileAliveCommand : ActorCommand
{
    AnimationType _idle_state;
    float confusion_time;
    ObjectId host_actor;

    public GrubbedWhileAliveCommand(
        AnimationType idle_state,
        long stamp,
        float confusion_time,
        ObjectId host_actor
    ) : base(stamp)
    {
        _idle_state = idle_state;
        this.confusion_time = confusion_time;
        this.host_actor = host_actor;
    }

    public override bool ExecuteFirstTime(ObjectOfTimeline actor, ITimeline timeline)
    {
        var step = actor.LocalStep();
        var idle_animatronic = new ParasiteParasiteAnimatronic(
            step,
            step + Utility.DurationToSteps(confusion_time),
            host: host_actor
        );
        actor.SetNextAnimatronic(idle_animatronic);
        return false;
    }

    override public bool CanBeInterrupted()
    {
        return false;
    }

    public override bool Execute(ObjectOfTimeline actor, ITimeline timeline)
    {
        var local_step = actor.LocalStep();
        if (local_step > StartStep + Utility.DurationToSteps(confusion_time))
            return true;
        return false;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _idle_state);
        result = FieldScanner.ModifyHash(result, confusion_time);
        result = FieldScanner.ModifyHash(result, host_actor);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as GrubbedWhileAliveCommand;
        return _idle_state == other._idle_state
            && confusion_time == other.confusion_time
            && host_actor == other.host_actor
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
