using System.Collections;
using System.Collections.Generic;
using System;
using UnityEngine;

public class JumpKillCommand : ShootCommand
{
    public override void KillTarget(ObjectOfTimeline actor, ITimeline tl, float absolute_offset)
    {
        var target = TargetObject(tl);

        var jump_anim = new PoseLerpAnimatronic(
            start_step: tl.CurrentStep(),
            finish_step: tl.CurrentStep() + (long)(Utility.GAME_GLOBAL_FREQUENCY * 0.5f),
            pose_a: actor.CurrentReferencedPose(),
            pose_b: target.CurrentReferencedPose()
        );
        actor.SetNextAnimatronic(jump_anim);

        tl.AddEvent(
            new DeathEvent(
                step: tl.CurrentStep()
                    + (long)(0 * actor.ReverseMultiplier() * Utility.GAME_GLOBAL_FREQUENCY),
                actor: target,
                who_kill_me: actor.Name(),
                reversed: target.IsReversed()
            )
        );
    }

    public JumpKillCommand(ObjectId target_actor, float shoot_distance, long stamp)
        : base(target_actor, shoot_distance, stamp, false) { }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _shoot_distance);
        result = FieldScanner.ModifyHash(result, timeout_before_shoot);
        result = FieldScanner.ModifyHash(result, ignore_obstacles);
        result = FieldScanner.ModifyHash(result, can_shoot_from_croach);
        result = FieldScanner.ModifyHash(result, target_actor_name);
        result = FieldScanner.ModifyHash(result, can_use_air_strike);
        result = FieldScanner.ModifyHash(result, walktype);
        result = FieldScanner.ModifyHash(result, use_interaction_pose);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as JumpKillCommand;
        return _shoot_distance == other._shoot_distance
            && timeout_before_shoot == other.timeout_before_shoot
            && ignore_obstacles == other.ignore_obstacles
            && can_shoot_from_croach == other.can_shoot_from_croach
            && target_actor_name == other.target_actor_name
            && can_use_air_strike == other.can_use_air_strike
            && walktype == other.walktype
            && use_interaction_pose == other.use_interaction_pose
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
