using System.Collections;
using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class RemoteRebootShootCommand : ShootCommand
{
    // public override void KillTarget(
    // 	ObjectOfTimeline actor,
    // 	ITimeline timeline,
    // 	float absolute_offset)
    // {
    // 	var target_actor = timeline.GetObject(TargetActorName());
    // 	timeline.AddEvent(
    // 		new StunEvent(
    // 			timeline.CurrentStep() + (long)(absolute_offset * Utility.GAME_GLOBAL_FREQUENCY),
    // 			target_actor,
    // 			target_actor.IsReversed()
    // 		)
    // 	);
    // }

    public RemoteRebootShootCommand(
        ObjectId target_actor,
        float shoot_distance,
        long stamp,
        bool ignore_obstacles = false
    ) : base(target_actor, shoot_distance, stamp, ignore_obstacles) { }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _shoot_distance);
        result = FieldScanner.ModifyHash(result, timeout_before_shoot);
        result = FieldScanner.ModifyHash(result, ignore_obstacles);
        result = FieldScanner.ModifyHash(result, can_shoot_from_croach);
        result = FieldScanner.ModifyHash(result, target_actor_name);
        result = FieldScanner.ModifyHash(result, can_use_air_strike);
        result = FieldScanner.ModifyHash(result, walktype);
        result = FieldScanner.ModifyHash(result, use_interaction_pose);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as RemoteRebootShootCommand;
        return _shoot_distance == other._shoot_distance
            && timeout_before_shoot == other.timeout_before_shoot
            && ignore_obstacles == other.ignore_obstacles
            && can_shoot_from_croach == other.can_shoot_from_croach
            && target_actor_name == other.target_actor_name
            && can_use_air_strike == other.can_use_air_strike
            && walktype == other.walktype
            && use_interaction_pose == other.use_interaction_pose
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
