using System;
using UnityEngine;

public class RestoreReverseTargetCommand : ClosestCommand
{
    public RestoreReverseTargetCommand(ObjectId target_actor, long stamp)
        : base(target_actor, WalkingType.Run, 0.5f, stamp) { }

    public override bool ActionPhase(ObjectOfTimeline actor, ITimeline timeline)
    {
        Debug.Log("RestoreReverseTargetCommand");
        var target_actor = TargetObject(timeline);

        AnigilationEvent secondary_anigilation_event = new AnigilationEvent(
            step: timeline.CurrentStep(),
            object_name: target_actor.Name(),
            reversed: target_actor.IsReversed()
        );
        timeline.AddNonDropableEvent(secondary_anigilation_event);

        // AnigilationEvent primary_anigilation_event = new AnigilationEvent(
        // 	step: timeline.CurrentStep(),
        // 	object_name: actor.Name(),
        // 	reversed: !target_actor.IsReversed()
        // );
        // timeline.AddNonDropableEvent(primary_anigilation_event);

        // //timeline.MarkParadoxes();

        return true;
    }

    public override bool IsActionStarted(ObjectOfTimeline actor)
    {
        return false;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _action_distance);
        result = FieldScanner.ModifyHash(result, target_actor_name);
        result = FieldScanner.ModifyHash(result, can_use_air_strike);
        result = FieldScanner.ModifyHash(result, walktype);
        result = FieldScanner.ModifyHash(result, use_interaction_pose);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as RestoreReverseTargetCommand;
        return _action_distance == other._action_distance
            && target_actor_name == other.target_actor_name
            && can_use_air_strike == other.can_use_air_strike
            && walktype == other.walktype
            && use_interaction_pose == other.use_interaction_pose
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
