using System.Collections;
using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class ReverseInTimeCommandSimplified : ReverseInTimeCommand
{
    public ReverseInTimeCommandSimplified(
        long add_step,
        bool active_is_reversed,
        long timeline_step,
        Vector3 actor_position
    ) : base(add_step, active_is_reversed, timeline_step, actor_position) { }

    protected override void CreateReversedCopy(Actor _actor, Timeline tl)
    {
        string copy_name = GenerateCopyName(_actor.Name());
        var timeline_step = tl.CurrentStep();

        var card = PrimaryAnigilationEvent(_actor);
        tl.AddNonDropableEvent(card);

        var guard_id = _actor.Name();
        var copy = _actor.Copy(tl) as Actor;

        copy.SetName(copy_name);
        tl.AddToNextPassList(copy);

        copy.SetObjectTimeReferencePoint(timeline_step, !copy.IsReversed());
        bool copy_is_reversed = copy.IsReversed();

        copy.DropToCurrentStateInverted();

        _actor.SetPrimaryChild(copy.Name());
        copy.SetParentGuardName(_actor.Name());

        var card2 = SecondaryAnigilationEvent(_actor);
        tl.AddNonDropableEvent(card2);

        tl.DropLastTimelineStep(copy_is_reversed ? TimeDirection.Backward : TimeDirection.Forward);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, active_is_reversed);
        result = FieldScanner.ModifyHash(result, timeline_step);
        result = FieldScanner.ModifyHash(result, actor_position);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ReverseInTimeCommandSimplified;
        return active_is_reversed == other.active_is_reversed
            && timeline_step == other.timeline_step
            && actor_position == other.actor_position
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
