using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class SetupLureCommand : ActorCommand
{
    AnimationType _idle_state = AnimationType.Idle;

    //float time_to_disguise = 1.0f;
    bool enabled = false;

    public SetupLureCommand(long stamp, bool en) : base(stamp)
    {
        enabled = en;
    }

    public override bool ExecuteFirstTime(ObjectOfTimeline actor, ITimeline timeline)
    {
        Debug.Log("SetupLureCommand.ExecuteFirstTime");

        var step = actor.LocalStep();
        var idle_animatronic = new IdleAnimatronic(
            step,
            actor.CurrentReferencedPose(),
            _idle_state,
            new Pose(new Vector3(0, actor.CameraLevel, 0), Quaternion.identity)
        );
        actor.SetNextAnimatronic(idle_animatronic);

        //actor.Disguise((long)(time_to_disguise * Utility.GAME_GLOBAL_FREQUENCY));
        return true;
    }

    public override bool Execute(ObjectOfTimeline actor, ITimeline timeline)
    {
        return true;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _idle_state);
        result = FieldScanner.ModifyHash(result, enabled);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as SetupLureCommand;
        return _idle_state == other._idle_state
            && enabled == other.enabled
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
