using System.Collections;
using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

[Serializable]
public class TimeModifierCommand : ActorCommand
{
    protected int add_coeff;

    public TimeModifierCommand(int add_coeff, long add_step) : base(add_step)
    {
        this.add_coeff = add_coeff;
    }

    public override bool ExecuteFirstTime(ObjectOfTimeline actor, ITimeline timeline)
    {
        var global_step = timeline.CurrentStep();

        var start_step = actor.ObjectTime().ToBroken(global_step);
        var time_modifier = new TimeModifierMul(
            mul: 10,
            start_step: start_step + 1,
            finish_step: start_step + 1 + 3 * (int)Utility.GAME_GLOBAL_FREQUENCY
        );

        actor.ObjectTime().AddModifier(time_modifier);
        return true;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, add_coeff);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TimeModifierCommand;
        return add_coeff == other.add_coeff
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
