using System.Collections.Generic;
using System;

#if UNITY_64
using UnityEngine;
#endif

public class TrapExploreCommand : ActorCommand
{
    AnimationType _idle_state;

    public TrapExploreCommand(AnimationType idle_state, long stamp) : base(stamp)
    {
        _idle_state = idle_state;
    }

    public override bool ExecuteFirstTime(ObjectOfTimeline actor, ITimeline timeline)
    {
        var step = actor.LocalStep();
        var idle_animatronic = new IdleAnimatronic(
            step,
            actor.CurrentReferencedPose(),
            _idle_state,
            new Pose(new Vector3(0, actor.CameraLevel, 0), Quaternion.identity)
        );
        actor.SetNextAnimatronic(idle_animatronic);
        return true;
    }

    public override bool Execute(ObjectOfTimeline actor, ITimeline timeline)
    {
        return true;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _idle_state);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as TrapExploreCommand;
        return _idle_state == other._idle_state
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
