<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/posteffects/blur.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;..shader&nbsp;import&nbsp;ShaderProgram<br>
from&nbsp;..postprocess&nbsp;import&nbsp;PostEffect<br>
<br>
#&nbsp;================================================================<br>
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TWO-PASS&nbsp;GAUSSIAN&nbsp;BLUR&nbsp;(H&nbsp;+&nbsp;V)<br>
#&nbsp;================================================================<br>
<br>
GAUSS_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location=0)&nbsp;in&nbsp;vec2&nbsp;a_pos;<br>
layout(location=1)&nbsp;in&nbsp;vec2&nbsp;a_uv;<br>
out&nbsp;vec2&nbsp;v_uv;<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_uv&nbsp;=&nbsp;a_uv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;vec4(a_pos,&nbsp;0.0,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
GAUSS_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec2&nbsp;v_uv;<br>
<br>
uniform&nbsp;sampler2D&nbsp;u_texture;<br>
uniform&nbsp;vec2&nbsp;u_direction;&nbsp;&nbsp;&nbsp;//&nbsp;(1,0)&nbsp;for&nbsp;horizontal,&nbsp;(0,1)&nbsp;for&nbsp;vertical<br>
uniform&nbsp;vec2&nbsp;u_texel_size;&nbsp;&nbsp;//&nbsp;1.0&nbsp;/&nbsp;resolution<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
//&nbsp;5-tap&nbsp;gaussian&nbsp;weights&nbsp;(approx&nbsp;sigma=2)<br>
const&nbsp;float&nbsp;w0&nbsp;=&nbsp;0.227027;<br>
const&nbsp;float&nbsp;w1&nbsp;=&nbsp;0.316216;<br>
const&nbsp;float&nbsp;w2&nbsp;=&nbsp;0.070270;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec2&nbsp;ts&nbsp;=&nbsp;u_texel_size;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec2&nbsp;dir&nbsp;=&nbsp;u_direction;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;c&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv).rgb&nbsp;*&nbsp;w0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;+=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;dir&nbsp;*&nbsp;ts&nbsp;*&nbsp;1.0).rgb&nbsp;*&nbsp;w1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;+=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;-&nbsp;dir&nbsp;*&nbsp;ts&nbsp;*&nbsp;1.0).rgb&nbsp;*&nbsp;w1;<br>
&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;+=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;dir&nbsp;*&nbsp;ts&nbsp;*&nbsp;2.0).rgb&nbsp;*&nbsp;w2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;+=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;-&nbsp;dir&nbsp;*&nbsp;ts&nbsp;*&nbsp;2.0).rgb&nbsp;*&nbsp;w2;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(c,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
class&nbsp;GaussianBlurPass(PostEffect):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Один&nbsp;проход:&nbsp;горизонтальный&nbsp;или&nbsp;вертикальный.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;direction):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader&nbsp;=&nbsp;ShaderProgram(GAUSS_VERT,&nbsp;GAUSS_FRAG)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.direction&nbsp;=&nbsp;np.array(direction,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw(self,&nbsp;gfx,&nbsp;key,&nbsp;color_tex,&nbsp;extra_textures,&nbsp;size):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w,&nbsp;h&nbsp;=&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;texel_size&nbsp;=&nbsp;np.array([1.0/max(1,w),&nbsp;1.0/max(1,h)],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader.ensure_ready(gfx)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader.use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color_tex.bind(0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader.set_uniform_int(&quot;u_texture&quot;,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader.set_uniform_auto(&quot;u_texel_size&quot;,&nbsp;texel_size)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.shader.set_uniform_auto(&quot;u_direction&quot;,&nbsp;self.direction)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_depth_test(False)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_cull_face(False)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_blend(False)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.draw_ui_textured_quad(key)<br>
<!-- END SCAT CODE -->
</body>
</html>
