#if UNITY_64
using UnityEngine;
#endif

using System;

[Serializable]
class CreateAvatarEvent : GlobalEvent
{
    string avatar_name;
    string location_name;

    public CreateAvatarEvent(long step, string avatar_name, string location_name) : base(step)
    {
        this.avatar_name = avatar_name;
        this.location_name = location_name;
    }

    public override void on_enter(long current_step, ITimeline tl)
    {
        Debug.Log("CreateAvatarEvent.on_enter");
        var location = tl.GetObject(location_name);
        var avatar = tl.GetObject(avatar_name);

        var pose = location.GlobalPose();
        //avatar.SetPose(pose, tl);
    }

    public override void on_leave(long current_step, ITimeline tl)
    {
        Debug.Log("CreateAvatarEvent.on_leave");
        var avatar = tl.GetObject(avatar_name);
        //avatar.SetPose(null, tl);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, avatar_name);
        result = FieldScanner.ModifyHash(result, location_name);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as CreateAvatarEvent;
        return avatar_name == other.avatar_name
            && location_name == other.location_name
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
