using System;

[Serializable]
public class DeathEvent : GlobalEvent
{
    ObjectId actor_id;
    string who_kill_me;
    bool reversed;

    public DeathEvent(long step, ObjectOfTimeline actor, string who_kill_me, bool reversed)
        : base(step)
    {
        if (who_kill_me == null)
            who_kill_me = "";

        this.actor_id = actor.ObjectId();
        this.who_kill_me = who_kill_me;
        this.reversed = reversed;
    }

    public override void on_forward_enter(long current_step, ITimeline tl)
    {
        if (tl.IsPast())
            return;

        bool timeline_is_reversed = tl.IsReversedPass();
        bool object_is_reversed = tl.GetObject(actor_id).IsReversed();
        var actor = tl.GetObject(actor_id);
        if (!reversed)
            actor.Death(tl, who_kill_me);
        else
            actor.Respawn(tl);
    }

    public override void on_backward_leave(long current_step, ITimeline tl)
    {
        if (tl.IsPast())
            return;

        bool timeline_is_reversed = tl.IsReversedPass();
        bool object_is_reversed = tl.GetObject(actor_id).IsReversed();
        var actor = tl.GetObject(actor_id);
        if (!reversed)
            actor.Respawn(tl);
        else
            actor.Death(tl, who_kill_me);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, actor_id);
        result = FieldScanner.ModifyHash(result, who_kill_me);
        result = FieldScanner.ModifyHash(result, reversed);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as DeathEvent;
        return actor_id == other.actor_id
            && who_kill_me == other.who_kill_me
            && reversed == other.reversed
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
