using System;
using UnityEngine;

public class ToggleDisguiseEvent : EventCard<ObjectOfTimeline>
{
    bool active_on_forward;

    public ToggleDisguiseEvent(long step, ObjectOfTimeline actor, bool active_on_forward)
        : base(step + 1, step + 2)
    {
        this.active_on_forward = active_on_forward;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        obj.SetDisguise(active_on_forward);
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        obj.SetDisguise(!active_on_forward);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, active_on_forward);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ToggleDisguiseEvent;
        return active_on_forward == other.active_on_forward
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
