#if UNITY_64
using UnityEngine;
#endif

using System;
using System.Collections.Generic;

[Serializable]
public class ExplosionEvent : GlobalEvent
{
    ReferencedPoint pos;
    float radius;

    public ExplosionEvent(long step, ReferencedPoint center, float radius)
        : base(step + 1, step + 2)
    {
        Debug.Log("Radius: " + radius);
        this.pos = center;
        this.radius = radius;
    }

    public MyList<ObjectOfTimeline> ListOfEnemiesInRadius(ITimeline tl)
    {
        MyList<ObjectOfTimeline> result = new MyList<ObjectOfTimeline>();
        var enemies = tl.Enemies();
        foreach (var enemy in enemies)
        {
            if (Vector3.Distance(enemy.GlobalPosition(), pos.GlobalPosition(tl)) < radius)
            {
                result.Add(enemy);
            }
        }
        return result;
    }

    public override void on_forward_enter(long current_step, ITimeline tl)
    {
        var enemies = ListOfEnemiesInRadius(tl);
        foreach (var enemy in enemies)
        {
            var death_event = new DeathEvent(
                current_step + 1,
                enemy,
                who_kill_me: null,
                reversed: false
            );
            tl.AddEvent(death_event);
        }
    }

    public override void on_backward_leave(long current_step, ITimeline tl) { }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, pos);
        result = FieldScanner.ModifyHash(result, radius);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ExplosionEvent;
        return pos == other.pos
            && radius == other.radius
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
