using System.Collections;
using System.Collections.Generic;

using System;

[Serializable]
public class GlobalEvent : EventCard<ITimeline>
{
    public GlobalEvent(long start_step, long finish_step) : base(start_step, finish_step) { }

    public GlobalEvent(long step) : base(step, step) { }

    // public virtual void DrawEffect(ITimeline tl, long current_step) {}
    // public virtual void EraseEffect(ITimeline tl, long current_step) {}


    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as GlobalEvent;
        return start_step == other.start_step && finish_step == other.finish_step && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
