using System;
using UnityEngine;

public class StunEvent : EventCard<ObjectOfTimeline>
{
    long length = 100;

    public StunEvent(long step, long length) : base(step)
    {
        this.length = length;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        //if (obj.GetTimeline().IsPast())
        // 	return;

        obj.SetStunStatus(StartStep, FinishStep);
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        //if (obj.GetTimeline().IsPast())
        // 	return;

        obj.UnsetStunStatus();
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, length);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as StunEvent;
        return length == other.length
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
