<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>utest/fem/spatial_inertia2d_test.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;termin.fem.inertia2d&nbsp;import&nbsp;SpatialInertia2D<br>
from&nbsp;termin.geombase.pose2&nbsp;import&nbsp;Pose2<br>
<br>
def&nbsp;test_spatial_inertia2d_add():<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Два&nbsp;тела&nbsp;с&nbsp;разными&nbsp;центрами&nbsp;масс<br>
&nbsp;&nbsp;&nbsp;&nbsp;I1&nbsp;=&nbsp;SpatialInertia2D(2.0,&nbsp;1.0,&nbsp;[0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;I2&nbsp;=&nbsp;SpatialInertia2D(3.0,&nbsp;2.0,&nbsp;[1.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;I_sum&nbsp;=&nbsp;I1&nbsp;+&nbsp;I2<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверяем&nbsp;массу<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.isclose(I_sum.m,&nbsp;5.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверяем&nbsp;центр&nbsp;масс<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.allclose(I_sum.c,&nbsp;[0.6,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Проверяем&nbsp;момент&nbsp;инерции&nbsp;с&nbsp;учетом&nbsp;Штейнера<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;I&nbsp;=&nbsp;1&nbsp;+&nbsp;2&nbsp;+&nbsp;2*0^2&nbsp;+&nbsp;3*0.4^2&nbsp;=&nbsp;3&nbsp;+&nbsp;0.48&nbsp;=&nbsp;3.48<br>
&nbsp;&nbsp;&nbsp;&nbsp;d1&nbsp;=&nbsp;np.array([0.0,&nbsp;0.0])&nbsp;-&nbsp;np.array([0.6,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;d2&nbsp;=&nbsp;np.array([1.0,&nbsp;0.0])&nbsp;-&nbsp;np.array([0.6,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;expected_I&nbsp;=&nbsp;1.0&nbsp;+&nbsp;2.0&nbsp;+&nbsp;2.0&nbsp;*&nbsp;np.dot(d1,&nbsp;d1)&nbsp;+&nbsp;3.0&nbsp;*&nbsp;np.dot(d2,&nbsp;d2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.isclose(I_sum.I_com,&nbsp;expected_I)<br>
<br>
def&nbsp;test_spatial_inertia2d_transform():<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Тело&nbsp;с&nbsp;центром&nbsp;масс&nbsp;не&nbsp;в&nbsp;начале<br>
&nbsp;&nbsp;&nbsp;&nbsp;I&nbsp;=&nbsp;SpatialInertia2D(1.0,&nbsp;2.0,&nbsp;[1.0,&nbsp;2.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;Pose2(ang=np.pi/2,&nbsp;lin=np.array([3.0,&nbsp;4.0]))&nbsp;&nbsp;#&nbsp;Поворот&nbsp;на&nbsp;90°&nbsp;и&nbsp;сдвиг<br>
&nbsp;&nbsp;&nbsp;&nbsp;I_tr&nbsp;=&nbsp;I.transform_by(pose)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Центр&nbsp;масс&nbsp;должен&nbsp;повернуться&nbsp;и&nbsp;сместиться<br>
&nbsp;&nbsp;&nbsp;&nbsp;expected_c&nbsp;=&nbsp;pose.transform_point([1.0,&nbsp;2.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.allclose(I_tr.c,&nbsp;expected_c)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Момент&nbsp;инерции&nbsp;не&nbsp;меняется<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.isclose(I_tr.I_com,&nbsp;2.0)<br>
<br>
def&nbsp;test_spatial_inertia2d_zero_mass():<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Сумма&nbsp;двух&nbsp;нулевых&nbsp;масс<br>
&nbsp;&nbsp;&nbsp;&nbsp;I1&nbsp;=&nbsp;SpatialInertia2D(0.0,&nbsp;0.0,&nbsp;[0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;I2&nbsp;=&nbsp;SpatialInertia2D(0.0,&nbsp;0.0,&nbsp;[1.0,&nbsp;1.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;I_sum&nbsp;=&nbsp;I1&nbsp;+&nbsp;I2<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.isclose(I_sum.m,&nbsp;0.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.allclose(I_sum.c,&nbsp;[0.0,&nbsp;0.0])<br>
&nbsp;&nbsp;&nbsp;&nbsp;assert&nbsp;np.isclose(I_sum.I_com,&nbsp;0.0)<br>
<!-- END SCAT CODE -->
</body>
</html>
