<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/glsl_preprocessor.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;GLSL&nbsp;Preprocessor&nbsp;-&nbsp;re-export&nbsp;from&nbsp;C++.&quot;&quot;&quot;<br>
<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;GlslPreprocessor,<br>
&nbsp;&nbsp;&nbsp;&nbsp;glsl_preprocessor,<br>
&nbsp;&nbsp;&nbsp;&nbsp;register_glsl_preprocessor,<br>
)<br>
<br>
<br>
class&nbsp;GlslPreprocessorError(Exception):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Error&nbsp;during&nbsp;GLSL&nbsp;preprocessing.&quot;&quot;&quot;<br>
<br>
<br>
def&nbsp;_glsl_fallback_loader(name:&nbsp;str)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;GLSL&nbsp;include&nbsp;from&nbsp;ResourceManager&nbsp;if&nbsp;not&nbsp;already&nbsp;registered.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native&nbsp;import&nbsp;log<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.resources&nbsp;import&nbsp;ResourceManager<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm&nbsp;=&nbsp;ResourceManager.instance()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;rm.glsl.get_asset(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.error(f&quot;[GlslPreprocessor]&nbsp;Fallback:&nbsp;glsl&nbsp;'{name}'&nbsp;not&nbsp;found&nbsp;in&nbsp;ResourceManager&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset.ensure_loaded()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;glsl_preprocessor().has_include(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.error(f&quot;[GlslPreprocessor]&nbsp;Fallback&nbsp;loader&nbsp;error&nbsp;for&nbsp;GLSL&nbsp;include&nbsp;'{name}':&nbsp;{e}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;False<br>
<br>
<br>
#&nbsp;Set&nbsp;up&nbsp;fallback&nbsp;loader&nbsp;on&nbsp;module&nbsp;import<br>
glsl_preprocessor().set_fallback_loader(_glsl_fallback_loader)<br>
<br>
#&nbsp;Register&nbsp;the&nbsp;preprocessor&nbsp;with&nbsp;the&nbsp;C&nbsp;shader&nbsp;compilation&nbsp;system<br>
#&nbsp;This&nbsp;allows&nbsp;tc_shader_compile_gpu&nbsp;to&nbsp;preprocess&nbsp;#include&nbsp;directives<br>
register_glsl_preprocessor()<br>
<br>
<br>
def&nbsp;preprocess_glsl(source:&nbsp;str,&nbsp;source_name:&nbsp;str&nbsp;=&nbsp;&quot;&lt;unknown&gt;&quot;)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Preprocess&nbsp;GLSL&nbsp;source,&nbsp;resolving&nbsp;#include&nbsp;directives.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Uses&nbsp;the&nbsp;global&nbsp;C++&nbsp;preprocessor&nbsp;instance.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Include&nbsp;files&nbsp;must&nbsp;be&nbsp;registered&nbsp;via&nbsp;glsl_preprocessor().register_include().<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source:&nbsp;GLSL&nbsp;source&nbsp;code<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_name:&nbsp;Name&nbsp;for&nbsp;error&nbsp;messages<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Processed&nbsp;source&nbsp;with&nbsp;includes&nbsp;resolved<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;glsl_preprocessor().preprocess(source,&nbsp;source_name)<br>
<br>
<br>
def&nbsp;has_includes(source:&nbsp;str)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Check&nbsp;if&nbsp;source&nbsp;contains&nbsp;any&nbsp;#include&nbsp;directives.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;GlslPreprocessor.has_includes(source)<br>
<br>
<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GlslPreprocessor&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GlslPreprocessorError&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;glsl_preprocessor&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;preprocess_glsl&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;has_includes&quot;,<br>
]<br>
<!-- END SCAT CODE -->
</body>
</html>
