<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/shader.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Shader&nbsp;wrapper&nbsp;delegating&nbsp;compilation&nbsp;and&nbsp;uniform&nbsp;uploads&nbsp;to&nbsp;a&nbsp;graphics&nbsp;backend.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;pathlib&nbsp;import&nbsp;Path<br>
from&nbsp;typing&nbsp;import&nbsp;Any,&nbsp;Optional<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.visualization.platform.backends&nbsp;import&nbsp;get_default_graphics_backend<br>
from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;GraphicsBackend,&nbsp;ShaderHandle<br>
<br>
<br>
class&nbsp;ShaderCompilationError(RuntimeError):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Raised&nbsp;when&nbsp;GLSL&nbsp;compilation&nbsp;or&nbsp;program&nbsp;linking&nbsp;fails.&quot;&quot;&quot;<br>
<br>
<br>
class&nbsp;ShaderProgram:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;A&nbsp;GLSL&nbsp;shader&nbsp;program&nbsp;(vertex&nbsp;+&nbsp;fragment).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Uniform&nbsp;setters&nbsp;inside&nbsp;the&nbsp;class&nbsp;assume&nbsp;column-major&nbsp;matrices&nbsp;and&nbsp;they&nbsp;set&nbsp;the<br>
&nbsp;&nbsp;&nbsp;&nbsp;combined&nbsp;MVP&nbsp;transform&nbsp;``P&nbsp;*&nbsp;V&nbsp;*&nbsp;M``&nbsp;in&nbsp;homogeneous&nbsp;coordinates.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_source:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fragment_source:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry_source:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.vertex_source&nbsp;=&nbsp;vertex_source<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.fragment_source&nbsp;=&nbsp;fragment_source<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.geometry_source&nbsp;=&nbsp;geometry_source<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._compiled&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle:&nbsp;ShaderHandle&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend:&nbsp;GraphicsBackend&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__post_init__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;default_shader()&nbsp;-&gt;&nbsp;&quot;ShaderProgram&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deprecated&nbsp;alias&nbsp;kept&nbsp;for&nbsp;обратная&nbsp;совместимость.&nbsp;Реальная&nbsp;реализация&nbsp;находится<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;в&nbsp;termin.visualization.render.materials.default_material.default_shader().<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.materials.default_material&nbsp;import&nbsp;default_shader<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;default_shader()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;ensure_ready(self,&nbsp;graphics:&nbsp;GraphicsBackend&nbsp;|&nbsp;None&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._compiled:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;backend&nbsp;=&nbsp;graphics&nbsp;or&nbsp;self._backend&nbsp;or&nbsp;get_default_graphics_backend()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;backend&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;RuntimeError(&quot;Graphics&nbsp;backend&nbsp;is&nbsp;not&nbsp;available&nbsp;for&nbsp;shader&nbsp;compilation.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend&nbsp;=&nbsp;backend<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle&nbsp;=&nbsp;backend.create_shader(self.vertex_source,&nbsp;self.fragment_source,&nbsp;self.geometry_source)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._compiled&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_require_handle(self)&nbsp;-&gt;&nbsp;ShaderHandle:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._handle&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;RuntimeError(&quot;ShaderProgram&nbsp;is&nbsp;not&nbsp;compiled.&nbsp;Call&nbsp;ensure_ready()&nbsp;first.&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._handle<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;use(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;stop(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._handle:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle.stop()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;delete(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._handle:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle.delete()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._handle&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_matrix4(self,&nbsp;name:&nbsp;str,&nbsp;matrix:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Upload&nbsp;a&nbsp;4x4&nbsp;matrix&nbsp;(float32)&nbsp;to&nbsp;uniform&nbsp;``name``.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_matrix4(name,&nbsp;matrix)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_vec2(self,&nbsp;name:&nbsp;str,&nbsp;vector:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_vec2(name,&nbsp;vector)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_vec3(self,&nbsp;name:&nbsp;str,&nbsp;vector:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_vec3(name,&nbsp;vector)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_vec4(self,&nbsp;name:&nbsp;str,&nbsp;vector:&nbsp;np.ndarray):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_vec4(name,&nbsp;vector)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_float(self,&nbsp;name:&nbsp;str,&nbsp;value:&nbsp;float):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_float(name,&nbsp;value)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_int(self,&nbsp;name:&nbsp;str,&nbsp;value:&nbsp;int):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._require_handle().set_uniform_int(name,&nbsp;value)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_uniform_auto(self,&nbsp;name:&nbsp;str,&nbsp;value:&nbsp;Any):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Best-effort&nbsp;setter&nbsp;that&nbsp;infers&nbsp;uniform&nbsp;type&nbsp;based&nbsp;on&nbsp;``value``.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(value,&nbsp;(list,&nbsp;tuple,&nbsp;np.ndarray)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arr&nbsp;=&nbsp;np.asarray(value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;arr.shape&nbsp;==&nbsp;(4,&nbsp;4):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_matrix4(name,&nbsp;arr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;arr.shape&nbsp;==&nbsp;(2,):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_vec2(name,&nbsp;arr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;arr.shape&nbsp;==&nbsp;(3,):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_vec3(name,&nbsp;arr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;arr.shape&nbsp;==&nbsp;(4,):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_vec4(name,&nbsp;arr)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;ValueError(f&quot;Unsupported&nbsp;uniform&nbsp;array&nbsp;shape&nbsp;for&nbsp;{name}:&nbsp;{arr.shape}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;isinstance(value,&nbsp;bool):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_int(name,&nbsp;int(value))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;isinstance(value,&nbsp;int):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_int(name,&nbsp;value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.set_uniform_float(name,&nbsp;float(value))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@classmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;from_files(cls,&nbsp;vertex_path:&nbsp;str&nbsp;|&nbsp;Path,&nbsp;fragment_path:&nbsp;str&nbsp;|&nbsp;Path)&nbsp;-&gt;&nbsp;&quot;ShaderProgram&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_source&nbsp;=&nbsp;Path(vertex_path).read_text(encoding=&quot;utf-8&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fragment_source&nbsp;=&nbsp;Path(fragment_path).read_text(encoding=&quot;utf-8&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;cls(vertex_source=vertex_source,&nbsp;fragment_source=fragment_source)<br>
<!-- END SCAT CODE -->
</body>
</html>
