<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/view.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
RenderView&nbsp;—&nbsp;описание&nbsp;&quot;что&nbsp;рендерим&quot;&nbsp;без&nbsp;привязки&nbsp;к&nbsp;конкретному&nbsp;окну.<br>
<br>
RenderView&nbsp;содержит:<br>
-&nbsp;scene:&nbsp;сцена&nbsp;с&nbsp;объектами<br>
-&nbsp;camera:&nbsp;камера&nbsp;(CameraComponent)<br>
-&nbsp;rect:&nbsp;нормализованный&nbsp;прямоугольник&nbsp;[0..1]&nbsp;внутри&nbsp;целевой&nbsp;поверхности<br>
-&nbsp;pipeline:&nbsp;конвейер&nbsp;рендеринга<br>
<br>
RenderView&nbsp;НЕ&nbsp;содержит:<br>
-&nbsp;fbos&nbsp;(это&nbsp;ViewportRenderState)<br>
-&nbsp;ссылки&nbsp;на&nbsp;Window<br>
<br>
Это&nbsp;позволяет&nbsp;использовать&nbsp;один&nbsp;RenderView&nbsp;для&nbsp;разных&nbsp;целей:<br>
-&nbsp;рендер&nbsp;в&nbsp;окно<br>
-&nbsp;offscreen&nbsp;рендер<br>
-&nbsp;рендер&nbsp;в&nbsp;текстуру&nbsp;для&nbsp;превью<br>
<br>
Формула&nbsp;преобразования&nbsp;rect&nbsp;→&nbsp;пиксели:<br>
&nbsp;&nbsp;&nbsp;&nbsp;px&nbsp;=&nbsp;rect.x&nbsp;*&nbsp;surface_width<br>
&nbsp;&nbsp;&nbsp;&nbsp;py&nbsp;=&nbsp;rect.y&nbsp;*&nbsp;surface_height<br>
&nbsp;&nbsp;&nbsp;&nbsp;pw&nbsp;=&nbsp;rect.w&nbsp;*&nbsp;surface_width<br>
&nbsp;&nbsp;&nbsp;&nbsp;ph&nbsp;=&nbsp;rect.h&nbsp;*&nbsp;surface_height<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;dataclasses&nbsp;import&nbsp;dataclass<br>
from&nbsp;typing&nbsp;import&nbsp;TYPE_CHECKING,&nbsp;Optional,&nbsp;Tuple<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.scene&nbsp;import&nbsp;Scene<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.camera&nbsp;import&nbsp;CameraComponent<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.viewport&nbsp;import&nbsp;Viewport<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.framegraph&nbsp;import&nbsp;RenderPipeline<br>
<br>
<br>
@dataclass<br>
class&nbsp;RenderView:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Описание&nbsp;&quot;что&nbsp;рендерим&quot;&nbsp;для&nbsp;RenderEngine.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Атрибуты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene:&nbsp;Сцена&nbsp;с&nbsp;объектами&nbsp;для&nbsp;рендеринга.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;camera:&nbsp;Камера,&nbsp;определяющая&nbsp;точку&nbsp;зрения.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rect:&nbsp;Нормализованный&nbsp;прямоугольник&nbsp;(x,&nbsp;y,&nbsp;w,&nbsp;h)&nbsp;в&nbsp;[0..1].<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(0,0)&nbsp;—&nbsp;левый&nbsp;нижний&nbsp;угол,&nbsp;(1,1)&nbsp;—&nbsp;правый&nbsp;верхний.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pipeline:&nbsp;Конвейер&nbsp;рендеринга.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layer_mask:&nbsp;Маска&nbsp;слоёв&nbsp;(какие&nbsp;entity&nbsp;рендерить).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;viewport:&nbsp;Опциональный&nbsp;Viewport&nbsp;(для&nbsp;доступа&nbsp;к&nbsp;internal_entities).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene:&nbsp;&quot;Scene&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera:&nbsp;&quot;CameraComponent&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;rect:&nbsp;Tuple[float,&nbsp;float,&nbsp;float,&nbsp;float]&nbsp;=&nbsp;(0.0,&nbsp;0.0,&nbsp;1.0,&nbsp;1.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;pipeline:&nbsp;Optional[&quot;RenderPipeline&quot;]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;layer_mask:&nbsp;int&nbsp;=&nbsp;0xFFFFFFFFFFFFFFFF<br>
&nbsp;&nbsp;&nbsp;&nbsp;viewport:&nbsp;Optional[&quot;Viewport&quot;]&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;compute_pixel_rect(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_width:&nbsp;int,&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_height:&nbsp;int<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int,&nbsp;int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Вычисляет&nbsp;прямоугольник&nbsp;в&nbsp;пикселях&nbsp;для&nbsp;заданного&nbsp;размера&nbsp;поверхности.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Формула:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;px&nbsp;=&nbsp;rect.x&nbsp;*&nbsp;width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py&nbsp;=&nbsp;rect.y&nbsp;*&nbsp;height&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pw&nbsp;=&nbsp;rect.w&nbsp;*&nbsp;width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ph&nbsp;=&nbsp;rect.h&nbsp;*&nbsp;height<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_width:&nbsp;Ширина&nbsp;поверхности&nbsp;в&nbsp;пикселях.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;surface_height:&nbsp;Высота&nbsp;поверхности&nbsp;в&nbsp;пикселях.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Кортеж&nbsp;(px,&nbsp;py,&nbsp;pw,&nbsp;ph)&nbsp;—&nbsp;позиция&nbsp;и&nbsp;размер&nbsp;в&nbsp;пикселях.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vx,&nbsp;vy,&nbsp;vw,&nbsp;vh&nbsp;=&nbsp;self.rect<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;px&nbsp;=&nbsp;int(vx&nbsp;*&nbsp;surface_width)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py&nbsp;=&nbsp;int(vy&nbsp;*&nbsp;surface_height)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pw&nbsp;=&nbsp;max(1,&nbsp;int(vw&nbsp;*&nbsp;surface_width))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ph&nbsp;=&nbsp;max(1,&nbsp;int(vh&nbsp;*&nbsp;surface_height))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(px,&nbsp;py,&nbsp;pw,&nbsp;ph)<br>
<!-- END SCAT CODE -->
</body>
</html>
