<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/materials/shaders/solid_color.shader</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
@program&nbsp;SolidColor<br>
<br>
@phase&nbsp;opaque<br>
@priority&nbsp;0<br>
@glDepthTest&nbsp;true<br>
@glDepthMask&nbsp;true<br>
@glCull&nbsp;true<br>
<br>
@property&nbsp;Color&nbsp;u_color&nbsp;=&nbsp;Color(0.8,&nbsp;0.2,&nbsp;0.2,&nbsp;1.0)<br>
<br>
@stage&nbsp;vertex<br>
#version&nbsp;330&nbsp;core<br>
<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_normal;<br>
out&nbsp;vec3&nbsp;v_world_pos;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec4&nbsp;world&nbsp;=&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_world_pos&nbsp;=&nbsp;world.xyz;<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(transpose(inverse(u_model)))&nbsp;*&nbsp;a_normal;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;world;<br>
}<br>
@endstage<br>
<br>
@stage&nbsp;fragment<br>
#version&nbsp;330&nbsp;core<br>
<br>
in&nbsp;vec3&nbsp;v_normal;<br>
in&nbsp;vec3&nbsp;v_world_pos;<br>
<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;N&nbsp;=&nbsp;normalize(v_normal);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;lightDir&nbsp;=&nbsp;normalize(vec3(1.0,&nbsp;1.0,&nbsp;1.0));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;ambient&nbsp;=&nbsp;0.3;<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;diffuse&nbsp;=&nbsp;max(dot(N,&nbsp;lightDir),&nbsp;0.0)&nbsp;*&nbsp;0.7;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;u_color.rgb&nbsp;*&nbsp;(ambient&nbsp;+&nbsp;diffuse);<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color,&nbsp;u_color.a);<br>
}<br>
@endstage<br>
<br>
@endphase<br>
<!-- END SCAT CODE -->
</body>
</html>
