using System;
using System.Collections.Generic;
using UnityEngine;

public class ChangeSearchStrategyStatus_PointChecked : StrategyEvent
{
    Vector3 pnt;

    public ChangeSearchStrategyStatus_PointChecked(long step, Vector3 vec) : base(step)
    {
        pnt = vec;
    }

    public override void on_forward_enter(long step, ObjectOfTimeline priv)
    {
        var strategy = Strategy(priv);
        int point_index = strategy.GetPointIndex(pnt);
        strategy.SetPointChecked(point_index, true);
    }

    public override void on_backward_leave(long step, ObjectOfTimeline priv)
    {
        var strategy = Strategy(priv);
        int point_index = strategy.GetPointIndex(pnt);
        strategy.SetPointChecked(point_index, false);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, pnt);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ChangeSearchStrategyStatus_PointChecked;
        return pnt == other.pnt
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
