public class ChangeAiEnabledCard : EventCard<ObjectOfTimeline>
{
    private ObjectId actor_name;
    bool prev_ai_state;
    bool new_ai_state;

    public ChangeAiEnabledCard(
        ObjectOfTimeline host_actor,
        long step,
        bool prev_ai_state,
        bool new_ai_state
    ) : base(step)
    {
        actor_name = host_actor.ObjectId();
        this.prev_ai_state = prev_ai_state;
        this.new_ai_state = new_ai_state;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj)
    {
        obj.EnableAi(new_ai_state);
    }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj)
    {
        obj.EnableAi(prev_ai_state);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, actor_name);
        result = FieldScanner.ModifyHash(result, prev_ai_state);
        result = FieldScanner.ModifyHash(result, new_ai_state);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as ChangeAiEnabledCard;
        return actor_name == other.actor_name
            && prev_ai_state == other.prev_ai_state
            && new_ai_state == other.new_ai_state
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
