public class EnableAiControllerEvent : EventCard<ObjectOfTimeline>
{
    bool enabled;

    public EnableAiControllerEvent(long step, bool en) : base(step)
    {
        this.enabled = en;
    }

    public override void on_forward_enter(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        var ai_controller = obj.AiController();
        if (ai_controller != null)
            ai_controller.SetEnabled(enabled);
    }

    public override void on_backward_leave(global::System.Int64 current_step, ObjectOfTimeline obj)
    {
        var ai_controller = obj.AiController();
        if (ai_controller != null)
            ai_controller.SetEnabled(!enabled);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, enabled);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as EnableAiControllerEvent;
        return enabled == other.enabled
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
