public class FoundCorpseAlarmSource : AlarmSource
{
    public ObjectId corpse;

    public FoundCorpseAlarmSource(long start_step, long final_step, ObjectId corpse)
        : base(start_step, final_step)
    {
        this.corpse = corpse;
    }

    public bool IsEqual(FoundCorpseAlarmSource other)
    {
        return corpse == other.corpse && base.IsEqual(other);
    }

    public override ReferencedPoint Center(ITimeline tl)
    {
        return tl.GetObject(corpse).CurrentReferencedPoint();
    }

    public override bool IsHighLevelAlarm()
    {
        return true;
    }

    public override bool IsCorpseReaction() => true;

    public override void on_forward_enter(long current_step, AttentionModule module)
    {
        //module.AddFoundedCorpse(current_step, corpse);
    }

    public override void on_backward_leave(long current_step, AttentionModule module)
    {
        //module.ForgetCorpse(corpse);
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, corpse);
        result = FieldScanner.ModifyHash(result, lures);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as FoundCorpseAlarmSource;
        return corpse == other.corpse
            && lures == other.lures
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
