public class LoudSoundAlarmSource : AlarmSource
{
    public ReferencedPoint center;

    public LoudSoundAlarmSource(
        long start_step,
        long final_step,
        ReferencedPoint center,
        bool lures = false
    ) : base(start_step, final_step)
    {
        this.center = center;
        this.lures = lures;
    }

    public bool IsEqual(LoudSoundAlarmSource other)
    {
        return center == other.center && lures == other.lures && base.IsEqual(other);
    }

    public bool Lures => lures;

    public override ReferencedPoint Center(ITimeline tl)
    {
        return center;
    }

    public override bool IsHighLevelAlarm()
    {
        return false;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, center);
        result = FieldScanner.ModifyHash(result, lures);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as LoudSoundAlarmSource;
        return center == other.center
            && lures == other.lures
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
