public class StrategyEvent : EventCard<ObjectOfTimeline>
{
    public StrategyEvent(long step) : base(step) { }

    public StrategyEvent(long sstep, long fstep) : base(sstep, fstep) { }

    public SearchStrategy Strategy(ObjectOfTimeline priv)
    {
        var group = priv as GroupController;
        return group.GetStrategy() as SearchStrategy;
    }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as StrategyEvent;
        return start_step == other.start_step && finish_step == other.finish_step && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}
