<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/platform/backends/nop_window.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
from&nbsp;typing&nbsp;import&nbsp;Any,&nbsp;Optional,&nbsp;Tuple<br>
from&nbsp;.base&nbsp;import&nbsp;BackendWindow,&nbsp;WindowBackend<br>
<br>
class&nbsp;NOPWindowHandle(BackendWindow):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Псевдо-окно:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;имеет&nbsp;размеры;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;хранит&nbsp;курсор;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;умеет&nbsp;закрываться;<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;хранит&nbsp;коллбеки,&nbsp;но&nbsp;сам&nbsp;их&nbsp;не&nbsp;вызывает.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;width:&nbsp;int,&nbsp;height:&nbsp;int,&nbsp;title:&nbsp;str,&nbsp;share:&nbsp;Optional[BackendWindow]&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._width&nbsp;=&nbsp;width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._height&nbsp;=&nbsp;height<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._closed&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._user_ptr:&nbsp;Any&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._cursor_x:&nbsp;float&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._cursor_y:&nbsp;float&nbsp;=&nbsp;0.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Коллбеки,&nbsp;чтобы&nbsp;Window&nbsp;мог&nbsp;их&nbsp;установить<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._framebuffer_callback&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._cursor_callback&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scroll_callback&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mouse_callback&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._key_callback&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;BackendWindow&nbsp;API&nbsp;----------------------------------------------<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;close(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._closed&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;should_close(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._closed&nbsp;is&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;make_current(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нет&nbsp;реального&nbsp;контекста,&nbsp;просто&nbsp;заглушка<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;swap_buffers(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ничего&nbsp;не&nbsp;свапаем<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;framebuffer_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._width,&nbsp;self._height<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;window_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._width,&nbsp;self._height<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_cursor_pos(self)&nbsp;-&gt;&nbsp;Tuple[float,&nbsp;float]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._cursor_x,&nbsp;self._cursor_y<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_should_close(self,&nbsp;flag:&nbsp;bool):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;flag:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._closed&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_user_pointer(self,&nbsp;ptr:&nbsp;Any):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._user_ptr&nbsp;=&nbsp;ptr<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_framebuffer_size_callback(self,&nbsp;callback):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._framebuffer_callback&nbsp;=&nbsp;callback<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_cursor_pos_callback(self,&nbsp;callback):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._cursor_callback&nbsp;=&nbsp;callback<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_scroll_callback(self,&nbsp;callback):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._scroll_callback&nbsp;=&nbsp;callback<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_mouse_button_callback(self,&nbsp;callback):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mouse_callback&nbsp;=&nbsp;callback<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_key_callback(self,&nbsp;callback):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._key_callback&nbsp;=&nbsp;callback<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;drives_render()&nbsp;оставляем&nbsp;по&nbsp;умолчанию&nbsp;(из&nbsp;базового&nbsp;класса),<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;то&nbsp;есть&nbsp;False:&nbsp;движок&nbsp;сам&nbsp;будет&nbsp;вызывать&nbsp;render().<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Если&nbsp;хочешь&nbsp;симулировать&nbsp;push-модель,&nbsp;можно&nbsp;сделать&nbsp;здесь&nbsp;True.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_window_framebuffer(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нет&nbsp;реального&nbsp;фреймбуфера,&nbsp;просто&nbsp;заглушка<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;request_update(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нечего&nbsp;обновлять<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
<br>
class&nbsp;NOPWindowBackend(WindowBackend):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Оконный&nbsp;бэкенд&nbsp;без&nbsp;настоящих&nbsp;окон&nbsp;(удобно&nbsp;для&nbsp;тестов).&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;create_window(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share:&nbsp;Optional[Any]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;NOPWindowHandle:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;NOPWindowHandle(width,&nbsp;height,&nbsp;title,&nbsp;share=share)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;poll_events(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Событий&nbsp;нет,&nbsp;всё&nbsp;молчит<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;terminate(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нечего&nbsp;завершать<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<!-- END SCAT CODE -->
</body>
</html>
