<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/platform/backends/sdl.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;SDL2-based&nbsp;window&nbsp;backend&nbsp;using&nbsp;C++&nbsp;implementation.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;Any,&nbsp;Callable,&nbsp;Optional,&nbsp;Tuple<br>
<br>
from&nbsp;termin._native.platform&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;SDLWindow,<br>
&nbsp;&nbsp;&nbsp;&nbsp;SDLWindowBackend&nbsp;as&nbsp;_SDLWindowBackend,<br>
)<br>
from&nbsp;termin.graphics&nbsp;import&nbsp;OpenGLGraphicsBackend<br>
<br>
from&nbsp;.base&nbsp;import&nbsp;Action,&nbsp;BackendWindow,&nbsp;Key,&nbsp;MouseButton,&nbsp;WindowBackend<br>
<br>
<br>
def&nbsp;_translate_mouse_button(button:&nbsp;int)&nbsp;-&gt;&nbsp;MouseButton:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Convert&nbsp;C++&nbsp;button&nbsp;constant&nbsp;to&nbsp;Python&nbsp;enum.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;button&nbsp;==&nbsp;SDLWindow.MOUSE_BUTTON_LEFT:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;MouseButton.LEFT<br>
&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;button&nbsp;==&nbsp;SDLWindow.MOUSE_BUTTON_RIGHT:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;MouseButton.RIGHT<br>
&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;button&nbsp;==&nbsp;SDLWindow.MOUSE_BUTTON_MIDDLE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;MouseButton.MIDDLE<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;MouseButton.LEFT<br>
<br>
<br>
def&nbsp;_translate_action(action:&nbsp;int)&nbsp;-&gt;&nbsp;Action:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Convert&nbsp;C++&nbsp;action&nbsp;constant&nbsp;to&nbsp;Python&nbsp;enum.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;action&nbsp;==&nbsp;SDLWindow.ACTION_RELEASE:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Action.RELEASE<br>
&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;action&nbsp;==&nbsp;SDLWindow.ACTION_PRESS:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Action.PRESS<br>
&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;action&nbsp;==&nbsp;SDLWindow.ACTION_REPEAT:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Action.REPEAT<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Action.PRESS<br>
<br>
<br>
def&nbsp;_translate_key(keycode:&nbsp;int)&nbsp;-&gt;&nbsp;Key:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Convert&nbsp;SDL&nbsp;keycode&nbsp;to&nbsp;Python&nbsp;Key&nbsp;enum.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Special&nbsp;keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;keycode&nbsp;==&nbsp;27:&nbsp;&nbsp;#&nbsp;SDLK_ESCAPE<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Key.ESCAPE<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;keycode&nbsp;==&nbsp;32:&nbsp;&nbsp;#&nbsp;SDLK_SPACE<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Key.SPACE<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;ASCII&nbsp;keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;0&nbsp;&lt;=&nbsp;keycode&nbsp;&lt;&nbsp;128:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Key(keycode)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;ValueError:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;Key.UNKNOWN<br>
<br>
<br>
class&nbsp;SDLWindowHandle(BackendWindow):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;SDL2&nbsp;window&nbsp;wrapper&nbsp;using&nbsp;C++&nbsp;SDLWindow.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share:&nbsp;Optional[BackendWindow]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics:&nbsp;Optional[OpenGLGraphicsBackend]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share_win&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;share&nbsp;is&nbsp;not&nbsp;None&nbsp;and&nbsp;isinstance(share,&nbsp;SDLWindowHandle):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share_win&nbsp;=&nbsp;share._window<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window&nbsp;=&nbsp;SDLWindow(width,&nbsp;height,&nbsp;title,&nbsp;share_win)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;graphics&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_graphics(graphics)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Python&nbsp;callbacks<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_framebuffer_size_callback:&nbsp;Optional[Callable]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_cursor_pos_callback:&nbsp;Optional[Callable]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_scroll_callback:&nbsp;Optional[Callable]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_mouse_button_callback:&nbsp;Optional[Callable]&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_key_callback:&nbsp;Optional[Callable]&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._user_pointer:&nbsp;Any&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;close(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.close()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;should_close(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.should_close()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;make_current(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.make_current()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;swap_buffers(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.swap_buffers()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;framebuffer_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.framebuffer_size()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;window_size(self)&nbsp;-&gt;&nbsp;Tuple[int,&nbsp;int]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.window_size()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_cursor_pos(self)&nbsp;-&gt;&nbsp;Tuple[float,&nbsp;float]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.get_cursor_pos()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_should_close(self,&nbsp;flag:&nbsp;bool)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_should_close(flag)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_user_pointer(self,&nbsp;ptr:&nbsp;Any)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._user_pointer&nbsp;=&nbsp;ptr<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_graphics(self,&nbsp;graphics:&nbsp;OpenGLGraphicsBackend)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;graphics&nbsp;backend&nbsp;for&nbsp;framebuffer&nbsp;creation.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_graphics(graphics)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_framebuffer_size_callback(self,&nbsp;callback:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_framebuffer_size_callback&nbsp;=&nbsp;callback<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callback&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_framebuffer_size_callback(None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;wrapper(win,&nbsp;w,&nbsp;h):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback(self,&nbsp;w,&nbsp;h)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_framebuffer_size_callback(wrapper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_cursor_pos_callback(self,&nbsp;callback:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_cursor_pos_callback&nbsp;=&nbsp;callback<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callback&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_cursor_pos_callback(None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;wrapper(win,&nbsp;x,&nbsp;y):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback(self,&nbsp;x,&nbsp;y)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_cursor_pos_callback(wrapper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_scroll_callback(self,&nbsp;callback:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_scroll_callback&nbsp;=&nbsp;callback<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callback&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_scroll_callback(None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;wrapper(win,&nbsp;x,&nbsp;y,&nbsp;mods):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback(self,&nbsp;x,&nbsp;y,&nbsp;mods)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_scroll_callback(wrapper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_mouse_button_callback(self,&nbsp;callback:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_mouse_button_callback&nbsp;=&nbsp;callback<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callback&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_mouse_button_callback(None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;wrapper(win,&nbsp;button,&nbsp;action,&nbsp;mods):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py_button&nbsp;=&nbsp;_translate_mouse_button(button)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py_action&nbsp;=&nbsp;_translate_action(action)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback(self,&nbsp;py_button,&nbsp;py_action,&nbsp;mods)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_mouse_button_callback(wrapper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_key_callback(self,&nbsp;callback:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._py_key_callback&nbsp;=&nbsp;callback<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;callback&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_key_callback(None)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;wrapper(win,&nbsp;key,&nbsp;scancode,&nbsp;action,&nbsp;mods):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py_key&nbsp;=&nbsp;_translate_key(key)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;py_action&nbsp;=&nbsp;_translate_action(action)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback(self,&nbsp;py_key,&nbsp;scancode,&nbsp;py_action,&nbsp;mods)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._window.set_key_callback(wrapper)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;request_update(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass&nbsp;&nbsp;#&nbsp;SDL&nbsp;uses&nbsp;pull&nbsp;model<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_window_framebuffer(self)&nbsp;-&gt;&nbsp;Any:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.get_window_framebuffer()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_window_id(self)&nbsp;-&gt;&nbsp;int:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._window.get_window_id()<br>
<br>
<br>
class&nbsp;SDLWindowBackend(WindowBackend):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;SDL2&nbsp;window&nbsp;backend&nbsp;using&nbsp;C++&nbsp;implementation.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;graphics:&nbsp;Optional[OpenGLGraphicsBackend]&nbsp;=&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend&nbsp;=&nbsp;_SDLWindowBackend()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._graphics&nbsp;=&nbsp;graphics<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._windows:&nbsp;dict[int,&nbsp;SDLWindowHandle]&nbsp;=&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_graphics(self,&nbsp;graphics:&nbsp;OpenGLGraphicsBackend)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;graphics&nbsp;backend&nbsp;for&nbsp;new&nbsp;windows.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._graphics&nbsp;=&nbsp;graphics<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;create_window(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height:&nbsp;int,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title:&nbsp;str,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share:&nbsp;Optional[BackendWindow]&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;SDLWindowHandle:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;window&nbsp;=&nbsp;SDLWindowHandle(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width,&nbsp;height,&nbsp;title,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;share=share,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics=self._graphics,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._windows[window.get_window_id()]&nbsp;=&nbsp;window<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;window<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;poll_events(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend.poll_events()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Clean&nbsp;up&nbsp;closed&nbsp;windows<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;closed_ids&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wid&nbsp;for&nbsp;wid,&nbsp;win&nbsp;in&nbsp;self._windows.items()&nbsp;if&nbsp;win.should_close()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;wid&nbsp;in&nbsp;closed_ids:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;self._windows[wid]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;terminate(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;win&nbsp;in&nbsp;list(self._windows.values()):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;win.close()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._windows.clear()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._backend.terminate()<br>
<!-- END SCAT CODE -->
</body>
</html>
