<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/loaders/fbx_loader.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
#&nbsp;termin/loaders/fbx_loader.py<br>
&quot;&quot;&quot;FBX&nbsp;loader&nbsp;using&nbsp;ufbx&nbsp;library.<br>
<br>
UFBX&nbsp;QUIRKS&nbsp;AND&nbsp;LIMITATIONS&nbsp;(discovered&nbsp;2025-12):<br>
=================================================<br>
<br>
1.&nbsp;SINGLE-PASS&nbsp;ITERATION&nbsp;ONLY<br>
&nbsp;&nbsp;&nbsp;ufbx&nbsp;crashes&nbsp;(segfault)&nbsp;if&nbsp;you&nbsp;iterate&nbsp;over&nbsp;the&nbsp;same&nbsp;collection&nbsp;twice,<br>
&nbsp;&nbsp;&nbsp;or&nbsp;iterate&nbsp;over&nbsp;different&nbsp;collections&nbsp;in&nbsp;certain&nbsp;orders.<br>
<br>
&nbsp;&nbsp;&nbsp;BAD&nbsp;(crashes):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mesh&nbsp;in&nbsp;scene.meshes:&nbsp;...<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mesh&nbsp;in&nbsp;scene.meshes:&nbsp;...&nbsp;&nbsp;#&nbsp;Second&nbsp;iteration&nbsp;=&nbsp;segfault<br>
<br>
&nbsp;&nbsp;&nbsp;BAD&nbsp;(crashes):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mesh&nbsp;in&nbsp;scene.meshes:&nbsp;...<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;node&nbsp;in&nbsp;scene.nodes:&nbsp;...&nbsp;&nbsp;&nbsp;#&nbsp;Wrong&nbsp;order&nbsp;=&nbsp;segfault<br>
<br>
&nbsp;&nbsp;&nbsp;GOOD:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;node&nbsp;in&nbsp;nodes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;node.mesh:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;process(node.mesh)&nbsp;&nbsp;#&nbsp;Access&nbsp;mesh&nbsp;through&nbsp;node&nbsp;in&nbsp;single&nbsp;pass<br>
<br>
2.&nbsp;ACCESS&nbsp;ORDER&nbsp;MATTERS<br>
&nbsp;&nbsp;&nbsp;Safe&nbsp;order:&nbsp;nodes&nbsp;-&gt;&nbsp;meshes&nbsp;(through&nbsp;nodes)&nbsp;-&gt;&nbsp;materials<br>
&nbsp;&nbsp;&nbsp;The&nbsp;only&nbsp;reliable&nbsp;way&nbsp;is&nbsp;to&nbsp;extract&nbsp;ALL&nbsp;mesh&nbsp;data&nbsp;while&nbsp;traversing&nbsp;nodes.<br>
<br>
3.&nbsp;NO&nbsp;as_triangles()&nbsp;METHOD<br>
&nbsp;&nbsp;&nbsp;Despite&nbsp;what&nbsp;some&nbsp;docs&nbsp;suggest,&nbsp;ufbx.Mesh&nbsp;has&nbsp;no&nbsp;as_triangles()&nbsp;method.<br>
&nbsp;&nbsp;&nbsp;Triangulation&nbsp;must&nbsp;be&nbsp;done&nbsp;manually&nbsp;using&nbsp;face.index_begin&nbsp;and&nbsp;face.num_indices.<br>
<br>
4.&nbsp;UV&nbsp;DATA&nbsp;LOCATION<br>
&nbsp;&nbsp;&nbsp;UVs&nbsp;are&nbsp;NOT&nbsp;in&nbsp;uv_sets[0].values&nbsp;directly.<br>
&nbsp;&nbsp;&nbsp;Correct&nbsp;path:&nbsp;mesh.uv_sets[0].vertex_uv.values&nbsp;and&nbsp;.indices<br>
<br>
5.&nbsp;TRANSFORM&nbsp;IS&nbsp;TRS,&nbsp;NOT&nbsp;MATRIX<br>
&nbsp;&nbsp;&nbsp;node.local_transform&nbsp;contains&nbsp;.translation,&nbsp;.rotation&nbsp;(quaternion),&nbsp;.scale<br>
&nbsp;&nbsp;&nbsp;NOT&nbsp;a&nbsp;4x4&nbsp;matrix&nbsp;with&nbsp;m00,&nbsp;m01,&nbsp;etc.<br>
<br>
6.&nbsp;LIST&nbsp;OBJECTS&nbsp;DON'T&nbsp;SUPPORT&nbsp;SLICING<br>
&nbsp;&nbsp;&nbsp;ufbx&nbsp;lists&nbsp;(Vec3List,&nbsp;Uint32List,&nbsp;etc.)&nbsp;don't&nbsp;support&nbsp;slice&nbsp;syntax&nbsp;[:10].<br>
&nbsp;&nbsp;&nbsp;Use&nbsp;index&nbsp;access&nbsp;in&nbsp;a&nbsp;loop&nbsp;instead.<br>
<br>
7.&nbsp;ALTERNATIVE&nbsp;LIBRARIES<br>
&nbsp;&nbsp;&nbsp;-&nbsp;pyassimp:&nbsp;Also&nbsp;crashes&nbsp;on&nbsp;complex&nbsp;FBX&nbsp;files&nbsp;with&nbsp;bones&nbsp;(NULL&nbsp;pointer&nbsp;access)<br>
&nbsp;&nbsp;&nbsp;-&nbsp;trimesh:&nbsp;Doesn't&nbsp;support&nbsp;FBX&nbsp;directly<br>
&nbsp;&nbsp;&nbsp;-&nbsp;Consider&nbsp;converting&nbsp;FBX&nbsp;to&nbsp;glTF&nbsp;externally&nbsp;for&nbsp;more&nbsp;reliable&nbsp;loading<br>
<br>
8.&nbsp;TEXTURE&nbsp;EXTRACTION<br>
&nbsp;&nbsp;&nbsp;Do&nbsp;NOT&nbsp;iterate&nbsp;scene.textures&nbsp;separately&nbsp;-&nbsp;it&nbsp;causes&nbsp;segfault.<br>
&nbsp;&nbsp;&nbsp;Extract&nbsp;texture&nbsp;data&nbsp;while&nbsp;iterating&nbsp;materials&nbsp;(via&nbsp;mat.pbr.base_color.texture).<br>
&nbsp;&nbsp;&nbsp;Embedded&nbsp;texture&nbsp;content&nbsp;is&nbsp;in&nbsp;tex.content&nbsp;with&nbsp;tex.content_size&nbsp;bytes.<br>
&quot;&quot;&quot;<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
import&nbsp;ufbx<br>
<br>
from&nbsp;termin._native&nbsp;import&nbsp;log<br>
<br>
<br>
class&nbsp;FBXMeshData:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;vertices,&nbsp;normals,&nbsp;uvs,&nbsp;indices,&nbsp;material_index):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.vertices&nbsp;=&nbsp;vertices<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.normals&nbsp;=&nbsp;normals<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.uvs&nbsp;=&nbsp;uvs<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.indices&nbsp;=&nbsp;indices<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.material_index&nbsp;=&nbsp;material_index<br>
<br>
<br>
class&nbsp;FBXTcTexture:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Holds&nbsp;texture&nbsp;data&nbsp;extracted&nbsp;from&nbsp;FBX.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;filename,&nbsp;content=None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.filename&nbsp;=&nbsp;filename&nbsp;&nbsp;#&nbsp;Original&nbsp;filename&nbsp;from&nbsp;FBX<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.content&nbsp;=&nbsp;content&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Raw&nbsp;bytes&nbsp;(PNG/JPG&nbsp;data)&nbsp;if&nbsp;embedded<br>
<br>
<br>
class&nbsp;FBXMaterialData:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;diffuse_color=None,&nbsp;diffuse_texture=None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.diffuse_color&nbsp;=&nbsp;diffuse_color<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.diffuse_texture&nbsp;=&nbsp;diffuse_texture&nbsp;&nbsp;#&nbsp;Texture&nbsp;filename/path<br>
<br>
<br>
class&nbsp;FBXNodeData:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;children=None,&nbsp;mesh_indices=None,&nbsp;transform=None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.children&nbsp;=&nbsp;children&nbsp;or&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.mesh_indices&nbsp;=&nbsp;mesh_indices&nbsp;or&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.transform&nbsp;=&nbsp;transform<br>
<br>
<br>
class&nbsp;FBXAnimationChannel:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;node_name,&nbsp;pos_keys,&nbsp;rot_keys,&nbsp;scale_keys):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.node_name&nbsp;=&nbsp;node_name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.pos_keys&nbsp;=&nbsp;pos_keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.rot_keys&nbsp;=&nbsp;rot_keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.scale_keys&nbsp;=&nbsp;scale_keys<br>
<br>
<br>
class&nbsp;FBXAnimationClip:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name,&nbsp;duration,&nbsp;tps,&nbsp;channels):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.duration&nbsp;=&nbsp;duration<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.ticks_per_second&nbsp;=&nbsp;tps<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.channels&nbsp;=&nbsp;channels<br>
<br>
<br>
class&nbsp;FBXSceneData:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.meshes&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.materials&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.textures&nbsp;=&nbsp;[]&nbsp;&nbsp;#&nbsp;FBXTcTexture&nbsp;list&nbsp;(embedded&nbsp;textures)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.root&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.animations&nbsp;=&nbsp;[]<br>
<br>
<br>
#&nbsp;----------&nbsp;PARSER&nbsp;HELPERS&nbsp;----------<br>
<br>
def&nbsp;_parse_materials(scene,&nbsp;out):<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mat&nbsp;in&nbsp;scene.materials:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name&nbsp;=&nbsp;mat.name&nbsp;if&nbsp;mat.name&nbsp;else&nbsp;&quot;Material&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat.pbr.base_color.has_value:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;=&nbsp;mat.pbr.base_color.value_vec4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color&nbsp;=&nbsp;np.array([c.x,&nbsp;c.y,&nbsp;c.z,&nbsp;c.w],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat.pbr.base_color.texture:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex&nbsp;=&nbsp;mat.pbr.base_color.texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex.filename:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture&nbsp;=&nbsp;tex.filename<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out.materials.append(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FBXMaterialData(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color=diffuse_color,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture=diffuse_texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
def&nbsp;_triangulate_face(vertex_indices,&nbsp;face):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Fan&nbsp;triangulation&nbsp;of&nbsp;a&nbsp;face&nbsp;with&nbsp;N&nbsp;vertices.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;triangles&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;begin&nbsp;=&nbsp;face.index_begin<br>
&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;face.num_indices<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;n&nbsp;&lt;&nbsp;3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;triangles<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Fan:&nbsp;(0,&nbsp;1,&nbsp;2),&nbsp;(0,&nbsp;2,&nbsp;3),&nbsp;(0,&nbsp;3,&nbsp;4),&nbsp;...<br>
&nbsp;&nbsp;&nbsp;&nbsp;v0&nbsp;=&nbsp;vertex_indices[begin]<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(1,&nbsp;n&nbsp;-&nbsp;1):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;vertex_indices[begin&nbsp;+&nbsp;i]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v2&nbsp;=&nbsp;vertex_indices[begin&nbsp;+&nbsp;i&nbsp;+&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;triangles.append((v0,&nbsp;v1,&nbsp;v2))<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;triangles<br>
<br>
<br>
def&nbsp;_parse_meshes(scene,&nbsp;out):<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mesh&nbsp;in&nbsp;scene.meshes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh.num_vertices&nbsp;==&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Triangulate&nbsp;all&nbsp;faces<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tri_indices&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;face_idx&nbsp;in&nbsp;range(mesh.num_faces):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;face&nbsp;=&nbsp;mesh.faces[face_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tri_indices.extend(_triangulate_face(mesh.vertex_indices,&nbsp;face))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;tri_indices:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;vertex&nbsp;arrays&nbsp;from&nbsp;triangulated&nbsp;indices<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;has_normals&nbsp;=&nbsp;mesh.vertex_normal.values&nbsp;and&nbsp;len(mesh.vertex_normal.values)&nbsp;&gt;&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;has_uvs&nbsp;=&nbsp;mesh.uv_sets&nbsp;and&nbsp;len(mesh.uv_sets)&nbsp;&gt;&nbsp;0&nbsp;and&nbsp;mesh.uv_sets[0].vertex_uv.values&nbsp;and&nbsp;len(mesh.uv_sets[0].vertex_uv.values)&nbsp;&gt;&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v0,&nbsp;v1,&nbsp;v2&nbsp;in&nbsp;tri_indices:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;idx&nbsp;in&nbsp;(v0,&nbsp;v1,&nbsp;v2):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Position<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v&nbsp;=&nbsp;mesh.vertices[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices.append((v.x,&nbsp;v.y,&nbsp;v.z))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Normal<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;has_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_idx&nbsp;=&nbsp;mesh.vertex_normal.indices[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;mesh.vertex_normal.values[n_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals.append((n.x,&nbsp;n.y,&nbsp;n.z))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;UV<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;has_uvs:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_uv&nbsp;=&nbsp;mesh.uv_sets[0].vertex_uv<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uv_idx&nbsp;=&nbsp;vertex_uv.indices[idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uv&nbsp;=&nbsp;vertex_uv.values[uv_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs.append((uv.x,&nbsp;uv.y))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices_np&nbsp;=&nbsp;np.array(vertices,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals_np&nbsp;=&nbsp;np.array(normals,&nbsp;dtype=np.float32)&nbsp;if&nbsp;normals&nbsp;else&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs_np&nbsp;=&nbsp;np.array(uvs,&nbsp;dtype=np.float32)&nbsp;if&nbsp;uvs&nbsp;else&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices_np&nbsp;=&nbsp;np.arange(len(vertices),&nbsp;dtype=np.uint32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Material&nbsp;index<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat_idx&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh.materials&nbsp;and&nbsp;len(mesh.materials)&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;first_mat&nbsp;=&nbsp;mesh.materials[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(scene.materials)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;scene.materials[i]&nbsp;==&nbsp;first_mat:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat_idx&nbsp;=&nbsp;i<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out.meshes.append(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FBXMeshData(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=mesh.name&nbsp;if&nbsp;mesh.name&nbsp;else&nbsp;&quot;Mesh&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices=vertices_np,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals=normals_np,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs=uvs_np,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices=indices_np,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material_index=mat_idx<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
def&nbsp;_parse_nodes_flat(scene,&nbsp;mesh_index_map):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Parse&nbsp;node&nbsp;hierarchy&nbsp;into&nbsp;flat&nbsp;list&nbsp;to&nbsp;avoid&nbsp;ufbx&nbsp;segfault&nbsp;issues.<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns&nbsp;root&nbsp;FBXNodeData&nbsp;with&nbsp;all&nbsp;mesh&nbsp;nodes&nbsp;as&nbsp;direct&nbsp;children.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;root&nbsp;=&nbsp;FBXNodeData(&quot;Root&quot;,&nbsp;children=[],&nbsp;mesh_indices=[],&nbsp;transform=np.eye(4,&nbsp;dtype=np.float32))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Iterate&nbsp;through&nbsp;all&nbsp;nodes&nbsp;and&nbsp;collect&nbsp;those&nbsp;with&nbsp;meshes<br>
&nbsp;&nbsp;&nbsp;&nbsp;stack&nbsp;=&nbsp;[scene.root_node]<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;stack:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node&nbsp;=&nbsp;stack.pop()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;node.mesh:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;idx&nbsp;=&nbsp;mesh_index_map.get(id(node.mesh))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;idx&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Extract&nbsp;transform&nbsp;data&nbsp;immediately&nbsp;(avoid&nbsp;keeping&nbsp;ufbx&nbsp;refs)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t&nbsp;=&nbsp;node.local_transform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;translation&nbsp;=&nbsp;np.array([t.translation.x,&nbsp;t.translation.y,&nbsp;t.translation.z],&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rotation&nbsp;=&nbsp;np.array([t.rotation.x,&nbsp;t.rotation.y,&nbsp;t.rotation.z,&nbsp;t.rotation.w],&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scale_vec&nbsp;=&nbsp;np.array([t.scale.x,&nbsp;t.scale.y,&nbsp;t.scale.z],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;transform&nbsp;matrix<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x,&nbsp;y,&nbsp;z,&nbsp;w&nbsp;=&nbsp;rotation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xx,&nbsp;yy,&nbsp;zz&nbsp;=&nbsp;x&nbsp;*&nbsp;x,&nbsp;y&nbsp;*&nbsp;y,&nbsp;z&nbsp;*&nbsp;z<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xy,&nbsp;xz,&nbsp;yz&nbsp;=&nbsp;x&nbsp;*&nbsp;y,&nbsp;x&nbsp;*&nbsp;z,&nbsp;y&nbsp;*&nbsp;z<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wx,&nbsp;wy,&nbsp;wz&nbsp;=&nbsp;w&nbsp;*&nbsp;x,&nbsp;w&nbsp;*&nbsp;y,&nbsp;w&nbsp;*&nbsp;z<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;np.array([<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1&nbsp;-&nbsp;2&nbsp;*&nbsp;(yy&nbsp;+&nbsp;zz),&nbsp;2&nbsp;*&nbsp;(xy&nbsp;-&nbsp;wz),&nbsp;2&nbsp;*&nbsp;(xz&nbsp;+&nbsp;wy)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2&nbsp;*&nbsp;(xy&nbsp;+&nbsp;wz),&nbsp;1&nbsp;-&nbsp;2&nbsp;*&nbsp;(xx&nbsp;+&nbsp;zz),&nbsp;2&nbsp;*&nbsp;(yz&nbsp;-&nbsp;wx)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2&nbsp;*&nbsp;(xz&nbsp;-&nbsp;wy),&nbsp;2&nbsp;*&nbsp;(yz&nbsp;+&nbsp;wx),&nbsp;1&nbsp;-&nbsp;2&nbsp;*&nbsp;(xx&nbsp;+&nbsp;yy)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot_scaled&nbsp;=&nbsp;rot&nbsp;*&nbsp;scale_vec<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform&nbsp;=&nbsp;np.eye(4,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform[:3,&nbsp;:3]&nbsp;=&nbsp;rot_scaled<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform[:3,&nbsp;3]&nbsp;=&nbsp;translation<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name&nbsp;=&nbsp;node.name&nbsp;if&nbsp;node.name&nbsp;else&nbsp;f&quot;Mesh_{idx}&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;child&nbsp;=&nbsp;FBXNodeData(name,&nbsp;children=[],&nbsp;mesh_indices=[idx],&nbsp;transform=transform)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;root.children.append(child)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Add&nbsp;children&nbsp;to&nbsp;stack<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(node.children)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stack.append(node.children[i])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;root<br>
<br>
<br>
def&nbsp;_parse_animations(scene,&nbsp;out):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Parse&nbsp;animations&nbsp;from&nbsp;ufbx&nbsp;scene.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Note:&nbsp;ufbx&nbsp;animation&nbsp;API&nbsp;is&nbsp;unstable.&nbsp;We&nbsp;wrap&nbsp;everything&nbsp;in&nbsp;try/except.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;anim_stack&nbsp;in&nbsp;scene.anim_stacks:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_parse_single_animation(anim_stack,&nbsp;out)<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warning(&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;parse&nbsp;animations&quot;,&nbsp;exc_info=True)<br>
<br>
<br>
def&nbsp;_parse_single_animation(anim_stack,&nbsp;out):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Parse&nbsp;a&nbsp;single&nbsp;animation&nbsp;stack.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name&nbsp;=&nbsp;anim_stack.name&nbsp;or&nbsp;&quot;Anim&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tps&nbsp;=&nbsp;30.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Duration<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;duration&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;duration&nbsp;=&nbsp;anim_stack.time_end&nbsp;-&nbsp;anim_stack.time_begin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warning(&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;get&nbsp;animation&nbsp;duration&quot;,&nbsp;exc_info=True)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;anim_stack.layers:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layer&nbsp;=&nbsp;anim_stack.layers[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_channels&nbsp;=&nbsp;{}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;CRITICAL:&nbsp;ufbx&nbsp;crashes&nbsp;if&nbsp;we&nbsp;iterate&nbsp;over&nbsp;anim_props&nbsp;directly!<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Must&nbsp;cache&nbsp;into&nbsp;a&nbsp;Python&nbsp;list&nbsp;first.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_props&nbsp;=&nbsp;len(layer.anim_props)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cached_props&nbsp;=&nbsp;[layer.anim_props[i]&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_props)]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;anim_prop&nbsp;in&nbsp;cached_props:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_parse_anim_prop(anim_prop,&nbsp;node_channels)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;channel&nbsp;list<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;channels&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;node_name,&nbsp;ch_data&nbsp;in&nbsp;node_channels.items():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;ch_data['pos_keys']&nbsp;or&nbsp;ch_data['rot_keys']&nbsp;or&nbsp;ch_data['scale_keys']:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;channels.append(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FBXAnimationChannel(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_name=node_name,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pos_keys=ch_data['pos_keys'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot_keys=ch_data['rot_keys'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scale_keys=ch_data['scale_keys']<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;channels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out.animations.append(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;FBXAnimationClip(name=name,&nbsp;duration=duration,&nbsp;tps=tps,&nbsp;channels=channels)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warning(&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;parse&nbsp;animation&nbsp;stack&quot;,&nbsp;exc_info=True)<br>
<br>
<br>
def&nbsp;_parse_anim_prop(anim_prop,&nbsp;node_channels):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Parse&nbsp;a&nbsp;single&nbsp;animated&nbsp;property.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;element&nbsp;=&nbsp;anim_prop.element<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;element:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;element&nbsp;может&nbsp;быть&nbsp;не&nbsp;только&nbsp;нодой,&nbsp;но&nbsp;и&nbsp;материалом&nbsp;и&nbsp;т.п.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;У&nbsp;них&nbsp;может&nbsp;не&nbsp;быть&nbsp;атрибута&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_name&nbsp;=&nbsp;element.name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;node_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;AttributeError:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;node_name&nbsp;not&nbsp;in&nbsp;node_channels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_channels[node_name]&nbsp;=&nbsp;{'pos_keys':&nbsp;[],&nbsp;'rot_keys':&nbsp;[],&nbsp;'scale_keys':&nbsp;[]}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prop_name&nbsp;=&nbsp;(anim_prop.prop_name&nbsp;or&nbsp;&quot;&quot;).lower()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;anim_value&nbsp;=&nbsp;anim_prop.anim_value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;anim_value&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keys&nbsp;=&nbsp;_extract_keys_safe(anim_value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;keys:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;'translation'&nbsp;in&nbsp;prop_name&nbsp;or&nbsp;'lcl&nbsp;translation'&nbsp;in&nbsp;prop_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_channels[node_name]['pos_keys']&nbsp;=&nbsp;keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;'rotation'&nbsp;in&nbsp;prop_name&nbsp;or&nbsp;'lcl&nbsp;rotation'&nbsp;in&nbsp;prop_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_channels[node_name]['rot_keys']&nbsp;=&nbsp;keys<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;'scaling'&nbsp;in&nbsp;prop_name&nbsp;or&nbsp;'lcl&nbsp;scaling'&nbsp;in&nbsp;prop_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_channels[node_name]['scale_keys']&nbsp;=&nbsp;keys<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warning(&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;parse&nbsp;anim&nbsp;prop&quot;,&nbsp;exc_info=True)<br>
<br>
<br>
def&nbsp;_extract_keys_safe(anim_value):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Extract&nbsp;keyframes&nbsp;from&nbsp;ufbx&nbsp;anim_value.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Get&nbsp;curves&nbsp;(ufbx&nbsp;stores&nbsp;as&nbsp;.curves&nbsp;list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;curves&nbsp;=&nbsp;list(anim_value.curves)[:3]&nbsp;if&nbsp;anim_value.curves&nbsp;else&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;curves:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Collect&nbsp;all&nbsp;keyframe&nbsp;times<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;times&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;curve&nbsp;in&nbsp;curves:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;curve&nbsp;and&nbsp;curve.keyframes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;kf&nbsp;in&nbsp;curve.keyframes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;times.add(kf.time)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;times:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Sample&nbsp;at&nbsp;each&nbsp;time<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keys&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;t&nbsp;in&nbsp;sorted(times):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;values&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;curve&nbsp;in&nbsp;curves:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;curve&nbsp;and&nbsp;curve.keyframes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;kf&nbsp;in&nbsp;curve.keyframes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;kf.time&nbsp;&lt;=&nbsp;t:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;val&nbsp;=&nbsp;kf.value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;values.append(val)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;len(values)&nbsp;&lt;&nbsp;3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;values.append(0.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;keys.append((t,&nbsp;np.array(values[:3],&nbsp;dtype=np.float32)))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;keys<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warning(&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;extract&nbsp;keyframes&quot;,&nbsp;exc_info=True)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
<br>
#&nbsp;----------&nbsp;PUBLIC&nbsp;API&nbsp;----------<br>
<br>
def&nbsp;load_fbx_file(path)&nbsp;-&gt;&nbsp;FBXSceneData:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Load&nbsp;FBX&nbsp;file&nbsp;using&nbsp;ufbx.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Note:&nbsp;ufbx&nbsp;has&nbsp;critical&nbsp;bugs&nbsp;-&nbsp;accessing&nbsp;animations&nbsp;corrupts&nbsp;mesh&nbsp;data&nbsp;and&nbsp;vice&nbsp;versa.<br>
&nbsp;&nbsp;&nbsp;&nbsp;We&nbsp;MUST&nbsp;load&nbsp;the&nbsp;file&nbsp;TWICE:&nbsp;once&nbsp;for&nbsp;animations,&nbsp;once&nbsp;for&nbsp;meshes.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene_data&nbsp;=&nbsp;FBXSceneData()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;LOAD&nbsp;#1:&nbsp;Extract&nbsp;animations&nbsp;first&nbsp;(in&nbsp;separate&nbsp;scene&nbsp;instance)<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;This&nbsp;must&nbsp;be&nbsp;done&nbsp;before&nbsp;mesh&nbsp;extraction&nbsp;due&nbsp;to&nbsp;ufbx&nbsp;memory&nbsp;corruption&nbsp;bugs<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene_anim&nbsp;=&nbsp;ufbx.load_file(path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;scene_anim:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;RuntimeError(f&quot;Failed&nbsp;to&nbsp;load&nbsp;FBX:&nbsp;{path}&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;_parse_animations(scene_anim,&nbsp;scene_data)<br>
&nbsp;&nbsp;&nbsp;&nbsp;del&nbsp;scene_anim&nbsp;&nbsp;#&nbsp;Release&nbsp;animation&nbsp;scene<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;LOAD&nbsp;#2:&nbsp;Extract&nbsp;meshes&nbsp;and&nbsp;materials<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;ufbx.load_file(path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;scene:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;RuntimeError(f&quot;Failed&nbsp;to&nbsp;load&nbsp;FBX:&nbsp;{path}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Extract&nbsp;ALL&nbsp;data&nbsp;in&nbsp;ONE&nbsp;pass&nbsp;through&nbsp;node&nbsp;tree.<br>
&nbsp;&nbsp;&nbsp;&nbsp;mesh_data_list&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;node_data_list&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;processed_meshes&nbsp;=&nbsp;set()&nbsp;&nbsp;#&nbsp;Track&nbsp;by&nbsp;mesh&nbsp;name&nbsp;to&nbsp;avoid&nbsp;duplicates<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;stack&nbsp;=&nbsp;[scene.root_node]&nbsp;if&nbsp;scene.root_node&nbsp;else&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;stack:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node&nbsp;=&nbsp;stack.pop()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;node.mesh&nbsp;and&nbsp;node.mesh.name&nbsp;not&nbsp;in&nbsp;processed_meshes:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;processed_meshes.add(node.mesh.name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh&nbsp;=&nbsp;node.mesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Extract&nbsp;transform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;t&nbsp;=&nbsp;node.local_transform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;translation&nbsp;=&nbsp;(t.translation.x,&nbsp;t.translation.y,&nbsp;t.translation.z)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rotation&nbsp;=&nbsp;(t.rotation.x,&nbsp;t.rotation.y,&nbsp;t.rotation.z,&nbsp;t.rotation.w)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scale&nbsp;=&nbsp;(t.scale.x,&nbsp;t.scale.y,&nbsp;t.scale.z)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Triangulate&nbsp;mesh<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Store&nbsp;tuples&nbsp;of&nbsp;(vertex_index,&nbsp;face_vertex_index)&nbsp;for&nbsp;correct&nbsp;UV&nbsp;lookup<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tri_data&nbsp;=&nbsp;[]&nbsp;&nbsp;#&nbsp;[(v_idx,&nbsp;fv_idx),&nbsp;...]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;face_idx&nbsp;in&nbsp;range(mesh.num_faces):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;face&nbsp;=&nbsp;mesh.faces[face_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;begin&nbsp;=&nbsp;face.index_begin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;face.num_indices<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;n&nbsp;&gt;=&nbsp;3:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Fan&nbsp;triangulation:&nbsp;(0,&nbsp;1,&nbsp;2),&nbsp;(0,&nbsp;2,&nbsp;3),&nbsp;...<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fv0&nbsp;=&nbsp;begin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v0&nbsp;=&nbsp;mesh.vertex_indices[fv0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;j&nbsp;in&nbsp;range(1,&nbsp;n&nbsp;-&nbsp;1):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fv1&nbsp;=&nbsp;begin&nbsp;+&nbsp;j<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fv2&nbsp;=&nbsp;begin&nbsp;+&nbsp;j&nbsp;+&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;mesh.vertex_indices[fv1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v2&nbsp;=&nbsp;mesh.vertex_indices[fv2]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tri_data.append(((v0,&nbsp;fv0),&nbsp;(v1,&nbsp;fv1),&nbsp;(v2,&nbsp;fv2)))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;tri_data:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(node.children)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stack.append(node.children[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;vertex&nbsp;arrays<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;has_normals&nbsp;=&nbsp;mesh.vertex_normal.values&nbsp;and&nbsp;len(mesh.vertex_normal.values)&nbsp;&gt;&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;has_uvs&nbsp;=&nbsp;mesh.uv_sets&nbsp;and&nbsp;len(mesh.uv_sets)&nbsp;&gt;&nbsp;0&nbsp;and&nbsp;mesh.uv_sets[0].vertex_uv.values&nbsp;and&nbsp;len(mesh.uv_sets[0].vertex_uv.values)&nbsp;&gt;&nbsp;0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(v0,&nbsp;fv0),&nbsp;(v1,&nbsp;fv1),&nbsp;(v2,&nbsp;fv2)&nbsp;in&nbsp;tri_data:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;v_idx,&nbsp;fv_idx&nbsp;in&nbsp;((v0,&nbsp;fv0),&nbsp;(v1,&nbsp;fv1),&nbsp;(v2,&nbsp;fv2)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v&nbsp;=&nbsp;mesh.vertices[v_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices.append((v.x,&nbsp;v.y,&nbsp;v.z))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;has_normals:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_idx&nbsp;=&nbsp;mesh.vertex_normal.indices[fv_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n&nbsp;=&nbsp;mesh.vertex_normal.values[n_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals.append((n.x,&nbsp;n.y,&nbsp;n.z))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;has_uvs:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_uv&nbsp;=&nbsp;mesh.uv_sets[0].vertex_uv<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uv_idx&nbsp;=&nbsp;vertex_uv.indices[fv_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uv&nbsp;=&nbsp;vertex_uv.values[uv_idx]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs.append((uv.x,&nbsp;uv.y))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh_idx&nbsp;=&nbsp;len(mesh_data_list)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh_data_list.append({<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name':&nbsp;mesh.name&nbsp;if&nbsp;mesh.name&nbsp;else&nbsp;f&quot;Mesh_{mesh_idx}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'vertices':&nbsp;np.array(vertices,&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'normals':&nbsp;np.array(normals,&nbsp;dtype=np.float32)&nbsp;if&nbsp;normals&nbsp;else&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'uvs':&nbsp;np.array(uvs,&nbsp;dtype=np.float32)&nbsp;if&nbsp;uvs&nbsp;else&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node_data_list.append({<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name':&nbsp;node.name&nbsp;if&nbsp;node.name&nbsp;else&nbsp;f&quot;Node_{mesh_idx}&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'mesh_idx':&nbsp;mesh_idx,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'translation':&nbsp;translation,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'rotation':&nbsp;rotation,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'scale':&nbsp;scale,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(len(node.children)):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;stack.append(node.children[i])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Materials&nbsp;and&nbsp;textures&nbsp;-&nbsp;extract&nbsp;together&nbsp;to&nbsp;avoid&nbsp;multiple&nbsp;iterations<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;NOTE:&nbsp;iterating&nbsp;scene.textures&nbsp;separately&nbsp;causes&nbsp;segfault!<br>
&nbsp;&nbsp;&nbsp;&nbsp;mat_data_list&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;tex_data_list&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;processed_textures&nbsp;=&nbsp;set()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mat&nbsp;in&nbsp;scene.materials:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat.pbr.base_color.has_value:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;=&nbsp;mat.pbr.base_color.value_vec4<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color&nbsp;=&nbsp;(c.x,&nbsp;c.y,&nbsp;c.z,&nbsp;c.w)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex&nbsp;=&nbsp;mat.pbr.base_color.texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex&nbsp;and&nbsp;tex.filename:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture&nbsp;=&nbsp;tex.filename<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Extract&nbsp;texture&nbsp;content&nbsp;while&nbsp;we&nbsp;have&nbsp;access&nbsp;to&nbsp;it<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex_key&nbsp;=&nbsp;tex.filename&nbsp;or&nbsp;id(tex)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;tex_key&nbsp;not&nbsp;in&nbsp;processed_textures:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;processed_textures.add(tex_key)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;content&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Check&nbsp;for&nbsp;embedded&nbsp;content&nbsp;(raw&nbsp;image&nbsp;bytes)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(tex,&nbsp;'content')&nbsp;and&nbsp;tex.content:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hasattr(tex,&nbsp;'content_size')&nbsp;and&nbsp;tex.content_size&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;content&nbsp;=&nbsp;bytes(tex.content[:tex.content_size])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.debug(f&quot;[FBX]&nbsp;Failed&nbsp;to&nbsp;extract&nbsp;embedded&nbsp;texture&nbsp;content:&nbsp;{e}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tex_data_list.append({<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name':&nbsp;tex.name&nbsp;if&nbsp;tex.name&nbsp;else&nbsp;tex.filename,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'filename':&nbsp;tex.filename,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'content':&nbsp;content,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat_data_list.append({<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'name':&nbsp;mat.name&nbsp;if&nbsp;mat.name&nbsp;else&nbsp;&quot;Material&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'diffuse_color':&nbsp;diffuse_color,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'diffuse_texture':&nbsp;diffuse_texture,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Now&nbsp;build&nbsp;FBXSceneData&nbsp;from&nbsp;extracted&nbsp;data&nbsp;(no&nbsp;more&nbsp;ufbx&nbsp;access)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Materials<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;mat_data&nbsp;in&nbsp;mat_data_list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_data.materials.append(FBXMaterialData(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=mat_data['name'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_color=np.array(mat_data['diffuse_color'],&nbsp;dtype=np.float32)&nbsp;if&nbsp;mat_data['diffuse_color']&nbsp;else&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;diffuse_texture=mat_data['diffuse_texture'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Textures<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;tex_data&nbsp;in&nbsp;tex_data_list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_data.textures.append(FBXTcTexture(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=tex_data['name'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;filename=tex_data['filename'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;content=tex_data['content'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Meshes<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i,&nbsp;mesh_data&nbsp;in&nbsp;enumerate(mesh_data_list):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scene_data.meshes.append(FBXMeshData(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=mesh_data['name'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices=mesh_data['vertices'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normals=mesh_data['normals'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uvs=mesh_data['uvs'],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices=np.arange(len(mesh_data['vertices']),&nbsp;dtype=np.uint32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material_index=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Node&nbsp;hierarchy&nbsp;(flat)<br>
&nbsp;&nbsp;&nbsp;&nbsp;root&nbsp;=&nbsp;FBXNodeData(&quot;Root&quot;,&nbsp;children=[],&nbsp;mesh_indices=[],&nbsp;transform=np.eye(4,&nbsp;dtype=np.float32))<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;node_data&nbsp;in&nbsp;node_data_list:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x,&nbsp;y,&nbsp;z,&nbsp;w&nbsp;=&nbsp;node_data['rotation']<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xx,&nbsp;yy,&nbsp;zz&nbsp;=&nbsp;x&nbsp;*&nbsp;x,&nbsp;y&nbsp;*&nbsp;y,&nbsp;z&nbsp;*&nbsp;z<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;xy,&nbsp;xz,&nbsp;yz&nbsp;=&nbsp;x&nbsp;*&nbsp;y,&nbsp;x&nbsp;*&nbsp;z,&nbsp;y&nbsp;*&nbsp;z<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;wx,&nbsp;wy,&nbsp;wz&nbsp;=&nbsp;w&nbsp;*&nbsp;x,&nbsp;w&nbsp;*&nbsp;y,&nbsp;w&nbsp;*&nbsp;z<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;np.array([<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[1&nbsp;-&nbsp;2&nbsp;*&nbsp;(yy&nbsp;+&nbsp;zz),&nbsp;2&nbsp;*&nbsp;(xy&nbsp;-&nbsp;wz),&nbsp;2&nbsp;*&nbsp;(xz&nbsp;+&nbsp;wy)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2&nbsp;*&nbsp;(xy&nbsp;+&nbsp;wz),&nbsp;1&nbsp;-&nbsp;2&nbsp;*&nbsp;(xx&nbsp;+&nbsp;zz),&nbsp;2&nbsp;*&nbsp;(yz&nbsp;-&nbsp;wx)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[2&nbsp;*&nbsp;(xz&nbsp;-&nbsp;wy),&nbsp;2&nbsp;*&nbsp;(yz&nbsp;+&nbsp;wx),&nbsp;1&nbsp;-&nbsp;2&nbsp;*&nbsp;(xx&nbsp;+&nbsp;yy)],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sx,&nbsp;sy,&nbsp;sz&nbsp;=&nbsp;node_data['scale']<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot_scaled&nbsp;=&nbsp;rot&nbsp;*&nbsp;np.array([sx,&nbsp;sy,&nbsp;sz],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform&nbsp;=&nbsp;np.eye(4,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform[:3,&nbsp;:3]&nbsp;=&nbsp;rot_scaled<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform[:3,&nbsp;3]&nbsp;=&nbsp;node_data['translation']<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;child&nbsp;=&nbsp;FBXNodeData(node_data['name'],&nbsp;children=[],&nbsp;mesh_indices=[node_data['mesh_idx']],&nbsp;transform=transform)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;root.children.append(child)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene_data.root&nbsp;=&nbsp;root<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene_data<br>
<!-- END SCAT CODE -->
</body>
</html>
