public class BioScanCard : EventCard<ObjectOfTimeline>
{
    private string _owner;
    private long _step;

    public BioScanCard(string owner, long step) : base(step)
    {
        _owner = owner;
        _step = step;
    }

    public override void on_forward_enter(long current_step, ObjectOfTimeline obj) { }

    public override void on_backward_leave(long current_step, ObjectOfTimeline obj) { }

    //BEGIN################################################################
    // This code was generated by FieldScanner

    public override long HashCode()
    {
        long result = 0;
        result = FieldScanner.ModifyHash(result, _owner);
        result = FieldScanner.ModifyHash(result, _step);
        result = FieldScanner.ModifyHash(result, start_step);
        result = FieldScanner.ModifyHash(result, finish_step);
        return result;
    }

    public override bool Equals(object obj)
    {
        if (obj == null)
            return false;
        if (obj.GetType() != GetType())
            return false;
        var other = obj as BioScanCard;
        return _owner == other._owner
            && _step == other._step
            && start_step == other.start_step
            && finish_step == other.finish_step
            && true;
    }

    public override int GetHashCode()
    {
        return (int)HashCode();
    }
    //END################################################################
}

public class BioScanner : ItemComponent
{
    float radius;

    public BioScanner(ObjectOfTimeline owner, float radius) : base(owner)
    {
        this.radius = radius;
    }

    public override ItemComponent Copy(ObjectOfTimeline owner)
    {
        return new BioScanner(owner, radius);
    }

    public override void Execute(long local_step, long timeline_step)
    {
        var heroes = Owner.GetTimeline().Heroes();
        foreach (var hero in heroes)
        {
            var distance = Owner
                .CurrentReferencedPoint()
                .DistanceTo(hero.CurrentReferencedPoint(), Owner.GetTimeline());
            if (distance < radius)
            {
                hero.AddCard(new BioScanCard(Owner.Name(), local_step));
            }
        }
    }
}
