<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/project/modules/game.module</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;name&quot;:&nbsp;&quot;game_components&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;sources&quot;:&nbsp;[&quot;components/spin_component.cpp&quot;],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;include_dirs&quot;:&nbsp;[&quot;.&quot;],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;components&quot;:&nbsp;[&quot;SpinComponent&quot;],<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;built_version&quot;:&nbsp;265<br>
}<br>
<!-- END SCAT CODE -->
</body>
</html>
