<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/framegraph/passes/material_pass.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;MaterialPass&nbsp;-&nbsp;Post-processing&nbsp;pass&nbsp;using&nbsp;a&nbsp;Material&nbsp;asset.<br>
<br>
Re-exports&nbsp;C++&nbsp;MaterialPass&nbsp;with&nbsp;Python-only&nbsp;utilities&nbsp;for&nbsp;editor.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;typing&nbsp;import&nbsp;List,&nbsp;Tuple<br>
<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;MaterialPass<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;InspectField<br>
from&nbsp;termin._native&nbsp;import&nbsp;log<br>
<br>
__all__&nbsp;=&nbsp;[&quot;MaterialPass&quot;,&nbsp;&quot;get_texture_inputs_for_material&quot;]<br>
<br>
#&nbsp;Add&nbsp;inspect_fields&nbsp;to&nbsp;C++&nbsp;class&nbsp;for&nbsp;editor&nbsp;integration<br>
#&nbsp;Key&nbsp;must&nbsp;match&nbsp;the&nbsp;property&nbsp;name&nbsp;for&nbsp;JSON&nbsp;param&nbsp;serialization<br>
MaterialPass.inspect_fields&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;material&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;material&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Material&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;tc_material&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;),<br>
}<br>
<br>
<br>
def&nbsp;get_texture_inputs_for_material(material_name:&nbsp;str)&nbsp;-&gt;&nbsp;List[Tuple[str,&nbsp;str]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Get&nbsp;list&nbsp;of&nbsp;texture&nbsp;inputs&nbsp;for&nbsp;a&nbsp;material's&nbsp;shader.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Args:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material_name:&nbsp;Name&nbsp;of&nbsp;the&nbsp;material.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Returns:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;List&nbsp;of&nbsp;(input_name,&nbsp;socket_type)&nbsp;tuples&nbsp;for&nbsp;node&nbsp;inputs.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input_name&nbsp;is&nbsp;derived&nbsp;from&nbsp;uniform&nbsp;name&nbsp;(u_depth&nbsp;-&gt;&nbsp;depth).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Includes&nbsp;u_input&nbsp;as&nbsp;&quot;input&quot;&nbsp;if&nbsp;shader&nbsp;uses&nbsp;it.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;material_name&nbsp;or&nbsp;material_name&nbsp;==&nbsp;&quot;(None)&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.resources&nbsp;import&nbsp;ResourceManager<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;rm&nbsp;=&nbsp;ResourceManager.instance()<br>
&nbsp;&nbsp;&nbsp;&nbsp;material&nbsp;=&nbsp;rm.get_material(material_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;material&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warn(f&quot;[get_texture_inputs_for_material]&nbsp;material&nbsp;'{material_name}'&nbsp;not&nbsp;found&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;shader_name&nbsp;=&nbsp;material.shader_name<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;shader_name:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warn(f&quot;[get_texture_inputs_for_material]&nbsp;material&nbsp;'{material_name}'&nbsp;has&nbsp;no&nbsp;shader_name&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;program&nbsp;=&nbsp;rm.get_shader(shader_name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;program&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;program.phases:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;log.warn(f&quot;[get_texture_inputs_for_material]&nbsp;shader&nbsp;'{shader_name}'&nbsp;not&nbsp;found&nbsp;or&nbsp;has&nbsp;no&nbsp;phases&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Collect&nbsp;texture&nbsp;uniforms&nbsp;from&nbsp;first&nbsp;phase<br>
&nbsp;&nbsp;&nbsp;&nbsp;inputs&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;prop&nbsp;in&nbsp;program.phases[0].uniforms:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;prop.property_type&nbsp;==&nbsp;&quot;Texture&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uniform_name&nbsp;=&nbsp;prop.name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Convert&nbsp;uniform&nbsp;name&nbsp;to&nbsp;input&nbsp;name:&nbsp;u_depth_texture&nbsp;-&gt;&nbsp;depth_texture<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;u_input&nbsp;-&gt;&nbsp;input&nbsp;(for&nbsp;standard&nbsp;post-effect&nbsp;input)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;uniform_name.startswith(&quot;u_&quot;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input_name&nbsp;=&nbsp;uniform_name[2:]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input_name&nbsp;=&nbsp;uniform_name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;inputs.append((input_name,&nbsp;&quot;fbo&quot;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;inputs<br>
<br>
<br>
#&nbsp;Add&nbsp;as&nbsp;class&nbsp;method&nbsp;for&nbsp;backwards&nbsp;compatibility<br>
MaterialPass.get_texture_inputs_for_material&nbsp;=&nbsp;staticmethod(get_texture_inputs_for_material)<br>
<!-- END SCAT CODE -->
</body>
</html>
