<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/gizmo/__init__.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
Unified&nbsp;gizmo&nbsp;system&nbsp;for&nbsp;editor.<br>
<br>
Provides&nbsp;a&nbsp;framework&nbsp;for&nbsp;interactive&nbsp;3D&nbsp;widgets&nbsp;(gizmos)&nbsp;that:<br>
-&nbsp;Draw&nbsp;themselves&nbsp;using&nbsp;immediate&nbsp;mode&nbsp;rendering<br>
-&nbsp;Declare&nbsp;colliders&nbsp;for&nbsp;picking<br>
-&nbsp;Receive&nbsp;events&nbsp;when&nbsp;interacted&nbsp;with<br>
<br>
Core&nbsp;classes:<br>
-&nbsp;Gizmo:&nbsp;Base&nbsp;class&nbsp;for&nbsp;all&nbsp;gizmos<br>
-&nbsp;GizmoCollider:&nbsp;Collider&nbsp;geometry&nbsp;+&nbsp;drag&nbsp;constraint<br>
-&nbsp;GizmoManager:&nbsp;Manages&nbsp;all&nbsp;gizmos,&nbsp;handles&nbsp;raycast&nbsp;and&nbsp;events<br>
-&nbsp;TransformGizmo:&nbsp;Standard&nbsp;translate/rotate&nbsp;gizmo<br>
&quot;&quot;&quot;<br>
<br>
#&nbsp;Import&nbsp;from&nbsp;C++&nbsp;native&nbsp;module<br>
from&nbsp;termin._native.editor&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Gizmo,<br>
&nbsp;&nbsp;&nbsp;&nbsp;GizmoCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;GizmoHit,<br>
&nbsp;&nbsp;&nbsp;&nbsp;GizmoManager,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TransformGizmo,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TransformElement,<br>
)<br>
<br>
#&nbsp;Python&nbsp;constraint&nbsp;and&nbsp;geometry&nbsp;types&nbsp;(for&nbsp;custom&nbsp;Python&nbsp;gizmos)<br>
from&nbsp;termin.editor.gizmo.base&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;DragConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;AxisConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PlaneConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;AngleConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;RadiusConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;NoDrag,<br>
&nbsp;&nbsp;&nbsp;&nbsp;ColliderGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;SphereGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;CylinderGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TorusGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QuadGeometry,<br>
)<br>
<br>
__all__&nbsp;=&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Base&nbsp;(from&nbsp;C++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;Gizmo&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GizmoCollider&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GizmoHit&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Manager&nbsp;(from&nbsp;C++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;GizmoManager&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Transform&nbsp;(from&nbsp;C++)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;TransformGizmo&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;TransformElement&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Python&nbsp;constraint&nbsp;types&nbsp;(for&nbsp;custom&nbsp;gizmos)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;DragConstraint&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;AxisConstraint&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;PlaneConstraint&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;AngleConstraint&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;RadiusConstraint&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;NoDrag&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;ColliderGeometry&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;SphereGeometry&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;CylinderGeometry&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;TorusGeometry&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;QuadGeometry&quot;,<br>
]<br>
<!-- END SCAT CODE -->
</body>
</html>
