<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/editor/gizmo/transform_gizmo.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
TransformGizmo&nbsp;—&nbsp;standard&nbsp;translate/rotate&nbsp;gizmo&nbsp;for&nbsp;entity&nbsp;transforms.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
from&nbsp;dataclasses&nbsp;import&nbsp;dataclass<br>
from&nbsp;enum&nbsp;import&nbsp;Enum,&nbsp;auto<br>
from&nbsp;typing&nbsp;import&nbsp;Callable,&nbsp;TYPE_CHECKING<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.editor.gizmo.base&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Gizmo,<br>
&nbsp;&nbsp;&nbsp;&nbsp;GizmoCollider,<br>
&nbsp;&nbsp;&nbsp;&nbsp;AxisConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PlaneConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;AngleConstraint,<br>
&nbsp;&nbsp;&nbsp;&nbsp;CylinderGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;TorusGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;QuadGeometry,<br>
&nbsp;&nbsp;&nbsp;&nbsp;_build_basis,<br>
)<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.immediate&nbsp;import&nbsp;ImmediateRenderer<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.solid_primitives&nbsp;import&nbsp;SolidPrimitiveRenderer<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.platform.backends.base&nbsp;import&nbsp;GraphicsBackend<br>
<br>
<br>
class&nbsp;TransformElement(Enum):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Identifiers&nbsp;for&nbsp;transform&nbsp;gizmo&nbsp;parts.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_X&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_Y&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_Z&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_XY&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_XZ&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;TRANSLATE_YZ&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;ROTATE_X&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;ROTATE_Y&nbsp;=&nbsp;auto()<br>
&nbsp;&nbsp;&nbsp;&nbsp;ROTATE_Z&nbsp;=&nbsp;auto()<br>
<br>
<br>
#&nbsp;Colors<br>
AXIS_COLORS&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;x&quot;:&nbsp;(0.9,&nbsp;0.2,&nbsp;0.2,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Red<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;y&quot;:&nbsp;(0.2,&nbsp;0.9,&nbsp;0.2,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Green<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;z&quot;:&nbsp;(0.2,&nbsp;0.2,&nbsp;0.9,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Blue<br>
}<br>
#&nbsp;Plane&nbsp;colors:&nbsp;blend&nbsp;of&nbsp;the&nbsp;two&nbsp;axis&nbsp;colors<br>
PLANE_COLORS&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;xy&quot;:&nbsp;(0.9,&nbsp;0.9,&nbsp;0.2,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Yellow&nbsp;(R+G)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;xz&quot;:&nbsp;(0.9,&nbsp;0.2,&nbsp;0.9,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Magenta&nbsp;(R+B)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;yz&quot;:&nbsp;(0.2,&nbsp;0.9,&nbsp;0.9,&nbsp;1.0),&nbsp;&nbsp;#&nbsp;Cyan&nbsp;(G+B)<br>
}<br>
HOVER_COLOR&nbsp;=&nbsp;(1.0,&nbsp;0.7,&nbsp;0.2,&nbsp;1.0)&nbsp;&nbsp;#&nbsp;Orange<br>
ACTIVE_COLOR&nbsp;=&nbsp;(1.0,&nbsp;1.0,&nbsp;1.0,&nbsp;1.0)&nbsp;&nbsp;#&nbsp;White<br>
PLANE_ALPHA&nbsp;=&nbsp;0.3<br>
<br>
<br>
class&nbsp;TransformGizmo(Gizmo):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Transform&nbsp;gizmo&nbsp;for&nbsp;translate&nbsp;and&nbsp;rotate&nbsp;operations.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Supports:<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Translation&nbsp;along&nbsp;X,&nbsp;Y,&nbsp;Z&nbsp;axes&nbsp;(arrows)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Translation&nbsp;in&nbsp;XY,&nbsp;XZ,&nbsp;YZ&nbsp;planes&nbsp;(quads)<br>
&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Rotation&nbsp;around&nbsp;X,&nbsp;Y,&nbsp;Z&nbsp;axes&nbsp;(rings)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;size:&nbsp;float&nbsp;=&nbsp;1.5,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;on_transform_changed:&nbsp;Callable[[],&nbsp;None]&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.visible&nbsp;=&nbsp;True<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.size&nbsp;=&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._on_transform_changed&nbsp;=&nbsp;on_transform_changed<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Target&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target:&nbsp;&quot;Entity&nbsp;|&nbsp;None&quot;&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target_position:&nbsp;np.ndarray&nbsp;=&nbsp;np.zeros(3,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Screen&nbsp;scale&nbsp;(adjusted&nbsp;based&nbsp;on&nbsp;camera&nbsp;distance)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._screen_scale:&nbsp;float&nbsp;=&nbsp;1.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Orientation&nbsp;mode:&nbsp;&quot;local&quot;&nbsp;or&nbsp;&quot;world&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._orientation_mode:&nbsp;str&nbsp;=&nbsp;&quot;local&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Hover/active&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._hovered_element:&nbsp;TransformElement&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._active_element:&nbsp;TransformElement&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Geometry&nbsp;parameters&nbsp;(scaled)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._arrow_length&nbsp;=&nbsp;1.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._shaft_radius&nbsp;=&nbsp;0.02<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._head_radius&nbsp;=&nbsp;0.06<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._head_length_ratio&nbsp;=&nbsp;0.2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ring_major_radius&nbsp;=&nbsp;0.75<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ring_minor_radius&nbsp;=&nbsp;0.02<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._plane_offset&nbsp;=&nbsp;0.25<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._plane_size&nbsp;=&nbsp;0.2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._pick_tolerance&nbsp;=&nbsp;0.03<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Translation&nbsp;drag&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_axis:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Fixed&nbsp;axis&nbsp;direction&nbsp;during&nbsp;drag<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_center:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Fixed&nbsp;center&nbsp;position&nbsp;during&nbsp;drag<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Rotation&nbsp;drag&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_start_angle:&nbsp;float&nbsp;=&nbsp;0.0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_start_quat:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_vec0:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Initial&nbsp;reference&nbsp;vector&nbsp;for&nbsp;rotation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_axis:&nbsp;np.ndarray&nbsp;|&nbsp;None&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Fixed&nbsp;rotation&nbsp;axis&nbsp;during&nbsp;drag<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Undo&nbsp;support<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_start_pose&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undo_handler:&nbsp;Callable&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;target(self)&nbsp;-&gt;&nbsp;&quot;Entity&nbsp;|&nbsp;None&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._target<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@target.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;target(self,&nbsp;entity:&nbsp;&quot;Entity&nbsp;|&nbsp;None&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target&nbsp;=&nbsp;entity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;entity&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._update_position()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_screen_scale(self,&nbsp;scale:&nbsp;float)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;screen&nbsp;scale&nbsp;factor.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._screen_scale&nbsp;=&nbsp;scale<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_orientation_mode(self,&nbsp;mode:&nbsp;str)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;orientation&nbsp;mode&nbsp;('local'&nbsp;or&nbsp;'world').&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._orientation_mode&nbsp;=&nbsp;mode<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_undo_handler(self,&nbsp;handler:&nbsp;Callable)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Set&nbsp;undo&nbsp;command&nbsp;handler.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undo_handler&nbsp;=&nbsp;handler<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_update_position(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Update&nbsp;cached&nbsp;position&nbsp;from&nbsp;target.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._target&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;self._target.transform.global_pose()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target_position&nbsp;=&nbsp;np.array(pose.lin,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_position(self)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;gizmo&nbsp;center&nbsp;position.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._target&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._update_position()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._target_position<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_world_axis(self,&nbsp;axis:&nbsp;str)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;axis&nbsp;direction&nbsp;in&nbsp;world&nbsp;space.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;base&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;x&quot;:&nbsp;np.array([1,&nbsp;0,&nbsp;0],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;y&quot;:&nbsp;np.array([0,&nbsp;1,&nbsp;0],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;z&quot;:&nbsp;np.array([0,&nbsp;0,&nbsp;1],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}[axis]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._orientation_mode&nbsp;==&nbsp;&quot;world&quot;&nbsp;or&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;base<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Local&nbsp;orientation:&nbsp;rotate&nbsp;by&nbsp;entity's&nbsp;rotation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;self._target.transform.global_pose()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;quat&nbsp;=&nbsp;np.array(pose.ang,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_quat_rotate(quat,&nbsp;base)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_color(self,&nbsp;axis:&nbsp;str,&nbsp;element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;tuple:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;color&nbsp;for&nbsp;axis,&nbsp;considering&nbsp;hover/active&nbsp;state.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._active_element&nbsp;==&nbsp;element:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;ACTIVE_COLOR<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._hovered_element&nbsp;==&nbsp;element:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;HOVER_COLOR<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;AXIS_COLORS[axis]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_plane_color(self,&nbsp;plane:&nbsp;str,&nbsp;element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;tuple:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;color&nbsp;for&nbsp;plane&nbsp;handle.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._active_element&nbsp;==&nbsp;element:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r,&nbsp;g,&nbsp;b,&nbsp;_&nbsp;=&nbsp;ACTIVE_COLOR<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;self._hovered_element&nbsp;==&nbsp;element:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r,&nbsp;g,&nbsp;b,&nbsp;_&nbsp;=&nbsp;HOVER_COLOR<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;r,&nbsp;g,&nbsp;b,&nbsp;_&nbsp;=&nbsp;PLANE_COLORS[plane]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;(r,&nbsp;g,&nbsp;b,&nbsp;PLANE_ALPHA)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_scaled(self,&nbsp;value:&nbsp;float)&nbsp;-&gt;&nbsp;float:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Scale&nbsp;value&nbsp;by&nbsp;size&nbsp;and&nbsp;screen&nbsp;scale.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;value&nbsp;*&nbsp;self.size&nbsp;*&nbsp;self._screen_scale<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Gizmo&nbsp;Interface<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;uses_solid_renderer(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Use&nbsp;efficient&nbsp;SolidPrimitiveRenderer.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw_solid(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;renderer:&nbsp;&quot;SolidPrimitiveRenderer&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics:&nbsp;&quot;GraphicsBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;proj:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Draw&nbsp;opaque&nbsp;gizmo&nbsp;geometry&nbsp;using&nbsp;efficient&nbsp;GPU&nbsp;meshes.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self.visible&nbsp;or&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin&nbsp;=&nbsp;self._get_position()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Draw&nbsp;translation&nbsp;arrows<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;axis,&nbsp;element&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;x&quot;,&nbsp;TransformElement.TRANSLATE_X),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;y&quot;,&nbsp;TransformElement.TRANSLATE_Y),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;z&quot;,&nbsp;TransformElement.TRANSLATE_Z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_dir&nbsp;=&nbsp;self._get_world_axis(axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color&nbsp;=&nbsp;self._get_color(axis,&nbsp;element)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;renderer.draw_arrow(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin=origin,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;direction=axis_dir,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;length=self._scaled(self._arrow_length),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color=color,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shaft_radius=self._scaled(self._shaft_radius),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;head_radius=self._scaled(self._head_radius),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;head_length_ratio=self._head_length_ratio,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Draw&nbsp;rotation&nbsp;rings<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;axis,&nbsp;element&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;x&quot;,&nbsp;TransformElement.ROTATE_X),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;y&quot;,&nbsp;TransformElement.ROTATE_Y),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;z&quot;,&nbsp;TransformElement.ROTATE_Z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ring_axis&nbsp;=&nbsp;self._get_world_axis(axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color&nbsp;=&nbsp;self._get_color(axis,&nbsp;element)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;model&nbsp;matrix&nbsp;for&nbsp;torus<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Unit&nbsp;torus&nbsp;has&nbsp;axis=Z,&nbsp;major_radius=1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;We&nbsp;need&nbsp;to&nbsp;rotate&nbsp;it&nbsp;so&nbsp;Z&nbsp;aligns&nbsp;with&nbsp;ring_axis<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;_rotation_align_z_to(ring_axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scale&nbsp;=&nbsp;self._scaled(self._ring_major_radius)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;model&nbsp;=&nbsp;_compose_trs(origin,&nbsp;rot,&nbsp;scale)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;renderer.draw_torus(model,&nbsp;color)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw_transparent_solid(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;renderer:&nbsp;&quot;SolidPrimitiveRenderer&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;graphics:&nbsp;&quot;GraphicsBackend&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;view:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;proj:&nbsp;np.ndarray,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Draw&nbsp;transparent&nbsp;gizmo&nbsp;geometry&nbsp;using&nbsp;efficient&nbsp;GPU&nbsp;meshes.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self.visible&nbsp;or&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin&nbsp;=&nbsp;self._get_position()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_x&nbsp;=&nbsp;self._get_world_axis(&quot;x&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_y&nbsp;=&nbsp;self._get_world_axis(&quot;y&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_z&nbsp;=&nbsp;self._get_world_axis(&quot;z&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;off&nbsp;=&nbsp;self._scaled(self._plane_offset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sz&nbsp;=&nbsp;self._scaled(self._plane_size)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;plane,&nbsp;element,&nbsp;a1,&nbsp;a2&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;xy&quot;,&nbsp;TransformElement.TRANSLATE_XY,&nbsp;axis_x,&nbsp;axis_y),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;xz&quot;,&nbsp;TransformElement.TRANSLATE_XZ,&nbsp;axis_z,&nbsp;axis_x),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;yz&quot;,&nbsp;TransformElement.TRANSLATE_YZ,&nbsp;axis_y,&nbsp;axis_z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color&nbsp;=&nbsp;self._get_plane_color(plane,&nbsp;element)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Unit&nbsp;quad&nbsp;is&nbsp;from&nbsp;(0,0,0)&nbsp;to&nbsp;(1,1,0)&nbsp;in&nbsp;XY&nbsp;plane<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;We&nbsp;need&nbsp;to&nbsp;position&nbsp;it&nbsp;at&nbsp;origin&nbsp;+&nbsp;offset&nbsp;and&nbsp;scale&nbsp;by&nbsp;sz<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p0&nbsp;=&nbsp;origin&nbsp;+&nbsp;a1&nbsp;*&nbsp;off&nbsp;+&nbsp;a2&nbsp;*&nbsp;off<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;rotation:&nbsp;X&nbsp;-&gt;&nbsp;a1,&nbsp;Y&nbsp;-&gt;&nbsp;a2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rot&nbsp;=&nbsp;np.column_stack([a1,&nbsp;a2,&nbsp;np.cross(a1,&nbsp;a2)]).astype(np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;model&nbsp;=&nbsp;_compose_trs(p0,&nbsp;rot,&nbsp;sz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;renderer.draw_quad(model,&nbsp;color)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw(self,&nbsp;renderer:&nbsp;&quot;ImmediateRenderer&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Legacy&nbsp;draw&nbsp;method&nbsp;-&nbsp;not&nbsp;used&nbsp;when&nbsp;uses_solid_renderer=True.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw_transparent(self,&nbsp;renderer:&nbsp;&quot;ImmediateRenderer&quot;)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Legacy&nbsp;draw&nbsp;method&nbsp;-&nbsp;not&nbsp;used&nbsp;when&nbsp;uses_solid_renderer=True.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_colliders(self)&nbsp;-&gt;&nbsp;list[GizmoCollider]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Get&nbsp;colliders&nbsp;for&nbsp;all&nbsp;gizmo&nbsp;elements.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self.visible&nbsp;or&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;colliders&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin&nbsp;=&nbsp;self._get_position()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tol&nbsp;=&nbsp;self._scaled(self._pick_tolerance)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Translation&nbsp;arrows&nbsp;(cylinders)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;axis,&nbsp;element&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;x&quot;,&nbsp;TransformElement.TRANSLATE_X),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;y&quot;,&nbsp;TransformElement.TRANSLATE_Y),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;z&quot;,&nbsp;TransformElement.TRANSLATE_Z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_dir&nbsp;=&nbsp;self._get_world_axis(axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;arrow_len&nbsp;=&nbsp;self._scaled(self._arrow_length)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shaft_end&nbsp;=&nbsp;origin&nbsp;+&nbsp;axis_dir&nbsp;*&nbsp;(arrow_len&nbsp;*&nbsp;(1&nbsp;-&nbsp;self._head_length_ratio))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tip&nbsp;=&nbsp;origin&nbsp;+&nbsp;axis_dir&nbsp;*&nbsp;arrow_len<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Shaft<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;colliders.append(GizmoCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id=element,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry=CylinderGeometry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start=origin.copy(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end=shaft_end,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=self._scaled(self._shaft_radius)&nbsp;+&nbsp;tol,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraint=AxisConstraint(origin=origin.copy(),&nbsp;axis=axis_dir.copy()),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Head<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;colliders.append(GizmoCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id=element,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry=CylinderGeometry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;start=shaft_end,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end=tip,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;radius=self._scaled(self._head_radius)&nbsp;+&nbsp;tol,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraint=AxisConstraint(origin=origin.copy(),&nbsp;axis=axis_dir.copy()),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Rotation&nbsp;rings&nbsp;(tori)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;axis,&nbsp;element&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;x&quot;,&nbsp;TransformElement.ROTATE_X),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;y&quot;,&nbsp;TransformElement.ROTATE_Y),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;z&quot;,&nbsp;TransformElement.ROTATE_Z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ring_axis&nbsp;=&nbsp;self._get_world_axis(axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;colliders.append(GizmoCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id=element,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry=TorusGeometry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;center=origin.copy(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis=ring_axis.copy(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;major_radius=self._scaled(self._ring_major_radius),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;minor_radius=self._scaled(self._ring_minor_radius)&nbsp;+&nbsp;tol,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraint=AngleConstraint(center=origin.copy(),&nbsp;axis=ring_axis.copy()),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Plane&nbsp;handles&nbsp;(quads)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_x&nbsp;=&nbsp;self._get_world_axis(&quot;x&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_y&nbsp;=&nbsp;self._get_world_axis(&quot;y&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_z&nbsp;=&nbsp;self._get_world_axis(&quot;z&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;off&nbsp;=&nbsp;self._scaled(self._plane_offset)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sz&nbsp;=&nbsp;self._scaled(self._plane_size)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;plane,&nbsp;element,&nbsp;a1,&nbsp;a2,&nbsp;normal&nbsp;in&nbsp;[<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;xy&quot;,&nbsp;TransformElement.TRANSLATE_XY,&nbsp;axis_x,&nbsp;axis_y,&nbsp;axis_z),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;xz&quot;,&nbsp;TransformElement.TRANSLATE_XZ,&nbsp;axis_z,&nbsp;axis_x,&nbsp;axis_y),&nbsp;&nbsp;#&nbsp;swapped&nbsp;to&nbsp;get&nbsp;+Y&nbsp;normal<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(&quot;yz&quot;,&nbsp;TransformElement.TRANSLATE_YZ,&nbsp;axis_y,&nbsp;axis_z,&nbsp;axis_x),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p0&nbsp;=&nbsp;origin&nbsp;+&nbsp;a1&nbsp;*&nbsp;off&nbsp;+&nbsp;a2&nbsp;*&nbsp;off<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p1&nbsp;=&nbsp;origin&nbsp;+&nbsp;a1&nbsp;*&nbsp;(off&nbsp;+&nbsp;sz)&nbsp;+&nbsp;a2&nbsp;*&nbsp;off<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p2&nbsp;=&nbsp;origin&nbsp;+&nbsp;a1&nbsp;*&nbsp;(off&nbsp;+&nbsp;sz)&nbsp;+&nbsp;a2&nbsp;*&nbsp;(off&nbsp;+&nbsp;sz)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p3&nbsp;=&nbsp;origin&nbsp;+&nbsp;a1&nbsp;*&nbsp;off&nbsp;+&nbsp;a2&nbsp;*&nbsp;(off&nbsp;+&nbsp;sz)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;colliders.append(GizmoCollider(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;id=element,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry=QuadGeometry(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p0=p0,&nbsp;p1=p1,&nbsp;p2=p2,&nbsp;p3=p3,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normal=normal.copy(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;constraint=PlaneConstraint(origin=origin.copy(),&nbsp;normal=normal.copy()),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;colliders<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_hover_enter(self,&nbsp;collider_id)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;isinstance(collider_id,&nbsp;TransformElement):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._hovered_element&nbsp;=&nbsp;collider_id<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_hover_exit(self,&nbsp;collider_id)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._hovered_element&nbsp;==&nbsp;collider_id:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._hovered_element&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_click(self,&nbsp;collider_id,&nbsp;hit_position:&nbsp;np.ndarray&nbsp;|&nbsp;None)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;isinstance(collider_id,&nbsp;TransformElement):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._active_element&nbsp;=&nbsp;collider_id<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Save&nbsp;start&nbsp;pose&nbsp;for&nbsp;undo<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._target&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_start_pose&nbsp;=&nbsp;self._target.transform.local_pose().copy()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin&nbsp;=&nbsp;self._get_position()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Save&nbsp;fixed&nbsp;center&nbsp;position&nbsp;for&nbsp;all&nbsp;drag&nbsp;types<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_center&nbsp;=&nbsp;origin.copy()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;For&nbsp;translation,&nbsp;compute&nbsp;grab&nbsp;offset&nbsp;and&nbsp;save&nbsp;fixed&nbsp;axis<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._is_translate_element(collider_id):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis&nbsp;=&nbsp;self._get_axis_for_element(collider_id)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_axis&nbsp;=&nbsp;self._get_world_axis(axis).copy()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hit_position&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset&nbsp;=&nbsp;origin&nbsp;-&nbsp;hit_position<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset&nbsp;=&nbsp;np.zeros(3,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;For&nbsp;plane&nbsp;translation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._is_plane_element(collider_id):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hit_position&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset&nbsp;=&nbsp;origin&nbsp;-&nbsp;hit_position<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset&nbsp;=&nbsp;np.zeros(3,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;For&nbsp;rotation,&nbsp;save&nbsp;initial&nbsp;rotation&nbsp;state,&nbsp;axis,&nbsp;and&nbsp;reference&nbsp;vector<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._is_rotate_element(collider_id):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._target&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose&nbsp;=&nbsp;self._target.transform.global_pose()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_start_quat&nbsp;=&nbsp;np.array(pose.ang,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_start_angle&nbsp;=&nbsp;0.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Save&nbsp;fixed&nbsp;rotation&nbsp;axis<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis&nbsp;=&nbsp;self._get_axis_for_element(collider_id)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_dir&nbsp;=&nbsp;self._get_world_axis(axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_axis&nbsp;=&nbsp;axis_dir.copy()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Compute&nbsp;initial&nbsp;reference&nbsp;vector&nbsp;(rot_vec0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;hit_position&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v0&nbsp;=&nbsp;hit_position&nbsp;-&nbsp;origin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Project&nbsp;onto&nbsp;plane&nbsp;perpendicular&nbsp;to&nbsp;rotation&nbsp;axis<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v0&nbsp;=&nbsp;v0&nbsp;-&nbsp;axis_dir&nbsp;*&nbsp;np.dot(v0,&nbsp;axis_dir)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm_v0&nbsp;=&nbsp;np.linalg.norm(v0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm_v0&nbsp;&gt;&nbsp;1e-6:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_vec0&nbsp;=&nbsp;v0&nbsp;/&nbsp;norm_v0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Hit&nbsp;center&nbsp;-&nbsp;use&nbsp;arbitrary&nbsp;vector&nbsp;in&nbsp;plane<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tangent,&nbsp;_&nbsp;=&nbsp;_build_basis(axis_dir)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_vec0&nbsp;=&nbsp;tangent.copy()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_vec0&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_drag(self,&nbsp;collider_id,&nbsp;position:&nbsp;np.ndarray,&nbsp;delta:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;isinstance(collider_id,&nbsp;TransformElement):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._is_translate_element(collider_id)&nbsp;or&nbsp;self._is_plane_element(collider_id):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._apply_translation(position)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;elif&nbsp;self._is_rotate_element(collider_id):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._apply_rotation(collider_id,&nbsp;position)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._on_transform_changed&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._on_transform_changed()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_release(self,&nbsp;collider_id)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._active_element&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._commit_undo()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_start_pose&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._grab_offset&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_axis&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._drag_center&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_start_quat&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_vec0&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rot_axis&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Transform&nbsp;Application<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_apply_translation(self,&nbsp;projected_position:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Apply&nbsp;translation&nbsp;to&nbsp;target&nbsp;entity.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Apply&nbsp;grab&nbsp;offset&nbsp;to&nbsp;get&nbsp;actual&nbsp;position<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._grab_offset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_position&nbsp;=&nbsp;projected_position&nbsp;+&nbsp;self._grab_offset<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_position&nbsp;=&nbsp;projected_position<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_pose&nbsp;=&nbsp;self._target.transform.global_pose()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_pose&nbsp;=&nbsp;Pose3(lin=new_position,&nbsp;ang=old_pose.ang)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target.transform.relocate_global(new_pose)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_apply_rotation(self,&nbsp;element:&nbsp;TransformElement,&nbsp;plane_hit:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Apply&nbsp;rotation&nbsp;to&nbsp;target&nbsp;entity.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._rot_start_quat&nbsp;is&nbsp;None&nbsp;or&nbsp;self._rot_vec0&nbsp;is&nbsp;None&nbsp;or&nbsp;self._rot_axis&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Use&nbsp;fixed&nbsp;center&nbsp;and&nbsp;axis&nbsp;saved&nbsp;at&nbsp;drag&nbsp;start&nbsp;(not&nbsp;current&nbsp;values!)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;origin&nbsp;=&nbsp;self._drag_center&nbsp;if&nbsp;self._drag_center&nbsp;is&nbsp;not&nbsp;None&nbsp;else&nbsp;self._get_position()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_dir&nbsp;=&nbsp;self._rot_axis<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Compute&nbsp;current&nbsp;vector&nbsp;from&nbsp;center&nbsp;to&nbsp;hit&nbsp;point<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;plane_hit&nbsp;-&nbsp;origin<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Project&nbsp;onto&nbsp;plane&nbsp;perpendicular&nbsp;to&nbsp;axis<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;v1&nbsp;-&nbsp;axis_dir&nbsp;*&nbsp;np.dot(v1,&nbsp;axis_dir)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm_v1&nbsp;=&nbsp;np.linalg.norm(v1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm_v1&nbsp;&lt;&nbsp;1e-6:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v1&nbsp;=&nbsp;v1&nbsp;/&nbsp;norm_v1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Compute&nbsp;angle&nbsp;between&nbsp;initial&nbsp;reference&nbsp;vector&nbsp;and&nbsp;current&nbsp;vector<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dot&nbsp;=&nbsp;float(np.clip(np.dot(self._rot_vec0,&nbsp;v1),&nbsp;-1.0,&nbsp;1.0))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cross&nbsp;=&nbsp;np.cross(self._rot_vec0,&nbsp;v1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sin_angle&nbsp;=&nbsp;np.linalg.norm(cross)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sign&nbsp;=&nbsp;np.sign(np.dot(cross,&nbsp;axis_dir))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;sign&nbsp;==&nbsp;0.0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sign&nbsp;=&nbsp;1.0<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;angle&nbsp;=&nbsp;float(np.arctan2(sin_angle,&nbsp;dot))&nbsp;*&nbsp;sign<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Build&nbsp;rotation&nbsp;quaternion<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;half&nbsp;=&nbsp;angle&nbsp;*&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;s&nbsp;=&nbsp;np.sin(half)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;c&nbsp;=&nbsp;np.cos(half)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dq&nbsp;=&nbsp;np.array([axis_dir[0]&nbsp;*&nbsp;s,&nbsp;axis_dir[1]&nbsp;*&nbsp;s,&nbsp;axis_dir[2]&nbsp;*&nbsp;s,&nbsp;c],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Apply&nbsp;to&nbsp;start&nbsp;rotation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_quat&nbsp;=&nbsp;_quat_mul(dq,&nbsp;self._rot_start_quat)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm_q&nbsp;=&nbsp;np.linalg.norm(new_quat)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm_q&nbsp;&gt;&nbsp;0.0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_quat&nbsp;/=&nbsp;norm_q<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_pose&nbsp;=&nbsp;Pose3(lin=origin,&nbsp;ang=new_quat)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._target.transform.relocate_global(new_pose)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_commit_undo(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Commit&nbsp;transform&nbsp;change&nbsp;to&nbsp;undo&nbsp;stack.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._undo_handler&nbsp;is&nbsp;None&nbsp;or&nbsp;self._target&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._drag_start_pose&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.editor.editor_commands&nbsp;import&nbsp;TransformEditCommand<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tf&nbsp;=&nbsp;self._target.transform<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;end_pose&nbsp;=&nbsp;tf.local_pose()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Check&nbsp;if&nbsp;anything&nbsp;changed<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.allclose(end_pose.lin,&nbsp;self._drag_start_pose.lin)&nbsp;and<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.allclose(end_pose.ang,&nbsp;self._drag_start_pose.ang)&nbsp;and<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.allclose(end_pose.scale,&nbsp;self._drag_start_pose.scale)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cmd&nbsp;=&nbsp;TransformEditCommand(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transform=tf,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old_pose=self._drag_start_pose,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_pose=end_pose,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._undo_handler(cmd,&nbsp;False)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Helpers<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;============================================================<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_is_translate_element(element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;element&nbsp;in&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_X,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_Y,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_Z,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_is_plane_element(element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;element&nbsp;in&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_XY,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_XZ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_YZ,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_is_rotate_element(element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;element&nbsp;in&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_X,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_Y,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_Z,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@staticmethod<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_axis_for_element(element:&nbsp;TransformElement)&nbsp;-&gt;&nbsp;str:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis_map&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_X:&nbsp;&quot;x&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_Y:&nbsp;&quot;y&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.TRANSLATE_Z:&nbsp;&quot;z&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_X:&nbsp;&quot;x&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_Y:&nbsp;&quot;y&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TransformElement.ROTATE_Z:&nbsp;&quot;z&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;axis_map.get(element,&nbsp;&quot;x&quot;)<br>
<br>
<br>
#&nbsp;============================================================<br>
#&nbsp;Quaternion&nbsp;Utilities<br>
#&nbsp;============================================================<br>
<br>
def&nbsp;_quat_rotate(q:&nbsp;np.ndarray,&nbsp;v:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Rotate&nbsp;vector&nbsp;by&nbsp;quaternion&nbsp;(x,&nbsp;y,&nbsp;z,&nbsp;w).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;qv&nbsp;=&nbsp;q[:3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;qw&nbsp;=&nbsp;q[3]<br>
&nbsp;&nbsp;&nbsp;&nbsp;t&nbsp;=&nbsp;2.0&nbsp;*&nbsp;np.cross(qv,&nbsp;v)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;v&nbsp;+&nbsp;qw&nbsp;*&nbsp;t&nbsp;+&nbsp;np.cross(qv,&nbsp;t)<br>
<br>
<br>
def&nbsp;_quat_mul(q1:&nbsp;np.ndarray,&nbsp;q2:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Multiply&nbsp;two&nbsp;quaternions&nbsp;(x,&nbsp;y,&nbsp;z,&nbsp;w).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;x1,&nbsp;y1,&nbsp;z1,&nbsp;w1&nbsp;=&nbsp;q1<br>
&nbsp;&nbsp;&nbsp;&nbsp;x2,&nbsp;y2,&nbsp;z2,&nbsp;w2&nbsp;=&nbsp;q2<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;np.array([<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w1&nbsp;*&nbsp;x2&nbsp;+&nbsp;x1&nbsp;*&nbsp;w2&nbsp;+&nbsp;y1&nbsp;*&nbsp;z2&nbsp;-&nbsp;z1&nbsp;*&nbsp;y2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w1&nbsp;*&nbsp;y2&nbsp;-&nbsp;x1&nbsp;*&nbsp;z2&nbsp;+&nbsp;y1&nbsp;*&nbsp;w2&nbsp;+&nbsp;z1&nbsp;*&nbsp;x2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w1&nbsp;*&nbsp;z2&nbsp;+&nbsp;x1&nbsp;*&nbsp;y2&nbsp;-&nbsp;y1&nbsp;*&nbsp;x2&nbsp;+&nbsp;z1&nbsp;*&nbsp;w2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w1&nbsp;*&nbsp;w2&nbsp;-&nbsp;x1&nbsp;*&nbsp;x2&nbsp;-&nbsp;y1&nbsp;*&nbsp;y2&nbsp;-&nbsp;z1&nbsp;*&nbsp;z2,<br>
&nbsp;&nbsp;&nbsp;&nbsp;],&nbsp;dtype=np.float32)<br>
<br>
<br>
#&nbsp;============================================================<br>
#&nbsp;Matrix&nbsp;Utilities&nbsp;for&nbsp;SolidPrimitiveRenderer<br>
#&nbsp;============================================================<br>
<br>
def&nbsp;_rotation_align_z_to(target:&nbsp;np.ndarray)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Build&nbsp;3x3&nbsp;rotation&nbsp;matrix&nbsp;that&nbsp;rotates&nbsp;Z&nbsp;axis&nbsp;to&nbsp;target&nbsp;direction.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;target&nbsp;=&nbsp;np.asarray(target,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;length&nbsp;=&nbsp;np.linalg.norm(target)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;length&nbsp;&lt;&nbsp;1e-6:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;np.eye(3,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;z_new&nbsp;=&nbsp;target&nbsp;/&nbsp;length<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;up&nbsp;=&nbsp;np.array([0.0,&nbsp;0.0,&nbsp;1.0],&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;abs(np.dot(z_new,&nbsp;up))&nbsp;&gt;&nbsp;0.99:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up&nbsp;=&nbsp;np.array([0.0,&nbsp;1.0,&nbsp;0.0],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;x_new&nbsp;=&nbsp;np.cross(up,&nbsp;z_new)<br>
&nbsp;&nbsp;&nbsp;&nbsp;x_new&nbsp;=&nbsp;x_new&nbsp;/&nbsp;np.linalg.norm(x_new)<br>
&nbsp;&nbsp;&nbsp;&nbsp;y_new&nbsp;=&nbsp;np.cross(z_new,&nbsp;x_new)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;np.column_stack([x_new,&nbsp;y_new,&nbsp;z_new]).astype(np.float32)<br>
<br>
<br>
def&nbsp;_compose_trs(translate:&nbsp;np.ndarray,&nbsp;rotate:&nbsp;np.ndarray,&nbsp;scale:&nbsp;float)&nbsp;-&gt;&nbsp;np.ndarray:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Compose&nbsp;4x4&nbsp;TRS&nbsp;matrix&nbsp;from&nbsp;translation,&nbsp;3x3&nbsp;rotation,&nbsp;and&nbsp;uniform&nbsp;scale.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;m&nbsp;=&nbsp;np.eye(4,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Apply&nbsp;scale&nbsp;to&nbsp;rotation&nbsp;columns<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[:3,&nbsp;0]&nbsp;=&nbsp;rotate[:,&nbsp;0]&nbsp;*&nbsp;scale<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[:3,&nbsp;1]&nbsp;=&nbsp;rotate[:,&nbsp;1]&nbsp;*&nbsp;scale<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[:3,&nbsp;2]&nbsp;=&nbsp;rotate[:,&nbsp;2]&nbsp;*&nbsp;scale<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Translation<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[0,&nbsp;3]&nbsp;=&nbsp;translate[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[1,&nbsp;3]&nbsp;=&nbsp;translate[1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;m[2,&nbsp;3]&nbsp;=&nbsp;translate[2]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;m<br>
<!-- END SCAT CODE -->
</body>
</html>
