<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/components/line_renderer.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
LineRenderer&nbsp;—&nbsp;компонент&nbsp;для&nbsp;рендеринга&nbsp;линий.<br>
<br>
Реализует&nbsp;Drawable&nbsp;протокол&nbsp;для&nbsp;интеграции&nbsp;с&nbsp;ColorPass&nbsp;и&nbsp;другими&nbsp;пассами.<br>
<br>
Два&nbsp;режима&nbsp;работы:<br>
-&nbsp;raw_lines=False&nbsp;(по&nbsp;умолчанию):&nbsp;использует&nbsp;geometry&nbsp;shader&nbsp;для&nbsp;генерации<br>
&nbsp;&nbsp;ленты&nbsp;на&nbsp;GPU,&nbsp;width&nbsp;работает&nbsp;с&nbsp;любым&nbsp;материалом<br>
-&nbsp;raw_lines=True:&nbsp;использует&nbsp;GL_LINES&nbsp;напрямую,&nbsp;width&nbsp;игнорируется,<br>
&nbsp;&nbsp;пользователь&nbsp;может&nbsp;использовать&nbsp;свой&nbsp;geometry&nbsp;shader&nbsp;для&nbsp;толщины<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;uuid<br>
from&nbsp;typing&nbsp;import&nbsp;Iterable,&nbsp;List,&nbsp;Optional,&nbsp;Set,&nbsp;TYPE_CHECKING<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.mesh&nbsp;import&nbsp;TcMesh<br>
from&nbsp;termin.mesh._mesh_native&nbsp;import&nbsp;TcVertexLayout,&nbsp;TcAttribType,&nbsp;TcDrawMode<br>
from&nbsp;termin.visualization.core.python_component&nbsp;import&nbsp;PythonComponent<br>
from&nbsp;termin.visualization.render.render_context&nbsp;import&nbsp;RenderContext<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcMaterial,&nbsp;TcRenderState<br>
from&nbsp;termin.visualization.render.drawable&nbsp;import&nbsp;GeometryDrawCall<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;InspectField<br>
<br>
if&nbsp;TYPE_CHECKING:<br>
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin._native.render&nbsp;import&nbsp;TcMaterialPhase<br>
<br>
<br>
#&nbsp;Дефолтный&nbsp;шейдер&nbsp;для&nbsp;линий<br>
_DEFAULT_LINE_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
_DEFAULT_LINE_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;u_color;<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
def&nbsp;_build_line_ribbon(<br>
&nbsp;&nbsp;&nbsp;&nbsp;points:&nbsp;List[tuple[float,&nbsp;float,&nbsp;float]],<br>
&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;float,<br>
&nbsp;&nbsp;&nbsp;&nbsp;up_hint:&nbsp;np.ndarray&nbsp;=&nbsp;None,<br>
)&nbsp;-&gt;&nbsp;tuple[np.ndarray,&nbsp;np.ndarray]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Строит&nbsp;ленту&nbsp;из&nbsp;треугольников&nbsp;для&nbsp;линии&nbsp;(CPU).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Для&nbsp;каждого&nbsp;сегмента&nbsp;создаёт&nbsp;quad&nbsp;(2&nbsp;треугольника).<br>
&nbsp;&nbsp;&nbsp;&nbsp;Ширина&nbsp;откладывается&nbsp;перпендикулярно&nbsp;направлению&nbsp;линии.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;points:&nbsp;Список&nbsp;точек&nbsp;линии&nbsp;[(x,&nbsp;y,&nbsp;z),&nbsp;...]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;Толщина&nbsp;линии&nbsp;в&nbsp;мировых&nbsp;координатах<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up_hint:&nbsp;Подсказка&nbsp;для&nbsp;направления&nbsp;&quot;вверх&quot;&nbsp;(по&nbsp;умолчанию&nbsp;Y)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Возвращает:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(vertices,&nbsp;triangles)&nbsp;—&nbsp;массивы&nbsp;для&nbsp;меша<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;len(points)&nbsp;&lt;&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;np.zeros((0,&nbsp;3),&nbsp;dtype=np.float32),&nbsp;np.zeros((0,&nbsp;3),&nbsp;dtype=np.int32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;up_hint&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up_hint&nbsp;=&nbsp;np.array([0.0,&nbsp;1.0,&nbsp;0.0],&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;pts&nbsp;=&nbsp;np.array(points,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;n_points&nbsp;=&nbsp;len(pts)<br>
&nbsp;&nbsp;&nbsp;&nbsp;n_segments&nbsp;=&nbsp;n_points&nbsp;-&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Для&nbsp;каждой&nbsp;точки&nbsp;вычисляем&nbsp;направление&nbsp;и&nbsp;перпендикуляр<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;На&nbsp;стыках&nbsp;усредняем&nbsp;направления&nbsp;соседних&nbsp;сегментов<br>
&nbsp;&nbsp;&nbsp;&nbsp;directions&nbsp;=&nbsp;np.zeros((n_points,&nbsp;3),&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_segments):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_dir&nbsp;=&nbsp;pts[i&nbsp;+&nbsp;1]&nbsp;-&nbsp;pts[i]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_len&nbsp;=&nbsp;np.linalg.norm(seg_dir)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;seg_len&nbsp;&gt;&nbsp;1e-8:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;seg_dir&nbsp;/=&nbsp;seg_len<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directions[i]&nbsp;+=&nbsp;seg_dir<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directions[i&nbsp;+&nbsp;1]&nbsp;+=&nbsp;seg_dir<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нормализуем&nbsp;направления<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_points):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d_len&nbsp;=&nbsp;np.linalg.norm(directions[i])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;d_len&nbsp;&gt;&nbsp;1e-8:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;directions[i]&nbsp;/=&nbsp;d_len<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Вычисляем&nbsp;перпендикуляры<br>
&nbsp;&nbsp;&nbsp;&nbsp;half_width&nbsp;=&nbsp;width&nbsp;*&nbsp;0.5<br>
&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_points):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;p&nbsp;=&nbsp;pts[i]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;d&nbsp;=&nbsp;directions[i]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Перпендикуляр&nbsp;=&nbsp;cross(direction,&nbsp;up_hint)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp&nbsp;=&nbsp;np.cross(d,&nbsp;up_hint)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp_len&nbsp;=&nbsp;np.linalg.norm(perp)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;perp_len&nbsp;&lt;&nbsp;1e-8:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Линия&nbsp;параллельна&nbsp;up_hint,&nbsp;используем&nbsp;другую&nbsp;ось<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;alt_up&nbsp;=&nbsp;np.array([1.0,&nbsp;0.0,&nbsp;0.0],&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp&nbsp;=&nbsp;np.cross(d,&nbsp;alt_up)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp_len&nbsp;=&nbsp;np.linalg.norm(perp)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;perp_len&nbsp;&lt;&nbsp;1e-8:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;alt_up&nbsp;=&nbsp;np.array([0.0,&nbsp;0.0,&nbsp;1.0],&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp&nbsp;=&nbsp;np.cross(d,&nbsp;alt_up)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp_len&nbsp;=&nbsp;np.linalg.norm(perp)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;perp_len&nbsp;&gt;&nbsp;1e-8:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;perp&nbsp;/=&nbsp;perp_len<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Две&nbsp;вершины:&nbsp;слева&nbsp;и&nbsp;справа&nbsp;от&nbsp;центра<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v_left&nbsp;=&nbsp;p&nbsp;-&nbsp;perp&nbsp;*&nbsp;half_width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v_right&nbsp;=&nbsp;p&nbsp;+&nbsp;perp&nbsp;*&nbsp;half_width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices.append(v_left)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices.append(v_right)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;np.array(vertices,&nbsp;dtype=np.float32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Строим&nbsp;треугольники<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Для&nbsp;каждого&nbsp;сегмента:&nbsp;2&nbsp;треугольника&nbsp;из&nbsp;4&nbsp;вершин<br>
&nbsp;&nbsp;&nbsp;&nbsp;triangles&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_segments):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Индексы&nbsp;вершин&nbsp;для&nbsp;сегмента&nbsp;i<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bl&nbsp;=&nbsp;i&nbsp;*&nbsp;2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;bottom-left<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;br&nbsp;=&nbsp;i&nbsp;*&nbsp;2&nbsp;+&nbsp;1&nbsp;&nbsp;#&nbsp;bottom-right<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tl&nbsp;=&nbsp;(i&nbsp;+&nbsp;1)&nbsp;*&nbsp;2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;top-left<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;tr&nbsp;=&nbsp;(i&nbsp;+&nbsp;1)&nbsp;*&nbsp;2&nbsp;+&nbsp;1&nbsp;&nbsp;#&nbsp;top-right<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Два&nbsp;треугольника<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;triangles.append([bl,&nbsp;tl,&nbsp;br])<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;triangles.append([br,&nbsp;tl,&nbsp;tr])<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;triangles&nbsp;=&nbsp;np.array(triangles,&nbsp;dtype=np.int32)&nbsp;if&nbsp;triangles&nbsp;else&nbsp;np.zeros((0,&nbsp;3),&nbsp;dtype=np.int32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;vertices,&nbsp;triangles<br>
<br>
<br>
class&nbsp;LineRenderer(PythonComponent):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;Компонент&nbsp;для&nbsp;рендеринга&nbsp;линий.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Реализует&nbsp;Drawable&nbsp;протокол&nbsp;для&nbsp;интеграции&nbsp;с&nbsp;ColorPass.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Атрибуты:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;points:&nbsp;Список&nbsp;точек&nbsp;линии&nbsp;[(x,&nbsp;y,&nbsp;z),&nbsp;...].<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;Толщина&nbsp;линии&nbsp;(в&nbsp;мировых&nbsp;координатах).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raw_lines:&nbsp;Если&nbsp;True,&nbsp;использует&nbsp;GL_LINES&nbsp;без&nbsp;geometry&nbsp;shader.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material:&nbsp;Материал&nbsp;для&nbsp;рендеринга&nbsp;(если&nbsp;None&nbsp;—&nbsp;создаётся&nbsp;дефолтный).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Фильтрация&nbsp;по&nbsp;фазам:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase_marks&nbsp;=&nbsp;фазы&nbsp;из&nbsp;материала.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;get_phases(phase_mark)&nbsp;возвращает&nbsp;MaterialPhase&nbsp;с&nbsp;совпадающим&nbsp;phase_mark.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;is_drawable&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;inspect_fields&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;points&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;points&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Points&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;vec3_list&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setter=lambda&nbsp;obj,&nbsp;value:&nbsp;obj.set_points(value),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;width&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;width&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Width&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;float&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=0.001,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max=10.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;step=0.01,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setter=lambda&nbsp;obj,&nbsp;value:&nbsp;obj.set_width(value),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;raw_lines&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;raw_lines&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Raw&nbsp;Lines&nbsp;(GL_LINES)&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;bool&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setter=lambda&nbsp;obj,&nbsp;value:&nbsp;obj.set_raw_lines(value),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;points:&nbsp;Iterable[tuple[float,&nbsp;float,&nbsp;float]]&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width:&nbsp;float&nbsp;=&nbsp;0.1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raw_lines:&nbsp;bool&nbsp;=&nbsp;False,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material:&nbsp;TcMaterial&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(enabled=True)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._points:&nbsp;List[tuple[float,&nbsp;float,&nbsp;float]]&nbsp;=&nbsp;list(points)&nbsp;if&nbsp;points&nbsp;else&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._width:&nbsp;float&nbsp;=&nbsp;width<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._raw_lines:&nbsp;bool&nbsp;=&nbsp;raw_lines<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Материал&nbsp;(TcMaterial&nbsp;or&nbsp;None&nbsp;for&nbsp;default)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._material:&nbsp;TcMaterial&nbsp;|&nbsp;None&nbsp;=&nbsp;material<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;TcMesh&nbsp;(always&nbsp;GL_LINES)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mesh:&nbsp;TcMesh&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Флаг&nbsp;необходимости&nbsp;перестроения&nbsp;меша<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._dirty&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Cached&nbsp;line&nbsp;ribbon&nbsp;material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material:&nbsp;TcMaterial&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material_source_uuid:&nbsp;str&nbsp;=&nbsp;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;phase_marks(self)&nbsp;-&gt;&nbsp;Set[str]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает&nbsp;множество&nbsp;phase_marks&nbsp;для&nbsp;этого&nbsp;renderer'а.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Собирается&nbsp;из&nbsp;phase_mark&nbsp;каждой&nbsp;фазы&nbsp;материала.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;marks:&nbsp;Set[str]&nbsp;=&nbsp;set()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;self._get_effective_material()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;marks<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(mat.phase_count):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase&nbsp;=&nbsp;mat.get_phase(i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;phase&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;marks.add(phase.phase_mark)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;marks<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Properties&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;points(self)&nbsp;-&gt;&nbsp;List[tuple[float,&nbsp;float,&nbsp;float]]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Список&nbsp;точек&nbsp;линии.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._points<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@points.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;points(self,&nbsp;value:&nbsp;Iterable[tuple[float,&nbsp;float,&nbsp;float]]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_points&nbsp;=&nbsp;list(value)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;new_points&nbsp;!=&nbsp;self._points:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._points&nbsp;=&nbsp;new_points<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._dirty&nbsp;=&nbsp;True<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;width(self)&nbsp;-&gt;&nbsp;float:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Толщина&nbsp;линии&nbsp;в&nbsp;мировых&nbsp;координатах.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._width<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@width.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;width(self,&nbsp;value:&nbsp;float):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._width&nbsp;=&nbsp;value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;width&nbsp;не&nbsp;требует&nbsp;пересборки&nbsp;меша&nbsp;-&nbsp;передаётся&nbsp;как&nbsp;uniform<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;raw_lines(self)&nbsp;-&gt;&nbsp;bool:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Режим&nbsp;GL_LINES&nbsp;без&nbsp;geometry&nbsp;shader.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._raw_lines<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@raw_lines.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;raw_lines(self,&nbsp;value:&nbsp;bool):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._raw_lines&nbsp;!=&nbsp;value:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._raw_lines&nbsp;=&nbsp;value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Invalidate&nbsp;cached&nbsp;ribbon&nbsp;material<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@property<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;material(self)&nbsp;-&gt;&nbsp;TcMaterial&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Текущий&nbsp;материал.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._material<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;@material.setter<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;material(self,&nbsp;value:&nbsp;TcMaterial&nbsp;|&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._material&nbsp;=&nbsp;value<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material&nbsp;=&nbsp;None&nbsp;&nbsp;#&nbsp;Invalidate&nbsp;cached&nbsp;ribbon&nbsp;material<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Setters&nbsp;for&nbsp;inspector&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_points(self,&nbsp;points:&nbsp;Iterable[tuple[float,&nbsp;float,&nbsp;float]]):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;точки&nbsp;линии.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.points&nbsp;=&nbsp;points<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_width(self,&nbsp;value:&nbsp;float):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;толщину&nbsp;линии.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.width&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_raw_lines(self,&nbsp;value:&nbsp;bool):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;режим&nbsp;GL_LINES.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.raw_lines&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_material(self,&nbsp;value:&nbsp;TcMaterial&nbsp;|&nbsp;None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;материал.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.material&nbsp;=&nbsp;value<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;set_material_by_name(self,&nbsp;name:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Устанавливает&nbsp;материал&nbsp;по&nbsp;имени&nbsp;из&nbsp;ResourceManager.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.assets.resources&nbsp;import&nbsp;ResourceManager<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm&nbsp;=&nbsp;ResourceManager.instance()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;asset&nbsp;=&nbsp;rm.get_material_asset(name)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;asset&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._material&nbsp;=&nbsp;asset.material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._material&nbsp;=&nbsp;None<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Geometry&nbsp;building&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_rebuild_geometry(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Перестраивает&nbsp;меш&nbsp;из&nbsp;точек.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mesh&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_points&nbsp;=&nbsp;len(self._points)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;n_points&nbsp;&lt;&nbsp;2:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._dirty&nbsp;=&nbsp;False<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Layout:&nbsp;position&nbsp;only&nbsp;(vec3)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout&nbsp;=&nbsp;TcVertexLayout()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout.add(&quot;position&quot;,&nbsp;3,&nbsp;TcAttribType.FLOAT32,&nbsp;0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Vertices:&nbsp;just&nbsp;positions<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices&nbsp;=&nbsp;np.array(self._points,&nbsp;dtype=np.float32).flatten()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Indices:&nbsp;pairs&nbsp;for&nbsp;each&nbsp;line&nbsp;segment<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;n_segments&nbsp;=&nbsp;n_points&nbsp;-&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices&nbsp;=&nbsp;np.zeros(n_segments&nbsp;*&nbsp;2,&nbsp;dtype=np.uint32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(n_segments):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices[i&nbsp;*&nbsp;2]&nbsp;=&nbsp;i<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices[i&nbsp;*&nbsp;2&nbsp;+&nbsp;1]&nbsp;=&nbsp;i&nbsp;+&nbsp;1<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Generate&nbsp;unique&nbsp;uuid&nbsp;for&nbsp;mesh&nbsp;registry&nbsp;lookup<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh_uuid&nbsp;=&nbsp;str(uuid.uuid4())<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mesh&nbsp;=&nbsp;TcMesh.from_interleaved(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertices=vertices,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_count=n_points,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;indices=indices,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;layout=layout,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=&quot;line_renderer&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;uuid=mesh_uuid,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;draw_mode=TcDrawMode.LINES,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._dirty&nbsp;=&nbsp;False<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_ensure_geometry(self):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Ленивое&nbsp;построение&nbsp;геометрии.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._dirty:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._rebuild_geometry()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_mesh(self)&nbsp;-&gt;&nbsp;TcMesh&nbsp;|&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;TcMesh.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ensure_geometry()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._mesh<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Class-level&nbsp;cache&nbsp;for&nbsp;default&nbsp;line&nbsp;material<br>
&nbsp;&nbsp;&nbsp;&nbsp;_default_material:&nbsp;Optional[TcMaterial]&nbsp;=&nbsp;None<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_base_material(self)&nbsp;-&gt;&nbsp;TcMaterial:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;базовый&nbsp;материал&nbsp;(без&nbsp;ribbon&nbsp;трансформации).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;self._material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mat&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;LineRenderer._default_material&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Create&nbsp;TcMaterial&nbsp;with&nbsp;default&nbsp;line&nbsp;shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default_mat&nbsp;=&nbsp;TcMaterial.create(name=&quot;DefaultLineMaterial&quot;,&nbsp;uuid_hint=&quot;&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;default_mat.shader_name&nbsp;=&nbsp;&quot;DefaultLineShader&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;state&nbsp;=&nbsp;TcRenderState.opaque()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;state.cull&nbsp;=&nbsp;0&nbsp;&nbsp;#&nbsp;Disable&nbsp;backface&nbsp;culling&nbsp;for&nbsp;lines<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase&nbsp;=&nbsp;default_mat.add_phase_from_sources(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vertex_source=_DEFAULT_LINE_VERT,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fragment_source=_DEFAULT_LINE_FRAG,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry_source=&quot;&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shader_name=&quot;DefaultLineShader&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase_mark=&quot;opaque&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;priority=0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;state=state,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;phase&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase.set_color(1.0,&nbsp;1.0,&nbsp;1.0,&nbsp;1.0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LineRenderer._default_material&nbsp;=&nbsp;default_mat<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;LineRenderer._default_material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;mat<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_get_effective_material(self)&nbsp;-&gt;&nbsp;TcMaterial:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Возвращает&nbsp;материал&nbsp;с&nbsp;учётом&nbsp;режима&nbsp;(ribbon&nbsp;или&nbsp;raw).&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;base_mat&nbsp;=&nbsp;self._get_base_material()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._raw_lines:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Raw&nbsp;mode&nbsp;-&nbsp;use&nbsp;material&nbsp;as-is<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;base_mat<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Ribbon&nbsp;mode&nbsp;-&nbsp;apply&nbsp;line&nbsp;ribbon&nbsp;transformation<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;source_uuid&nbsp;=&nbsp;base_mat.uuid<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self._ribbon_material&nbsp;is&nbsp;None&nbsp;or&nbsp;self._ribbon_material_source_uuid&nbsp;!=&nbsp;source_uuid:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;termin.visualization.render.shader_line_ribbon&nbsp;import&nbsp;get_line_ribbon_material<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material&nbsp;=&nbsp;get_line_ribbon_material(base_mat)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ribbon_material_source_uuid&nbsp;=&nbsp;source_uuid<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;self._ribbon_material<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Drawable&nbsp;protocol&nbsp;---<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw_geometry(self,&nbsp;context:&nbsp;RenderContext,&nbsp;geometry_id:&nbsp;int&nbsp;=&nbsp;0)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Рисует&nbsp;геометрию&nbsp;линий&nbsp;(шейдер&nbsp;уже&nbsp;привязан&nbsp;пассом).<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context:&nbsp;Контекст&nbsp;рендеринга.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;geometry_id:&nbsp;Идентификатор&nbsp;геометрии&nbsp;(игнорируется&nbsp;—&nbsp;одна&nbsp;геометрия).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh&nbsp;=&nbsp;self._get_mesh()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;mesh&nbsp;is&nbsp;None&nbsp;or&nbsp;not&nbsp;mesh.is_valid:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Set&nbsp;line&nbsp;width&nbsp;uniform&nbsp;for&nbsp;geometry&nbsp;shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;self._raw_lines&nbsp;and&nbsp;context.current_shader&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;context.current_shader.set_uniform_float(&quot;u_line_width&quot;,&nbsp;self._width)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh.draw_gpu()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;get_geometry_draws(self,&nbsp;phase_mark:&nbsp;str&nbsp;|&nbsp;None&nbsp;=&nbsp;None)&nbsp;-&gt;&nbsp;List[GeometryDrawCall]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает&nbsp;GeometryDrawCalls&nbsp;для&nbsp;указанной&nbsp;метки&nbsp;фазы.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Параметры:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase_mark:&nbsp;Фильтр&nbsp;по&nbsp;метке&nbsp;(&quot;opaque&quot;,&nbsp;&quot;transparent&quot;,&nbsp;&quot;editor&quot;,&nbsp;etc.)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Если&nbsp;None,&nbsp;возвращает&nbsp;все&nbsp;фазы.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Возвращает:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Список&nbsp;GeometryDrawCall&nbsp;с&nbsp;совпадающим&nbsp;phase_mark,&nbsp;отсортированный&nbsp;по&nbsp;priority.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mat&nbsp;=&nbsp;self._get_effective_material()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Collect&nbsp;phases&nbsp;from&nbsp;TcMaterial<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phases:&nbsp;List[&quot;TcMaterialPhase&quot;]&nbsp;=&nbsp;[]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(mat.phase_count):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phase&nbsp;=&nbsp;mat.get_phase(i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;phase&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;continue<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;phase_mark&nbsp;is&nbsp;None&nbsp;or&nbsp;phase.phase_mark&nbsp;==&nbsp;phase_mark:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phases.append(phase)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Note:&nbsp;culling&nbsp;is&nbsp;already&nbsp;disabled&nbsp;in&nbsp;the&nbsp;material's&nbsp;render&nbsp;state<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;phases.sort(key=lambda&nbsp;p:&nbsp;p.priority)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;[GeometryDrawCall(phase=p)&nbsp;for&nbsp;p&nbsp;in&nbsp;phases]<br>
<!-- END SCAT CODE -->
</body>
</html>
