<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/render/posteffects/bloom.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;BloomEffect&nbsp;-&nbsp;HDR&nbsp;bloom&nbsp;post-processing&nbsp;effect.<br>
<br>
Uses&nbsp;progressive&nbsp;downsampling/upsampling&nbsp;for&nbsp;wide,&nbsp;high-quality&nbsp;bloom.<br>
Based&nbsp;on&nbsp;the&nbsp;approach&nbsp;used&nbsp;in&nbsp;Unreal&nbsp;Engine&nbsp;and&nbsp;Unity.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
from&nbsp;..postprocess&nbsp;import&nbsp;PostEffect<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;InspectField<br>
<br>
<br>
#&nbsp;================================================================<br>
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BRIGHT&nbsp;PASS&nbsp;-&nbsp;Extract&nbsp;pixels&nbsp;above&nbsp;threshold<br>
#&nbsp;================================================================<br>
<br>
BRIGHT_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location=0)&nbsp;in&nbsp;vec2&nbsp;a_pos;<br>
layout(location=1)&nbsp;in&nbsp;vec2&nbsp;a_uv;<br>
out&nbsp;vec2&nbsp;v_uv;<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_uv&nbsp;=&nbsp;a_uv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;vec4(a_pos,&nbsp;0.0,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
BRIGHT_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec2&nbsp;v_uv;<br>
<br>
uniform&nbsp;sampler2D&nbsp;u_texture;<br>
uniform&nbsp;float&nbsp;u_threshold;<br>
uniform&nbsp;float&nbsp;u_soft_threshold;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Calculate&nbsp;brightness&nbsp;(luminance)<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;brightness&nbsp;=&nbsp;dot(color,&nbsp;vec3(0.2126,&nbsp;0.7152,&nbsp;0.0722));<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Soft&nbsp;threshold&nbsp;with&nbsp;knee<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;knee&nbsp;=&nbsp;u_threshold&nbsp;*&nbsp;u_soft_threshold;<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;soft&nbsp;=&nbsp;brightness&nbsp;-&nbsp;u_threshold&nbsp;+&nbsp;knee;<br>
&nbsp;&nbsp;&nbsp;&nbsp;soft&nbsp;=&nbsp;clamp(soft,&nbsp;0.0,&nbsp;2.0&nbsp;*&nbsp;knee);<br>
&nbsp;&nbsp;&nbsp;&nbsp;soft&nbsp;=&nbsp;soft&nbsp;*&nbsp;soft&nbsp;/&nbsp;(4.0&nbsp;*&nbsp;knee&nbsp;+&nbsp;0.00001);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;contribution&nbsp;=&nbsp;max(soft,&nbsp;brightness&nbsp;-&nbsp;u_threshold)&nbsp;/&nbsp;max(brightness,&nbsp;0.00001);<br>
&nbsp;&nbsp;&nbsp;&nbsp;contribution&nbsp;=&nbsp;max(contribution,&nbsp;0.0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color&nbsp;*&nbsp;contribution,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
#&nbsp;================================================================<br>
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DOWNSAMPLE&nbsp;PASS&nbsp;-&nbsp;4x4&nbsp;box&nbsp;filter&nbsp;with&nbsp;bilinear&nbsp;sampling<br>
#&nbsp;================================================================<br>
<br>
DOWNSAMPLE_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location=0)&nbsp;in&nbsp;vec2&nbsp;a_pos;<br>
layout(location=1)&nbsp;in&nbsp;vec2&nbsp;a_uv;<br>
out&nbsp;vec2&nbsp;v_uv;<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_uv&nbsp;=&nbsp;a_uv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;vec4(a_pos,&nbsp;0.0,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
DOWNSAMPLE_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec2&nbsp;v_uv;<br>
<br>
uniform&nbsp;sampler2D&nbsp;u_texture;<br>
uniform&nbsp;vec2&nbsp;u_texel_size;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;13-tap&nbsp;downsample&nbsp;(Karis&nbsp;average&nbsp;style)<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Reduces&nbsp;fireflies&nbsp;and&nbsp;gives&nbsp;better&nbsp;quality<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec2&nbsp;ts&nbsp;=&nbsp;u_texel_size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;a&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-2.0,&nbsp;-2.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;b&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;-2.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;c&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;2.0,&nbsp;-2.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;d&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-2.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;e&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;f&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;2.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;g&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-2.0,&nbsp;&nbsp;2.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;h&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;&nbsp;2.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;i&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;2.0,&nbsp;&nbsp;2.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;j&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-1.0,&nbsp;-1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;k&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;1.0,&nbsp;-1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;l&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-1.0,&nbsp;&nbsp;1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;m&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;1.0,&nbsp;&nbsp;1.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Weighted&nbsp;average<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;result&nbsp;=&nbsp;e&nbsp;*&nbsp;0.125;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;+=&nbsp;(a&nbsp;+&nbsp;c&nbsp;+&nbsp;g&nbsp;+&nbsp;i)&nbsp;*&nbsp;0.03125;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;+=&nbsp;(b&nbsp;+&nbsp;d&nbsp;+&nbsp;f&nbsp;+&nbsp;h)&nbsp;*&nbsp;0.0625;<br>
&nbsp;&nbsp;&nbsp;&nbsp;result&nbsp;+=&nbsp;(j&nbsp;+&nbsp;k&nbsp;+&nbsp;l&nbsp;+&nbsp;m)&nbsp;*&nbsp;0.125;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(result,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
#&nbsp;================================================================<br>
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;UPSAMPLE&nbsp;PASS&nbsp;-&nbsp;Tent&nbsp;filter&nbsp;(3x3)&nbsp;with&nbsp;additive&nbsp;blend<br>
#&nbsp;================================================================<br>
<br>
UPSAMPLE_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location=0)&nbsp;in&nbsp;vec2&nbsp;a_pos;<br>
layout(location=1)&nbsp;in&nbsp;vec2&nbsp;a_uv;<br>
out&nbsp;vec2&nbsp;v_uv;<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_uv&nbsp;=&nbsp;a_uv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;vec4(a_pos,&nbsp;0.0,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
UPSAMPLE_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec2&nbsp;v_uv;<br>
<br>
uniform&nbsp;sampler2D&nbsp;u_texture;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Lower&nbsp;mip&nbsp;(being&nbsp;upsampled)<br>
uniform&nbsp;sampler2D&nbsp;u_higher_mip;&nbsp;&nbsp;&nbsp;//&nbsp;Higher&nbsp;mip&nbsp;(to&nbsp;blend&nbsp;with)<br>
uniform&nbsp;vec2&nbsp;u_texel_size;<br>
uniform&nbsp;float&nbsp;u_blend_factor;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;How&nbsp;much&nbsp;of&nbsp;the&nbsp;upsampled&nbsp;to&nbsp;add<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;9-tap&nbsp;tent&nbsp;filter&nbsp;for&nbsp;smooth&nbsp;upsampling<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec2&nbsp;ts&nbsp;=&nbsp;u_texel_size;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;a&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-1.0,&nbsp;-1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;b&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;-1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;c&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;1.0,&nbsp;-1.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;d&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-1.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;e&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;f&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;1.0,&nbsp;&nbsp;0.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;g&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(-1.0,&nbsp;&nbsp;1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;h&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;0.0,&nbsp;&nbsp;1.0)&nbsp;*&nbsp;ts).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;i&nbsp;=&nbsp;texture(u_texture,&nbsp;v_uv&nbsp;+&nbsp;vec2(&nbsp;1.0,&nbsp;&nbsp;1.0)&nbsp;*&nbsp;ts).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Tent&nbsp;filter&nbsp;weights<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;upsampled&nbsp;=&nbsp;e&nbsp;*&nbsp;4.0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;upsampled&nbsp;+=&nbsp;(b&nbsp;+&nbsp;d&nbsp;+&nbsp;f&nbsp;+&nbsp;h)&nbsp;*&nbsp;2.0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;upsampled&nbsp;+=&nbsp;(a&nbsp;+&nbsp;c&nbsp;+&nbsp;g&nbsp;+&nbsp;i);<br>
&nbsp;&nbsp;&nbsp;&nbsp;upsampled&nbsp;/=&nbsp;16.0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Blend&nbsp;with&nbsp;higher&nbsp;resolution&nbsp;mip<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;higher&nbsp;=&nbsp;texture(u_higher_mip,&nbsp;v_uv).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(higher&nbsp;+&nbsp;upsampled&nbsp;*&nbsp;u_blend_factor,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
#&nbsp;================================================================<br>
#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;COMPOSITE&nbsp;PASS&nbsp;-&nbsp;Blend&nbsp;bloom&nbsp;with&nbsp;original<br>
#&nbsp;================================================================<br>
<br>
COMPOSITE_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location=0)&nbsp;in&nbsp;vec2&nbsp;a_pos;<br>
layout(location=1)&nbsp;in&nbsp;vec2&nbsp;a_uv;<br>
out&nbsp;vec2&nbsp;v_uv;<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_uv&nbsp;=&nbsp;a_uv;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;vec4(a_pos,&nbsp;0.0,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
COMPOSITE_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec2&nbsp;v_uv;<br>
<br>
uniform&nbsp;sampler2D&nbsp;u_original;<br>
uniform&nbsp;sampler2D&nbsp;u_bloom;<br>
uniform&nbsp;float&nbsp;u_intensity;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;original&nbsp;=&nbsp;texture(u_original,&nbsp;v_uv).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;bloom&nbsp;=&nbsp;texture(u_bloom,&nbsp;v_uv).rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;//&nbsp;Additive&nbsp;blend<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;result&nbsp;=&nbsp;original&nbsp;+&nbsp;bloom&nbsp;*&nbsp;u_intensity;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(result,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
#&nbsp;Lazy-loaded&nbsp;shared&nbsp;shaders<br>
_bright_shader:&nbsp;TcShader&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
_downsample_shader:&nbsp;TcShader&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
_upsample_shader:&nbsp;TcShader&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
_composite_shader:&nbsp;TcShader&nbsp;|&nbsp;None&nbsp;=&nbsp;None<br>
<br>
<br>
def&nbsp;_get_bright_shader()&nbsp;-&gt;&nbsp;TcShader:<br>
&nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;_bright_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;_bright_shader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_bright_shader&nbsp;=&nbsp;TcShader.from_sources(BRIGHT_VERT,&nbsp;BRIGHT_FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;BloomBright&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_bright_shader<br>
<br>
<br>
def&nbsp;_get_downsample_shader()&nbsp;-&gt;&nbsp;TcShader:<br>
&nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;_downsample_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;_downsample_shader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_downsample_shader&nbsp;=&nbsp;TcShader.from_sources(DOWNSAMPLE_VERT,&nbsp;DOWNSAMPLE_FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;BloomDownsample&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_downsample_shader<br>
<br>
<br>
def&nbsp;_get_upsample_shader()&nbsp;-&gt;&nbsp;TcShader:<br>
&nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;_upsample_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;_upsample_shader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_upsample_shader&nbsp;=&nbsp;TcShader.from_sources(UPSAMPLE_VERT,&nbsp;UPSAMPLE_FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;BloomUpsample&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_upsample_shader<br>
<br>
<br>
def&nbsp;_get_composite_shader()&nbsp;-&gt;&nbsp;TcShader:<br>
&nbsp;&nbsp;&nbsp;&nbsp;global&nbsp;_composite_shader<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;_composite_shader&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_composite_shader&nbsp;=&nbsp;TcShader.from_sources(COMPOSITE_VERT,&nbsp;COMPOSITE_FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;BloomComposite&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;_composite_shader<br>
<br>
<br>
class&nbsp;BloomEffect(PostEffect):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;HDR&nbsp;Bloom&nbsp;post-processing&nbsp;effect&nbsp;with&nbsp;progressive&nbsp;downsampling.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;Uses&nbsp;mip-chain&nbsp;approach:&nbsp;downsample&nbsp;-&gt;&nbsp;blur&nbsp;at&nbsp;each&nbsp;level&nbsp;-&gt;&nbsp;upsample.<br>
&nbsp;&nbsp;&nbsp;&nbsp;This&nbsp;creates&nbsp;wide,&nbsp;smooth&nbsp;bloom&nbsp;with&nbsp;good&nbsp;performance.<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;For&nbsp;best&nbsp;results,&nbsp;use&nbsp;with&nbsp;HDR&nbsp;framebuffer&nbsp;(rgba16f&nbsp;format)&nbsp;and<br>
&nbsp;&nbsp;&nbsp;&nbsp;emission&nbsp;intensity&nbsp;&gt;&nbsp;1.0&nbsp;in&nbsp;materials.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;name&nbsp;=&nbsp;&quot;bloom&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;inspect_fields&nbsp;=&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;threshold&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;threshold&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Threshold&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;float&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=0.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max=10.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;soft_threshold&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;soft_threshold&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Soft&nbsp;Knee&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;float&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=0.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max=1.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;intensity&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;intensity&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Intensity&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;float&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=0.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max=5.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;mip_levels&quot;:&nbsp;InspectField(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;path=&quot;mip_levels&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Mip&nbsp;Levels&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;kind=&quot;int&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=1,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;max=8,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;),<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;threshold:&nbsp;float&nbsp;=&nbsp;1.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;soft_threshold:&nbsp;float&nbsp;=&nbsp;0.5,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;intensity:&nbsp;float&nbsp;=&nbsp;1.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip_levels:&nbsp;int&nbsp;=&nbsp;5,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.threshold&nbsp;=&nbsp;threshold<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.soft_threshold&nbsp;=&nbsp;soft_threshold<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.intensity&nbsp;=&nbsp;intensity<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.mip_levels&nbsp;=&nbsp;mip_levels<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Mip&nbsp;chain&nbsp;FBOs<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mip_fbos&nbsp;=&nbsp;[]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;_ensure_mip_fbos(self,&nbsp;graphics,&nbsp;base_size:&nbsp;tuple[int,&nbsp;int],&nbsp;format_str:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Ensure&nbsp;we&nbsp;have&nbsp;FBOs&nbsp;for&nbsp;each&nbsp;mip&nbsp;level.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w,&nbsp;h&nbsp;=&nbsp;base_size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip_levels&nbsp;=&nbsp;int(self.mip_levels)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(mip_levels):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip_w&nbsp;=&nbsp;max(1,&nbsp;w&nbsp;&gt;&gt;&nbsp;i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip_h&nbsp;=&nbsp;max(1,&nbsp;h&nbsp;&gt;&gt;&nbsp;i)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;i&nbsp;&gt;=&nbsp;len(self._mip_fbos):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo&nbsp;=&nbsp;graphics.create_framebuffer((mip_w,&nbsp;mip_h),&nbsp;1,&nbsp;format_str)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mip_fbos.append(fbo)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mip_fbos[i].resize(mip_w,&nbsp;mip_h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;while&nbsp;len(self._mip_fbos)&nbsp;&gt;&nbsp;mip_levels:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo&nbsp;=&nbsp;self._mip_fbos.pop()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo.delete()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;draw(self,&nbsp;gfx,color_tex,&nbsp;extra_textures,&nbsp;size,&nbsp;target_fbo=None):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Execute&nbsp;bloom&nbsp;effect&nbsp;with&nbsp;progressive&nbsp;downsample/upsample.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;w,&nbsp;h&nbsp;=&nbsp;size<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;format_str&nbsp;=&nbsp;&quot;rgba16f&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip_levels&nbsp;=&nbsp;int(self.mip_levels)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._ensure_mip_fbos(gfx,&nbsp;size,&nbsp;format_str)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_depth_test(False)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_blend(False)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;===&nbsp;1.&nbsp;Bright&nbsp;Pass&nbsp;-&gt;&nbsp;mip[0]&nbsp;===<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mip0&nbsp;=&nbsp;self._mip_fbos[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.bind_framebuffer(mip0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_viewport(0,&nbsp;0,&nbsp;w,&nbsp;h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright&nbsp;=&nbsp;_get_bright_shader()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright.ensure_ready()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright.use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color_tex.bind(0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright.set_uniform_int(&quot;u_texture&quot;,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright.set_uniform_float(&quot;u_threshold&quot;,&nbsp;self.threshold)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;bright.set_uniform_float(&quot;u_soft_threshold&quot;,&nbsp;self.soft_threshold)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.draw_ui_textured_quad()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;===&nbsp;2.&nbsp;Progressive&nbsp;Downsample&nbsp;===<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down&nbsp;=&nbsp;_get_downsample_shader()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down.ensure_ready()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down.use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(1,&nbsp;mip_levels):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_fbo&nbsp;=&nbsp;self._mip_fbos[i&nbsp;-&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_fbo&nbsp;=&nbsp;self._mip_fbos[i]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_w&nbsp;=&nbsp;max(1,&nbsp;w&nbsp;&gt;&gt;&nbsp;(i&nbsp;-&nbsp;1))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_h&nbsp;=&nbsp;max(1,&nbsp;h&nbsp;&gt;&gt;&nbsp;(i&nbsp;-&nbsp;1))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_w&nbsp;=&nbsp;max(1,&nbsp;w&nbsp;&gt;&gt;&nbsp;i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_h&nbsp;=&nbsp;max(1,&nbsp;h&nbsp;&gt;&gt;&nbsp;i)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.bind_framebuffer(dst_fbo)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_viewport(0,&nbsp;0,&nbsp;dst_w,&nbsp;dst_h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_fbo.color_texture().bind(0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down.set_uniform_int(&quot;u_texture&quot;,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down.set_uniform_vec2(&quot;u_texel_size&quot;,&nbsp;1.0&nbsp;/&nbsp;max(1,&nbsp;src_w),&nbsp;1.0&nbsp;/&nbsp;max(1,&nbsp;src_h))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.draw_ui_textured_quad()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;===&nbsp;3.&nbsp;Progressive&nbsp;Upsample&nbsp;(accumulate&nbsp;bloom)&nbsp;===<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up&nbsp;=&nbsp;_get_upsample_shader()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.ensure_ready()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;i&nbsp;in&nbsp;range(mip_levels&nbsp;-&nbsp;2,&nbsp;-1,&nbsp;-1):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_fbo&nbsp;=&nbsp;self._mip_fbos[i&nbsp;+&nbsp;1]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_fbo&nbsp;=&nbsp;self._mip_fbos[i]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_w&nbsp;=&nbsp;max(1,&nbsp;w&nbsp;&gt;&gt;&nbsp;(i&nbsp;+&nbsp;1))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_h&nbsp;=&nbsp;max(1,&nbsp;h&nbsp;&gt;&gt;&nbsp;(i&nbsp;+&nbsp;1))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_w&nbsp;=&nbsp;max(1,&nbsp;w&nbsp;&gt;&gt;&nbsp;i)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_h&nbsp;=&nbsp;max(1,&nbsp;h&nbsp;&gt;&gt;&nbsp;i)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.bind_framebuffer(dst_fbo)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_viewport(0,&nbsp;0,&nbsp;dst_w,&nbsp;dst_h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src_fbo.color_texture().bind(0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dst_fbo.color_texture().bind(1)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.set_uniform_int(&quot;u_texture&quot;,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.set_uniform_int(&quot;u_higher_mip&quot;,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.set_uniform_vec2(&quot;u_texel_size&quot;,&nbsp;1.0&nbsp;/&nbsp;max(1,&nbsp;src_w),&nbsp;1.0&nbsp;/&nbsp;max(1,&nbsp;src_h))<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;up.set_uniform_float(&quot;u_blend_factor&quot;,&nbsp;1.0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.draw_ui_textured_quad()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;===&nbsp;4.&nbsp;Composite&nbsp;Pass&nbsp;===<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;target_fbo&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.bind_framebuffer(target_fbo)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.set_viewport(0,&nbsp;0,&nbsp;w,&nbsp;h)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp&nbsp;=&nbsp;_get_composite_shader()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp.ensure_ready()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp.use()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color_tex.bind(0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mip_fbos[0].color_texture().bind(1)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp.set_uniform_int(&quot;u_original&quot;,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp.set_uniform_int(&quot;u_bloom&quot;,&nbsp;1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;comp.set_uniform_float(&quot;u_intensity&quot;,&nbsp;self.intensity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;gfx.draw_ui_textured_quad()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;clear_callbacks(self)&nbsp;-&gt;&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Clean&nbsp;up&nbsp;resources.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;fbo&nbsp;in&nbsp;self._mip_fbos:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;fbo&nbsp;is&nbsp;not&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fbo.delete()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self._mip_fbos.clear()<br>
<!-- END SCAT CODE -->
</body>
</html>
