<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/project/InitScript.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
<br>
import&nbsp;traceback<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.timeline_initializer<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;controllers&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.object_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;ObjectController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.chronosphere_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;ChronosphereController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.timeline_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;TimelineController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.click_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;ClickController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.game_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;GameController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.action_server_component<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;ActionServerComponent&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.action.blink_action_component<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;BlinkActionComponent&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.animation_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;AnimationController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.colliders.human_model_collider<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;HumanModelCollider&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()&nbsp;&nbsp;&nbsp;&nbsp;<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.visual_effects_controller<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;VisualEffectsController&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.effects.blind_effect<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;BlindEffect&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()<br>
<br>
try:<br>
&nbsp;&nbsp;&nbsp;&nbsp;import&nbsp;termin.chronosquad.controllers.navmesh_fov_shower<br>
except&nbsp;ImportError&nbsp;as&nbsp;e:<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;[Project&nbsp;InitScript]&nbsp;ChronoSquad&nbsp;NavMeshFovShowerComponent&nbsp;not&nbsp;found,&nbsp;skipping&nbsp;initialization:&nbsp;&quot;,&nbsp;e)<br>
&nbsp;&nbsp;&nbsp;&nbsp;traceback.print_exc()<br>
<br>
#&nbsp;Install&nbsp;ChronoSquad&nbsp;menu<br>
from&nbsp;termin.chronosquad.editor&nbsp;import&nbsp;install_menu<br>
install_menu()<br>
<!-- END SCAT CODE -->
</body>
</html>
