<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>termin/visualization/components/rotator.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Simple&nbsp;rotation&nbsp;component&nbsp;for&nbsp;testing&nbsp;game&nbsp;mode.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Component<br>
from&nbsp;termin.editor.inspect_field&nbsp;import&nbsp;inspect<br>
from&nbsp;termin.geombase.pose3&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.util&nbsp;import&nbsp;qmul<br>
<br>
<br>
class&nbsp;RotatorComponent(Component):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Компонент,&nbsp;который&nbsp;вращает&nbsp;entity&nbsp;вокруг&nbsp;заданной&nbsp;оси.&quot;&quot;&quot;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;speed&nbsp;=&nbsp;inspect(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;90.0,&nbsp;label=&quot;Speed&nbsp;(deg/s)&quot;,&nbsp;kind=&quot;float&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;min=-360.0,&nbsp;max=360.0,&nbsp;step=1.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;axis&nbsp;=&nbsp;inspect(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;np.array([0.0,&nbsp;0.0,&nbsp;1.0],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;label=&quot;Axis&quot;,&nbsp;kind=&quot;vec3&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;serializable_fields&nbsp;=&nbsp;[&quot;speed&quot;,&nbsp;&quot;axis&quot;]<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;speed:&nbsp;float&nbsp;=&nbsp;90.0,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis:&nbsp;np.ndarray&nbsp;|&nbsp;list&nbsp;|&nbsp;None&nbsp;=&nbsp;None,<br>
&nbsp;&nbsp;&nbsp;&nbsp;):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__(enabled=True)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.speed&nbsp;=&nbsp;speed&nbsp;&nbsp;#&nbsp;градусов&nbsp;в&nbsp;секунду<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;axis&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;axis&nbsp;=&nbsp;[0.0,&nbsp;0.0,&nbsp;1.0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.axis&nbsp;=&nbsp;np.array(axis,&nbsp;dtype=np.float32)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Нормализуем&nbsp;ось<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;norm&nbsp;=&nbsp;np.linalg.norm(self.axis)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;norm&nbsp;&gt;&nbsp;0:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.axis&nbsp;=&nbsp;self.axis&nbsp;/&nbsp;norm<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;update(self,&nbsp;dt:&nbsp;float):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;self.entity&nbsp;is&nbsp;None:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Угол&nbsp;поворота&nbsp;за&nbsp;этот&nbsp;кадр&nbsp;(в&nbsp;радианах)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;angle_rad&nbsp;=&nbsp;np.radians(self.speed&nbsp;*&nbsp;dt)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Создаём&nbsp;инкрементальный&nbsp;поворот<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;delta_rotation&nbsp;=&nbsp;Pose3.rotation(self.axis,&nbsp;angle_rad)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Получаем&nbsp;текущую&nbsp;позу<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;current_pose&nbsp;=&nbsp;self.entity.transform.local_pose()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Применяем&nbsp;поворот:&nbsp;new_q&nbsp;=&nbsp;current_q&nbsp;*&nbsp;delta_q<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_ang&nbsp;=&nbsp;qmul(current_pose.ang,&nbsp;delta_rotation.ang)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Обновляем&nbsp;позу<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new_pose&nbsp;=&nbsp;Pose3(lin=current_pose.lin,&nbsp;ang=new_ang)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.entity.transform.relocate(new_pose)<br>
<!-- END SCAT CODE -->
</body>
</html>
