<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/visual/clickable.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Textured&nbsp;cube&nbsp;demo&nbsp;using&nbsp;the&nbsp;component-based&nbsp;visualization&nbsp;world.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.mesh.mesh&nbsp;import&nbsp;TexturedCubeMesh<br>
from&nbsp;termin.visualization&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MeshDrawable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Material,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Texture,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Visualization,<br>
&nbsp;&nbsp;&nbsp;&nbsp;VisualizationWorld,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PerspectiveCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrbitCameraController,<br>
)<br>
from&nbsp;termin.visualization.core.entity&nbsp;import&nbsp;Entity,&nbsp;Component<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer,&nbsp;LightComponent<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
from&nbsp;termin.colliders&nbsp;import&nbsp;BoxCollider<br>
from&nbsp;termin.colliders.collider_component&nbsp;import&nbsp;ColliderComponent<br>
from&nbsp;termin.geombase._geom_native&nbsp;import&nbsp;Vec3<br>
<br>
#&nbsp;===&nbsp;воображаемый&nbsp;интерфейс&nbsp;кликабельности&nbsp;===<br>
class&nbsp;Clickable:<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_click(self,&nbsp;hit,&nbsp;button:&nbsp;int):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pass<br>
<br>
#&nbsp;===&nbsp;простой&nbsp;обработчик&nbsp;клика&nbsp;===<br>
class&nbsp;CubeClickHandler(Component,&nbsp;Clickable):<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;__init__(self,&nbsp;name:&nbsp;str):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.name&nbsp;=&nbsp;name<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;super().__init__()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_click(self,&nbsp;hit,&nbsp;button:&nbsp;int):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Клик&nbsp;по&nbsp;кубу&nbsp;'{self.name}',&nbsp;точка:&nbsp;{hit.point}&quot;)<br>
<br>
<br>
VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
layout(location&nbsp;=&nbsp;2)&nbsp;in&nbsp;vec2&nbsp;a_texcoord;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_normal;<br>
out&nbsp;vec3&nbsp;v_world_pos;<br>
out&nbsp;vec2&nbsp;v_texcoord;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec4&nbsp;world&nbsp;=&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_world_pos&nbsp;=&nbsp;world.xyz;<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(transpose(inverse(u_model)))&nbsp;*&nbsp;a_normal;<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_texcoord&nbsp;=&nbsp;a_texcoord;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;world;<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec3&nbsp;v_normal;<br>
in&nbsp;vec3&nbsp;v_world_pos;<br>
in&nbsp;vec2&nbsp;v_texcoord;<br>
<br>
uniform&nbsp;vec3&nbsp;u_light_dir;<br>
uniform&nbsp;vec3&nbsp;u_light_color;<br>
uniform&nbsp;vec3&nbsp;u_view_pos;<br>
uniform&nbsp;sampler2D&nbsp;u_diffuse_map;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;N&nbsp;=&nbsp;normalize(v_normal);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;L&nbsp;=&nbsp;normalize(-u_light_dir);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;V&nbsp;=&nbsp;normalize(u_view_pos&nbsp;-&nbsp;v_world_pos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;texColor&nbsp;=&nbsp;texture(u_diffuse_map,&nbsp;v_texcoord).rgb;<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;ndotl&nbsp;=&nbsp;max(dot(N,&nbsp;L),&nbsp;0.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;diffuse&nbsp;=&nbsp;texColor&nbsp;*&nbsp;ndotl;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;ambient&nbsp;=&nbsp;texColor&nbsp;*&nbsp;0.2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;H&nbsp;=&nbsp;normalize(L&nbsp;+&nbsp;V);<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;spec&nbsp;=&nbsp;pow(max(dot(N,&nbsp;H),&nbsp;0.0),&nbsp;32.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;specular&nbsp;=&nbsp;vec3(0.4)&nbsp;*&nbsp;spec;<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;(ambient&nbsp;+&nbsp;diffuse)&nbsp;*&nbsp;u_light_color&nbsp;+&nbsp;specular;<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
def&nbsp;build_scene(world:&nbsp;VisualizationWorld)&nbsp;-&gt;&nbsp;tuple[Scene,&nbsp;PerspectiveCameraComponent]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;texture_path&nbsp;=&nbsp;&quot;examples/data/textures/crate_diffuse.png&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;texture&nbsp;=&nbsp;Texture.from_file(texture_path)<br>
&nbsp;&nbsp;&nbsp;&nbsp;mesh&nbsp;=&nbsp;TexturedCubeMesh()<br>
&nbsp;&nbsp;&nbsp;&nbsp;drawable&nbsp;=&nbsp;MeshDrawable(mesh)<br>
&nbsp;&nbsp;&nbsp;&nbsp;shader_prog&nbsp;=&nbsp;TcShader.from_sources(VERT,&nbsp;FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;ClickableShader&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;material&nbsp;=&nbsp;Material(shader=shader_prog,&nbsp;color=None,&nbsp;textures={&quot;u_diffuse_map&quot;:&nbsp;texture})<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Первый&nbsp;куб<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube1&nbsp;=&nbsp;Entity(pose=Pose3.identity(),&nbsp;name=&quot;cube_1&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube1.add_component(MeshRenderer(drawable,&nbsp;material))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube1.add_component(CubeClickHandler(&quot;cube_1&quot;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube1.add_component(ColliderComponent(BoxCollider(Vec3(0.5,&nbsp;0.5,&nbsp;0.5))))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube1.transform.relocate(Pose3(lin=np.array([-2.0,&nbsp;0.0,&nbsp;0.0])))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Второй&nbsp;куб<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2&nbsp;=&nbsp;Entity(pose=Pose3.identity(),&nbsp;name=&quot;cube_2&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2.add_component(MeshRenderer(drawable,&nbsp;material))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2.add_component(CubeClickHandler(&quot;cube_2&quot;))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2.add_component(ColliderComponent(BoxCollider(Vec3(0.5,&nbsp;0.5,&nbsp;0.5))))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2.transform.relocate(Pose3(lin=np.array([0.0,&nbsp;0.0,&nbsp;1.0])))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube2.transform.set_parent(cube1.transform)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;Scene()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(cube1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(cube2)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.add_scene(scene)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Light<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_entity&nbsp;=&nbsp;Entity(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose=Pose3.from_euler(np.deg2rad(-45),&nbsp;np.deg2rad(-45),&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=&quot;light&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_entity.add_component(LightComponent())<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(light_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Camera<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity&nbsp;=&nbsp;Entity(name=&quot;camera&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera&nbsp;=&nbsp;PerspectiveCameraComponent()<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity.add_component(camera)<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity.add_component(OrbitCameraController())<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(camera_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene,&nbsp;camera<br>
<br>
<br>
def&nbsp;main():<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Запуск&nbsp;текстурированного&nbsp;куба...&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world&nbsp;=&nbsp;VisualizationWorld()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene,&nbsp;camera&nbsp;=&nbsp;build_scene(world)<br>
&nbsp;&nbsp;&nbsp;&nbsp;window&nbsp;=&nbsp;world.create_window(title=&quot;termin&nbsp;textured&nbsp;cube&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;window.add_viewport(scene,&nbsp;camera)<br>
&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Запуск&nbsp;основного&nbsp;цикла&nbsp;визуализации...&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.run()<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
<!-- END SCAT CODE -->
</body>
</html>
