<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/visual/multimaterial.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;<br>
demo_wire_cube.py<br>
<br>
Куб&nbsp;с&nbsp;кастомным&nbsp;solid-шейдером.<br>
<br>
Демонстрирует&nbsp;создание&nbsp;собственного&nbsp;TcShader&nbsp;и&nbsp;Material.<br>
&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.mesh.mesh&nbsp;import&nbsp;CubeMesh<br>
from&nbsp;termin.visualization&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MeshDrawable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Material,<br>
&nbsp;&nbsp;&nbsp;&nbsp;VisualizationWorld,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PerspectiveCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrbitCameraController,<br>
)<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer,&nbsp;LightComponent<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
<br>
<br>
#&nbsp;----------------------------------------------------------------------<br>
#&nbsp;SOLID&nbsp;SHADER&nbsp;(почти&nbsp;твой&nbsp;исходный)<br>
#&nbsp;----------------------------------------------------------------------<br>
<br>
SOLID_VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_normal;<br>
out&nbsp;vec3&nbsp;v_world_pos;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec4&nbsp;world&nbsp;=&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_world_pos&nbsp;=&nbsp;world.xyz;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(transpose(inverse(u_model)))&nbsp;*&nbsp;a_normal;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;world;<br>
}<br>
&quot;&quot;&quot;<br>
<br>
SOLID_FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
<br>
in&nbsp;vec3&nbsp;v_normal;<br>
in&nbsp;vec3&nbsp;v_world_pos;<br>
<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
uniform&nbsp;vec3&nbsp;u_light_dir;<br>
uniform&nbsp;vec3&nbsp;u_light_color;<br>
uniform&nbsp;vec3&nbsp;u_view_pos;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;N&nbsp;=&nbsp;normalize(v_normal);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;L&nbsp;=&nbsp;normalize(-u_light_dir);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;V&nbsp;=&nbsp;normalize(u_view_pos&nbsp;-&nbsp;v_world_pos);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;H&nbsp;=&nbsp;normalize(L&nbsp;+&nbsp;V);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;float&nbsp;ambientStrength&nbsp;&nbsp;=&nbsp;0.2;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;float&nbsp;diffuseStrength&nbsp;&nbsp;=&nbsp;0.8;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;float&nbsp;specularStrength&nbsp;=&nbsp;0.4;<br>
&nbsp;&nbsp;&nbsp;&nbsp;const&nbsp;float&nbsp;shininess&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;32.0;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;ambient&nbsp;=&nbsp;ambientStrength&nbsp;*&nbsp;u_color.rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;ndotl&nbsp;=&nbsp;max(dot(N,&nbsp;L),&nbsp;0.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;diffuse&nbsp;=&nbsp;diffuseStrength&nbsp;*&nbsp;ndotl&nbsp;*&nbsp;u_color.rgb;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;specFactor&nbsp;=&nbsp;0.0;<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(ndotl&nbsp;&gt;&nbsp;0.0)&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;specFactor&nbsp;=&nbsp;pow(max(dot(N,&nbsp;H),&nbsp;0.0),&nbsp;shininess);<br>
&nbsp;&nbsp;&nbsp;&nbsp;}<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;specular&nbsp;=&nbsp;specularStrength&nbsp;*&nbsp;specFactor&nbsp;*&nbsp;u_light_color;<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;(ambient&nbsp;+&nbsp;diffuse)&nbsp;*&nbsp;u_light_color&nbsp;+&nbsp;specular;<br>
&nbsp;&nbsp;&nbsp;&nbsp;color&nbsp;=&nbsp;clamp(color,&nbsp;0.0,&nbsp;1.0);<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color,&nbsp;u_color.a);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
#&nbsp;----------------------------------------------------------------------<br>
#&nbsp;SCENE&nbsp;BUILDING<br>
#&nbsp;----------------------------------------------------------------------<br>
<br>
def&nbsp;build_scene(world:&nbsp;VisualizationWorld):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Меш&nbsp;куба<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube_mesh&nbsp;=&nbsp;CubeMesh()<br>
&nbsp;&nbsp;&nbsp;&nbsp;drawable&nbsp;=&nbsp;MeshDrawable(cube_mesh)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Solid&nbsp;материал&nbsp;---<br>
&nbsp;&nbsp;&nbsp;&nbsp;solid_shader&nbsp;=&nbsp;TcShader.from_sources(SOLID_VERT,&nbsp;SOLID_FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;SolidShader&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;solid_material&nbsp;=&nbsp;Material(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shader=solid_shader,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color=np.array([0.8,&nbsp;0.3,&nbsp;0.3,&nbsp;1.0],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Entity&nbsp;с&nbsp;MeshRenderer&nbsp;---<br>
&nbsp;&nbsp;&nbsp;&nbsp;entity&nbsp;=&nbsp;Entity(pose=Pose3.identity(),&nbsp;name=&quot;cube&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;entity.add_component(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MeshRenderer(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mesh=drawable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;material=solid_material,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;Scene&nbsp;+&nbsp;камера&nbsp;---<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;Scene()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.add_scene(scene)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Light<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_entity&nbsp;=&nbsp;Entity(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pose=Pose3.from_euler(np.deg2rad(-45),&nbsp;np.deg2rad(-45),&nbsp;0),<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;name=&quot;light&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;light_entity.add_component(LightComponent())<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(light_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Camera<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity&nbsp;=&nbsp;Entity(name=&quot;camera&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera&nbsp;=&nbsp;PerspectiveCameraComponent()<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity.add_component(camera)<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera_entity.add_component(OrbitCameraController())<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(camera_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene,&nbsp;camera<br>
<br>
<br>
def&nbsp;main():<br>
&nbsp;&nbsp;&nbsp;&nbsp;world&nbsp;=&nbsp;VisualizationWorld()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene,&nbsp;camera&nbsp;=&nbsp;build_scene(world)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;window&nbsp;=&nbsp;world.create_window(title=&quot;termin&nbsp;custom&nbsp;shader&nbsp;demo&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;window.add_viewport(scene,&nbsp;camera)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.run()<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
<!-- END SCAT CODE -->
</body>
</html>
