<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/visual/qt_embed.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Embed&nbsp;termin&nbsp;visualization&nbsp;view&nbsp;inside&nbsp;a&nbsp;PyQt6&nbsp;application.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
from&nbsp;PyQt6&nbsp;import&nbsp;QtWidgets<br>
<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.mesh.mesh&nbsp;import&nbsp;UVSphereMesh<br>
from&nbsp;termin.visualization&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MeshDrawable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Material,<br>
&nbsp;&nbsp;&nbsp;&nbsp;VisualizationWorld,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PerspectiveCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrbitCameraController,<br>
)<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
from&nbsp;termin.visualization.platform.backends.qt&nbsp;import&nbsp;QtWindowBackend<br>
<br>
<br>
VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_normal;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(transpose(inverse(u_model)))&nbsp;*&nbsp;a_normal;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec3&nbsp;v_normal;<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;n&nbsp;=&nbsp;normalize(v_normal);<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;ndotl&nbsp;=&nbsp;max(dot(n,&nbsp;vec3(0.2,&nbsp;0.6,&nbsp;0.5)),&nbsp;0.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;u_color.rgb&nbsp;*&nbsp;(0.25&nbsp;+&nbsp;0.75&nbsp;*&nbsp;ndotl);<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color,&nbsp;u_color.a);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
def&nbsp;build_scene(world:&nbsp;VisualizationWorld)&nbsp;-&gt;&nbsp;tuple[Scene,&nbsp;PerspectiveCameraComponent]:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&quot;&quot;&quot;Создаём&nbsp;простую&nbsp;сцену&nbsp;с&nbsp;шаром&nbsp;и&nbsp;skybox.&quot;&quot;&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;shader&nbsp;=&nbsp;TcShader.from_sources(VERT,&nbsp;FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;QtEmbedShader&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;material&nbsp;=&nbsp;Material(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shader=shader,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;color=np.array([0.3,&nbsp;0.7,&nbsp;0.9,&nbsp;1.0],&nbsp;dtype=np.float32),<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;mesh&nbsp;=&nbsp;MeshDrawable(UVSphereMesh(radius=1.0,&nbsp;n_meridians=32,&nbsp;n_parallels=16))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;sphere&nbsp;=&nbsp;Entity(pose=Pose3.identity(),&nbsp;name=&quot;sphere&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;sphere.add_component(MeshRenderer(mesh,&nbsp;material))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;Scene()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(sphere)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.add_scene(scene)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity&nbsp;=&nbsp;Entity(name=&quot;camera&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;camera&nbsp;=&nbsp;PerspectiveCameraComponent()<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity.add_component(camera)<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity.add_component(OrbitCameraController(radius=4.0))<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(cam_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene,&nbsp;camera<br>
<br>
<br>
def&nbsp;main():<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;1)&nbsp;Создаём&nbsp;Qt&nbsp;backend&nbsp;—&nbsp;внутри&nbsp;поднимется&nbsp;QApplication,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;поэтому&nbsp;до&nbsp;этого&nbsp;нельзя&nbsp;создавать&nbsp;QtWidgets.QWidget().<br>
&nbsp;&nbsp;&nbsp;&nbsp;qt_backend&nbsp;=&nbsp;QtWindowBackend()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;2)&nbsp;Создаём&nbsp;мир&nbsp;визуализации&nbsp;с&nbsp;Qt&nbsp;окном.<br>
&nbsp;&nbsp;&nbsp;&nbsp;world&nbsp;=&nbsp;VisualizationWorld(window_backend=qt_backend)<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene,&nbsp;camera&nbsp;=&nbsp;build_scene(world)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;3)&nbsp;Дальше&nbsp;обычный&nbsp;Qt-интерфейс.<br>
&nbsp;&nbsp;&nbsp;&nbsp;main_window&nbsp;=&nbsp;QtWidgets.QMainWindow()<br>
&nbsp;&nbsp;&nbsp;&nbsp;central&nbsp;=&nbsp;QtWidgets.QWidget()<br>
&nbsp;&nbsp;&nbsp;&nbsp;layout&nbsp;=&nbsp;QtWidgets.QVBoxLayout(central)<br>
&nbsp;&nbsp;&nbsp;&nbsp;layout.setContentsMargins(0,&nbsp;0,&nbsp;0,&nbsp;0)<br>
&nbsp;&nbsp;&nbsp;&nbsp;layout.setSpacing(6)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;4)&nbsp;Создаём&nbsp;окно&nbsp;визуализации&nbsp;как&nbsp;&quot;дочернее&quot;&nbsp;к&nbsp;central.<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;QtWindowBackend&nbsp;внутри:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;создаст&nbsp;QOpenGLWindow,<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;обернёт&nbsp;его&nbsp;в&nbsp;QWidget.createWindowContainer(parent),<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;вернёт&nbsp;handle,&nbsp;у&nbsp;которого&nbsp;.widget&nbsp;—&nbsp;это&nbsp;либо&nbsp;контейнер,&nbsp;либо&nbsp;само&nbsp;окно.<br>
&nbsp;&nbsp;&nbsp;&nbsp;vis_window&nbsp;=&nbsp;world.create_window(<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width=800,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;height=600,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;title=&quot;termin&nbsp;Qt&nbsp;embed&quot;,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;parent=central,&nbsp;&nbsp;#&nbsp;ключевой&nbsp;момент&nbsp;—&nbsp;передаём&nbsp;parent<br>
&nbsp;&nbsp;&nbsp;&nbsp;)<br>
<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;vis_window.add_viewport(scene,&nbsp;camera)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;handle.widget&nbsp;должен&nbsp;вернуть&nbsp;Qt-вский&nbsp;виджет&nbsp;(container),&nbsp;который&nbsp;можно&nbsp;добавить&nbsp;в&nbsp;layout<br>
&nbsp;&nbsp;&nbsp;&nbsp;layout.addWidget(vis_window.handle.widget)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;quit_btn&nbsp;=&nbsp;QtWidgets.QPushButton(&quot;Закрыть&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;close_all():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vis_window.close()<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main_window.close()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;quit_btn.clicked.connect(close_all)<br>
&nbsp;&nbsp;&nbsp;&nbsp;layout.addWidget(quit_btn)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;main_window.setCentralWidget(central)<br>
&nbsp;&nbsp;&nbsp;&nbsp;main_window.resize(900,&nbsp;700)<br>
&nbsp;&nbsp;&nbsp;&nbsp;main_window.setWindowTitle(&quot;Qt&nbsp;+&nbsp;termin&nbsp;visualization&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;main_window.show()<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;5)&nbsp;Главный&nbsp;цикл:&nbsp;внутри&nbsp;будет<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;world.run()&nbsp;→&nbsp;while&nbsp;windows:<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;window.render()<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;window_backend.poll_events()<br>
&nbsp;&nbsp;&nbsp;&nbsp;#<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;В&nbsp;Qt&nbsp;backend&nbsp;poll_events()&nbsp;делает&nbsp;app.processEvents(),<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;&nbsp;&nbsp;&nbsp;так&nbsp;что&nbsp;отдельного&nbsp;app.exec_()&nbsp;вызывать&nbsp;не&nbsp;надо.<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.run()<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
<!-- END SCAT CODE -->
</body>
</html>
