<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>examples/visual/ui_widget_yaml.py</title>
</head>
<body>
<!-- BEGIN SCAT CODE -->
&quot;&quot;&quot;Demo&nbsp;of&nbsp;the&nbsp;widget-based&nbsp;UI&nbsp;system&nbsp;with&nbsp;YAML&nbsp;loading.&quot;&quot;&quot;<br>
<br>
from&nbsp;__future__&nbsp;import&nbsp;annotations<br>
<br>
import&nbsp;numpy&nbsp;as&nbsp;np<br>
<br>
from&nbsp;termin.geombase&nbsp;import&nbsp;Pose3<br>
from&nbsp;termin.mesh.mesh&nbsp;import&nbsp;CubeMesh<br>
from&nbsp;termin.visualization&nbsp;import&nbsp;(<br>
&nbsp;&nbsp;&nbsp;&nbsp;Entity,<br>
&nbsp;&nbsp;&nbsp;&nbsp;MeshDrawable,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Scene,<br>
&nbsp;&nbsp;&nbsp;&nbsp;Material,<br>
&nbsp;&nbsp;&nbsp;&nbsp;VisualizationWorld,<br>
&nbsp;&nbsp;&nbsp;&nbsp;PerspectiveCameraComponent,<br>
&nbsp;&nbsp;&nbsp;&nbsp;OrbitCameraController,<br>
)<br>
from&nbsp;termin.visualization.render.components&nbsp;import&nbsp;MeshRenderer<br>
from&nbsp;termin._native.render&nbsp;import&nbsp;TcShader<br>
from&nbsp;termin.visualization.ui.widgets&nbsp;import&nbsp;UIComponent,&nbsp;Button<br>
from&nbsp;termin.visualization.ui.font&nbsp;import&nbsp;FontTextureAtlas<br>
<br>
<br>
#&nbsp;3D&nbsp;shader<br>
VERT&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
layout(location&nbsp;=&nbsp;0)&nbsp;in&nbsp;vec3&nbsp;a_position;<br>
layout(location&nbsp;=&nbsp;1)&nbsp;in&nbsp;vec3&nbsp;a_normal;<br>
<br>
uniform&nbsp;mat4&nbsp;u_model;<br>
uniform&nbsp;mat4&nbsp;u_view;<br>
uniform&nbsp;mat4&nbsp;u_projection;<br>
<br>
out&nbsp;vec3&nbsp;v_normal;<br>
<br>
void&nbsp;main()&nbsp;{<br>
&nbsp;&nbsp;&nbsp;&nbsp;v_normal&nbsp;=&nbsp;mat3(transpose(inverse(u_model)))&nbsp;*&nbsp;a_normal;<br>
&nbsp;&nbsp;&nbsp;&nbsp;gl_Position&nbsp;=&nbsp;u_projection&nbsp;*&nbsp;u_view&nbsp;*&nbsp;u_model&nbsp;*&nbsp;vec4(a_position,&nbsp;1.0);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
FRAG&nbsp;=&nbsp;&quot;&quot;&quot;<br>
#version&nbsp;330&nbsp;core<br>
in&nbsp;vec3&nbsp;v_normal;<br>
uniform&nbsp;vec4&nbsp;u_color;<br>
uniform&nbsp;vec3&nbsp;u_light_dir;<br>
out&nbsp;vec4&nbsp;FragColor;<br>
<br>
void&nbsp;main(){<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;N&nbsp;=&nbsp;normalize(v_normal);<br>
&nbsp;&nbsp;&nbsp;&nbsp;float&nbsp;ndotl&nbsp;=&nbsp;max(dot(N,&nbsp;-normalize(u_light_dir)),&nbsp;0.0);<br>
&nbsp;&nbsp;&nbsp;&nbsp;vec3&nbsp;color&nbsp;=&nbsp;u_color.rgb&nbsp;*&nbsp;(0.2&nbsp;+&nbsp;0.8&nbsp;*&nbsp;ndotl);<br>
&nbsp;&nbsp;&nbsp;&nbsp;FragColor&nbsp;=&nbsp;vec4(color,&nbsp;u_color.a);<br>
}<br>
&quot;&quot;&quot;<br>
<br>
<br>
def&nbsp;build_scene(world:&nbsp;VisualizationWorld):<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;3D&nbsp;cube<br>
&nbsp;&nbsp;&nbsp;&nbsp;shader&nbsp;=&nbsp;TcShader.from_sources(VERT,&nbsp;FRAG,&nbsp;&quot;&quot;,&nbsp;&quot;UIWidgetYamlShader&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;material&nbsp;=&nbsp;Material(shader=shader,&nbsp;color=np.array([0.6,&nbsp;0.8,&nbsp;0.9,&nbsp;1.0],&nbsp;dtype=np.float32))<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube_mesh&nbsp;=&nbsp;MeshDrawable(CubeMesh(size=1.0))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube&nbsp;=&nbsp;Entity(name=&quot;cube&quot;,&nbsp;pose=Pose3.identity())<br>
&nbsp;&nbsp;&nbsp;&nbsp;cube.add_component(MeshRenderer(cube_mesh,&nbsp;material))<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene&nbsp;=&nbsp;Scene()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(cube)<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.add_scene(scene)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Camera&nbsp;+&nbsp;orbit&nbsp;controller<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity&nbsp;=&nbsp;Entity(name=&quot;camera&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam&nbsp;=&nbsp;PerspectiveCameraComponent()<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity.add_component(cam)<br>
&nbsp;&nbsp;&nbsp;&nbsp;cam_entity.add_component(OrbitCameraController(radius=5.0))<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(cam_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;---&nbsp;UI&nbsp;via&nbsp;UIComponent&nbsp;with&nbsp;YAML&nbsp;---<br>
&nbsp;&nbsp;&nbsp;&nbsp;ui_entity&nbsp;=&nbsp;Entity(name=&quot;ui&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;ui_comp&nbsp;=&nbsp;UIComponent(priority=0)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Load&nbsp;font<br>
&nbsp;&nbsp;&nbsp;&nbsp;ui_comp.font&nbsp;=&nbsp;FontTextureAtlas(&quot;examples/data/fonts/Roboto-Regular.ttf&quot;,&nbsp;size=32)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Load&nbsp;UI&nbsp;from&nbsp;YAML&nbsp;file<br>
&nbsp;&nbsp;&nbsp;&nbsp;ui_comp.load(&quot;examples/data/ui/demo_menu.yaml&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;Connect&nbsp;button&nbsp;handlers&nbsp;after&nbsp;loading<br>
&nbsp;&nbsp;&nbsp;&nbsp;click_count&nbsp;=&nbsp;[0]<br>
&nbsp;&nbsp;&nbsp;&nbsp;info_label&nbsp;=&nbsp;ui_comp.find(&quot;info_label&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_click():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click_count[0]&nbsp;+=&nbsp;1<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;info_label:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info_label.text&nbsp;=&nbsp;f&quot;Click&nbsp;count:&nbsp;{click_count[0]}&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(f&quot;Button&nbsp;clicked!&nbsp;Count:&nbsp;{click_count[0]}&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;on_reset():<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click_count[0]&nbsp;=&nbsp;0<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;info_label:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;info_label.text&nbsp;=&nbsp;&quot;Click&nbsp;count:&nbsp;0&quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(&quot;Counter&nbsp;reset!&quot;)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;click_btn&nbsp;=&nbsp;ui_comp.find(&quot;click_button&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;click_btn&nbsp;and&nbsp;isinstance(click_btn,&nbsp;Button):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click_btn.on_click&nbsp;=&nbsp;on_click<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;reset_btn&nbsp;=&nbsp;ui_comp.find(&quot;reset_button&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;reset_btn&nbsp;and&nbsp;isinstance(reset_btn,&nbsp;Button):<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reset_btn.on_click&nbsp;=&nbsp;on_reset<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;ui_entity.add_component(ui_comp)<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene.add(ui_entity)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;scene,&nbsp;cam<br>
<br>
<br>
def&nbsp;main():<br>
&nbsp;&nbsp;&nbsp;&nbsp;world&nbsp;=&nbsp;VisualizationWorld()<br>
&nbsp;&nbsp;&nbsp;&nbsp;scene,&nbsp;cam&nbsp;=&nbsp;build_scene(world)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;win&nbsp;=&nbsp;world.create_window(title=&quot;Widget&nbsp;UI&nbsp;YAML&nbsp;Demo&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;win.add_viewport(scene,&nbsp;cam)<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;world.run()<br>
<br>
<br>
if&nbsp;__name__&nbsp;==&nbsp;&quot;__main__&quot;:<br>
&nbsp;&nbsp;&nbsp;&nbsp;main()<br>
<!-- END SCAT CODE -->
</body>
</html>
